
# Loop constraints
directive set /stockham_DIT/core/core:rlp CSTEPS_FROM {{. == 0}}
directive set /stockham_DIT/core/core:rlp/main CSTEPS_FROM {{. == 2} {.. == 0}}
directive set /stockham_DIT/core/core:rlp/main/OUTER_LOOP CSTEPS_FROM {{. == 2} {.. == 1}}
directive set /stockham_DIT/core/core:rlp/main/OUTER_LOOP/INNER_LOOP CSTEPS_FROM {{. == 148} {.. == 1}}

# IO operation constraints
directive set /stockham_DIT/core/core:rlp/main/p:io_read(p:rsc.@) CSTEPS_FROM {{.. == 1}}
directive set /stockham_DIT/core/core:rlp/main/g:io_read(g:rsc.@) CSTEPS_FROM {{.. == 1}}

# Sync operation constraints

# Real operation constraints
directive set /stockham_DIT/core/core:rlp/main/OUTER_LOOP/OUTER_LOOP:m:acc CSTEPS_FROM {{.. == 1}}
directive set /stockham_DIT/core/core:rlp/main/OUTER_LOOP/OUTER_LOOP:m:lshift CSTEPS_FROM {{.. == 1}}
directive set /stockham_DIT/core/core:rlp/main/OUTER_LOOP/INNER_LOOP/INNER_LOOP-1:upper:acc CSTEPS_FROM {{.. == 1}}
directive set /stockham_DIT/core/core:rlp/main/OUTER_LOOP/INNER_LOOP/INNER_LOOP-1:upper:and CSTEPS_FROM {{.. == 1}}
directive set /stockham_DIT/core/core:rlp/main/OUTER_LOOP/INNER_LOOP/INNER_LOOP-1:q:and CSTEPS_FROM {{.. == 1}}
directive set /stockham_DIT/core/core:rlp/main/OUTER_LOOP/INNER_LOOP/INNER_LOOP:a:acc CSTEPS_FROM {{.. == 1}}
directive set /stockham_DIT/core/core:rlp/main/OUTER_LOOP/INNER_LOOP/INNER_LOOP:a:read_mem(xt:rsc(0)(0).@) CSTEPS_FROM {{.. == 2}}
directive set /stockham_DIT/core/core:rlp/main/OUTER_LOOP/INNER_LOOP/INNER_LOOP:a:read_mem(yt:rsc(0)(0).@) CSTEPS_FROM {{.. == 2}}
directive set /stockham_DIT/core/core:rlp/main/OUTER_LOOP/INNER_LOOP/INNER_LOOP:a:INNER_LOOP:a:mux#6 CSTEPS_FROM {{.. == 3}}
directive set /stockham_DIT/core/core:rlp/main/OUTER_LOOP/INNER_LOOP/INNER_LOOP:b:acc#10 CSTEPS_FROM {{.. == 1}}
directive set /stockham_DIT/core/core:rlp/main/OUTER_LOOP/INNER_LOOP/INNER_LOOP:b:acc CSTEPS_FROM {{.. == 1}}
directive set /stockham_DIT/core/core:rlp/main/OUTER_LOOP/INNER_LOOP/INNER_LOOP:b:read_mem(xt:rsc(0)(0).@) CSTEPS_FROM {{.. == 1}}
directive set /stockham_DIT/core/core:rlp/main/OUTER_LOOP/INNER_LOOP/INNER_LOOP:b:read_mem(xt:rsc(0)(1).@) CSTEPS_FROM {{.. == 1}}
directive set /stockham_DIT/core/core:rlp/main/OUTER_LOOP/INNER_LOOP/INNER_LOOP:b:read_mem(xt:rsc(0)(2).@) CSTEPS_FROM {{.. == 1}}
directive set /stockham_DIT/core/core:rlp/main/OUTER_LOOP/INNER_LOOP/INNER_LOOP:b:read_mem(xt:rsc(0)(3).@) CSTEPS_FROM {{.. == 1}}
directive set /stockham_DIT/core/core:rlp/main/OUTER_LOOP/INNER_LOOP/INNER_LOOP:b:read_mem(yt:rsc(0)(0).@) CSTEPS_FROM {{.. == 1}}
directive set /stockham_DIT/core/core:rlp/main/OUTER_LOOP/INNER_LOOP/INNER_LOOP:b:read_mem(yt:rsc(0)(1).@) CSTEPS_FROM {{.. == 1}}
directive set /stockham_DIT/core/core:rlp/main/OUTER_LOOP/INNER_LOOP/INNER_LOOP:b:read_mem(yt:rsc(0)(2).@) CSTEPS_FROM {{.. == 1}}
directive set /stockham_DIT/core/core:rlp/main/OUTER_LOOP/INNER_LOOP/INNER_LOOP:b:read_mem(yt:rsc(0)(3).@) CSTEPS_FROM {{.. == 1}}
directive set /stockham_DIT/core/core:rlp/main/OUTER_LOOP/INNER_LOOP/INNER_LOOP:b:mux1h CSTEPS_FROM {{.. == 2}}
directive set /stockham_DIT/core/core:rlp/main/OUTER_LOOP/INNER_LOOP/INNER_LOOP-1:w:rshift CSTEPS_FROM {{.. == 1}}
directive set /stockham_DIT/core/core:rlp/main/OUTER_LOOP/INNER_LOOP/INNER_LOOP-1:w:lshift CSTEPS_FROM {{.. == 1}}
directive set /stockham_DIT/core/core:rlp/main/OUTER_LOOP/INNER_LOOP/INNER_LOOP:w:read_mem(twiddle:rsc(0)(0).@) CSTEPS_FROM {{.. == 1}}
directive set /stockham_DIT/core/core:rlp/main/OUTER_LOOP/INNER_LOOP/INNER_LOOP:w:read_mem(twiddle:rsc(0)(1).@) CSTEPS_FROM {{.. == 1}}
directive set /stockham_DIT/core/core:rlp/main/OUTER_LOOP/INNER_LOOP/INNER_LOOP:w:read_mem(twiddle:rsc(0)(2).@) CSTEPS_FROM {{.. == 1}}
directive set /stockham_DIT/core/core:rlp/main/OUTER_LOOP/INNER_LOOP/INNER_LOOP:w:read_mem(twiddle:rsc(0)(3).@) CSTEPS_FROM {{.. == 1}}
directive set /stockham_DIT/core/core:rlp/main/OUTER_LOOP/INNER_LOOP/INNER_LOOP:w:mux1h CSTEPS_FROM {{.. == 2}}
directive set /stockham_DIT/core/core:rlp/main/OUTER_LOOP/INNER_LOOP/INNER_LOOP-1:b:mul CSTEPS_FROM {{.. == 2}}
directive set /stockham_DIT/core/core:rlp/main/OUTER_LOOP/INNER_LOOP/INNER_LOOP-1:b:rem CSTEPS_FROM {{.. == 2}}
directive set /stockham_DIT/core/core:rlp/main/OUTER_LOOP/INNER_LOOP/INNER_LOOP:acc CSTEPS_FROM {{.. == 1}}
directive set /stockham_DIT/core/core:rlp/main/OUTER_LOOP/INNER_LOOP/INNER_LOOP-1:acc#2 CSTEPS_FROM {{.. == 22}}
directive set /stockham_DIT/core/core:rlp/main/OUTER_LOOP/INNER_LOOP/INNER_LOOP-1:modulo_dev() CSTEPS_FROM {{.. == 22}}
directive set /stockham_DIT/core/core:rlp/main/OUTER_LOOP/INNER_LOOP/INNER_LOOP:write_mem(xt:rsc(0)(0).@) CSTEPS_FROM {{.. == 35}}
directive set /stockham_DIT/core/core:rlp/main/OUTER_LOOP/INNER_LOOP/INNER_LOOP:write_mem(yt:rsc(0)(0).@) CSTEPS_FROM {{.. == 35}}
directive set /stockham_DIT/core/core:rlp/main/OUTER_LOOP/INNER_LOOP/INNER_LOOP-1:mul CSTEPS_FROM {{.. == 1}}
directive set /stockham_DIT/core/core:rlp/main/OUTER_LOOP/INNER_LOOP/INNER_LOOP:acc#23 CSTEPS_FROM {{.. == 1}}
directive set /stockham_DIT/core/core:rlp/main/OUTER_LOOP/INNER_LOOP/INNER_LOOP-1:INNER_LOOP:acc#1 CSTEPS_FROM {{.. == 1}}
directive set /stockham_DIT/core/core:rlp/main/OUTER_LOOP/INNER_LOOP/INNER_LOOP-1:acc#5 CSTEPS_FROM {{.. == 22}}
directive set /stockham_DIT/core/core:rlp/main/OUTER_LOOP/INNER_LOOP/INNER_LOOP-1:modulo_dev()#1 CSTEPS_FROM {{.. == 23}}
directive set /stockham_DIT/core/core:rlp/main/OUTER_LOOP/INNER_LOOP/INNER_LOOP:write_mem(xt:rsc(0)(0).@)#1 CSTEPS_FROM {{.. == 36}}
directive set /stockham_DIT/core/core:rlp/main/OUTER_LOOP/INNER_LOOP/INNER_LOOP:write_mem(xt:rsc(0)(1).@)#1 CSTEPS_FROM {{.. == 36}}
directive set /stockham_DIT/core/core:rlp/main/OUTER_LOOP/INNER_LOOP/INNER_LOOP:write_mem(xt:rsc(0)(2).@)#1 CSTEPS_FROM {{.. == 36}}
directive set /stockham_DIT/core/core:rlp/main/OUTER_LOOP/INNER_LOOP/INNER_LOOP:write_mem(xt:rsc(0)(3).@)#1 CSTEPS_FROM {{.. == 36}}
directive set /stockham_DIT/core/core:rlp/main/OUTER_LOOP/INNER_LOOP/INNER_LOOP:write_mem(yt:rsc(0)(0).@)#1 CSTEPS_FROM {{.. == 36}}
directive set /stockham_DIT/core/core:rlp/main/OUTER_LOOP/INNER_LOOP/INNER_LOOP:write_mem(yt:rsc(0)(1).@)#1 CSTEPS_FROM {{.. == 36}}
directive set /stockham_DIT/core/core:rlp/main/OUTER_LOOP/INNER_LOOP/INNER_LOOP:write_mem(yt:rsc(0)(2).@)#1 CSTEPS_FROM {{.. == 36}}
directive set /stockham_DIT/core/core:rlp/main/OUTER_LOOP/INNER_LOOP/INNER_LOOP:write_mem(yt:rsc(0)(3).@)#1 CSTEPS_FROM {{.. == 36}}
directive set /stockham_DIT/core/core:rlp/main/OUTER_LOOP/INNER_LOOP/INNER_LOOP:a:read_mem(xt:rsc(0)(1).@)#1 CSTEPS_FROM {{.. == 37}}
directive set /stockham_DIT/core/core:rlp/main/OUTER_LOOP/INNER_LOOP/INNER_LOOP:a:read_mem(xt:rsc(0)(2).@)#1 CSTEPS_FROM {{.. == 37}}
directive set /stockham_DIT/core/core:rlp/main/OUTER_LOOP/INNER_LOOP/INNER_LOOP:a:read_mem(yt:rsc(0)(1).@)#1 CSTEPS_FROM {{.. == 37}}
directive set /stockham_DIT/core/core:rlp/main/OUTER_LOOP/INNER_LOOP/INNER_LOOP:a:read_mem(yt:rsc(0)(2).@)#1 CSTEPS_FROM {{.. == 37}}
directive set /stockham_DIT/core/core:rlp/main/OUTER_LOOP/INNER_LOOP/INNER_LOOP:a:INNER_LOOP:a:INNER_LOOP:a:mux1h CSTEPS_FROM {{.. == 38}}
directive set /stockham_DIT/core/core:rlp/main/OUTER_LOOP/INNER_LOOP/INNER_LOOP:b:acc#11 CSTEPS_FROM {{.. == 1}}
directive set /stockham_DIT/core/core:rlp/main/OUTER_LOOP/INNER_LOOP/INNER_LOOP-2:b:INNER_LOOP:b:acc CSTEPS_FROM {{.. == 1}}
directive set /stockham_DIT/core/core:rlp/main/OUTER_LOOP/INNER_LOOP/INNER_LOOP:b:read_mem(xt:rsc(0)(0).@)#1 CSTEPS_FROM {{.. == 37}}
directive set /stockham_DIT/core/core:rlp/main/OUTER_LOOP/INNER_LOOP/INNER_LOOP:b:read_mem(xt:rsc(0)(1).@)#1 CSTEPS_FROM {{.. == 38}}
directive set /stockham_DIT/core/core:rlp/main/OUTER_LOOP/INNER_LOOP/INNER_LOOP:b:read_mem(xt:rsc(0)(2).@)#1 CSTEPS_FROM {{.. == 38}}
directive set /stockham_DIT/core/core:rlp/main/OUTER_LOOP/INNER_LOOP/INNER_LOOP:b:read_mem(xt:rsc(0)(3).@)#1 CSTEPS_FROM {{.. == 37}}
directive set /stockham_DIT/core/core:rlp/main/OUTER_LOOP/INNER_LOOP/INNER_LOOP:b:read_mem(yt:rsc(0)(0).@)#1 CSTEPS_FROM {{.. == 37}}
directive set /stockham_DIT/core/core:rlp/main/OUTER_LOOP/INNER_LOOP/INNER_LOOP:b:read_mem(yt:rsc(0)(1).@)#1 CSTEPS_FROM {{.. == 38}}
directive set /stockham_DIT/core/core:rlp/main/OUTER_LOOP/INNER_LOOP/INNER_LOOP:b:read_mem(yt:rsc(0)(2).@)#1 CSTEPS_FROM {{.. == 38}}
directive set /stockham_DIT/core/core:rlp/main/OUTER_LOOP/INNER_LOOP/INNER_LOOP:b:read_mem(yt:rsc(0)(3).@)#1 CSTEPS_FROM {{.. == 37}}
directive set /stockham_DIT/core/core:rlp/main/OUTER_LOOP/INNER_LOOP/INNER_LOOP:b:mux1h#7 CSTEPS_FROM {{.. == 39}}
directive set /stockham_DIT/core/core:rlp/main/OUTER_LOOP/INNER_LOOP/INNER_LOOP-2:w:rshift CSTEPS_FROM {{.. == 2}}
directive set /stockham_DIT/core/core:rlp/main/OUTER_LOOP/INNER_LOOP/INNER_LOOP-2:w:lshift CSTEPS_FROM {{.. == 2}}
directive set /stockham_DIT/core/core:rlp/main/OUTER_LOOP/INNER_LOOP/INNER_LOOP:w:read_mem(twiddle:rsc(0)(0).@)#1 CSTEPS_FROM {{.. == 2}}
directive set /stockham_DIT/core/core:rlp/main/OUTER_LOOP/INNER_LOOP/INNER_LOOP:w:read_mem(twiddle:rsc(0)(1).@)#1 CSTEPS_FROM {{.. == 2}}
directive set /stockham_DIT/core/core:rlp/main/OUTER_LOOP/INNER_LOOP/INNER_LOOP:w:read_mem(twiddle:rsc(0)(2).@)#1 CSTEPS_FROM {{.. == 2}}
directive set /stockham_DIT/core/core:rlp/main/OUTER_LOOP/INNER_LOOP/INNER_LOOP:w:read_mem(twiddle:rsc(0)(3).@)#1 CSTEPS_FROM {{.. == 2}}
directive set /stockham_DIT/core/core:rlp/main/OUTER_LOOP/INNER_LOOP/INNER_LOOP:w:mux1h#1 CSTEPS_FROM {{.. == 3}}
directive set /stockham_DIT/core/core:rlp/main/OUTER_LOOP/INNER_LOOP/INNER_LOOP-2:b:mul CSTEPS_FROM {{.. == 39}}
directive set /stockham_DIT/core/core:rlp/main/OUTER_LOOP/INNER_LOOP/INNER_LOOP-2:b:rem CSTEPS_FROM {{.. == 39}}
directive set /stockham_DIT/core/core:rlp/main/OUTER_LOOP/INNER_LOOP/INNER_LOOP-2:acc#2 CSTEPS_FROM {{.. == 59}}
directive set /stockham_DIT/core/core:rlp/main/OUTER_LOOP/INNER_LOOP/INNER_LOOP-2:modulo_dev() CSTEPS_FROM {{.. == 59}}
directive set /stockham_DIT/core/core:rlp/main/OUTER_LOOP/INNER_LOOP/INNER_LOOP:write_mem(xt:rsc(0)(1).@)#2 CSTEPS_FROM {{.. == 72}}
directive set /stockham_DIT/core/core:rlp/main/OUTER_LOOP/INNER_LOOP/INNER_LOOP:write_mem(yt:rsc(0)(1).@)#2 CSTEPS_FROM {{.. == 72}}
directive set /stockham_DIT/core/core:rlp/main/OUTER_LOOP/INNER_LOOP/INNER_LOOP:acc#24 CSTEPS_FROM {{.. == 1}}
directive set /stockham_DIT/core/core:rlp/main/OUTER_LOOP/INNER_LOOP/INNER_LOOP-2:INNER_LOOP:acc#1 CSTEPS_FROM {{.. == 1}}
directive set /stockham_DIT/core/core:rlp/main/OUTER_LOOP/INNER_LOOP/INNER_LOOP-2:acc#5 CSTEPS_FROM {{.. == 59}}
directive set /stockham_DIT/core/core:rlp/main/OUTER_LOOP/INNER_LOOP/INNER_LOOP-2:modulo_dev()#1 CSTEPS_FROM {{.. == 60}}
directive set /stockham_DIT/core/core:rlp/main/OUTER_LOOP/INNER_LOOP/INNER_LOOP:write_mem(xt:rsc(0)(0).@)#3 CSTEPS_FROM {{.. == 73}}
directive set /stockham_DIT/core/core:rlp/main/OUTER_LOOP/INNER_LOOP/INNER_LOOP:write_mem(xt:rsc(0)(1).@)#3 CSTEPS_FROM {{.. == 73}}
directive set /stockham_DIT/core/core:rlp/main/OUTER_LOOP/INNER_LOOP/INNER_LOOP:write_mem(xt:rsc(0)(2).@)#3 CSTEPS_FROM {{.. == 73}}
directive set /stockham_DIT/core/core:rlp/main/OUTER_LOOP/INNER_LOOP/INNER_LOOP:write_mem(xt:rsc(0)(3).@)#3 CSTEPS_FROM {{.. == 73}}
directive set /stockham_DIT/core/core:rlp/main/OUTER_LOOP/INNER_LOOP/INNER_LOOP:write_mem(yt:rsc(0)(0).@)#3 CSTEPS_FROM {{.. == 73}}
directive set /stockham_DIT/core/core:rlp/main/OUTER_LOOP/INNER_LOOP/INNER_LOOP:write_mem(yt:rsc(0)(1).@)#3 CSTEPS_FROM {{.. == 73}}
directive set /stockham_DIT/core/core:rlp/main/OUTER_LOOP/INNER_LOOP/INNER_LOOP:write_mem(yt:rsc(0)(2).@)#3 CSTEPS_FROM {{.. == 73}}
directive set /stockham_DIT/core/core:rlp/main/OUTER_LOOP/INNER_LOOP/INNER_LOOP:write_mem(yt:rsc(0)(3).@)#3 CSTEPS_FROM {{.. == 73}}
directive set /stockham_DIT/core/core:rlp/main/OUTER_LOOP/INNER_LOOP/INNER_LOOP:a:acc#2 CSTEPS_FROM {{.. == 1}}
directive set /stockham_DIT/core/core:rlp/main/OUTER_LOOP/INNER_LOOP/INNER_LOOP:a:read_mem(xt:rsc(0)(0).@)#2 CSTEPS_FROM {{.. == 74}}
directive set /stockham_DIT/core/core:rlp/main/OUTER_LOOP/INNER_LOOP/INNER_LOOP:a:read_mem(xt:rsc(0)(2).@)#2 CSTEPS_FROM {{.. == 74}}
directive set /stockham_DIT/core/core:rlp/main/OUTER_LOOP/INNER_LOOP/INNER_LOOP:a:read_mem(yt:rsc(0)(0).@)#2 CSTEPS_FROM {{.. == 74}}
directive set /stockham_DIT/core/core:rlp/main/OUTER_LOOP/INNER_LOOP/INNER_LOOP:a:read_mem(yt:rsc(0)(2).@)#2 CSTEPS_FROM {{.. == 74}}
directive set /stockham_DIT/core/core:rlp/main/OUTER_LOOP/INNER_LOOP/INNER_LOOP:a:INNER_LOOP:a:INNER_LOOP:a:mux1h#1 CSTEPS_FROM {{.. == 75}}
directive set /stockham_DIT/core/core:rlp/main/OUTER_LOOP/INNER_LOOP/INNER_LOOP:b:acc#12 CSTEPS_FROM {{.. == 1}}
directive set /stockham_DIT/core/core:rlp/main/OUTER_LOOP/INNER_LOOP/INNER_LOOP:b:acc#1 CSTEPS_FROM {{.. == 1}}
directive set /stockham_DIT/core/core:rlp/main/OUTER_LOOP/INNER_LOOP/INNER_LOOP:b:read_mem(xt:rsc(0)(0).@)#2 CSTEPS_FROM {{.. == 75}}
directive set /stockham_DIT/core/core:rlp/main/OUTER_LOOP/INNER_LOOP/INNER_LOOP:b:read_mem(xt:rsc(0)(1).@)#2 CSTEPS_FROM {{.. == 74}}
directive set /stockham_DIT/core/core:rlp/main/OUTER_LOOP/INNER_LOOP/INNER_LOOP:b:read_mem(xt:rsc(0)(2).@)#2 CSTEPS_FROM {{.. == 75}}
directive set /stockham_DIT/core/core:rlp/main/OUTER_LOOP/INNER_LOOP/INNER_LOOP:b:read_mem(xt:rsc(0)(3).@)#2 CSTEPS_FROM {{.. == 74}}
directive set /stockham_DIT/core/core:rlp/main/OUTER_LOOP/INNER_LOOP/INNER_LOOP:b:read_mem(yt:rsc(0)(0).@)#2 CSTEPS_FROM {{.. == 75}}
directive set /stockham_DIT/core/core:rlp/main/OUTER_LOOP/INNER_LOOP/INNER_LOOP:b:read_mem(yt:rsc(0)(1).@)#2 CSTEPS_FROM {{.. == 74}}
directive set /stockham_DIT/core/core:rlp/main/OUTER_LOOP/INNER_LOOP/INNER_LOOP:b:read_mem(yt:rsc(0)(2).@)#2 CSTEPS_FROM {{.. == 75}}
directive set /stockham_DIT/core/core:rlp/main/OUTER_LOOP/INNER_LOOP/INNER_LOOP:b:read_mem(yt:rsc(0)(3).@)#2 CSTEPS_FROM {{.. == 74}}
directive set /stockham_DIT/core/core:rlp/main/OUTER_LOOP/INNER_LOOP/INNER_LOOP:b:mux1h#12 CSTEPS_FROM {{.. == 76}}
directive set /stockham_DIT/core/core:rlp/main/OUTER_LOOP/INNER_LOOP/INNER_LOOP-3:w:rshift CSTEPS_FROM {{.. == 3}}
directive set /stockham_DIT/core/core:rlp/main/OUTER_LOOP/INNER_LOOP/INNER_LOOP-3:w:lshift CSTEPS_FROM {{.. == 3}}
directive set /stockham_DIT/core/core:rlp/main/OUTER_LOOP/INNER_LOOP/INNER_LOOP:w:read_mem(twiddle:rsc(0)(0).@)#2 CSTEPS_FROM {{.. == 3}}
directive set /stockham_DIT/core/core:rlp/main/OUTER_LOOP/INNER_LOOP/INNER_LOOP:w:read_mem(twiddle:rsc(0)(1).@)#2 CSTEPS_FROM {{.. == 3}}
directive set /stockham_DIT/core/core:rlp/main/OUTER_LOOP/INNER_LOOP/INNER_LOOP:w:read_mem(twiddle:rsc(0)(2).@)#2 CSTEPS_FROM {{.. == 3}}
directive set /stockham_DIT/core/core:rlp/main/OUTER_LOOP/INNER_LOOP/INNER_LOOP:w:read_mem(twiddle:rsc(0)(3).@)#2 CSTEPS_FROM {{.. == 3}}
directive set /stockham_DIT/core/core:rlp/main/OUTER_LOOP/INNER_LOOP/INNER_LOOP:w:mux1h#2 CSTEPS_FROM {{.. == 4}}
directive set /stockham_DIT/core/core:rlp/main/OUTER_LOOP/INNER_LOOP/INNER_LOOP-3:b:mul CSTEPS_FROM {{.. == 76}}
directive set /stockham_DIT/core/core:rlp/main/OUTER_LOOP/INNER_LOOP/INNER_LOOP-3:b:rem CSTEPS_FROM {{.. == 76}}
directive set /stockham_DIT/core/core:rlp/main/OUTER_LOOP/INNER_LOOP/INNER_LOOP-3:acc#2 CSTEPS_FROM {{.. == 96}}
directive set /stockham_DIT/core/core:rlp/main/OUTER_LOOP/INNER_LOOP/INNER_LOOP-3:modulo_dev() CSTEPS_FROM {{.. == 96}}
directive set /stockham_DIT/core/core:rlp/main/OUTER_LOOP/INNER_LOOP/INNER_LOOP:write_mem(xt:rsc(0)(2).@)#4 CSTEPS_FROM {{.. == 109}}
directive set /stockham_DIT/core/core:rlp/main/OUTER_LOOP/INNER_LOOP/INNER_LOOP:write_mem(yt:rsc(0)(2).@)#4 CSTEPS_FROM {{.. == 109}}
directive set /stockham_DIT/core/core:rlp/main/OUTER_LOOP/INNER_LOOP/INNER_LOOP:acc#25 CSTEPS_FROM {{.. == 1}}
directive set /stockham_DIT/core/core:rlp/main/OUTER_LOOP/INNER_LOOP/INNER_LOOP:acc#12 CSTEPS_FROM {{.. == 1}}
directive set /stockham_DIT/core/core:rlp/main/OUTER_LOOP/INNER_LOOP/INNER_LOOP-3:acc#5 CSTEPS_FROM {{.. == 96}}
directive set /stockham_DIT/core/core:rlp/main/OUTER_LOOP/INNER_LOOP/INNER_LOOP-3:modulo_dev()#1 CSTEPS_FROM {{.. == 97}}
directive set /stockham_DIT/core/core:rlp/main/OUTER_LOOP/INNER_LOOP/INNER_LOOP:write_mem(xt:rsc(0)(0).@)#5 CSTEPS_FROM {{.. == 110}}
directive set /stockham_DIT/core/core:rlp/main/OUTER_LOOP/INNER_LOOP/INNER_LOOP:write_mem(xt:rsc(0)(1).@)#5 CSTEPS_FROM {{.. == 110}}
directive set /stockham_DIT/core/core:rlp/main/OUTER_LOOP/INNER_LOOP/INNER_LOOP:write_mem(xt:rsc(0)(2).@)#5 CSTEPS_FROM {{.. == 110}}
directive set /stockham_DIT/core/core:rlp/main/OUTER_LOOP/INNER_LOOP/INNER_LOOP:write_mem(xt:rsc(0)(3).@)#5 CSTEPS_FROM {{.. == 110}}
directive set /stockham_DIT/core/core:rlp/main/OUTER_LOOP/INNER_LOOP/INNER_LOOP:write_mem(yt:rsc(0)(0).@)#5 CSTEPS_FROM {{.. == 110}}
directive set /stockham_DIT/core/core:rlp/main/OUTER_LOOP/INNER_LOOP/INNER_LOOP:write_mem(yt:rsc(0)(1).@)#5 CSTEPS_FROM {{.. == 110}}
directive set /stockham_DIT/core/core:rlp/main/OUTER_LOOP/INNER_LOOP/INNER_LOOP:write_mem(yt:rsc(0)(2).@)#5 CSTEPS_FROM {{.. == 110}}
directive set /stockham_DIT/core/core:rlp/main/OUTER_LOOP/INNER_LOOP/INNER_LOOP:write_mem(yt:rsc(0)(3).@)#5 CSTEPS_FROM {{.. == 110}}
directive set /stockham_DIT/core/core:rlp/main/OUTER_LOOP/INNER_LOOP/INNER_LOOP-4:a:acc CSTEPS_FROM {{.. == 1}}
directive set /stockham_DIT/core/core:rlp/main/OUTER_LOOP/INNER_LOOP/INNER_LOOP:a:read_mem(xt:rsc(0)(0).@)#3 CSTEPS_FROM {{.. == 111}}
directive set /stockham_DIT/core/core:rlp/main/OUTER_LOOP/INNER_LOOP/INNER_LOOP:a:read_mem(xt:rsc(0)(1).@)#3 CSTEPS_FROM {{.. == 111}}
directive set /stockham_DIT/core/core:rlp/main/OUTER_LOOP/INNER_LOOP/INNER_LOOP:a:read_mem(xt:rsc(0)(2).@)#3 CSTEPS_FROM {{.. == 111}}
directive set /stockham_DIT/core/core:rlp/main/OUTER_LOOP/INNER_LOOP/INNER_LOOP:a:read_mem(xt:rsc(0)(3).@)#3 CSTEPS_FROM {{.. == 111}}
directive set /stockham_DIT/core/core:rlp/main/OUTER_LOOP/INNER_LOOP/INNER_LOOP:a:read_mem(yt:rsc(0)(0).@)#3 CSTEPS_FROM {{.. == 111}}
directive set /stockham_DIT/core/core:rlp/main/OUTER_LOOP/INNER_LOOP/INNER_LOOP:a:read_mem(yt:rsc(0)(1).@)#3 CSTEPS_FROM {{.. == 111}}
directive set /stockham_DIT/core/core:rlp/main/OUTER_LOOP/INNER_LOOP/INNER_LOOP:a:read_mem(yt:rsc(0)(2).@)#3 CSTEPS_FROM {{.. == 111}}
directive set /stockham_DIT/core/core:rlp/main/OUTER_LOOP/INNER_LOOP/INNER_LOOP:a:read_mem(yt:rsc(0)(3).@)#3 CSTEPS_FROM {{.. == 111}}
directive set /stockham_DIT/core/core:rlp/main/OUTER_LOOP/INNER_LOOP/INNER_LOOP:a:INNER_LOOP:a:INNER_LOOP:a:mux1h#2 CSTEPS_FROM {{.. == 112}}
directive set /stockham_DIT/core/core:rlp/main/OUTER_LOOP/INNER_LOOP/INNER_LOOP:b:acc#14 CSTEPS_FROM {{.. == 1}}
directive set /stockham_DIT/core/core:rlp/main/OUTER_LOOP/INNER_LOOP/INNER_LOOP:b:acc#13 CSTEPS_FROM {{.. == 1}}
directive set /stockham_DIT/core/core:rlp/main/OUTER_LOOP/INNER_LOOP/INNER_LOOP-4:b:INNER_LOOP:b:acc CSTEPS_FROM {{.. == 1}}
directive set /stockham_DIT/core/core:rlp/main/OUTER_LOOP/INNER_LOOP/INNER_LOOP:b:read_mem(xt:rsc(0)(0).@)#3 CSTEPS_FROM {{.. == 112}}
directive set /stockham_DIT/core/core:rlp/main/OUTER_LOOP/INNER_LOOP/INNER_LOOP:b:read_mem(xt:rsc(0)(1).@)#3 CSTEPS_FROM {{.. == 112}}
directive set /stockham_DIT/core/core:rlp/main/OUTER_LOOP/INNER_LOOP/INNER_LOOP:b:read_mem(xt:rsc(0)(2).@)#3 CSTEPS_FROM {{.. == 112}}
directive set /stockham_DIT/core/core:rlp/main/OUTER_LOOP/INNER_LOOP/INNER_LOOP:b:read_mem(xt:rsc(0)(3).@)#3 CSTEPS_FROM {{.. == 112}}
directive set /stockham_DIT/core/core:rlp/main/OUTER_LOOP/INNER_LOOP/INNER_LOOP:b:read_mem(yt:rsc(0)(0).@)#3 CSTEPS_FROM {{.. == 112}}
directive set /stockham_DIT/core/core:rlp/main/OUTER_LOOP/INNER_LOOP/INNER_LOOP:b:read_mem(yt:rsc(0)(1).@)#3 CSTEPS_FROM {{.. == 112}}
directive set /stockham_DIT/core/core:rlp/main/OUTER_LOOP/INNER_LOOP/INNER_LOOP:b:read_mem(yt:rsc(0)(2).@)#3 CSTEPS_FROM {{.. == 112}}
directive set /stockham_DIT/core/core:rlp/main/OUTER_LOOP/INNER_LOOP/INNER_LOOP:b:read_mem(yt:rsc(0)(3).@)#3 CSTEPS_FROM {{.. == 112}}
directive set /stockham_DIT/core/core:rlp/main/OUTER_LOOP/INNER_LOOP/INNER_LOOP:b:mux1h#17 CSTEPS_FROM {{.. == 113}}
directive set /stockham_DIT/core/core:rlp/main/OUTER_LOOP/INNER_LOOP/INNER_LOOP-4:w:rshift CSTEPS_FROM {{.. == 4}}
directive set /stockham_DIT/core/core:rlp/main/OUTER_LOOP/INNER_LOOP/INNER_LOOP-4:w:lshift CSTEPS_FROM {{.. == 4}}
directive set /stockham_DIT/core/core:rlp/main/OUTER_LOOP/INNER_LOOP/INNER_LOOP:w:read_mem(twiddle:rsc(0)(0).@)#3 CSTEPS_FROM {{.. == 4}}
directive set /stockham_DIT/core/core:rlp/main/OUTER_LOOP/INNER_LOOP/INNER_LOOP:w:read_mem(twiddle:rsc(0)(1).@)#3 CSTEPS_FROM {{.. == 4}}
directive set /stockham_DIT/core/core:rlp/main/OUTER_LOOP/INNER_LOOP/INNER_LOOP:w:read_mem(twiddle:rsc(0)(2).@)#3 CSTEPS_FROM {{.. == 4}}
directive set /stockham_DIT/core/core:rlp/main/OUTER_LOOP/INNER_LOOP/INNER_LOOP:w:read_mem(twiddle:rsc(0)(3).@)#3 CSTEPS_FROM {{.. == 4}}
directive set /stockham_DIT/core/core:rlp/main/OUTER_LOOP/INNER_LOOP/INNER_LOOP:w:mux1h#3 CSTEPS_FROM {{.. == 5}}
directive set /stockham_DIT/core/core:rlp/main/OUTER_LOOP/INNER_LOOP/INNER_LOOP-4:b:mul CSTEPS_FROM {{.. == 113}}
directive set /stockham_DIT/core/core:rlp/main/OUTER_LOOP/INNER_LOOP/INNER_LOOP-4:b:rem CSTEPS_FROM {{.. == 113}}
directive set /stockham_DIT/core/core:rlp/main/OUTER_LOOP/INNER_LOOP/INNER_LOOP-4:acc#2 CSTEPS_FROM {{.. == 133}}
directive set /stockham_DIT/core/core:rlp/main/OUTER_LOOP/INNER_LOOP/INNER_LOOP-4:modulo_dev() CSTEPS_FROM {{.. == 133}}
directive set /stockham_DIT/core/core:rlp/main/OUTER_LOOP/INNER_LOOP/INNER_LOOP:write_mem(xt:rsc(0)(3).@)#6 CSTEPS_FROM {{.. == 146}}
directive set /stockham_DIT/core/core:rlp/main/OUTER_LOOP/INNER_LOOP/INNER_LOOP:write_mem(yt:rsc(0)(3).@)#6 CSTEPS_FROM {{.. == 146}}
directive set /stockham_DIT/core/core:rlp/main/OUTER_LOOP/INNER_LOOP/INNER_LOOP:acc#26 CSTEPS_FROM {{.. == 1}}
directive set /stockham_DIT/core/core:rlp/main/OUTER_LOOP/INNER_LOOP/INNER_LOOP-4:INNER_LOOP:acc#1 CSTEPS_FROM {{.. == 1}}
directive set /stockham_DIT/core/core:rlp/main/OUTER_LOOP/INNER_LOOP/INNER_LOOP-4:acc#5 CSTEPS_FROM {{.. == 133}}
directive set /stockham_DIT/core/core:rlp/main/OUTER_LOOP/INNER_LOOP/INNER_LOOP-4:modulo_dev()#1 CSTEPS_FROM {{.. == 134}}
directive set /stockham_DIT/core/core:rlp/main/OUTER_LOOP/INNER_LOOP/INNER_LOOP:write_mem(xt:rsc(0)(0).@)#7 CSTEPS_FROM {{.. == 147}}
directive set /stockham_DIT/core/core:rlp/main/OUTER_LOOP/INNER_LOOP/INNER_LOOP:write_mem(xt:rsc(0)(1).@)#7 CSTEPS_FROM {{.. == 147}}
directive set /stockham_DIT/core/core:rlp/main/OUTER_LOOP/INNER_LOOP/INNER_LOOP:write_mem(xt:rsc(0)(2).@)#7 CSTEPS_FROM {{.. == 147}}
directive set /stockham_DIT/core/core:rlp/main/OUTER_LOOP/INNER_LOOP/INNER_LOOP:write_mem(xt:rsc(0)(3).@)#7 CSTEPS_FROM {{.. == 147}}
directive set /stockham_DIT/core/core:rlp/main/OUTER_LOOP/INNER_LOOP/INNER_LOOP:write_mem(yt:rsc(0)(0).@)#7 CSTEPS_FROM {{.. == 147}}
directive set /stockham_DIT/core/core:rlp/main/OUTER_LOOP/INNER_LOOP/INNER_LOOP:write_mem(yt:rsc(0)(1).@)#7 CSTEPS_FROM {{.. == 147}}
directive set /stockham_DIT/core/core:rlp/main/OUTER_LOOP/INNER_LOOP/INNER_LOOP:write_mem(yt:rsc(0)(2).@)#7 CSTEPS_FROM {{.. == 147}}
directive set /stockham_DIT/core/core:rlp/main/OUTER_LOOP/INNER_LOOP/INNER_LOOP:write_mem(yt:rsc(0)(3).@)#7 CSTEPS_FROM {{.. == 147}}
directive set /stockham_DIT/core/core:rlp/main/OUTER_LOOP/INNER_LOOP/INNER_LOOP:acc#10 CSTEPS_FROM {{.. == 1}}
directive set /stockham_DIT/core/core:rlp/main/OUTER_LOOP/OUTER_LOOP:acc#1 CSTEPS_FROM {{.. == 2}}
directive set /stockham_DIT/core/core:rlp/main/OUTER_LOOP/OUTER_LOOP:acc CSTEPS_FROM {{.. == 2}}
directive set /stockham_DIT/core/core:rlp/main/OUTER_LOOP/OUTER_LOOP:acc#2 CSTEPS_FROM {{.. == 1}}

# Probe constraints
