directive set /stockham_DIT/stockham_DIT:core/core/drf(y).smx.lpi#2 REGISTER_NAME drf(y).smx.lpi#2
directive set /stockham_DIT/stockham_DIT:core/core/drf(y).smx.lpi#3 REGISTER_NAME drf(y).smx.lpi#2
directive set /stockham_DIT/stockham_DIT:core/core/drf(y).smx.lpi#3.dfm#3 REGISTER_NAME drf(y).smx.lpi#2
directive set /stockham_DIT/stockham_DIT:core/core/INNER_LOOP:b#1.sva REGISTER_NAME drf(y).smx.lpi#2
directive set /stockham_DIT/stockham_DIT:core/core/INNER_LOOP:b#2.sva REGISTER_NAME drf(y).smx.lpi#2
directive set /stockham_DIT/stockham_DIT:core/core/INNER_LOOP:b#3.sva REGISTER_NAME drf(y).smx.lpi#2
directive set /stockham_DIT/stockham_DIT:core/core/tmp#11.sva#3 REGISTER_NAME drf(y).smx.lpi#2
directive set /stockham_DIT/stockham_DIT:core/core/tmp#13.sva#1 REGISTER_NAME drf(y).smx.lpi#2
directive set /stockham_DIT/stockham_DIT:core/core/INNER_LOOP-1:q:and.psp.sva REGISTER_NAME INNER_LOOP-1:q:and.psp.sva
directive set /stockham_DIT/stockham_DIT:core/core/INNER_LOOP:t(8:2).sva REGISTER_NAME INNER_LOOP-1:q:and.psp.sva
directive set /stockham_DIT/stockham_DIT:core/core/INNER_LOOP:a:conc#12.itm(1) REGISTER_NAME INNER_LOOP:a:conc#12.itm(1)
directive set /stockham_DIT/stockham_DIT:core/core/INNER_LOOP:a:conc#17.itm(1) REGISTER_NAME INNER_LOOP:a:conc#12.itm(1)
directive set /stockham_DIT/stockham_DIT:core/core/INNER_LOOP-1:w:lshift.idiv.sva REGISTER_NAME INNER_LOOP-1:w:lshift.idiv.sva
directive set /stockham_DIT/stockham_DIT:core/core/INNER_LOOP-2:w:lshift.idiv.sva REGISTER_NAME INNER_LOOP-1:w:lshift.idiv.sva
directive set /stockham_DIT/stockham_DIT:core/core/INNER_LOOP-3:w:lshift.idiv.sva REGISTER_NAME INNER_LOOP-1:w:lshift.idiv.sva
directive set /stockham_DIT/stockham_DIT:core/core/INNER_LOOP-4:w:lshift.idiv.sva REGISTER_NAME INNER_LOOP-1:w:lshift.idiv.sva
directive set /stockham_DIT/stockham_DIT:core/core/INNER_LOOP:a:slc(INNER_LOOP-1:q:and.psp)(0)#5.itm REGISTER_NAME INNER_LOOP:a:slc(INNER_LOOP-1:q:and.psp)(0)#5.itm
directive set /stockham_DIT/stockham_DIT:core/core/INNER_LOOP:a:slc(INNER_LOOP-1:q:and.psp)(0)#6.itm REGISTER_NAME INNER_LOOP:a:slc(INNER_LOOP-1:q:and.psp)(0)#5.itm
directive set /stockham_DIT/stockham_DIT:core/core/INNER_LOOP:a:slc(INNER_LOOP-1:q:and.psp)(0)#8.itm REGISTER_NAME INNER_LOOP:a:slc(INNER_LOOP-1:q:and.psp)(0)#5.itm
directive set /stockham_DIT/stockham_DIT:core/core/INNER_LOOP:a:slc(INNER_LOOP-1:q:and.psp)(0)#9.itm REGISTER_NAME INNER_LOOP:a:slc(INNER_LOOP-1:q:and.psp)(0)#5.itm
directive set /stockham_DIT/stockham_DIT:core/core/drf(y).smx.lpi#3.dfm REGISTER_NAME drf(y).smx.lpi#3.dfm
directive set /stockham_DIT/stockham_DIT:core/core/drf(y).smx.lpi#3.dfm#1 REGISTER_NAME drf(y).smx.lpi#3.dfm
directive set /stockham_DIT/stockham_DIT:core/core/INNER_LOOP:b.sva REGISTER_NAME drf(y).smx.lpi#3.dfm
directive set /stockham_DIT/stockham_DIT:core/core/drf(y).smx.lpi#3.dfm#2 REGISTER_NAME drf(y).smx.lpi#3.dfm
directive set /stockham_DIT/stockham_DIT:core/core/INNER_LOOP-1:acc#5.itm REGISTER_NAME INNER_LOOP-1:acc#5.itm
directive set /stockham_DIT/stockham_DIT:core/core/INNER_LOOP-2:acc#5.itm REGISTER_NAME INNER_LOOP-1:acc#5.itm
directive set /stockham_DIT/stockham_DIT:core/core/INNER_LOOP-3:acc#5.itm REGISTER_NAME INNER_LOOP-1:acc#5.itm
directive set /stockham_DIT/stockham_DIT:core/core/INNER_LOOP-4:acc#5.itm REGISTER_NAME INNER_LOOP-1:acc#5.itm
directive set /stockham_DIT/stockham_DIT:core/core/INNER_LOOP:a#1.lpi#3.dfm REGISTER_NAME INNER_LOOP-1:acc#5.itm
directive set /stockham_DIT/stockham_DIT:core/core/INNER_LOOP:a#2.lpi#3.dfm REGISTER_NAME INNER_LOOP-1:acc#5.itm
directive set /stockham_DIT/stockham_DIT:core/core/INNER_LOOP:a#3.lpi#3.dfm REGISTER_NAME INNER_LOOP-1:acc#5.itm
directive set /stockham_DIT/stockham_DIT:core/core/INNER_LOOP:a.lpi#3.dfm REGISTER_NAME INNER_LOOP-1:acc#5.itm
directive set /stockham_DIT/stockham_DIT:core/core/tmp#3.sva#3 REGISTER_NAME tmp#3.sva#3
directive set /stockham_DIT/stockham_DIT:core/core/tmp#5.sva#1 REGISTER_NAME tmp#3.sva#3
directive set /stockham_DIT/stockham_DIT:core/core/INNER_LOOP:a:INNER_LOOP:a:and#25.itm REGISTER_NAME INNER_LOOP:a:INNER_LOOP:a:and#25.itm
directive set /stockham_DIT/stockham_DIT:core/core/INNER_LOOP:a:INNER_LOOP:a:nor#3.itm REGISTER_NAME INNER_LOOP:a:INNER_LOOP:a:and#25.itm
directive set /stockham_DIT/stockham_DIT:core/core/OUTER_LOOP:acc#2.itm REGISTER_NAME OUTER_LOOP:acc#2.itm
directive set /stockham_DIT/stockham_DIT:core/core/shift(3:0).sva REGISTER_NAME OUTER_LOOP:acc#2.itm
