directive set /stockham_DIT/stockham_DIT:core/stockham_DIT:core:conc/OUTER_LOOP:acc#2 RESOURCE_NAME OUTER_LOOP:acc#2:rg
directive set /stockham_DIT/stockham_DIT:core/stockham_DIT:core:conc/OUTER_LOOP:m:acc RESOURCE_NAME OUTER_LOOP:acc#2:rg
directive set /stockham_DIT/stockham_DIT:core/stockham_DIT:core:conc/OUTER_LOOP:acc#1 RESOURCE_NAME INNER_LOOP-1:upper:acc:rg
directive set /stockham_DIT/stockham_DIT:core/stockham_DIT:core:conc/INNER_LOOP-1:upper:acc RESOURCE_NAME INNER_LOOP-1:upper:acc:rg
directive set /stockham_DIT/stockham_DIT:core/stockham_DIT:core:conc/INNER_LOOP-1:acc#5 RESOURCE_NAME INNER_LOOP-1:acc#5:rg
directive set /stockham_DIT/stockham_DIT:core/stockham_DIT:core:conc/INNER_LOOP-4:acc#5 RESOURCE_NAME INNER_LOOP-1:acc#5:rg
directive set /stockham_DIT/stockham_DIT:core/stockham_DIT:core:conc/INNER_LOOP-1:acc#2 RESOURCE_NAME INNER_LOOP-1:acc#2:rg
directive set /stockham_DIT/stockham_DIT:core/stockham_DIT:core:conc/INNER_LOOP-4:acc#2 RESOURCE_NAME INNER_LOOP-1:acc#2:rg
directive set /stockham_DIT/stockham_DIT:core/stockham_DIT:core:conc/INNER_LOOP-1:b:mul RESOURCE_NAME INNER_LOOP-1:b:mul:rg
directive set /stockham_DIT/stockham_DIT:core/stockham_DIT:core:conc/INNER_LOOP-2:b:mul RESOURCE_NAME INNER_LOOP-1:b:mul:rg
directive set /stockham_DIT/stockham_DIT:core/stockham_DIT:core:conc/INNER_LOOP-3:b:mul RESOURCE_NAME INNER_LOOP-1:b:mul:rg
directive set /stockham_DIT/stockham_DIT:core/stockham_DIT:core:conc/INNER_LOOP-4:b:mul RESOURCE_NAME INNER_LOOP-1:b:mul:rg
directive set /stockham_DIT/stockham_DIT:core/stockham_DIT:core:conc/INNER_LOOP-1:mul RESOURCE_NAME INNER_LOOP-1:b:mul:rg
directive set /stockham_DIT/stockham_DIT:core/stockham_DIT:core:conc/INNER_LOOP-1:w:rshift RESOURCE_NAME INNER_LOOP-1:w:rshift:rg
directive set /stockham_DIT/stockham_DIT:core/stockham_DIT:core:conc/INNER_LOOP-2:w:rshift RESOURCE_NAME INNER_LOOP-1:w:rshift:rg
directive set /stockham_DIT/stockham_DIT:core/stockham_DIT:core:conc/INNER_LOOP-3:w:rshift RESOURCE_NAME INNER_LOOP-1:w:rshift:rg
directive set /stockham_DIT/stockham_DIT:core/stockham_DIT:core:conc/INNER_LOOP-4:w:rshift RESOURCE_NAME INNER_LOOP-1:w:rshift:rg
directive set /stockham_DIT/stockham_DIT:core/stockham_DIT:core:conc/OUTER_LOOP:m:lshift RESOURCE_NAME INNER_LOOP-1:w:lshift:rg
directive set /stockham_DIT/stockham_DIT:core/stockham_DIT:core:conc/INNER_LOOP-1:w:lshift RESOURCE_NAME INNER_LOOP-1:w:lshift:rg
directive set /stockham_DIT/stockham_DIT:core/stockham_DIT:core:conc/INNER_LOOP-2:w:lshift RESOURCE_NAME INNER_LOOP-1:w:lshift:rg
directive set /stockham_DIT/stockham_DIT:core/stockham_DIT:core:conc/INNER_LOOP-3:w:lshift RESOURCE_NAME INNER_LOOP-1:w:lshift:rg
directive set /stockham_DIT/stockham_DIT:core/stockham_DIT:core:conc/INNER_LOOP-4:w:lshift RESOURCE_NAME INNER_LOOP-1:w:lshift:rg
