directive set /inPlaceNTT_DIT/inPlaceNTT_DIT:core/core/operator-<64,false>:acc.mut REGISTER_NAME operator-<64,false>:acc.mut
directive set /inPlaceNTT_DIT/inPlaceNTT_DIT:core/core/operator>><64,false>:slc(modExp:exp)(63-1).itm REGISTER_NAME operator-<64,false>:acc.mut
directive set /inPlaceNTT_DIT/inPlaceNTT_DIT:core/core/tmp#2.lpi#4.dfm REGISTER_NAME operator-<64,false>:acc.mut
directive set /inPlaceNTT_DIT/inPlaceNTT_DIT:core/core/tmp.lpi#4.dfm REGISTER_NAME operator-<64,false>:acc.mut
directive set /inPlaceNTT_DIT/inPlaceNTT_DIT:core/core/COMP_LOOP-1:operator><64,false>#1:slc(operator><64,false>#1:acc)(9)#1.itm REGISTER_NAME COMP_LOOP-1:operator><64,false>#1:slc(operator><64,false>#1:acc)(9)#1.itm
directive set /inPlaceNTT_DIT/inPlaceNTT_DIT:core/core/operator><64,false>#1:slc(COMP_LOOP-2:operator><64,false>#1:acc)(8).itm REGISTER_NAME COMP_LOOP-1:operator><64,false>#1:slc(operator><64,false>#1:acc)(9)#1.itm
directive set /inPlaceNTT_DIT/inPlaceNTT_DIT:core/core/COMP_LOOP-2:slc(COMP_LOOP:acc)(9).itm REGISTER_NAME COMP_LOOP-1:operator><64,false>#1:slc(operator><64,false>#1:acc)(9)#1.itm
directive set /inPlaceNTT_DIT/inPlaceNTT_DIT:core/core/modExp:exp#1(0)#1.sva REGISTER_NAME modExp:exp#1(0)#1.sva
directive set /inPlaceNTT_DIT/inPlaceNTT_DIT:core/core/modExp:exp#1(0).sva REGISTER_NAME modExp:exp#1(0)#1.sva
directive set /inPlaceNTT_DIT/inPlaceNTT_DIT:core/core/operator%<64,false>:slc(modExp:exp)(0)#1.itm REGISTER_NAME modExp:exp#1(0)#1.sva
directive set /inPlaceNTT_DIT/inPlaceNTT_DIT:core/core/modExp:exp#1(5)#1.sva#1 REGISTER_NAME modExp:exp#1(5)#1.sva#1
directive set /inPlaceNTT_DIT/inPlaceNTT_DIT:core/core/modExp:exp#1(6)#1.sva REGISTER_NAME modExp:exp#1(5)#1.sva#1
directive set /inPlaceNTT_DIT/inPlaceNTT_DIT:core/core/modExp:exp#1(7).sva REGISTER_NAME modExp:exp#1(5)#1.sva#1
directive set /inPlaceNTT_DIT/inPlaceNTT_DIT:core/core/modExp:exp#1(0)#1.sva#1 REGISTER_NAME modExp:exp#1(0)#1.sva#1
directive set /inPlaceNTT_DIT/inPlaceNTT_DIT:core/core/modExp:exp#1(1).sva REGISTER_NAME modExp:exp#1(0)#1.sva#1
directive set /inPlaceNTT_DIT/inPlaceNTT_DIT:core/core/modExp:exp#1(7)#1.sva REGISTER_NAME modExp:exp#1(7)#1.sva
directive set /inPlaceNTT_DIT/inPlaceNTT_DIT:core/core/modExp:exp#1(8).sva REGISTER_NAME modExp:exp#1(7)#1.sva
directive set /inPlaceNTT_DIT/inPlaceNTT_DIT:core/core/modExp:exp#1(5)#1.sva REGISTER_NAME modExp:exp#1(5)#1.sva
directive set /inPlaceNTT_DIT/inPlaceNTT_DIT:core/core/modExp:exp#1(6).sva REGISTER_NAME modExp:exp#1(5)#1.sva
directive set /inPlaceNTT_DIT/inPlaceNTT_DIT:core/core/modExp:exp#1(4)#1.sva REGISTER_NAME modExp:exp#1(4)#1.sva
directive set /inPlaceNTT_DIT/inPlaceNTT_DIT:core/core/modExp:exp#1(5).sva REGISTER_NAME modExp:exp#1(4)#1.sva
directive set /inPlaceNTT_DIT/inPlaceNTT_DIT:core/core/modExp:exp#1(3)#1.sva REGISTER_NAME modExp:exp#1(3)#1.sva
directive set /inPlaceNTT_DIT/inPlaceNTT_DIT:core/core/modExp:exp#1(4).sva REGISTER_NAME modExp:exp#1(3)#1.sva
directive set /inPlaceNTT_DIT/inPlaceNTT_DIT:core/core/modExp:exp#1(2)#1.sva REGISTER_NAME modExp:exp#1(2)#1.sva
directive set /inPlaceNTT_DIT/inPlaceNTT_DIT:core/core/modExp:exp#1(3).sva REGISTER_NAME modExp:exp#1(2)#1.sva
directive set /inPlaceNTT_DIT/inPlaceNTT_DIT:core/core/exit:COMP_LOOP-1:modExp#1:while.sva REGISTER_NAME exit:COMP_LOOP-1:modExp#1:while.sva
directive set /inPlaceNTT_DIT/inPlaceNTT_DIT:core/core/exit:modExp:while.sva REGISTER_NAME exit:COMP_LOOP-1:modExp#1:while.sva
directive set /inPlaceNTT_DIT/inPlaceNTT_DIT:core/core/exit:COMP_LOOP.sva REGISTER_NAME exit:COMP_LOOP-1:modExp#1:while.sva
directive set /inPlaceNTT_DIT/inPlaceNTT_DIT:core/core/modExp:exp#1(1)#1.sva REGISTER_NAME modExp:exp#1(1)#1.sva
directive set /inPlaceNTT_DIT/inPlaceNTT_DIT:core/core/modExp:exp#1(2).sva REGISTER_NAME modExp:exp#1(1)#1.sva
directive set /inPlaceNTT_DIT/inPlaceNTT_DIT:core/core/modExp:exp#1(8)#1.sva REGISTER_NAME modExp:exp#1(1)#1.sva
directive set /inPlaceNTT_DIT/inPlaceNTT_DIT:core/core/COMP_LOOP:acc#10.cse(12:1)#1.sva REGISTER_NAME COMP_LOOP:acc#10.cse(12:1)#1.sva
directive set /inPlaceNTT_DIT/inPlaceNTT_DIT:core/core/COMP_LOOP:acc#10.cse(12:1).sva REGISTER_NAME COMP_LOOP:acc#10.cse(12:1)#1.sva
directive set /inPlaceNTT_DIT/inPlaceNTT_DIT:core/core/COMP_LOOP-1:acc#8.itm REGISTER_NAME COMP_LOOP-1:acc#8.itm
directive set /inPlaceNTT_DIT/inPlaceNTT_DIT:core/core/COMP_LOOP-2:acc#8.itm REGISTER_NAME COMP_LOOP-1:acc#8.itm
directive set /inPlaceNTT_DIT/inPlaceNTT_DIT:core/core/modExp#1:result#1.sva REGISTER_NAME COMP_LOOP-1:acc#8.itm
directive set /inPlaceNTT_DIT/inPlaceNTT_DIT:core/core/modExp#1:result.sva REGISTER_NAME COMP_LOOP-1:acc#8.itm
directive set /inPlaceNTT_DIT/inPlaceNTT_DIT:core/core/modExp#1:result.sva.dfm REGISTER_NAME COMP_LOOP-1:acc#8.itm
directive set /inPlaceNTT_DIT/inPlaceNTT_DIT:core/core/modExp:exp.sva REGISTER_NAME COMP_LOOP-1:acc#8.itm
directive set /inPlaceNTT_DIT/inPlaceNTT_DIT:core/core/COMP_LOOP-1:acc#5.mut REGISTER_NAME COMP_LOOP-1:acc#5.mut
directive set /inPlaceNTT_DIT/inPlaceNTT_DIT:core/core/COMP_LOOP-2:acc#5.mut REGISTER_NAME COMP_LOOP-1:acc#5.mut
directive set /inPlaceNTT_DIT/inPlaceNTT_DIT:core/core/COMP_LOOP:mux#1.itm REGISTER_NAME COMP_LOOP-1:acc#5.mut
directive set /inPlaceNTT_DIT/inPlaceNTT_DIT:core/core/COMP_LOOP:mux#3.itm REGISTER_NAME COMP_LOOP-1:acc#5.mut
directive set /inPlaceNTT_DIT/inPlaceNTT_DIT:core/core/modExp:base#1.sva REGISTER_NAME COMP_LOOP-1:acc#5.mut
directive set /inPlaceNTT_DIT/inPlaceNTT_DIT:core/core/modExp:base#2.sva REGISTER_NAME COMP_LOOP-1:acc#5.mut
directive set /inPlaceNTT_DIT/inPlaceNTT_DIT:core/core/modExp:base.sva REGISTER_NAME COMP_LOOP-1:acc#5.mut
directive set /inPlaceNTT_DIT/inPlaceNTT_DIT:core/core/modulo#3:mux#1.itm REGISTER_NAME COMP_LOOP-1:acc#5.mut
