directive set /inPlaceNTT_DIT/inPlaceNTT_DIT:core/inPlaceNTT_DIT:core:conc/COMP_LOOP-1:acc#8 RESOURCE_NAME COMP_LOOP-1:acc#10:rg
directive set /inPlaceNTT_DIT/inPlaceNTT_DIT:core/inPlaceNTT_DIT:core:conc/COMP_LOOP-1:operator><64,false>#1:acc#1 RESOURCE_NAME COMP_LOOP-1:acc#10:rg
directive set /inPlaceNTT_DIT/inPlaceNTT_DIT:core/inPlaceNTT_DIT:core:conc/COMP_LOOP-2:operator><64,false>#1:acc RESOURCE_NAME COMP_LOOP-1:acc#10:rg
directive set /inPlaceNTT_DIT/inPlaceNTT_DIT:core/inPlaceNTT_DIT:core:conc/COMP_LOOP-1:acc#10 RESOURCE_NAME COMP_LOOP-1:acc#10:rg
directive set /inPlaceNTT_DIT/inPlaceNTT_DIT:core/inPlaceNTT_DIT:core:conc/COMP_LOOP-2:acc#10 RESOURCE_NAME COMP_LOOP-1:acc#10:rg
directive set /inPlaceNTT_DIT/inPlaceNTT_DIT:core/inPlaceNTT_DIT:core:conc/VEC_LOOP:acc#1 RESOURCE_NAME COMP_LOOP-1:acc#10:rg
directive set /inPlaceNTT_DIT/inPlaceNTT_DIT:core/inPlaceNTT_DIT:core:conc/COMP_LOOP-1:operator><64,false>#1:acc RESOURCE_NAME COMP_LOOP-1:acc#10:rg
directive set /inPlaceNTT_DIT/inPlaceNTT_DIT:core/inPlaceNTT_DIT:core:conc/COMP_LOOP:acc#11 RESOURCE_NAME COMP_LOOP:acc#11:rg
directive set /inPlaceNTT_DIT/inPlaceNTT_DIT:core/inPlaceNTT_DIT:core:conc/COMP_LOOP:acc#12 RESOURCE_NAME COMP_LOOP:acc#11:rg
directive set /inPlaceNTT_DIT/inPlaceNTT_DIT:core/inPlaceNTT_DIT:core:conc/COMP_LOOP-2:acc RESOURCE_NAME COMP_LOOP-1:acc#5:rg
directive set /inPlaceNTT_DIT/inPlaceNTT_DIT:core/inPlaceNTT_DIT:core:conc/COMP_LOOP-2:acc#1 RESOURCE_NAME COMP_LOOP-1:acc#5:rg
directive set /inPlaceNTT_DIT/inPlaceNTT_DIT:core/inPlaceNTT_DIT:core:conc/COMP_LOOP-1:acc#5 RESOURCE_NAME COMP_LOOP-1:acc#5:rg
directive set /inPlaceNTT_DIT/inPlaceNTT_DIT:core/inPlaceNTT_DIT:core:conc/operator-<64,false>:acc RESOURCE_NAME COMP_LOOP-1:acc#5:rg
directive set /inPlaceNTT_DIT/inPlaceNTT_DIT:core/inPlaceNTT_DIT:core:conc/operator><64,false>:acc RESOURCE_NAME COMP_LOOP-1:acc#5:rg
directive set /inPlaceNTT_DIT/inPlaceNTT_DIT:core/inPlaceNTT_DIT:core:conc/COMP_LOOP:slc(COMP_LOOP-2:COMP_LOOP:acc RESOURCE_NAME COMP_LOOP-1:acc#5:rg
directive set /inPlaceNTT_DIT/inPlaceNTT_DIT:core/inPlaceNTT_DIT:core:conc/operator><64,false>:acc#1 RESOURCE_NAME COMP_LOOP-1:acc#5:rg
directive set /inPlaceNTT_DIT/inPlaceNTT_DIT:core/inPlaceNTT_DIT:core:conc/modExp:while:if:mul RESOURCE_NAME COMP_LOOP-2:modExp#1:while:if:mul:rg
directive set /inPlaceNTT_DIT/inPlaceNTT_DIT:core/inPlaceNTT_DIT:core:conc/modExp:while:mul RESOURCE_NAME COMP_LOOP-2:modExp#1:while:if:mul:rg
directive set /inPlaceNTT_DIT/inPlaceNTT_DIT:core/inPlaceNTT_DIT:core:conc/COMP_LOOP-2:modExp#1:while:if:mul RESOURCE_NAME COMP_LOOP-2:modExp#1:while:if:mul:rg
