directive set /inPlaceNTT_DIF_precomp/inPlaceNTT_DIF_precomp:core/core/COMP_LOOP:twiddle_help#1.sva REGISTER_NAME COMP_LOOP:twiddle_help#1.sva
directive set /inPlaceNTT_DIF_precomp/inPlaceNTT_DIF_precomp:core/core/COMP_LOOP:twiddle_help#2.sva REGISTER_NAME COMP_LOOP:twiddle_help#1.sva
directive set /inPlaceNTT_DIF_precomp/inPlaceNTT_DIF_precomp:core/core/COMP_LOOP:twiddle_help#3.sva REGISTER_NAME COMP_LOOP:twiddle_help#1.sva
directive set /inPlaceNTT_DIF_precomp/inPlaceNTT_DIF_precomp:core/core/COMP_LOOP:twiddle_help#4.sva REGISTER_NAME COMP_LOOP:twiddle_help#1.sva
directive set /inPlaceNTT_DIF_precomp/inPlaceNTT_DIF_precomp:core/core/COMP_LOOP:twiddle_help#5.sva REGISTER_NAME COMP_LOOP:twiddle_help#1.sva
directive set /inPlaceNTT_DIF_precomp/inPlaceNTT_DIF_precomp:core/core/COMP_LOOP:twiddle_help#6.sva REGISTER_NAME COMP_LOOP:twiddle_help#1.sva
directive set /inPlaceNTT_DIF_precomp/inPlaceNTT_DIF_precomp:core/core/COMP_LOOP:twiddle_help#7.sva REGISTER_NAME COMP_LOOP:twiddle_help#1.sva
directive set /inPlaceNTT_DIF_precomp/inPlaceNTT_DIF_precomp:core/core/COMP_LOOP:twiddle_help.sva REGISTER_NAME COMP_LOOP:twiddle_help#1.sva
directive set /inPlaceNTT_DIF_precomp/inPlaceNTT_DIF_precomp:core/core/COMP_LOOP:twiddle_f#1.sva REGISTER_NAME COMP_LOOP:twiddle_f#1.sva
directive set /inPlaceNTT_DIF_precomp/inPlaceNTT_DIF_precomp:core/core/COMP_LOOP:twiddle_f#2.sva REGISTER_NAME COMP_LOOP:twiddle_f#1.sva
directive set /inPlaceNTT_DIF_precomp/inPlaceNTT_DIF_precomp:core/core/COMP_LOOP:twiddle_f#3.sva REGISTER_NAME COMP_LOOP:twiddle_f#1.sva
directive set /inPlaceNTT_DIF_precomp/inPlaceNTT_DIF_precomp:core/core/COMP_LOOP:twiddle_f#4.sva REGISTER_NAME COMP_LOOP:twiddle_f#1.sva
directive set /inPlaceNTT_DIF_precomp/inPlaceNTT_DIF_precomp:core/core/COMP_LOOP:twiddle_f#5.sva REGISTER_NAME COMP_LOOP:twiddle_f#1.sva
directive set /inPlaceNTT_DIF_precomp/inPlaceNTT_DIF_precomp:core/core/COMP_LOOP:twiddle_f#6.sva REGISTER_NAME COMP_LOOP:twiddle_f#1.sva
directive set /inPlaceNTT_DIF_precomp/inPlaceNTT_DIF_precomp:core/core/COMP_LOOP:twiddle_f#7.sva REGISTER_NAME COMP_LOOP:twiddle_f#1.sva
directive set /inPlaceNTT_DIF_precomp/inPlaceNTT_DIF_precomp:core/core/COMP_LOOP:twiddle_f.sva REGISTER_NAME COMP_LOOP:twiddle_f#1.sva
directive set /inPlaceNTT_DIF_precomp/inPlaceNTT_DIF_precomp:core/core/VEC_LOOP:j(12:0)#1.sva#1 REGISTER_NAME VEC_LOOP:j(12:0)#1.sva#1
directive set /inPlaceNTT_DIF_precomp/inPlaceNTT_DIF_precomp:core/core/VEC_LOOP:j(12:0)#2.sva#1 REGISTER_NAME VEC_LOOP:j(12:0)#1.sva#1
directive set /inPlaceNTT_DIF_precomp/inPlaceNTT_DIF_precomp:core/core/VEC_LOOP:j(12:0)#3.sva#1 REGISTER_NAME VEC_LOOP:j(12:0)#1.sva#1
directive set /inPlaceNTT_DIF_precomp/inPlaceNTT_DIF_precomp:core/core/VEC_LOOP:j(12:0)#4.sva#1 REGISTER_NAME VEC_LOOP:j(12:0)#1.sva#1
directive set /inPlaceNTT_DIF_precomp/inPlaceNTT_DIF_precomp:core/core/VEC_LOOP:j(12:0)#5.sva#1 REGISTER_NAME VEC_LOOP:j(12:0)#1.sva#1
directive set /inPlaceNTT_DIF_precomp/inPlaceNTT_DIF_precomp:core/core/VEC_LOOP:j(12:0)#6.sva#1 REGISTER_NAME VEC_LOOP:j(12:0)#1.sva#1
directive set /inPlaceNTT_DIF_precomp/inPlaceNTT_DIF_precomp:core/core/VEC_LOOP:j(12:0)#7.sva#1 REGISTER_NAME VEC_LOOP:j(12:0)#1.sva#1
directive set /inPlaceNTT_DIF_precomp/inPlaceNTT_DIF_precomp:core/core/VEC_LOOP:j(12:0).sva#1 REGISTER_NAME VEC_LOOP:j(12:0)#1.sva#1
directive set /inPlaceNTT_DIF_precomp/inPlaceNTT_DIF_precomp:core/core/VEC_LOOP:acc#10.cse#1.sva REGISTER_NAME VEC_LOOP:acc#10.cse#1.sva
directive set /inPlaceNTT_DIF_precomp/inPlaceNTT_DIF_precomp:core/core/VEC_LOOP:acc#10.cse#2.sva REGISTER_NAME VEC_LOOP:acc#10.cse#1.sva
directive set /inPlaceNTT_DIF_precomp/inPlaceNTT_DIF_precomp:core/core/VEC_LOOP:acc#10.cse#3.sva REGISTER_NAME VEC_LOOP:acc#10.cse#1.sva
directive set /inPlaceNTT_DIF_precomp/inPlaceNTT_DIF_precomp:core/core/VEC_LOOP:acc#10.cse#4.sva REGISTER_NAME VEC_LOOP:acc#10.cse#1.sva
directive set /inPlaceNTT_DIF_precomp/inPlaceNTT_DIF_precomp:core/core/VEC_LOOP:acc#10.cse#5.sva REGISTER_NAME VEC_LOOP:acc#10.cse#1.sva
directive set /inPlaceNTT_DIF_precomp/inPlaceNTT_DIF_precomp:core/core/VEC_LOOP:acc#10.cse#6.sva REGISTER_NAME VEC_LOOP:acc#10.cse#1.sva
directive set /inPlaceNTT_DIF_precomp/inPlaceNTT_DIF_precomp:core/core/VEC_LOOP:acc#10.cse#7.sva REGISTER_NAME VEC_LOOP:acc#10.cse#1.sva
directive set /inPlaceNTT_DIF_precomp/inPlaceNTT_DIF_precomp:core/core/VEC_LOOP:acc#10.cse.sva REGISTER_NAME VEC_LOOP:acc#10.cse#1.sva
directive set /inPlaceNTT_DIF_precomp/inPlaceNTT_DIF_precomp:core/core/VEC_LOOP:acc#1.cse#2.sva REGISTER_NAME VEC_LOOP:acc#1.cse#2.sva
directive set /inPlaceNTT_DIF_precomp/inPlaceNTT_DIF_precomp:core/core/VEC_LOOP:acc#1.cse#4.sva REGISTER_NAME VEC_LOOP:acc#1.cse#2.sva
directive set /inPlaceNTT_DIF_precomp/inPlaceNTT_DIF_precomp:core/core/VEC_LOOP:acc#1.cse#6.sva REGISTER_NAME VEC_LOOP:acc#1.cse#2.sva
directive set /inPlaceNTT_DIF_precomp/inPlaceNTT_DIF_precomp:core/core/VEC_LOOP:acc#1.cse.sva REGISTER_NAME VEC_LOOP:acc#1.cse#2.sva
directive set /inPlaceNTT_DIF_precomp/inPlaceNTT_DIF_precomp:core/core/VEC_LOOP:j(12:0)#2.sva(11:0) REGISTER_NAME VEC_LOOP:acc#1.cse#2.sva
directive set /inPlaceNTT_DIF_precomp/inPlaceNTT_DIF_precomp:core/core/VEC_LOOP:j(12:0)#4.sva(11:0) REGISTER_NAME VEC_LOOP:acc#1.cse#2.sva
directive set /inPlaceNTT_DIF_precomp/inPlaceNTT_DIF_precomp:core/core/VEC_LOOP:j(12:0)#6.sva(11:0) REGISTER_NAME VEC_LOOP:acc#1.cse#2.sva
directive set /inPlaceNTT_DIF_precomp/inPlaceNTT_DIF_precomp:core/core/VEC_LOOP:j(12:0).sva(11:0) REGISTER_NAME VEC_LOOP:acc#1.cse#2.sva
directive set /inPlaceNTT_DIF_precomp/inPlaceNTT_DIF_precomp:core/core/VEC_LOOP:j(12:0)#7.sva(11:0) REGISTER_NAME VEC_LOOP:acc#1.cse#2.sva
directive set /inPlaceNTT_DIF_precomp/inPlaceNTT_DIF_precomp:core/core/VEC_LOOP:j(12:0)#3.sva(11:0) REGISTER_NAME VEC_LOOP:acc#1.cse#2.sva
directive set /inPlaceNTT_DIF_precomp/inPlaceNTT_DIF_precomp:core/core/VEC_LOOP:j(12:0)#5.sva(11:0) REGISTER_NAME VEC_LOOP:acc#1.cse#2.sva
directive set /inPlaceNTT_DIF_precomp/inPlaceNTT_DIF_precomp:core/core/VEC_LOOP:j(12:0)#1.sva(11:0) REGISTER_NAME VEC_LOOP:acc#1.cse#2.sva
directive set /inPlaceNTT_DIF_precomp/inPlaceNTT_DIF_precomp:core/core/VEC_LOOP:acc#11.psp.sva REGISTER_NAME VEC_LOOP:acc#11.psp.sva
directive set /inPlaceNTT_DIF_precomp/inPlaceNTT_DIF_precomp:core/core/VEC_LOOP:acc#13.psp.sva REGISTER_NAME VEC_LOOP:acc#11.psp.sva
directive set /inPlaceNTT_DIF_precomp/inPlaceNTT_DIF_precomp:core/core/VEC_LOOP:acc.psp.sva REGISTER_NAME VEC_LOOP:acc#11.psp.sva
directive set /inPlaceNTT_DIF_precomp/inPlaceNTT_DIF_precomp:core/core/COMP_LOOP-5:twiddle_f:lshift.itm REGISTER_NAME VEC_LOOP:acc#11.psp.sva
directive set /inPlaceNTT_DIF_precomp/inPlaceNTT_DIF_precomp:core/core/VEC_LOOP:acc#12.psp.sva REGISTER_NAME VEC_LOOP:acc#11.psp.sva
