
# Loop constraints
directive set /fir_filter/core/core:rlp CSTEPS_FROM {{. == 0}}
directive set /fir_filter/core/core:rlp/main CSTEPS_FROM {{. == 3} {.. == 0}}
directive set /fir_filter/core/core:rlp/main/SHIFT_LOOP CSTEPS_FROM {{. == 1} {.. == 1}}
directive set /fir_filter/core/core:rlp/main/MAC_LOOP CSTEPS_FROM {{. == 1} {.. == 1}}

# IO operation constraints
directive set /fir_filter/core/core:rlp/main/i_sample:io_read(i_sample:rsc.@) CSTEPS_FROM {{.. == 1}}
directive set /fir_filter/core/core:rlp/main/MAC_LOOP/MAC_LOOP:io_read(b:rsc.@) CSTEPS_FROM {{.. == 1}}
directive set /fir_filter/core/core:rlp/main/io_write(y:rsc.@) CSTEPS_FROM {{.. == 2}}

# Sync operation constraints

# Real operation constraints
directive set /fir_filter/core/core:rlp/main/SHIFT_LOOP/SHIFT_LOOP:acc#2 CSTEPS_FROM {{.. == 1}}
directive set /fir_filter/core/core:rlp/main/SHIFT_LOOP/SHIFT_LOOP:mux#126 CSTEPS_FROM {{.. == 1}}
directive set /fir_filter/core/core:rlp/main/SHIFT_LOOP/SHIFT_LOOP:mux CSTEPS_FROM {{.. == 1}}
directive set /fir_filter/core/core:rlp/main/SHIFT_LOOP/SHIFT_LOOP:mux#1 CSTEPS_FROM {{.. == 1}}
directive set /fir_filter/core/core:rlp/main/SHIFT_LOOP/SHIFT_LOOP:mux#2 CSTEPS_FROM {{.. == 1}}
directive set /fir_filter/core/core:rlp/main/SHIFT_LOOP/SHIFT_LOOP:mux#3 CSTEPS_FROM {{.. == 1}}
directive set /fir_filter/core/core:rlp/main/SHIFT_LOOP/SHIFT_LOOP:mux#4 CSTEPS_FROM {{.. == 1}}
directive set /fir_filter/core/core:rlp/main/SHIFT_LOOP/SHIFT_LOOP:mux#5 CSTEPS_FROM {{.. == 1}}
directive set /fir_filter/core/core:rlp/main/SHIFT_LOOP/SHIFT_LOOP:mux#6 CSTEPS_FROM {{.. == 1}}
directive set /fir_filter/core/core:rlp/main/SHIFT_LOOP/SHIFT_LOOP:mux#7 CSTEPS_FROM {{.. == 1}}
directive set /fir_filter/core/core:rlp/main/SHIFT_LOOP/SHIFT_LOOP:mux#8 CSTEPS_FROM {{.. == 1}}
directive set /fir_filter/core/core:rlp/main/SHIFT_LOOP/SHIFT_LOOP:mux#9 CSTEPS_FROM {{.. == 1}}
directive set /fir_filter/core/core:rlp/main/SHIFT_LOOP/SHIFT_LOOP:mux#10 CSTEPS_FROM {{.. == 1}}
directive set /fir_filter/core/core:rlp/main/SHIFT_LOOP/SHIFT_LOOP:mux#11 CSTEPS_FROM {{.. == 1}}
directive set /fir_filter/core/core:rlp/main/SHIFT_LOOP/SHIFT_LOOP:mux#12 CSTEPS_FROM {{.. == 1}}
directive set /fir_filter/core/core:rlp/main/SHIFT_LOOP/SHIFT_LOOP:mux#13 CSTEPS_FROM {{.. == 1}}
directive set /fir_filter/core/core:rlp/main/SHIFT_LOOP/SHIFT_LOOP:mux#14 CSTEPS_FROM {{.. == 1}}
directive set /fir_filter/core/core:rlp/main/SHIFT_LOOP/SHIFT_LOOP:mux#15 CSTEPS_FROM {{.. == 1}}
directive set /fir_filter/core/core:rlp/main/SHIFT_LOOP/SHIFT_LOOP:mux#16 CSTEPS_FROM {{.. == 1}}
directive set /fir_filter/core/core:rlp/main/SHIFT_LOOP/SHIFT_LOOP:mux#17 CSTEPS_FROM {{.. == 1}}
directive set /fir_filter/core/core:rlp/main/SHIFT_LOOP/SHIFT_LOOP:mux#18 CSTEPS_FROM {{.. == 1}}
directive set /fir_filter/core/core:rlp/main/SHIFT_LOOP/SHIFT_LOOP:mux#19 CSTEPS_FROM {{.. == 1}}
directive set /fir_filter/core/core:rlp/main/SHIFT_LOOP/SHIFT_LOOP:mux#20 CSTEPS_FROM {{.. == 1}}
directive set /fir_filter/core/core:rlp/main/SHIFT_LOOP/SHIFT_LOOP:mux#21 CSTEPS_FROM {{.. == 1}}
directive set /fir_filter/core/core:rlp/main/SHIFT_LOOP/SHIFT_LOOP:mux#22 CSTEPS_FROM {{.. == 1}}
directive set /fir_filter/core/core:rlp/main/SHIFT_LOOP/SHIFT_LOOP:mux#23 CSTEPS_FROM {{.. == 1}}
directive set /fir_filter/core/core:rlp/main/SHIFT_LOOP/SHIFT_LOOP:mux#24 CSTEPS_FROM {{.. == 1}}
directive set /fir_filter/core/core:rlp/main/SHIFT_LOOP/SHIFT_LOOP:mux#25 CSTEPS_FROM {{.. == 1}}
directive set /fir_filter/core/core:rlp/main/SHIFT_LOOP/SHIFT_LOOP:mux#26 CSTEPS_FROM {{.. == 1}}
directive set /fir_filter/core/core:rlp/main/SHIFT_LOOP/SHIFT_LOOP:mux#27 CSTEPS_FROM {{.. == 1}}
directive set /fir_filter/core/core:rlp/main/SHIFT_LOOP/SHIFT_LOOP:mux#28 CSTEPS_FROM {{.. == 1}}
directive set /fir_filter/core/core:rlp/main/SHIFT_LOOP/SHIFT_LOOP:mux#29 CSTEPS_FROM {{.. == 1}}
directive set /fir_filter/core/core:rlp/main/SHIFT_LOOP/SHIFT_LOOP:mux#30 CSTEPS_FROM {{.. == 1}}
directive set /fir_filter/core/core:rlp/main/SHIFT_LOOP/SHIFT_LOOP:mux#31 CSTEPS_FROM {{.. == 1}}
directive set /fir_filter/core/core:rlp/main/SHIFT_LOOP/SHIFT_LOOP:mux#32 CSTEPS_FROM {{.. == 1}}
directive set /fir_filter/core/core:rlp/main/SHIFT_LOOP/SHIFT_LOOP:mux#33 CSTEPS_FROM {{.. == 1}}
directive set /fir_filter/core/core:rlp/main/SHIFT_LOOP/SHIFT_LOOP:mux#34 CSTEPS_FROM {{.. == 1}}
directive set /fir_filter/core/core:rlp/main/SHIFT_LOOP/SHIFT_LOOP:mux#35 CSTEPS_FROM {{.. == 1}}
directive set /fir_filter/core/core:rlp/main/SHIFT_LOOP/SHIFT_LOOP:mux#36 CSTEPS_FROM {{.. == 1}}
directive set /fir_filter/core/core:rlp/main/SHIFT_LOOP/SHIFT_LOOP:mux#37 CSTEPS_FROM {{.. == 1}}
directive set /fir_filter/core/core:rlp/main/SHIFT_LOOP/SHIFT_LOOP:mux#38 CSTEPS_FROM {{.. == 1}}
directive set /fir_filter/core/core:rlp/main/SHIFT_LOOP/SHIFT_LOOP:mux#39 CSTEPS_FROM {{.. == 1}}
directive set /fir_filter/core/core:rlp/main/SHIFT_LOOP/SHIFT_LOOP:mux#40 CSTEPS_FROM {{.. == 1}}
directive set /fir_filter/core/core:rlp/main/SHIFT_LOOP/SHIFT_LOOP:mux#41 CSTEPS_FROM {{.. == 1}}
directive set /fir_filter/core/core:rlp/main/SHIFT_LOOP/SHIFT_LOOP:mux#42 CSTEPS_FROM {{.. == 1}}
directive set /fir_filter/core/core:rlp/main/SHIFT_LOOP/SHIFT_LOOP:mux#43 CSTEPS_FROM {{.. == 1}}
directive set /fir_filter/core/core:rlp/main/SHIFT_LOOP/SHIFT_LOOP:mux#44 CSTEPS_FROM {{.. == 1}}
directive set /fir_filter/core/core:rlp/main/SHIFT_LOOP/SHIFT_LOOP:mux#45 CSTEPS_FROM {{.. == 1}}
directive set /fir_filter/core/core:rlp/main/SHIFT_LOOP/SHIFT_LOOP:mux#46 CSTEPS_FROM {{.. == 1}}
directive set /fir_filter/core/core:rlp/main/SHIFT_LOOP/SHIFT_LOOP:mux#47 CSTEPS_FROM {{.. == 1}}
directive set /fir_filter/core/core:rlp/main/SHIFT_LOOP/SHIFT_LOOP:mux#48 CSTEPS_FROM {{.. == 1}}
directive set /fir_filter/core/core:rlp/main/SHIFT_LOOP/SHIFT_LOOP:mux#49 CSTEPS_FROM {{.. == 1}}
directive set /fir_filter/core/core:rlp/main/SHIFT_LOOP/SHIFT_LOOP:mux#50 CSTEPS_FROM {{.. == 1}}
directive set /fir_filter/core/core:rlp/main/SHIFT_LOOP/SHIFT_LOOP:mux#51 CSTEPS_FROM {{.. == 1}}
directive set /fir_filter/core/core:rlp/main/SHIFT_LOOP/SHIFT_LOOP:mux#52 CSTEPS_FROM {{.. == 1}}
directive set /fir_filter/core/core:rlp/main/SHIFT_LOOP/SHIFT_LOOP:mux#53 CSTEPS_FROM {{.. == 1}}
directive set /fir_filter/core/core:rlp/main/SHIFT_LOOP/SHIFT_LOOP:mux#54 CSTEPS_FROM {{.. == 1}}
directive set /fir_filter/core/core:rlp/main/SHIFT_LOOP/SHIFT_LOOP:mux#55 CSTEPS_FROM {{.. == 1}}
directive set /fir_filter/core/core:rlp/main/SHIFT_LOOP/SHIFT_LOOP:mux#56 CSTEPS_FROM {{.. == 1}}
directive set /fir_filter/core/core:rlp/main/SHIFT_LOOP/SHIFT_LOOP:mux#57 CSTEPS_FROM {{.. == 1}}
directive set /fir_filter/core/core:rlp/main/SHIFT_LOOP/SHIFT_LOOP:mux#58 CSTEPS_FROM {{.. == 1}}
directive set /fir_filter/core/core:rlp/main/SHIFT_LOOP/SHIFT_LOOP:mux#59 CSTEPS_FROM {{.. == 1}}
directive set /fir_filter/core/core:rlp/main/SHIFT_LOOP/SHIFT_LOOP:mux#60 CSTEPS_FROM {{.. == 1}}
directive set /fir_filter/core/core:rlp/main/SHIFT_LOOP/SHIFT_LOOP:mux#61 CSTEPS_FROM {{.. == 1}}
directive set /fir_filter/core/core:rlp/main/SHIFT_LOOP/SHIFT_LOOP:mux#62 CSTEPS_FROM {{.. == 1}}
directive set /fir_filter/core/core:rlp/main/SHIFT_LOOP/SHIFT_LOOP:mux#63 CSTEPS_FROM {{.. == 1}}
directive set /fir_filter/core/core:rlp/main/SHIFT_LOOP/SHIFT_LOOP:mux#64 CSTEPS_FROM {{.. == 1}}
directive set /fir_filter/core/core:rlp/main/SHIFT_LOOP/SHIFT_LOOP:mux#65 CSTEPS_FROM {{.. == 1}}
directive set /fir_filter/core/core:rlp/main/SHIFT_LOOP/SHIFT_LOOP:mux#66 CSTEPS_FROM {{.. == 1}}
directive set /fir_filter/core/core:rlp/main/SHIFT_LOOP/SHIFT_LOOP:mux#67 CSTEPS_FROM {{.. == 1}}
directive set /fir_filter/core/core:rlp/main/SHIFT_LOOP/SHIFT_LOOP:mux#68 CSTEPS_FROM {{.. == 1}}
directive set /fir_filter/core/core:rlp/main/SHIFT_LOOP/SHIFT_LOOP:mux#69 CSTEPS_FROM {{.. == 1}}
directive set /fir_filter/core/core:rlp/main/SHIFT_LOOP/SHIFT_LOOP:mux#70 CSTEPS_FROM {{.. == 1}}
directive set /fir_filter/core/core:rlp/main/SHIFT_LOOP/SHIFT_LOOP:mux#71 CSTEPS_FROM {{.. == 1}}
directive set /fir_filter/core/core:rlp/main/SHIFT_LOOP/SHIFT_LOOP:mux#72 CSTEPS_FROM {{.. == 1}}
directive set /fir_filter/core/core:rlp/main/SHIFT_LOOP/SHIFT_LOOP:mux#73 CSTEPS_FROM {{.. == 1}}
directive set /fir_filter/core/core:rlp/main/SHIFT_LOOP/SHIFT_LOOP:mux#74 CSTEPS_FROM {{.. == 1}}
directive set /fir_filter/core/core:rlp/main/SHIFT_LOOP/SHIFT_LOOP:mux#75 CSTEPS_FROM {{.. == 1}}
directive set /fir_filter/core/core:rlp/main/SHIFT_LOOP/SHIFT_LOOP:mux#76 CSTEPS_FROM {{.. == 1}}
directive set /fir_filter/core/core:rlp/main/SHIFT_LOOP/SHIFT_LOOP:mux#77 CSTEPS_FROM {{.. == 1}}
directive set /fir_filter/core/core:rlp/main/SHIFT_LOOP/SHIFT_LOOP:mux#78 CSTEPS_FROM {{.. == 1}}
directive set /fir_filter/core/core:rlp/main/SHIFT_LOOP/SHIFT_LOOP:mux#79 CSTEPS_FROM {{.. == 1}}
directive set /fir_filter/core/core:rlp/main/SHIFT_LOOP/SHIFT_LOOP:mux#80 CSTEPS_FROM {{.. == 1}}
directive set /fir_filter/core/core:rlp/main/SHIFT_LOOP/SHIFT_LOOP:mux#81 CSTEPS_FROM {{.. == 1}}
directive set /fir_filter/core/core:rlp/main/SHIFT_LOOP/SHIFT_LOOP:mux#82 CSTEPS_FROM {{.. == 1}}
directive set /fir_filter/core/core:rlp/main/SHIFT_LOOP/SHIFT_LOOP:mux#83 CSTEPS_FROM {{.. == 1}}
directive set /fir_filter/core/core:rlp/main/SHIFT_LOOP/SHIFT_LOOP:mux#84 CSTEPS_FROM {{.. == 1}}
directive set /fir_filter/core/core:rlp/main/SHIFT_LOOP/SHIFT_LOOP:mux#85 CSTEPS_FROM {{.. == 1}}
directive set /fir_filter/core/core:rlp/main/SHIFT_LOOP/SHIFT_LOOP:mux#86 CSTEPS_FROM {{.. == 1}}
directive set /fir_filter/core/core:rlp/main/SHIFT_LOOP/SHIFT_LOOP:mux#87 CSTEPS_FROM {{.. == 1}}
directive set /fir_filter/core/core:rlp/main/SHIFT_LOOP/SHIFT_LOOP:mux#88 CSTEPS_FROM {{.. == 1}}
directive set /fir_filter/core/core:rlp/main/SHIFT_LOOP/SHIFT_LOOP:mux#89 CSTEPS_FROM {{.. == 1}}
directive set /fir_filter/core/core:rlp/main/SHIFT_LOOP/SHIFT_LOOP:mux#90 CSTEPS_FROM {{.. == 1}}
directive set /fir_filter/core/core:rlp/main/SHIFT_LOOP/SHIFT_LOOP:mux#91 CSTEPS_FROM {{.. == 1}}
directive set /fir_filter/core/core:rlp/main/SHIFT_LOOP/SHIFT_LOOP:mux#92 CSTEPS_FROM {{.. == 1}}
directive set /fir_filter/core/core:rlp/main/SHIFT_LOOP/SHIFT_LOOP:mux#93 CSTEPS_FROM {{.. == 1}}
directive set /fir_filter/core/core:rlp/main/SHIFT_LOOP/SHIFT_LOOP:mux#94 CSTEPS_FROM {{.. == 1}}
directive set /fir_filter/core/core:rlp/main/SHIFT_LOOP/SHIFT_LOOP:mux#95 CSTEPS_FROM {{.. == 1}}
directive set /fir_filter/core/core:rlp/main/SHIFT_LOOP/SHIFT_LOOP:mux#96 CSTEPS_FROM {{.. == 1}}
directive set /fir_filter/core/core:rlp/main/SHIFT_LOOP/SHIFT_LOOP:mux#97 CSTEPS_FROM {{.. == 1}}
directive set /fir_filter/core/core:rlp/main/SHIFT_LOOP/SHIFT_LOOP:mux#98 CSTEPS_FROM {{.. == 1}}
directive set /fir_filter/core/core:rlp/main/SHIFT_LOOP/SHIFT_LOOP:mux#99 CSTEPS_FROM {{.. == 1}}
directive set /fir_filter/core/core:rlp/main/SHIFT_LOOP/SHIFT_LOOP:mux#100 CSTEPS_FROM {{.. == 1}}
directive set /fir_filter/core/core:rlp/main/SHIFT_LOOP/SHIFT_LOOP:mux#101 CSTEPS_FROM {{.. == 1}}
directive set /fir_filter/core/core:rlp/main/SHIFT_LOOP/SHIFT_LOOP:mux#102 CSTEPS_FROM {{.. == 1}}
directive set /fir_filter/core/core:rlp/main/SHIFT_LOOP/SHIFT_LOOP:mux#103 CSTEPS_FROM {{.. == 1}}
directive set /fir_filter/core/core:rlp/main/SHIFT_LOOP/SHIFT_LOOP:mux#104 CSTEPS_FROM {{.. == 1}}
directive set /fir_filter/core/core:rlp/main/SHIFT_LOOP/SHIFT_LOOP:mux#105 CSTEPS_FROM {{.. == 1}}
directive set /fir_filter/core/core:rlp/main/SHIFT_LOOP/SHIFT_LOOP:mux#106 CSTEPS_FROM {{.. == 1}}
directive set /fir_filter/core/core:rlp/main/SHIFT_LOOP/SHIFT_LOOP:mux#107 CSTEPS_FROM {{.. == 1}}
directive set /fir_filter/core/core:rlp/main/SHIFT_LOOP/SHIFT_LOOP:mux#108 CSTEPS_FROM {{.. == 1}}
directive set /fir_filter/core/core:rlp/main/SHIFT_LOOP/SHIFT_LOOP:mux#109 CSTEPS_FROM {{.. == 1}}
directive set /fir_filter/core/core:rlp/main/SHIFT_LOOP/SHIFT_LOOP:mux#110 CSTEPS_FROM {{.. == 1}}
directive set /fir_filter/core/core:rlp/main/SHIFT_LOOP/SHIFT_LOOP:mux#111 CSTEPS_FROM {{.. == 1}}
directive set /fir_filter/core/core:rlp/main/SHIFT_LOOP/SHIFT_LOOP:mux#112 CSTEPS_FROM {{.. == 1}}
directive set /fir_filter/core/core:rlp/main/SHIFT_LOOP/SHIFT_LOOP:mux#113 CSTEPS_FROM {{.. == 1}}
directive set /fir_filter/core/core:rlp/main/SHIFT_LOOP/SHIFT_LOOP:mux#114 CSTEPS_FROM {{.. == 1}}
directive set /fir_filter/core/core:rlp/main/SHIFT_LOOP/SHIFT_LOOP:mux#115 CSTEPS_FROM {{.. == 1}}
directive set /fir_filter/core/core:rlp/main/SHIFT_LOOP/SHIFT_LOOP:mux#116 CSTEPS_FROM {{.. == 1}}
directive set /fir_filter/core/core:rlp/main/SHIFT_LOOP/SHIFT_LOOP:mux#117 CSTEPS_FROM {{.. == 1}}
directive set /fir_filter/core/core:rlp/main/SHIFT_LOOP/SHIFT_LOOP:mux#118 CSTEPS_FROM {{.. == 1}}
directive set /fir_filter/core/core:rlp/main/SHIFT_LOOP/SHIFT_LOOP:mux#119 CSTEPS_FROM {{.. == 1}}
directive set /fir_filter/core/core:rlp/main/SHIFT_LOOP/SHIFT_LOOP:mux#120 CSTEPS_FROM {{.. == 1}}
directive set /fir_filter/core/core:rlp/main/SHIFT_LOOP/SHIFT_LOOP:mux#121 CSTEPS_FROM {{.. == 1}}
directive set /fir_filter/core/core:rlp/main/SHIFT_LOOP/SHIFT_LOOP:mux#122 CSTEPS_FROM {{.. == 1}}
directive set /fir_filter/core/core:rlp/main/SHIFT_LOOP/SHIFT_LOOP:mux#123 CSTEPS_FROM {{.. == 1}}
directive set /fir_filter/core/core:rlp/main/SHIFT_LOOP/SHIFT_LOOP:mux#124 CSTEPS_FROM {{.. == 1}}
directive set /fir_filter/core/core:rlp/main/SHIFT_LOOP/SHIFT_LOOP:mux#125 CSTEPS_FROM {{.. == 1}}
directive set /fir_filter/core/core:rlp/main/SHIFT_LOOP/SHIFT_LOOP:acc CSTEPS_FROM {{.. == 1}}
directive set /fir_filter/core/core:rlp/main/MAC_LOOP/MAC_LOOP:mux CSTEPS_FROM {{.. == 1}}
directive set /fir_filter/core/core:rlp/main/MAC_LOOP/MAC_LOOP:mux#1 CSTEPS_FROM {{.. == 1}}
directive set /fir_filter/core/core:rlp/main/MAC_LOOP/MAC_LOOP:mul CSTEPS_FROM {{.. == 1}}
directive set /fir_filter/core/core:rlp/main/MAC_LOOP/MAC_LOOP:acc#1 CSTEPS_FROM {{.. == 1}}
directive set /fir_filter/core/core:rlp/main/MAC_LOOP/MAC_LOOP:acc#2 CSTEPS_FROM {{.. == 1}}
directive set /fir_filter/core/core:rlp/main/MAC_LOOP/MAC_LOOP:acc CSTEPS_FROM {{.. == 1}}
directive set /fir_filter/core/core:rlp/main/acc CSTEPS_FROM {{.. == 2}}
directive set /fir_filter/core/core:rlp/main/nor#5 CSTEPS_FROM {{.. == 2}}
directive set /fir_filter/core/core:rlp/main/nor#4 CSTEPS_FROM {{.. == 2}}

# Probe constraints
