directive set /peaseNTT/peaseNTT:core/core/c(1).sva REGISTER_NAME c(1).sva
directive set /peaseNTT/peaseNTT:core/core/c(1).sva#1 REGISTER_NAME c(1).sva
directive set /peaseNTT/peaseNTT:core/core/operator-<20,false>:acc.cse.sva REGISTER_NAME operator-<20,false>:acc.cse.sva
directive set /peaseNTT/peaseNTT:core/core/operator<<<33,true>#2:lshift.psp(2:0).sva REGISTER_NAME operator-<20,false>:acc.cse.sva
directive set /peaseNTT/peaseNTT:core/core/c(3:2).sva REGISTER_NAME operator-<20,false>:acc.cse.sva
directive set /peaseNTT/peaseNTT:core/core/operator<<<33,true>#3:lshift.psp(1:0).sva REGISTER_NAME operator-<20,false>:acc.cse.sva
directive set /peaseNTT/peaseNTT:core/core/INNER_LOOP1:r(9:0).sva(8:0) REGISTER_NAME INNER_LOOP1:r(9:0).sva(8:0)
directive set /peaseNTT/peaseNTT:core/core/INNER_LOOP2:r(9:0).sva(8:0) REGISTER_NAME INNER_LOOP1:r(9:0).sva(8:0)
directive set /peaseNTT/peaseNTT:core/core/INNER_LOOP3:r(9:0).sva(8:0) REGISTER_NAME INNER_LOOP1:r(9:0).sva(8:0)
directive set /peaseNTT/peaseNTT:core/core/INNER_LOOP4:r(9:0).sva(8:0) REGISTER_NAME INNER_LOOP1:r(9:0).sva(8:0)
directive set /peaseNTT/peaseNTT:core/core/operator<<<33,true>:return(8:0).sva REGISTER_NAME operator<<<33,true>:return(8:0).sva
directive set /peaseNTT/peaseNTT:core/core/operator<<<33,true>#1:lshift.psp(7:0).sva REGISTER_NAME operator<<<33,true>:return(8:0).sva
directive set /peaseNTT/peaseNTT:core/core/INNER_LOOP1:r(9:0).sva#1 REGISTER_NAME INNER_LOOP1:r(9:0).sva#1
directive set /peaseNTT/peaseNTT:core/core/INNER_LOOP2:r(9:0).sva#1 REGISTER_NAME INNER_LOOP1:r(9:0).sva#1
directive set /peaseNTT/peaseNTT:core/core/INNER_LOOP3:r(9:0).sva#1 REGISTER_NAME INNER_LOOP1:r(9:0).sva#1
directive set /peaseNTT/peaseNTT:core/core/INNER_LOOP4:r(9:0).sva#1 REGISTER_NAME INNER_LOOP1:r(9:0).sva#1
directive set /peaseNTT/peaseNTT:core/core/butterFly1#1:f1.sva REGISTER_NAME butterFly1#1:f1.sva
directive set /peaseNTT/peaseNTT:core/core/butterFly1:f1.sva REGISTER_NAME butterFly1#1:f1.sva
directive set /peaseNTT/peaseNTT:core/core/butterFly2#1:f1.sva REGISTER_NAME butterFly1#1:f1.sva
directive set /peaseNTT/peaseNTT:core/core/butterFly2:f1.sva REGISTER_NAME butterFly1#1:f1.sva
directive set /peaseNTT/peaseNTT:core/core/butterFly1#1:f2:asn.itm REGISTER_NAME butterFly1#1:f1.sva
directive set /peaseNTT/peaseNTT:core/core/butterFly1#1:modulo_add(return).sva REGISTER_NAME butterFly1#1:f1.sva
directive set /peaseNTT/peaseNTT:core/core/butterFly1:modulo_add(return).sva REGISTER_NAME butterFly1#1:f1.sva
directive set /peaseNTT/peaseNTT:core/core/butterFly2#1:f2:asn.itm REGISTER_NAME butterFly1#1:f1.sva
directive set /peaseNTT/peaseNTT:core/core/butterFly2#1:modulo_add(return).sva REGISTER_NAME butterFly1#1:f1.sva
directive set /peaseNTT/peaseNTT:core/core/butterFly2:modulo_add(return).sva REGISTER_NAME butterFly1#1:f1.sva
