directive set /inPlaceNTT_DIT_precomp/inPlaceNTT_DIT_precomp:core/core/COMP_LOOP:twiddle_help#1.sva REGISTER_NAME COMP_LOOP:twiddle_help#1.sva
directive set /inPlaceNTT_DIT_precomp/inPlaceNTT_DIT_precomp:core/core/COMP_LOOP:twiddle_help#2.sva REGISTER_NAME COMP_LOOP:twiddle_help#1.sva
directive set /inPlaceNTT_DIT_precomp/inPlaceNTT_DIT_precomp:core/core/COMP_LOOP:twiddle_help#3.sva REGISTER_NAME COMP_LOOP:twiddle_help#1.sva
directive set /inPlaceNTT_DIT_precomp/inPlaceNTT_DIT_precomp:core/core/COMP_LOOP:twiddle_help#4.sva REGISTER_NAME COMP_LOOP:twiddle_help#1.sva
directive set /inPlaceNTT_DIT_precomp/inPlaceNTT_DIT_precomp:core/core/COMP_LOOP:twiddle_help#5.sva REGISTER_NAME COMP_LOOP:twiddle_help#1.sva
directive set /inPlaceNTT_DIT_precomp/inPlaceNTT_DIT_precomp:core/core/COMP_LOOP:twiddle_help#6.sva REGISTER_NAME COMP_LOOP:twiddle_help#1.sva
directive set /inPlaceNTT_DIT_precomp/inPlaceNTT_DIT_precomp:core/core/COMP_LOOP:twiddle_help#7.sva REGISTER_NAME COMP_LOOP:twiddle_help#1.sva
directive set /inPlaceNTT_DIT_precomp/inPlaceNTT_DIT_precomp:core/core/COMP_LOOP:twiddle_help.sva REGISTER_NAME COMP_LOOP:twiddle_help#1.sva
directive set /inPlaceNTT_DIT_precomp/inPlaceNTT_DIT_precomp:core/core/COMP_LOOP:twiddle_f#1.sva REGISTER_NAME COMP_LOOP:twiddle_f#1.sva
directive set /inPlaceNTT_DIT_precomp/inPlaceNTT_DIT_precomp:core/core/COMP_LOOP:twiddle_f#2.sva REGISTER_NAME COMP_LOOP:twiddle_f#1.sva
directive set /inPlaceNTT_DIT_precomp/inPlaceNTT_DIT_precomp:core/core/COMP_LOOP:twiddle_f#3.sva REGISTER_NAME COMP_LOOP:twiddle_f#1.sva
directive set /inPlaceNTT_DIT_precomp/inPlaceNTT_DIT_precomp:core/core/COMP_LOOP:twiddle_f#4.sva REGISTER_NAME COMP_LOOP:twiddle_f#1.sva
directive set /inPlaceNTT_DIT_precomp/inPlaceNTT_DIT_precomp:core/core/COMP_LOOP:twiddle_f#5.sva REGISTER_NAME COMP_LOOP:twiddle_f#1.sva
directive set /inPlaceNTT_DIT_precomp/inPlaceNTT_DIT_precomp:core/core/COMP_LOOP:twiddle_f#6.sva REGISTER_NAME COMP_LOOP:twiddle_f#1.sva
directive set /inPlaceNTT_DIT_precomp/inPlaceNTT_DIT_precomp:core/core/COMP_LOOP:twiddle_f#7.sva REGISTER_NAME COMP_LOOP:twiddle_f#1.sva
directive set /inPlaceNTT_DIT_precomp/inPlaceNTT_DIT_precomp:core/core/COMP_LOOP:twiddle_f.sva REGISTER_NAME COMP_LOOP:twiddle_f#1.sva
directive set /inPlaceNTT_DIT_precomp/inPlaceNTT_DIT_precomp:core/core/COMP_LOOP-1:VEC_LOOP:slc(VEC_LOOP:acc)(22).itm REGISTER_NAME COMP_LOOP-1:VEC_LOOP:slc(VEC_LOOP:acc)(22).itm
directive set /inPlaceNTT_DIT_precomp/inPlaceNTT_DIT_precomp:core/core/run_ac_sync_tmp_dobj.sva REGISTER_NAME COMP_LOOP-1:VEC_LOOP:slc(VEC_LOOP:acc)(22).itm
directive set /inPlaceNTT_DIT_precomp/inPlaceNTT_DIT_precomp:core/core/VEC_LOOP:acc#10.cse#1.sva REGISTER_NAME VEC_LOOP:acc#10.cse#1.sva
directive set /inPlaceNTT_DIT_precomp/inPlaceNTT_DIT_precomp:core/core/VEC_LOOP:acc#10.cse#2.sva REGISTER_NAME VEC_LOOP:acc#10.cse#1.sva
directive set /inPlaceNTT_DIT_precomp/inPlaceNTT_DIT_precomp:core/core/VEC_LOOP:acc#10.cse#3.sva REGISTER_NAME VEC_LOOP:acc#10.cse#1.sva
directive set /inPlaceNTT_DIT_precomp/inPlaceNTT_DIT_precomp:core/core/VEC_LOOP:acc#10.cse#4.sva REGISTER_NAME VEC_LOOP:acc#10.cse#1.sva
directive set /inPlaceNTT_DIT_precomp/inPlaceNTT_DIT_precomp:core/core/VEC_LOOP:acc#10.cse#5.sva REGISTER_NAME VEC_LOOP:acc#10.cse#1.sva
directive set /inPlaceNTT_DIT_precomp/inPlaceNTT_DIT_precomp:core/core/VEC_LOOP:acc#10.cse#6.sva REGISTER_NAME VEC_LOOP:acc#10.cse#1.sva
directive set /inPlaceNTT_DIT_precomp/inPlaceNTT_DIT_precomp:core/core/VEC_LOOP:acc#10.cse#7.sva REGISTER_NAME VEC_LOOP:acc#10.cse#1.sva
directive set /inPlaceNTT_DIT_precomp/inPlaceNTT_DIT_precomp:core/core/VEC_LOOP:acc#10.cse.sva REGISTER_NAME VEC_LOOP:acc#10.cse#1.sva
directive set /inPlaceNTT_DIT_precomp/inPlaceNTT_DIT_precomp:core/core/factor1#1.sva REGISTER_NAME factor1#1.sva
directive set /inPlaceNTT_DIT_precomp/inPlaceNTT_DIT_precomp:core/core/factor1#2.sva REGISTER_NAME factor1#1.sva
directive set /inPlaceNTT_DIT_precomp/inPlaceNTT_DIT_precomp:core/core/factor1#3.sva REGISTER_NAME factor1#1.sva
directive set /inPlaceNTT_DIT_precomp/inPlaceNTT_DIT_precomp:core/core/factor1#4.sva REGISTER_NAME factor1#1.sva
directive set /inPlaceNTT_DIT_precomp/inPlaceNTT_DIT_precomp:core/core/factor1#5.sva REGISTER_NAME factor1#1.sva
directive set /inPlaceNTT_DIT_precomp/inPlaceNTT_DIT_precomp:core/core/factor1#6.sva REGISTER_NAME factor1#1.sva
directive set /inPlaceNTT_DIT_precomp/inPlaceNTT_DIT_precomp:core/core/factor1#7.sva REGISTER_NAME factor1#1.sva
directive set /inPlaceNTT_DIT_precomp/inPlaceNTT_DIT_precomp:core/core/factor1.sva REGISTER_NAME factor1#1.sva
directive set /inPlaceNTT_DIT_precomp/inPlaceNTT_DIT_precomp:core/core/COMP_LOOP-1:operator>><96,false>:operator>><96,false>:slc(mult:t:mul)(63-32).itm REGISTER_NAME COMP_LOOP-1:operator>><96,false>:operator>><96,false>:slc(mult:t:mul)(63-32).itm
directive set /inPlaceNTT_DIT_precomp/inPlaceNTT_DIT_precomp:core/core/COMP_LOOP-2:operator>><96,false>:operator>><96,false>:slc(mult:t:mul)(63-32).itm REGISTER_NAME COMP_LOOP-1:operator>><96,false>:operator>><96,false>:slc(mult:t:mul)(63-32).itm
directive set /inPlaceNTT_DIT_precomp/inPlaceNTT_DIT_precomp:core/core/COMP_LOOP-3:operator>><96,false>:operator>><96,false>:slc(mult:t:mul)(63-32).itm REGISTER_NAME COMP_LOOP-1:operator>><96,false>:operator>><96,false>:slc(mult:t:mul)(63-32).itm
directive set /inPlaceNTT_DIT_precomp/inPlaceNTT_DIT_precomp:core/core/COMP_LOOP-4:operator>><96,false>:operator>><96,false>:slc(mult:t:mul)(63-32).itm REGISTER_NAME COMP_LOOP-1:operator>><96,false>:operator>><96,false>:slc(mult:t:mul)(63-32).itm
directive set /inPlaceNTT_DIT_precomp/inPlaceNTT_DIT_precomp:core/core/COMP_LOOP-5:operator>><96,false>:operator>><96,false>:slc(mult:t:mul)(63-32).itm REGISTER_NAME COMP_LOOP-1:operator>><96,false>:operator>><96,false>:slc(mult:t:mul)(63-32).itm
directive set /inPlaceNTT_DIT_precomp/inPlaceNTT_DIT_precomp:core/core/COMP_LOOP-6:operator>><96,false>:operator>><96,false>:slc(mult:t:mul)(63-32).itm REGISTER_NAME COMP_LOOP-1:operator>><96,false>:operator>><96,false>:slc(mult:t:mul)(63-32).itm
directive set /inPlaceNTT_DIT_precomp/inPlaceNTT_DIT_precomp:core/core/COMP_LOOP-7:operator>><96,false>:operator>><96,false>:slc(mult:t:mul)(63-32).itm REGISTER_NAME COMP_LOOP-1:operator>><96,false>:operator>><96,false>:slc(mult:t:mul)(63-32).itm
directive set /inPlaceNTT_DIT_precomp/inPlaceNTT_DIT_precomp:core/core/COMP_LOOP-8:operator>><96,false>:operator>><96,false>:slc(mult:t:mul)(63-32).itm REGISTER_NAME COMP_LOOP-1:operator>><96,false>:operator>><96,false>:slc(mult:t:mul)(63-32).itm
directive set /inPlaceNTT_DIT_precomp/inPlaceNTT_DIT_precomp:core/core/mult:x#1.sva REGISTER_NAME COMP_LOOP-1:operator>><96,false>:operator>><96,false>:slc(mult:t:mul)(63-32).itm
directive set /inPlaceNTT_DIT_precomp/inPlaceNTT_DIT_precomp:core/core/mult:x#2.sva REGISTER_NAME COMP_LOOP-1:operator>><96,false>:operator>><96,false>:slc(mult:t:mul)(63-32).itm
directive set /inPlaceNTT_DIT_precomp/inPlaceNTT_DIT_precomp:core/core/mult:x#3.sva REGISTER_NAME COMP_LOOP-1:operator>><96,false>:operator>><96,false>:slc(mult:t:mul)(63-32).itm
directive set /inPlaceNTT_DIT_precomp/inPlaceNTT_DIT_precomp:core/core/mult:x#4.sva REGISTER_NAME COMP_LOOP-1:operator>><96,false>:operator>><96,false>:slc(mult:t:mul)(63-32).itm
directive set /inPlaceNTT_DIT_precomp/inPlaceNTT_DIT_precomp:core/core/mult:x#5.sva REGISTER_NAME COMP_LOOP-1:operator>><96,false>:operator>><96,false>:slc(mult:t:mul)(63-32).itm
directive set /inPlaceNTT_DIT_precomp/inPlaceNTT_DIT_precomp:core/core/mult:x#6.sva REGISTER_NAME COMP_LOOP-1:operator>><96,false>:operator>><96,false>:slc(mult:t:mul)(63-32).itm
directive set /inPlaceNTT_DIT_precomp/inPlaceNTT_DIT_precomp:core/core/mult:x#7.sva REGISTER_NAME COMP_LOOP-1:operator>><96,false>:operator>><96,false>:slc(mult:t:mul)(63-32).itm
directive set /inPlaceNTT_DIT_precomp/inPlaceNTT_DIT_precomp:core/core/mult:x.sva REGISTER_NAME COMP_LOOP-1:operator>><96,false>:operator>><96,false>:slc(mult:t:mul)(63-32).itm
directive set /inPlaceNTT_DIT_precomp/inPlaceNTT_DIT_precomp:core/core/VEC_LOOP:modulo_sub(return)#1.sva REGISTER_NAME COMP_LOOP-1:operator>><96,false>:operator>><96,false>:slc(mult:t:mul)(63-32).itm
directive set /inPlaceNTT_DIT_precomp/inPlaceNTT_DIT_precomp:core/core/VEC_LOOP:modulo_sub(return)#2.sva REGISTER_NAME COMP_LOOP-1:operator>><96,false>:operator>><96,false>:slc(mult:t:mul)(63-32).itm
directive set /inPlaceNTT_DIT_precomp/inPlaceNTT_DIT_precomp:core/core/VEC_LOOP:modulo_sub(return)#3.sva REGISTER_NAME COMP_LOOP-1:operator>><96,false>:operator>><96,false>:slc(mult:t:mul)(63-32).itm
directive set /inPlaceNTT_DIT_precomp/inPlaceNTT_DIT_precomp:core/core/VEC_LOOP:modulo_sub(return)#4.sva REGISTER_NAME COMP_LOOP-1:operator>><96,false>:operator>><96,false>:slc(mult:t:mul)(63-32).itm
directive set /inPlaceNTT_DIT_precomp/inPlaceNTT_DIT_precomp:core/core/VEC_LOOP:modulo_sub(return)#5.sva REGISTER_NAME COMP_LOOP-1:operator>><96,false>:operator>><96,false>:slc(mult:t:mul)(63-32).itm
directive set /inPlaceNTT_DIT_precomp/inPlaceNTT_DIT_precomp:core/core/VEC_LOOP:modulo_sub(return)#6.sva REGISTER_NAME COMP_LOOP-1:operator>><96,false>:operator>><96,false>:slc(mult:t:mul)(63-32).itm
directive set /inPlaceNTT_DIT_precomp/inPlaceNTT_DIT_precomp:core/core/VEC_LOOP:modulo_sub(return)#7.sva REGISTER_NAME COMP_LOOP-1:operator>><96,false>:operator>><96,false>:slc(mult:t:mul)(63-32).itm
directive set /inPlaceNTT_DIT_precomp/inPlaceNTT_DIT_precomp:core/core/VEC_LOOP:modulo_sub(return).sva REGISTER_NAME COMP_LOOP-1:operator>><96,false>:operator>><96,false>:slc(mult:t:mul)(63-32).itm
directive set /inPlaceNTT_DIT_precomp/inPlaceNTT_DIT_precomp:core/core/VEC_LOOP:j#2(10:0).sva#1 REGISTER_NAME VEC_LOOP:j#2(10:0).sva#1
directive set /inPlaceNTT_DIT_precomp/inPlaceNTT_DIT_precomp:core/core/VEC_LOOP:j#3(10:0).sva#1 REGISTER_NAME VEC_LOOP:j#2(10:0).sva#1
directive set /inPlaceNTT_DIT_precomp/inPlaceNTT_DIT_precomp:core/core/VEC_LOOP:j#4(10:0).sva#1 REGISTER_NAME VEC_LOOP:j#2(10:0).sva#1
directive set /inPlaceNTT_DIT_precomp/inPlaceNTT_DIT_precomp:core/core/VEC_LOOP:j#5(10:0).sva#1 REGISTER_NAME VEC_LOOP:j#2(10:0).sva#1
directive set /inPlaceNTT_DIT_precomp/inPlaceNTT_DIT_precomp:core/core/VEC_LOOP:j#6(10:0).sva#1 REGISTER_NAME VEC_LOOP:j#2(10:0).sva#1
directive set /inPlaceNTT_DIT_precomp/inPlaceNTT_DIT_precomp:core/core/VEC_LOOP:j#7(10:0).sva#1 REGISTER_NAME VEC_LOOP:j#2(10:0).sva#1
directive set /inPlaceNTT_DIT_precomp/inPlaceNTT_DIT_precomp:core/core/VEC_LOOP:j(10:0).sva#1 REGISTER_NAME VEC_LOOP:j#2(10:0).sva#1
directive set /inPlaceNTT_DIT_precomp/inPlaceNTT_DIT_precomp:core/core/VEC_LOOP:acc#1.cse#2.sva REGISTER_NAME VEC_LOOP:acc#1.cse#2.sva
directive set /inPlaceNTT_DIT_precomp/inPlaceNTT_DIT_precomp:core/core/VEC_LOOP:acc#1.cse#4.sva REGISTER_NAME VEC_LOOP:acc#1.cse#2.sva
directive set /inPlaceNTT_DIT_precomp/inPlaceNTT_DIT_precomp:core/core/VEC_LOOP:acc#1.cse#6.sva REGISTER_NAME VEC_LOOP:acc#1.cse#2.sva
directive set /inPlaceNTT_DIT_precomp/inPlaceNTT_DIT_precomp:core/core/VEC_LOOP:acc#1.cse.sva REGISTER_NAME VEC_LOOP:acc#1.cse#2.sva
directive set /inPlaceNTT_DIT_precomp/inPlaceNTT_DIT_precomp:core/core/VEC_LOOP:j#2(10:0).sva(9:0) REGISTER_NAME VEC_LOOP:acc#1.cse#2.sva
directive set /inPlaceNTT_DIT_precomp/inPlaceNTT_DIT_precomp:core/core/VEC_LOOP:j#4(10:0).sva(9:0) REGISTER_NAME VEC_LOOP:acc#1.cse#2.sva
directive set /inPlaceNTT_DIT_precomp/inPlaceNTT_DIT_precomp:core/core/VEC_LOOP:j#6(10:0).sva(9:0) REGISTER_NAME VEC_LOOP:acc#1.cse#2.sva
directive set /inPlaceNTT_DIT_precomp/inPlaceNTT_DIT_precomp:core/core/VEC_LOOP:j(10:0).sva(9:0) REGISTER_NAME VEC_LOOP:acc#1.cse#2.sva
directive set /inPlaceNTT_DIT_precomp/inPlaceNTT_DIT_precomp:core/core/VEC_LOOP:j#7(10:0).sva(9:0) REGISTER_NAME VEC_LOOP:acc#1.cse#2.sva
directive set /inPlaceNTT_DIT_precomp/inPlaceNTT_DIT_precomp:core/core/VEC_LOOP:j#3(10:0).sva(9:0) REGISTER_NAME VEC_LOOP:acc#1.cse#2.sva
directive set /inPlaceNTT_DIT_precomp/inPlaceNTT_DIT_precomp:core/core/VEC_LOOP:j#5(10:0).sva(9:0) REGISTER_NAME VEC_LOOP:acc#1.cse#2.sva
directive set /inPlaceNTT_DIT_precomp/inPlaceNTT_DIT_precomp:core/core/VEC_LOOP:acc#11.psp.sva REGISTER_NAME VEC_LOOP:acc#11.psp.sva
directive set /inPlaceNTT_DIT_precomp/inPlaceNTT_DIT_precomp:core/core/VEC_LOOP:acc#13.psp.sva REGISTER_NAME VEC_LOOP:acc#11.psp.sva
directive set /inPlaceNTT_DIT_precomp/inPlaceNTT_DIT_precomp:core/core/COMP_LOOP-5:twiddle_f:lshift.itm REGISTER_NAME COMP_LOOP-5:twiddle_f:lshift.itm
directive set /inPlaceNTT_DIT_precomp/inPlaceNTT_DIT_precomp:core/core/VEC_LOOP:acc#12.psp.sva REGISTER_NAME COMP_LOOP-5:twiddle_f:lshift.itm
directive set /inPlaceNTT_DIT_precomp/inPlaceNTT_DIT_precomp:core/core/COMP_LOOP-1:twiddle_f:acc.cse.sva REGISTER_NAME COMP_LOOP-5:twiddle_f:lshift.itm
