directive set /stockham_DIT/stockham_DIT:core/core/INNER_LOOP:a:slc(INNER_LOOP-1:q:and.psp)(0)#1.itm REGISTER_NAME INNER_LOOP:a:slc(INNER_LOOP-1:q:and.psp)(0)#1.itm
directive set /stockham_DIT/stockham_DIT:core/core/INNER_LOOP:a:slc(INNER_LOOP-1:q:and.psp)(0).itm REGISTER_NAME INNER_LOOP:a:slc(INNER_LOOP-1:q:and.psp)(0)#1.itm
directive set /stockham_DIT/stockham_DIT:core/core/INNER_LOOP:upper:slc(INNER_LOOP:upper:acc.psp#10(8:0)#1)(0)#2.itm REGISTER_NAME INNER_LOOP:upper:slc(INNER_LOOP:upper:acc.psp#10(8:0)#1)(0)#2.itm
directive set /stockham_DIT/stockham_DIT:core/core/INNER_LOOP:upper:slc(INNER_LOOP:upper:acc.psp#10(8:0)#1)(0)#3.itm REGISTER_NAME INNER_LOOP:upper:slc(INNER_LOOP:upper:acc.psp#10(8:0)#1)(0)#2.itm
directive set /stockham_DIT/stockham_DIT:core/core/INNER_LOOP-1:upper:and.psp.sva REGISTER_NAME INNER_LOOP-1:upper:and.psp.sva
directive set /stockham_DIT/stockham_DIT:core/core/INNER_LOOP:t(8:1).sva REGISTER_NAME INNER_LOOP-1:upper:and.psp.sva
directive set /stockham_DIT/stockham_DIT:core/core/drf(y).smx.lpi#3.dfm REGISTER_NAME drf(y).smx.lpi#3.dfm
directive set /stockham_DIT/stockham_DIT:core/core/drf(y).smx.lpi#3.dfm#1 REGISTER_NAME drf(y).smx.lpi#3.dfm
directive set /stockham_DIT/stockham_DIT:core/core/drf(y).smx.lpi#3 REGISTER_NAME drf(y).smx.lpi#3.dfm
directive set /stockham_DIT/stockham_DIT:core/core/drf(y).smx.lpi#2 REGISTER_NAME drf(y).smx.lpi#3.dfm
directive set /stockham_DIT/stockham_DIT:core/core/INNER_LOOP:w:asn#3.itm REGISTER_NAME INNER_LOOP:w:asn#3.itm
directive set /stockham_DIT/stockham_DIT:core/core/INNER_LOOP:w:asn.itm REGISTER_NAME INNER_LOOP:w:asn#3.itm
directive set /stockham_DIT/stockham_DIT:core/core/INNER_LOOP-1:acc#5.itm REGISTER_NAME INNER_LOOP-1:acc#5.itm
directive set /stockham_DIT/stockham_DIT:core/core/INNER_LOOP-2:acc#5.itm REGISTER_NAME INNER_LOOP-1:acc#5.itm
directive set /stockham_DIT/stockham_DIT:core/core/INNER_LOOP-1:acc#2.psp REGISTER_NAME INNER_LOOP-1:acc#2.psp
directive set /stockham_DIT/stockham_DIT:core/core/INNER_LOOP-2:acc#2.psp REGISTER_NAME INNER_LOOP-1:acc#2.psp
directive set /stockham_DIT/stockham_DIT:core/core/INNER_LOOP:a#1.lpi#3.dfm REGISTER_NAME INNER_LOOP-1:acc#2.psp
directive set /stockham_DIT/stockham_DIT:core/core/INNER_LOOP:a.lpi#3.dfm REGISTER_NAME INNER_LOOP-1:acc#2.psp
directive set /stockham_DIT/stockham_DIT:core/core/modulo_dev:_qr#1.lpi#3.dfm REGISTER_NAME INNER_LOOP-1:acc#2.psp
directive set /stockham_DIT/stockham_DIT:core/core/OUTER_LOOP:acc#2.itm REGISTER_NAME OUTER_LOOP:acc#2.itm
directive set /stockham_DIT/stockham_DIT:core/core/shift(3:0).sva REGISTER_NAME OUTER_LOOP:acc#2.itm
