// Generated by ZYANG
#ifndef INCLUDED_CCS_DUT_WRAPPER_H
#define INCLUDED_CCS_DUT_WRAPPER_H

#ifndef SC_USE_STD_STRING
#define SC_USE_STD_STRING
#endif

#include <systemc.h>
#include <mc_simulator_extensions.h>

#ifdef CCS_SYSC
namespace HDL {
#endif
#if defined(CCS_DUT_SYSC)
// alias ccs_DUT_wrapper to namespace enclosure of either cycle or RTL SystemC netlist
namespace
    ccs_design {
#if defined(CCS_DUT_CYCLE)
#include "cycle.cxx"
#else
#if defined(CCS_DUT_RTL)
#include "rtl.cxx"
#endif
#endif
}
typedef
    ccs_design::HDL::hybrid ccs_DUT_wrapper;

#else

// Create a foreign module wrapper around the HDL
#ifdef VCS_SYSTEMC
// VCS support - ccs_DUT_wrapper is derived from VCS-generated SystemC wrapper around HDL code
class ccs_DUT_wrapper : public TOP_HDL_ENTITY
{
public:
  ccs_DUT_wrapper(const sc_module_name& nm, const char *hdl_name)
  : TOP_HDL_ENTITY(nm)
  {
  // elaborate_foreign_module(hdl_name);
  }

  ~ccs_DUT_wrapper() {}
};

#else
// non VCS simulators - ccs_DUT_wrapper is derived from mc_foreign_module (adding 2nd ctor arg)
class ccs_DUT_wrapper: public mc_foreign_module
{
public:
  // Interface Ports
  sc_in<bool> clk;
  sc_in<sc_logic> rst;
  sc_in<sc_logic> x_rsc_s_tdone;
  sc_in<sc_logic> x_rsc_tr_write_done;
  sc_in<sc_logic> x_rsc_RREADY;
  sc_out<sc_logic> x_rsc_RVALID;
  sc_out<sc_logic> x_rsc_RUSER;
  sc_out<sc_logic> x_rsc_RLAST;
  sc_out<sc_lv<2> > x_rsc_RRESP;
  sc_out<sc_lv<32> > x_rsc_RDATA;
  sc_out<sc_logic> x_rsc_RID;
  sc_out<sc_logic> x_rsc_ARREADY;
  sc_in<sc_logic> x_rsc_ARVALID;
  sc_in<sc_logic> x_rsc_ARUSER;
  sc_in<sc_lv<4> > x_rsc_ARREGION;
  sc_in<sc_lv<4> > x_rsc_ARQOS;
  sc_in<sc_lv<3> > x_rsc_ARPROT;
  sc_in<sc_lv<4> > x_rsc_ARCACHE;
  sc_in<sc_logic> x_rsc_ARLOCK;
  sc_in<sc_lv<2> > x_rsc_ARBURST;
  sc_in<sc_lv<3> > x_rsc_ARSIZE;
  sc_in<sc_lv<8> > x_rsc_ARLEN;
  sc_in<sc_lv<12> > x_rsc_ARADDR;
  sc_in<sc_logic> x_rsc_ARID;
  sc_in<sc_logic> x_rsc_BREADY;
  sc_out<sc_logic> x_rsc_BVALID;
  sc_out<sc_logic> x_rsc_BUSER;
  sc_out<sc_lv<2> > x_rsc_BRESP;
  sc_out<sc_logic> x_rsc_BID;
  sc_out<sc_logic> x_rsc_WREADY;
  sc_in<sc_logic> x_rsc_WVALID;
  sc_in<sc_logic> x_rsc_WUSER;
  sc_in<sc_logic> x_rsc_WLAST;
  sc_in<sc_lv<4> > x_rsc_WSTRB;
  sc_in<sc_lv<32> > x_rsc_WDATA;
  sc_out<sc_logic> x_rsc_AWREADY;
  sc_in<sc_logic> x_rsc_AWVALID;
  sc_in<sc_logic> x_rsc_AWUSER;
  sc_in<sc_lv<4> > x_rsc_AWREGION;
  sc_in<sc_lv<4> > x_rsc_AWQOS;
  sc_in<sc_lv<3> > x_rsc_AWPROT;
  sc_in<sc_lv<4> > x_rsc_AWCACHE;
  sc_in<sc_logic> x_rsc_AWLOCK;
  sc_in<sc_lv<2> > x_rsc_AWBURST;
  sc_in<sc_lv<3> > x_rsc_AWSIZE;
  sc_in<sc_lv<8> > x_rsc_AWLEN;
  sc_in<sc_lv<12> > x_rsc_AWADDR;
  sc_in<sc_logic> x_rsc_AWID;
  sc_out<sc_logic> x_rsc_triosy_lz;
  sc_in<sc_lv<32> > m_rsc_dat;
  sc_out<sc_logic> m_rsc_triosy_lz;
  sc_in<sc_logic> twiddle_rsc_s_tdone;
  sc_in<sc_logic> twiddle_rsc_tr_write_done;
  sc_in<sc_logic> twiddle_rsc_RREADY;
  sc_out<sc_logic> twiddle_rsc_RVALID;
  sc_out<sc_logic> twiddle_rsc_RUSER;
  sc_out<sc_logic> twiddle_rsc_RLAST;
  sc_out<sc_lv<2> > twiddle_rsc_RRESP;
  sc_out<sc_lv<32> > twiddle_rsc_RDATA;
  sc_out<sc_logic> twiddle_rsc_RID;
  sc_out<sc_logic> twiddle_rsc_ARREADY;
  sc_in<sc_logic> twiddle_rsc_ARVALID;
  sc_in<sc_logic> twiddle_rsc_ARUSER;
  sc_in<sc_lv<4> > twiddle_rsc_ARREGION;
  sc_in<sc_lv<4> > twiddle_rsc_ARQOS;
  sc_in<sc_lv<3> > twiddle_rsc_ARPROT;
  sc_in<sc_lv<4> > twiddle_rsc_ARCACHE;
  sc_in<sc_logic> twiddle_rsc_ARLOCK;
  sc_in<sc_lv<2> > twiddle_rsc_ARBURST;
  sc_in<sc_lv<3> > twiddle_rsc_ARSIZE;
  sc_in<sc_lv<8> > twiddle_rsc_ARLEN;
  sc_in<sc_lv<12> > twiddle_rsc_ARADDR;
  sc_in<sc_logic> twiddle_rsc_ARID;
  sc_in<sc_logic> twiddle_rsc_BREADY;
  sc_out<sc_logic> twiddle_rsc_BVALID;
  sc_out<sc_logic> twiddle_rsc_BUSER;
  sc_out<sc_lv<2> > twiddle_rsc_BRESP;
  sc_out<sc_logic> twiddle_rsc_BID;
  sc_out<sc_logic> twiddle_rsc_WREADY;
  sc_in<sc_logic> twiddle_rsc_WVALID;
  sc_in<sc_logic> twiddle_rsc_WUSER;
  sc_in<sc_logic> twiddle_rsc_WLAST;
  sc_in<sc_lv<4> > twiddle_rsc_WSTRB;
  sc_in<sc_lv<32> > twiddle_rsc_WDATA;
  sc_out<sc_logic> twiddle_rsc_AWREADY;
  sc_in<sc_logic> twiddle_rsc_AWVALID;
  sc_in<sc_logic> twiddle_rsc_AWUSER;
  sc_in<sc_lv<4> > twiddle_rsc_AWREGION;
  sc_in<sc_lv<4> > twiddle_rsc_AWQOS;
  sc_in<sc_lv<3> > twiddle_rsc_AWPROT;
  sc_in<sc_lv<4> > twiddle_rsc_AWCACHE;
  sc_in<sc_logic> twiddle_rsc_AWLOCK;
  sc_in<sc_lv<2> > twiddle_rsc_AWBURST;
  sc_in<sc_lv<3> > twiddle_rsc_AWSIZE;
  sc_in<sc_lv<8> > twiddle_rsc_AWLEN;
  sc_in<sc_lv<12> > twiddle_rsc_AWADDR;
  sc_in<sc_logic> twiddle_rsc_AWID;
  sc_out<sc_logic> twiddle_rsc_triosy_lz;
  sc_in<sc_logic> twiddle_h_rsc_s_tdone;
  sc_in<sc_logic> twiddle_h_rsc_tr_write_done;
  sc_in<sc_logic> twiddle_h_rsc_RREADY;
  sc_out<sc_logic> twiddle_h_rsc_RVALID;
  sc_out<sc_logic> twiddle_h_rsc_RUSER;
  sc_out<sc_logic> twiddle_h_rsc_RLAST;
  sc_out<sc_lv<2> > twiddle_h_rsc_RRESP;
  sc_out<sc_lv<32> > twiddle_h_rsc_RDATA;
  sc_out<sc_logic> twiddle_h_rsc_RID;
  sc_out<sc_logic> twiddle_h_rsc_ARREADY;
  sc_in<sc_logic> twiddle_h_rsc_ARVALID;
  sc_in<sc_logic> twiddle_h_rsc_ARUSER;
  sc_in<sc_lv<4> > twiddle_h_rsc_ARREGION;
  sc_in<sc_lv<4> > twiddle_h_rsc_ARQOS;
  sc_in<sc_lv<3> > twiddle_h_rsc_ARPROT;
  sc_in<sc_lv<4> > twiddle_h_rsc_ARCACHE;
  sc_in<sc_logic> twiddle_h_rsc_ARLOCK;
  sc_in<sc_lv<2> > twiddle_h_rsc_ARBURST;
  sc_in<sc_lv<3> > twiddle_h_rsc_ARSIZE;
  sc_in<sc_lv<8> > twiddle_h_rsc_ARLEN;
  sc_in<sc_lv<12> > twiddle_h_rsc_ARADDR;
  sc_in<sc_logic> twiddle_h_rsc_ARID;
  sc_in<sc_logic> twiddle_h_rsc_BREADY;
  sc_out<sc_logic> twiddle_h_rsc_BVALID;
  sc_out<sc_logic> twiddle_h_rsc_BUSER;
  sc_out<sc_lv<2> > twiddle_h_rsc_BRESP;
  sc_out<sc_logic> twiddle_h_rsc_BID;
  sc_out<sc_logic> twiddle_h_rsc_WREADY;
  sc_in<sc_logic> twiddle_h_rsc_WVALID;
  sc_in<sc_logic> twiddle_h_rsc_WUSER;
  sc_in<sc_logic> twiddle_h_rsc_WLAST;
  sc_in<sc_lv<4> > twiddle_h_rsc_WSTRB;
  sc_in<sc_lv<32> > twiddle_h_rsc_WDATA;
  sc_out<sc_logic> twiddle_h_rsc_AWREADY;
  sc_in<sc_logic> twiddle_h_rsc_AWVALID;
  sc_in<sc_logic> twiddle_h_rsc_AWUSER;
  sc_in<sc_lv<4> > twiddle_h_rsc_AWREGION;
  sc_in<sc_lv<4> > twiddle_h_rsc_AWQOS;
  sc_in<sc_lv<3> > twiddle_h_rsc_AWPROT;
  sc_in<sc_lv<4> > twiddle_h_rsc_AWCACHE;
  sc_in<sc_logic> twiddle_h_rsc_AWLOCK;
  sc_in<sc_lv<2> > twiddle_h_rsc_AWBURST;
  sc_in<sc_lv<3> > twiddle_h_rsc_AWSIZE;
  sc_in<sc_lv<8> > twiddle_h_rsc_AWLEN;
  sc_in<sc_lv<12> > twiddle_h_rsc_AWADDR;
  sc_in<sc_logic> twiddle_h_rsc_AWID;
  sc_out<sc_logic> twiddle_h_rsc_triosy_lz;
  sc_in<sc_logic> revArr_rsc_s_tdone;
  sc_in<sc_logic> revArr_rsc_tr_write_done;
  sc_in<sc_logic> revArr_rsc_RREADY;
  sc_out<sc_logic> revArr_rsc_RVALID;
  sc_out<sc_logic> revArr_rsc_RUSER;
  sc_out<sc_logic> revArr_rsc_RLAST;
  sc_out<sc_lv<2> > revArr_rsc_RRESP;
  sc_out<sc_lv<32> > revArr_rsc_RDATA;
  sc_out<sc_logic> revArr_rsc_RID;
  sc_out<sc_logic> revArr_rsc_ARREADY;
  sc_in<sc_logic> revArr_rsc_ARVALID;
  sc_in<sc_logic> revArr_rsc_ARUSER;
  sc_in<sc_lv<4> > revArr_rsc_ARREGION;
  sc_in<sc_lv<4> > revArr_rsc_ARQOS;
  sc_in<sc_lv<3> > revArr_rsc_ARPROT;
  sc_in<sc_lv<4> > revArr_rsc_ARCACHE;
  sc_in<sc_logic> revArr_rsc_ARLOCK;
  sc_in<sc_lv<2> > revArr_rsc_ARBURST;
  sc_in<sc_lv<3> > revArr_rsc_ARSIZE;
  sc_in<sc_lv<8> > revArr_rsc_ARLEN;
  sc_in<sc_lv<12> > revArr_rsc_ARADDR;
  sc_in<sc_logic> revArr_rsc_ARID;
  sc_in<sc_logic> revArr_rsc_BREADY;
  sc_out<sc_logic> revArr_rsc_BVALID;
  sc_out<sc_logic> revArr_rsc_BUSER;
  sc_out<sc_lv<2> > revArr_rsc_BRESP;
  sc_out<sc_logic> revArr_rsc_BID;
  sc_out<sc_logic> revArr_rsc_WREADY;
  sc_in<sc_logic> revArr_rsc_WVALID;
  sc_in<sc_logic> revArr_rsc_WUSER;
  sc_in<sc_logic> revArr_rsc_WLAST;
  sc_in<sc_lv<4> > revArr_rsc_WSTRB;
  sc_in<sc_lv<32> > revArr_rsc_WDATA;
  sc_out<sc_logic> revArr_rsc_AWREADY;
  sc_in<sc_logic> revArr_rsc_AWVALID;
  sc_in<sc_logic> revArr_rsc_AWUSER;
  sc_in<sc_lv<4> > revArr_rsc_AWREGION;
  sc_in<sc_lv<4> > revArr_rsc_AWQOS;
  sc_in<sc_lv<3> > revArr_rsc_AWPROT;
  sc_in<sc_lv<4> > revArr_rsc_AWCACHE;
  sc_in<sc_logic> revArr_rsc_AWLOCK;
  sc_in<sc_lv<2> > revArr_rsc_AWBURST;
  sc_in<sc_lv<3> > revArr_rsc_AWSIZE;
  sc_in<sc_lv<8> > revArr_rsc_AWLEN;
  sc_in<sc_lv<12> > revArr_rsc_AWADDR;
  sc_in<sc_logic> revArr_rsc_AWID;
  sc_out<sc_logic> revArr_rsc_triosy_lz;
  sc_in<sc_logic> tw_rsc_s_tdone;
  sc_in<sc_logic> tw_rsc_tr_write_done;
  sc_in<sc_logic> tw_rsc_RREADY;
  sc_out<sc_logic> tw_rsc_RVALID;
  sc_out<sc_logic> tw_rsc_RUSER;
  sc_out<sc_logic> tw_rsc_RLAST;
  sc_out<sc_lv<2> > tw_rsc_RRESP;
  sc_out<sc_lv<32> > tw_rsc_RDATA;
  sc_out<sc_logic> tw_rsc_RID;
  sc_out<sc_logic> tw_rsc_ARREADY;
  sc_in<sc_logic> tw_rsc_ARVALID;
  sc_in<sc_logic> tw_rsc_ARUSER;
  sc_in<sc_lv<4> > tw_rsc_ARREGION;
  sc_in<sc_lv<4> > tw_rsc_ARQOS;
  sc_in<sc_lv<3> > tw_rsc_ARPROT;
  sc_in<sc_lv<4> > tw_rsc_ARCACHE;
  sc_in<sc_logic> tw_rsc_ARLOCK;
  sc_in<sc_lv<2> > tw_rsc_ARBURST;
  sc_in<sc_lv<3> > tw_rsc_ARSIZE;
  sc_in<sc_lv<8> > tw_rsc_ARLEN;
  sc_in<sc_lv<12> > tw_rsc_ARADDR;
  sc_in<sc_logic> tw_rsc_ARID;
  sc_in<sc_logic> tw_rsc_BREADY;
  sc_out<sc_logic> tw_rsc_BVALID;
  sc_out<sc_logic> tw_rsc_BUSER;
  sc_out<sc_lv<2> > tw_rsc_BRESP;
  sc_out<sc_logic> tw_rsc_BID;
  sc_out<sc_logic> tw_rsc_WREADY;
  sc_in<sc_logic> tw_rsc_WVALID;
  sc_in<sc_logic> tw_rsc_WUSER;
  sc_in<sc_logic> tw_rsc_WLAST;
  sc_in<sc_lv<4> > tw_rsc_WSTRB;
  sc_in<sc_lv<32> > tw_rsc_WDATA;
  sc_out<sc_logic> tw_rsc_AWREADY;
  sc_in<sc_logic> tw_rsc_AWVALID;
  sc_in<sc_logic> tw_rsc_AWUSER;
  sc_in<sc_lv<4> > tw_rsc_AWREGION;
  sc_in<sc_lv<4> > tw_rsc_AWQOS;
  sc_in<sc_lv<3> > tw_rsc_AWPROT;
  sc_in<sc_lv<4> > tw_rsc_AWCACHE;
  sc_in<sc_logic> tw_rsc_AWLOCK;
  sc_in<sc_lv<2> > tw_rsc_AWBURST;
  sc_in<sc_lv<3> > tw_rsc_AWSIZE;
  sc_in<sc_lv<8> > tw_rsc_AWLEN;
  sc_in<sc_lv<12> > tw_rsc_AWADDR;
  sc_in<sc_logic> tw_rsc_AWID;
  sc_out<sc_logic> tw_rsc_triosy_lz;
  sc_in<sc_logic> tw_h_rsc_s_tdone;
  sc_in<sc_logic> tw_h_rsc_tr_write_done;
  sc_in<sc_logic> tw_h_rsc_RREADY;
  sc_out<sc_logic> tw_h_rsc_RVALID;
  sc_out<sc_logic> tw_h_rsc_RUSER;
  sc_out<sc_logic> tw_h_rsc_RLAST;
  sc_out<sc_lv<2> > tw_h_rsc_RRESP;
  sc_out<sc_lv<32> > tw_h_rsc_RDATA;
  sc_out<sc_logic> tw_h_rsc_RID;
  sc_out<sc_logic> tw_h_rsc_ARREADY;
  sc_in<sc_logic> tw_h_rsc_ARVALID;
  sc_in<sc_logic> tw_h_rsc_ARUSER;
  sc_in<sc_lv<4> > tw_h_rsc_ARREGION;
  sc_in<sc_lv<4> > tw_h_rsc_ARQOS;
  sc_in<sc_lv<3> > tw_h_rsc_ARPROT;
  sc_in<sc_lv<4> > tw_h_rsc_ARCACHE;
  sc_in<sc_logic> tw_h_rsc_ARLOCK;
  sc_in<sc_lv<2> > tw_h_rsc_ARBURST;
  sc_in<sc_lv<3> > tw_h_rsc_ARSIZE;
  sc_in<sc_lv<8> > tw_h_rsc_ARLEN;
  sc_in<sc_lv<12> > tw_h_rsc_ARADDR;
  sc_in<sc_logic> tw_h_rsc_ARID;
  sc_in<sc_logic> tw_h_rsc_BREADY;
  sc_out<sc_logic> tw_h_rsc_BVALID;
  sc_out<sc_logic> tw_h_rsc_BUSER;
  sc_out<sc_lv<2> > tw_h_rsc_BRESP;
  sc_out<sc_logic> tw_h_rsc_BID;
  sc_out<sc_logic> tw_h_rsc_WREADY;
  sc_in<sc_logic> tw_h_rsc_WVALID;
  sc_in<sc_logic> tw_h_rsc_WUSER;
  sc_in<sc_logic> tw_h_rsc_WLAST;
  sc_in<sc_lv<4> > tw_h_rsc_WSTRB;
  sc_in<sc_lv<32> > tw_h_rsc_WDATA;
  sc_out<sc_logic> tw_h_rsc_AWREADY;
  sc_in<sc_logic> tw_h_rsc_AWVALID;
  sc_in<sc_logic> tw_h_rsc_AWUSER;
  sc_in<sc_lv<4> > tw_h_rsc_AWREGION;
  sc_in<sc_lv<4> > tw_h_rsc_AWQOS;
  sc_in<sc_lv<3> > tw_h_rsc_AWPROT;
  sc_in<sc_lv<4> > tw_h_rsc_AWCACHE;
  sc_in<sc_logic> tw_h_rsc_AWLOCK;
  sc_in<sc_lv<2> > tw_h_rsc_AWBURST;
  sc_in<sc_lv<3> > tw_h_rsc_AWSIZE;
  sc_in<sc_lv<8> > tw_h_rsc_AWLEN;
  sc_in<sc_lv<12> > tw_h_rsc_AWADDR;
  sc_in<sc_logic> tw_h_rsc_AWID;
  sc_out<sc_logic> tw_h_rsc_triosy_lz;
public:
  ccs_DUT_wrapper(const sc_module_name& nm, const char *hdl_name)
  :
    mc_foreign_module(nm, hdl_name), 
    clk("clk"), 
    rst("rst"), 
    x_rsc_s_tdone("x_rsc_s_tdone"), 
    x_rsc_tr_write_done("x_rsc_tr_write_done"), 
    x_rsc_RREADY("x_rsc_RREADY"), 
    x_rsc_RVALID("x_rsc_RVALID"), 
    x_rsc_RUSER("x_rsc_RUSER"), 
    x_rsc_RLAST("x_rsc_RLAST"), 
    x_rsc_RRESP("x_rsc_RRESP"), 
    x_rsc_RDATA("x_rsc_RDATA"), 
    x_rsc_RID("x_rsc_RID"), 
    x_rsc_ARREADY("x_rsc_ARREADY"), 
    x_rsc_ARVALID("x_rsc_ARVALID"), 
    x_rsc_ARUSER("x_rsc_ARUSER"), 
    x_rsc_ARREGION("x_rsc_ARREGION"), 
    x_rsc_ARQOS("x_rsc_ARQOS"), 
    x_rsc_ARPROT("x_rsc_ARPROT"), 
    x_rsc_ARCACHE("x_rsc_ARCACHE"), 
    x_rsc_ARLOCK("x_rsc_ARLOCK"), 
    x_rsc_ARBURST("x_rsc_ARBURST"), 
    x_rsc_ARSIZE("x_rsc_ARSIZE"), 
    x_rsc_ARLEN("x_rsc_ARLEN"), 
    x_rsc_ARADDR("x_rsc_ARADDR"), 
    x_rsc_ARID("x_rsc_ARID"), 
    x_rsc_BREADY("x_rsc_BREADY"), 
    x_rsc_BVALID("x_rsc_BVALID"), 
    x_rsc_BUSER("x_rsc_BUSER"), 
    x_rsc_BRESP("x_rsc_BRESP"), 
    x_rsc_BID("x_rsc_BID"), 
    x_rsc_WREADY("x_rsc_WREADY"), 
    x_rsc_WVALID("x_rsc_WVALID"), 
    x_rsc_WUSER("x_rsc_WUSER"), 
    x_rsc_WLAST("x_rsc_WLAST"), 
    x_rsc_WSTRB("x_rsc_WSTRB"), 
    x_rsc_WDATA("x_rsc_WDATA"), 
    x_rsc_AWREADY("x_rsc_AWREADY"), 
    x_rsc_AWVALID("x_rsc_AWVALID"), 
    x_rsc_AWUSER("x_rsc_AWUSER"), 
    x_rsc_AWREGION("x_rsc_AWREGION"), 
    x_rsc_AWQOS("x_rsc_AWQOS"), 
    x_rsc_AWPROT("x_rsc_AWPROT"), 
    x_rsc_AWCACHE("x_rsc_AWCACHE"), 
    x_rsc_AWLOCK("x_rsc_AWLOCK"), 
    x_rsc_AWBURST("x_rsc_AWBURST"), 
    x_rsc_AWSIZE("x_rsc_AWSIZE"), 
    x_rsc_AWLEN("x_rsc_AWLEN"), 
    x_rsc_AWADDR("x_rsc_AWADDR"), 
    x_rsc_AWID("x_rsc_AWID"), 
    x_rsc_triosy_lz("x_rsc_triosy_lz"), 
    m_rsc_dat("m_rsc_dat"), 
    m_rsc_triosy_lz("m_rsc_triosy_lz"), 
    twiddle_rsc_s_tdone("twiddle_rsc_s_tdone"), 
    twiddle_rsc_tr_write_done("twiddle_rsc_tr_write_done"), 
    twiddle_rsc_RREADY("twiddle_rsc_RREADY"), 
    twiddle_rsc_RVALID("twiddle_rsc_RVALID"), 
    twiddle_rsc_RUSER("twiddle_rsc_RUSER"), 
    twiddle_rsc_RLAST("twiddle_rsc_RLAST"), 
    twiddle_rsc_RRESP("twiddle_rsc_RRESP"), 
    twiddle_rsc_RDATA("twiddle_rsc_RDATA"), 
    twiddle_rsc_RID("twiddle_rsc_RID"), 
    twiddle_rsc_ARREADY("twiddle_rsc_ARREADY"), 
    twiddle_rsc_ARVALID("twiddle_rsc_ARVALID"), 
    twiddle_rsc_ARUSER("twiddle_rsc_ARUSER"), 
    twiddle_rsc_ARREGION("twiddle_rsc_ARREGION"), 
    twiddle_rsc_ARQOS("twiddle_rsc_ARQOS"), 
    twiddle_rsc_ARPROT("twiddle_rsc_ARPROT"), 
    twiddle_rsc_ARCACHE("twiddle_rsc_ARCACHE"), 
    twiddle_rsc_ARLOCK("twiddle_rsc_ARLOCK"), 
    twiddle_rsc_ARBURST("twiddle_rsc_ARBURST"), 
    twiddle_rsc_ARSIZE("twiddle_rsc_ARSIZE"), 
    twiddle_rsc_ARLEN("twiddle_rsc_ARLEN"), 
    twiddle_rsc_ARADDR("twiddle_rsc_ARADDR"), 
    twiddle_rsc_ARID("twiddle_rsc_ARID"), 
    twiddle_rsc_BREADY("twiddle_rsc_BREADY"), 
    twiddle_rsc_BVALID("twiddle_rsc_BVALID"), 
    twiddle_rsc_BUSER("twiddle_rsc_BUSER"), 
    twiddle_rsc_BRESP("twiddle_rsc_BRESP"), 
    twiddle_rsc_BID("twiddle_rsc_BID"), 
    twiddle_rsc_WREADY("twiddle_rsc_WREADY"), 
    twiddle_rsc_WVALID("twiddle_rsc_WVALID"), 
    twiddle_rsc_WUSER("twiddle_rsc_WUSER"), 
    twiddle_rsc_WLAST("twiddle_rsc_WLAST"), 
    twiddle_rsc_WSTRB("twiddle_rsc_WSTRB"), 
    twiddle_rsc_WDATA("twiddle_rsc_WDATA"), 
    twiddle_rsc_AWREADY("twiddle_rsc_AWREADY"), 
    twiddle_rsc_AWVALID("twiddle_rsc_AWVALID"), 
    twiddle_rsc_AWUSER("twiddle_rsc_AWUSER"), 
    twiddle_rsc_AWREGION("twiddle_rsc_AWREGION"), 
    twiddle_rsc_AWQOS("twiddle_rsc_AWQOS"), 
    twiddle_rsc_AWPROT("twiddle_rsc_AWPROT"), 
    twiddle_rsc_AWCACHE("twiddle_rsc_AWCACHE"), 
    twiddle_rsc_AWLOCK("twiddle_rsc_AWLOCK"), 
    twiddle_rsc_AWBURST("twiddle_rsc_AWBURST"), 
    twiddle_rsc_AWSIZE("twiddle_rsc_AWSIZE"), 
    twiddle_rsc_AWLEN("twiddle_rsc_AWLEN"), 
    twiddle_rsc_AWADDR("twiddle_rsc_AWADDR"), 
    twiddle_rsc_AWID("twiddle_rsc_AWID"), 
    twiddle_rsc_triosy_lz("twiddle_rsc_triosy_lz"), 
    twiddle_h_rsc_s_tdone("twiddle_h_rsc_s_tdone"), 
    twiddle_h_rsc_tr_write_done("twiddle_h_rsc_tr_write_done"), 
    twiddle_h_rsc_RREADY("twiddle_h_rsc_RREADY"), 
    twiddle_h_rsc_RVALID("twiddle_h_rsc_RVALID"), 
    twiddle_h_rsc_RUSER("twiddle_h_rsc_RUSER"), 
    twiddle_h_rsc_RLAST("twiddle_h_rsc_RLAST"), 
    twiddle_h_rsc_RRESP("twiddle_h_rsc_RRESP"), 
    twiddle_h_rsc_RDATA("twiddle_h_rsc_RDATA"), 
    twiddle_h_rsc_RID("twiddle_h_rsc_RID"), 
    twiddle_h_rsc_ARREADY("twiddle_h_rsc_ARREADY"), 
    twiddle_h_rsc_ARVALID("twiddle_h_rsc_ARVALID"), 
    twiddle_h_rsc_ARUSER("twiddle_h_rsc_ARUSER"), 
    twiddle_h_rsc_ARREGION("twiddle_h_rsc_ARREGION"), 
    twiddle_h_rsc_ARQOS("twiddle_h_rsc_ARQOS"), 
    twiddle_h_rsc_ARPROT("twiddle_h_rsc_ARPROT"), 
    twiddle_h_rsc_ARCACHE("twiddle_h_rsc_ARCACHE"), 
    twiddle_h_rsc_ARLOCK("twiddle_h_rsc_ARLOCK"), 
    twiddle_h_rsc_ARBURST("twiddle_h_rsc_ARBURST"), 
    twiddle_h_rsc_ARSIZE("twiddle_h_rsc_ARSIZE"), 
    twiddle_h_rsc_ARLEN("twiddle_h_rsc_ARLEN"), 
    twiddle_h_rsc_ARADDR("twiddle_h_rsc_ARADDR"), 
    twiddle_h_rsc_ARID("twiddle_h_rsc_ARID"), 
    twiddle_h_rsc_BREADY("twiddle_h_rsc_BREADY"), 
    twiddle_h_rsc_BVALID("twiddle_h_rsc_BVALID"), 
    twiddle_h_rsc_BUSER("twiddle_h_rsc_BUSER"), 
    twiddle_h_rsc_BRESP("twiddle_h_rsc_BRESP"), 
    twiddle_h_rsc_BID("twiddle_h_rsc_BID"), 
    twiddle_h_rsc_WREADY("twiddle_h_rsc_WREADY"), 
    twiddle_h_rsc_WVALID("twiddle_h_rsc_WVALID"), 
    twiddle_h_rsc_WUSER("twiddle_h_rsc_WUSER"), 
    twiddle_h_rsc_WLAST("twiddle_h_rsc_WLAST"), 
    twiddle_h_rsc_WSTRB("twiddle_h_rsc_WSTRB"), 
    twiddle_h_rsc_WDATA("twiddle_h_rsc_WDATA"), 
    twiddle_h_rsc_AWREADY("twiddle_h_rsc_AWREADY"), 
    twiddle_h_rsc_AWVALID("twiddle_h_rsc_AWVALID"), 
    twiddle_h_rsc_AWUSER("twiddle_h_rsc_AWUSER"), 
    twiddle_h_rsc_AWREGION("twiddle_h_rsc_AWREGION"), 
    twiddle_h_rsc_AWQOS("twiddle_h_rsc_AWQOS"), 
    twiddle_h_rsc_AWPROT("twiddle_h_rsc_AWPROT"), 
    twiddle_h_rsc_AWCACHE("twiddle_h_rsc_AWCACHE"), 
    twiddle_h_rsc_AWLOCK("twiddle_h_rsc_AWLOCK"), 
    twiddle_h_rsc_AWBURST("twiddle_h_rsc_AWBURST"), 
    twiddle_h_rsc_AWSIZE("twiddle_h_rsc_AWSIZE"), 
    twiddle_h_rsc_AWLEN("twiddle_h_rsc_AWLEN"), 
    twiddle_h_rsc_AWADDR("twiddle_h_rsc_AWADDR"), 
    twiddle_h_rsc_AWID("twiddle_h_rsc_AWID"), 
    twiddle_h_rsc_triosy_lz("twiddle_h_rsc_triosy_lz"), 
    revArr_rsc_s_tdone("revArr_rsc_s_tdone"), 
    revArr_rsc_tr_write_done("revArr_rsc_tr_write_done"), 
    revArr_rsc_RREADY("revArr_rsc_RREADY"), 
    revArr_rsc_RVALID("revArr_rsc_RVALID"), 
    revArr_rsc_RUSER("revArr_rsc_RUSER"), 
    revArr_rsc_RLAST("revArr_rsc_RLAST"), 
    revArr_rsc_RRESP("revArr_rsc_RRESP"), 
    revArr_rsc_RDATA("revArr_rsc_RDATA"), 
    revArr_rsc_RID("revArr_rsc_RID"), 
    revArr_rsc_ARREADY("revArr_rsc_ARREADY"), 
    revArr_rsc_ARVALID("revArr_rsc_ARVALID"), 
    revArr_rsc_ARUSER("revArr_rsc_ARUSER"), 
    revArr_rsc_ARREGION("revArr_rsc_ARREGION"), 
    revArr_rsc_ARQOS("revArr_rsc_ARQOS"), 
    revArr_rsc_ARPROT("revArr_rsc_ARPROT"), 
    revArr_rsc_ARCACHE("revArr_rsc_ARCACHE"), 
    revArr_rsc_ARLOCK("revArr_rsc_ARLOCK"), 
    revArr_rsc_ARBURST("revArr_rsc_ARBURST"), 
    revArr_rsc_ARSIZE("revArr_rsc_ARSIZE"), 
    revArr_rsc_ARLEN("revArr_rsc_ARLEN"), 
    revArr_rsc_ARADDR("revArr_rsc_ARADDR"), 
    revArr_rsc_ARID("revArr_rsc_ARID"), 
    revArr_rsc_BREADY("revArr_rsc_BREADY"), 
    revArr_rsc_BVALID("revArr_rsc_BVALID"), 
    revArr_rsc_BUSER("revArr_rsc_BUSER"), 
    revArr_rsc_BRESP("revArr_rsc_BRESP"), 
    revArr_rsc_BID("revArr_rsc_BID"), 
    revArr_rsc_WREADY("revArr_rsc_WREADY"), 
    revArr_rsc_WVALID("revArr_rsc_WVALID"), 
    revArr_rsc_WUSER("revArr_rsc_WUSER"), 
    revArr_rsc_WLAST("revArr_rsc_WLAST"), 
    revArr_rsc_WSTRB("revArr_rsc_WSTRB"), 
    revArr_rsc_WDATA("revArr_rsc_WDATA"), 
    revArr_rsc_AWREADY("revArr_rsc_AWREADY"), 
    revArr_rsc_AWVALID("revArr_rsc_AWVALID"), 
    revArr_rsc_AWUSER("revArr_rsc_AWUSER"), 
    revArr_rsc_AWREGION("revArr_rsc_AWREGION"), 
    revArr_rsc_AWQOS("revArr_rsc_AWQOS"), 
    revArr_rsc_AWPROT("revArr_rsc_AWPROT"), 
    revArr_rsc_AWCACHE("revArr_rsc_AWCACHE"), 
    revArr_rsc_AWLOCK("revArr_rsc_AWLOCK"), 
    revArr_rsc_AWBURST("revArr_rsc_AWBURST"), 
    revArr_rsc_AWSIZE("revArr_rsc_AWSIZE"), 
    revArr_rsc_AWLEN("revArr_rsc_AWLEN"), 
    revArr_rsc_AWADDR("revArr_rsc_AWADDR"), 
    revArr_rsc_AWID("revArr_rsc_AWID"), 
    revArr_rsc_triosy_lz("revArr_rsc_triosy_lz"), 
    tw_rsc_s_tdone("tw_rsc_s_tdone"), 
    tw_rsc_tr_write_done("tw_rsc_tr_write_done"), 
    tw_rsc_RREADY("tw_rsc_RREADY"), 
    tw_rsc_RVALID("tw_rsc_RVALID"), 
    tw_rsc_RUSER("tw_rsc_RUSER"), 
    tw_rsc_RLAST("tw_rsc_RLAST"), 
    tw_rsc_RRESP("tw_rsc_RRESP"), 
    tw_rsc_RDATA("tw_rsc_RDATA"), 
    tw_rsc_RID("tw_rsc_RID"), 
    tw_rsc_ARREADY("tw_rsc_ARREADY"), 
    tw_rsc_ARVALID("tw_rsc_ARVALID"), 
    tw_rsc_ARUSER("tw_rsc_ARUSER"), 
    tw_rsc_ARREGION("tw_rsc_ARREGION"), 
    tw_rsc_ARQOS("tw_rsc_ARQOS"), 
    tw_rsc_ARPROT("tw_rsc_ARPROT"), 
    tw_rsc_ARCACHE("tw_rsc_ARCACHE"), 
    tw_rsc_ARLOCK("tw_rsc_ARLOCK"), 
    tw_rsc_ARBURST("tw_rsc_ARBURST"), 
    tw_rsc_ARSIZE("tw_rsc_ARSIZE"), 
    tw_rsc_ARLEN("tw_rsc_ARLEN"), 
    tw_rsc_ARADDR("tw_rsc_ARADDR"), 
    tw_rsc_ARID("tw_rsc_ARID"), 
    tw_rsc_BREADY("tw_rsc_BREADY"), 
    tw_rsc_BVALID("tw_rsc_BVALID"), 
    tw_rsc_BUSER("tw_rsc_BUSER"), 
    tw_rsc_BRESP("tw_rsc_BRESP"), 
    tw_rsc_BID("tw_rsc_BID"), 
    tw_rsc_WREADY("tw_rsc_WREADY"), 
    tw_rsc_WVALID("tw_rsc_WVALID"), 
    tw_rsc_WUSER("tw_rsc_WUSER"), 
    tw_rsc_WLAST("tw_rsc_WLAST"), 
    tw_rsc_WSTRB("tw_rsc_WSTRB"), 
    tw_rsc_WDATA("tw_rsc_WDATA"), 
    tw_rsc_AWREADY("tw_rsc_AWREADY"), 
    tw_rsc_AWVALID("tw_rsc_AWVALID"), 
    tw_rsc_AWUSER("tw_rsc_AWUSER"), 
    tw_rsc_AWREGION("tw_rsc_AWREGION"), 
    tw_rsc_AWQOS("tw_rsc_AWQOS"), 
    tw_rsc_AWPROT("tw_rsc_AWPROT"), 
    tw_rsc_AWCACHE("tw_rsc_AWCACHE"), 
    tw_rsc_AWLOCK("tw_rsc_AWLOCK"), 
    tw_rsc_AWBURST("tw_rsc_AWBURST"), 
    tw_rsc_AWSIZE("tw_rsc_AWSIZE"), 
    tw_rsc_AWLEN("tw_rsc_AWLEN"), 
    tw_rsc_AWADDR("tw_rsc_AWADDR"), 
    tw_rsc_AWID("tw_rsc_AWID"), 
    tw_rsc_triosy_lz("tw_rsc_triosy_lz"), 
    tw_h_rsc_s_tdone("tw_h_rsc_s_tdone"), 
    tw_h_rsc_tr_write_done("tw_h_rsc_tr_write_done"), 
    tw_h_rsc_RREADY("tw_h_rsc_RREADY"), 
    tw_h_rsc_RVALID("tw_h_rsc_RVALID"), 
    tw_h_rsc_RUSER("tw_h_rsc_RUSER"), 
    tw_h_rsc_RLAST("tw_h_rsc_RLAST"), 
    tw_h_rsc_RRESP("tw_h_rsc_RRESP"), 
    tw_h_rsc_RDATA("tw_h_rsc_RDATA"), 
    tw_h_rsc_RID("tw_h_rsc_RID"), 
    tw_h_rsc_ARREADY("tw_h_rsc_ARREADY"), 
    tw_h_rsc_ARVALID("tw_h_rsc_ARVALID"), 
    tw_h_rsc_ARUSER("tw_h_rsc_ARUSER"), 
    tw_h_rsc_ARREGION("tw_h_rsc_ARREGION"), 
    tw_h_rsc_ARQOS("tw_h_rsc_ARQOS"), 
    tw_h_rsc_ARPROT("tw_h_rsc_ARPROT"), 
    tw_h_rsc_ARCACHE("tw_h_rsc_ARCACHE"), 
    tw_h_rsc_ARLOCK("tw_h_rsc_ARLOCK"), 
    tw_h_rsc_ARBURST("tw_h_rsc_ARBURST"), 
    tw_h_rsc_ARSIZE("tw_h_rsc_ARSIZE"), 
    tw_h_rsc_ARLEN("tw_h_rsc_ARLEN"), 
    tw_h_rsc_ARADDR("tw_h_rsc_ARADDR"), 
    tw_h_rsc_ARID("tw_h_rsc_ARID"), 
    tw_h_rsc_BREADY("tw_h_rsc_BREADY"), 
    tw_h_rsc_BVALID("tw_h_rsc_BVALID"), 
    tw_h_rsc_BUSER("tw_h_rsc_BUSER"), 
    tw_h_rsc_BRESP("tw_h_rsc_BRESP"), 
    tw_h_rsc_BID("tw_h_rsc_BID"), 
    tw_h_rsc_WREADY("tw_h_rsc_WREADY"), 
    tw_h_rsc_WVALID("tw_h_rsc_WVALID"), 
    tw_h_rsc_WUSER("tw_h_rsc_WUSER"), 
    tw_h_rsc_WLAST("tw_h_rsc_WLAST"), 
    tw_h_rsc_WSTRB("tw_h_rsc_WSTRB"), 
    tw_h_rsc_WDATA("tw_h_rsc_WDATA"), 
    tw_h_rsc_AWREADY("tw_h_rsc_AWREADY"), 
    tw_h_rsc_AWVALID("tw_h_rsc_AWVALID"), 
    tw_h_rsc_AWUSER("tw_h_rsc_AWUSER"), 
    tw_h_rsc_AWREGION("tw_h_rsc_AWREGION"), 
    tw_h_rsc_AWQOS("tw_h_rsc_AWQOS"), 
    tw_h_rsc_AWPROT("tw_h_rsc_AWPROT"), 
    tw_h_rsc_AWCACHE("tw_h_rsc_AWCACHE"), 
    tw_h_rsc_AWLOCK("tw_h_rsc_AWLOCK"), 
    tw_h_rsc_AWBURST("tw_h_rsc_AWBURST"), 
    tw_h_rsc_AWSIZE("tw_h_rsc_AWSIZE"), 
    tw_h_rsc_AWLEN("tw_h_rsc_AWLEN"), 
    tw_h_rsc_AWADDR("tw_h_rsc_AWADDR"), 
    tw_h_rsc_AWID("tw_h_rsc_AWID"), 
    tw_h_rsc_triosy_lz("tw_h_rsc_triosy_lz")
  {
    elaborate_foreign_module(hdl_name);
  }

  ~ccs_DUT_wrapper() {}
};
#endif

#endif

#ifdef CCS_SYSC
} // end namespace HDL
#endif
#endif


