directive set /inPlaceNTT_DIF_precomp/inPlaceNTT_DIF_precomp:core/core/COMP_LOOP:twiddle_help#1.sva REGISTER_NAME COMP_LOOP:twiddle_help#1.sva
directive set /inPlaceNTT_DIF_precomp/inPlaceNTT_DIF_precomp:core/core/COMP_LOOP:twiddle_help.sva REGISTER_NAME COMP_LOOP:twiddle_help#1.sva
directive set /inPlaceNTT_DIF_precomp/inPlaceNTT_DIF_precomp:core/core/COMP_LOOP:twiddle_f#1.sva REGISTER_NAME COMP_LOOP:twiddle_f#1.sva
directive set /inPlaceNTT_DIF_precomp/inPlaceNTT_DIF_precomp:core/core/COMP_LOOP:twiddle_f.sva REGISTER_NAME COMP_LOOP:twiddle_f#1.sva
directive set /inPlaceNTT_DIF_precomp/inPlaceNTT_DIF_precomp:core/core/VEC_LOOP:j#1.sva REGISTER_NAME VEC_LOOP:j#1.sva
directive set /inPlaceNTT_DIF_precomp/inPlaceNTT_DIF_precomp:core/core/VEC_LOOP:j.sva REGISTER_NAME VEC_LOOP:j#1.sva
directive set /inPlaceNTT_DIF_precomp/inPlaceNTT_DIF_precomp:core/core/VEC_LOOP:j.sva#1 REGISTER_NAME VEC_LOOP:j#1.sva
directive set /inPlaceNTT_DIF_precomp/inPlaceNTT_DIF_precomp:core/core/COMP_LOOP-1:VEC_LOOP:slc(VEC_LOOP:acc)(20).itm REGISTER_NAME COMP_LOOP-1:VEC_LOOP:slc(VEC_LOOP:acc)(20).itm
directive set /inPlaceNTT_DIF_precomp/inPlaceNTT_DIF_precomp:core/core/COMP_LOOP-2:VEC_LOOP:slc(VEC_LOOP:acc)(20).itm REGISTER_NAME COMP_LOOP-1:VEC_LOOP:slc(VEC_LOOP:acc)(20).itm
directive set /inPlaceNTT_DIF_precomp/inPlaceNTT_DIF_precomp:core/core/run_ac_sync_tmp_dobj.sva REGISTER_NAME COMP_LOOP-1:VEC_LOOP:slc(VEC_LOOP:acc)(20).itm
directive set /inPlaceNTT_DIF_precomp/inPlaceNTT_DIF_precomp:core/core/VEC_LOOP:acc#10.cse#1.sva REGISTER_NAME VEC_LOOP:acc#10.cse#1.sva
directive set /inPlaceNTT_DIF_precomp/inPlaceNTT_DIF_precomp:core/core/VEC_LOOP:acc#10.cse.sva REGISTER_NAME VEC_LOOP:acc#10.cse#1.sva
directive set /inPlaceNTT_DIF_precomp/inPlaceNTT_DIF_precomp:core/core/VEC_LOOP:acc#1.cse.sva REGISTER_NAME VEC_LOOP:acc#1.cse.sva
directive set /inPlaceNTT_DIF_precomp/inPlaceNTT_DIF_precomp:core/core/VEC_LOOP:acc.psp.sva REGISTER_NAME VEC_LOOP:acc#1.cse.sva
