directive set /peaseNTT/peaseNTT:core/core/c(1).sva REGISTER_NAME c(1).sva
directive set /peaseNTT/peaseNTT:core/core/c(1).sva#1 REGISTER_NAME c(1).sva
directive set /peaseNTT/peaseNTT:core/core/operator-<20,false>:acc.cse.sva REGISTER_NAME operator-<20,false>:acc.cse.sva
directive set /peaseNTT/peaseNTT:core/core/operator<<<33,true>#2:lshift.psp(2:0).sva REGISTER_NAME operator-<20,false>:acc.cse.sva
directive set /peaseNTT/peaseNTT:core/core/c(3:2).sva REGISTER_NAME operator-<20,false>:acc.cse.sva
directive set /peaseNTT/peaseNTT:core/core/operator<<<33,true>#3:lshift.psp(1:0).sva REGISTER_NAME operator-<20,false>:acc.cse.sva
directive set /peaseNTT/peaseNTT:core/core/INNER_LOOP1:r(9:0).sva(8:0) REGISTER_NAME INNER_LOOP1:r(9:0).sva(8:0)
directive set /peaseNTT/peaseNTT:core/core/INNER_LOOP2:r(9:0).sva(8:0) REGISTER_NAME INNER_LOOP1:r(9:0).sva(8:0)
directive set /peaseNTT/peaseNTT:core/core/INNER_LOOP3:r(9:0).sva(8:0) REGISTER_NAME INNER_LOOP1:r(9:0).sva(8:0)
directive set /peaseNTT/peaseNTT:core/core/INNER_LOOP4:r(9:0).sva(8:0) REGISTER_NAME INNER_LOOP1:r(9:0).sva(8:0)
directive set /peaseNTT/peaseNTT:core/core/operator<<<33,true>:return(8:0).sva REGISTER_NAME operator<<<33,true>:return(8:0).sva
directive set /peaseNTT/peaseNTT:core/core/operator<<<33,true>#1:lshift.psp(7:0).sva REGISTER_NAME operator<<<33,true>:return(8:0).sva
directive set /peaseNTT/peaseNTT:core/core/INNER_LOOP1:r(9:0).sva#1 REGISTER_NAME INNER_LOOP1:r(9:0).sva#1
directive set /peaseNTT/peaseNTT:core/core/INNER_LOOP2:r(9:0).sva#1 REGISTER_NAME INNER_LOOP1:r(9:0).sva#1
directive set /peaseNTT/peaseNTT:core/core/INNER_LOOP3:r(9:0).sva#1 REGISTER_NAME INNER_LOOP1:r(9:0).sva#1
directive set /peaseNTT/peaseNTT:core/core/INNER_LOOP4:r(9:0).sva#1 REGISTER_NAME INNER_LOOP1:r(9:0).sva#1
directive set /peaseNTT/peaseNTT:core/core/butterFly1#1:f1.sva REGISTER_NAME butterFly1#1:f1.sva
directive set /peaseNTT/peaseNTT:core/core/butterFly1:f1.sva REGISTER_NAME butterFly1#1:f1.sva
directive set /peaseNTT/peaseNTT:core/core/butterFly2#1:f1.sva REGISTER_NAME butterFly1#1:f1.sva
directive set /peaseNTT/peaseNTT:core/core/butterFly2:f1.sva REGISTER_NAME butterFly1#1:f1.sva
directive set /peaseNTT/peaseNTT:core/core/modulo_add:base#1.sva REGISTER_NAME butterFly1#1:f1.sva
directive set /peaseNTT/peaseNTT:core/core/modulo_add:base#2.sva REGISTER_NAME butterFly1#1:f1.sva
directive set /peaseNTT/peaseNTT:core/core/modulo_add:base#3.sva REGISTER_NAME butterFly1#1:f1.sva
directive set /peaseNTT/peaseNTT:core/core/modulo_add:base.sva REGISTER_NAME butterFly1#1:f1.sva
directive set /peaseNTT/peaseNTT:core/core/modulo_add#1:mux.itm REGISTER_NAME butterFly1#1:f1.sva
directive set /peaseNTT/peaseNTT:core/core/modulo_add#2:mux.itm REGISTER_NAME butterFly1#1:f1.sva
directive set /peaseNTT/peaseNTT:core/core/modulo_add#3:mux.itm REGISTER_NAME butterFly1#1:f1.sva
directive set /peaseNTT/peaseNTT:core/core/modulo_add:mux.itm REGISTER_NAME butterFly1#1:f1.sva
directive set /peaseNTT/peaseNTT:core/core/INNER_LOOP1:tw:asn.itm REGISTER_NAME butterFly1#1:f1.sva
directive set /peaseNTT/peaseNTT:core/core/INNER_LOOP2:tw:asn#3.itm REGISTER_NAME butterFly1#1:f1.sva
directive set /peaseNTT/peaseNTT:core/core/butterFly2#1:tw:asn.itm REGISTER_NAME butterFly1#1:f1.sva
directive set /peaseNTT/peaseNTT:core/core/butterFly2:tw:asn.itm REGISTER_NAME butterFly1#1:f1.sva
directive set /peaseNTT/peaseNTT:core/core/mult#1:z:slc(mult:z:mul:cmp.z)(31-0).itm REGISTER_NAME mult#1:z:slc(mult:z:mul:cmp.z)(31-0).itm
directive set /peaseNTT/peaseNTT:core/core/mult#2:z:slc(mult:z:mul:cmp.z)(31-0).itm REGISTER_NAME mult#1:z:slc(mult:z:mul:cmp.z)(31-0).itm
directive set /peaseNTT/peaseNTT:core/core/mult#3:z:slc(mult:z:mul:cmp.z)(31-0).itm REGISTER_NAME mult#1:z:slc(mult:z:mul:cmp.z)(31-0).itm
directive set /peaseNTT/peaseNTT:core/core/mult:z:slc(mult:z:mul:cmp.z)(31-0).itm REGISTER_NAME mult#1:z:slc(mult:z:mul:cmp.z)(31-0).itm
directive set /peaseNTT/peaseNTT:core/core/mult:x#1.sva REGISTER_NAME mult#1:z:slc(mult:z:mul:cmp.z)(31-0).itm
directive set /peaseNTT/peaseNTT:core/core/mult:x#2.sva REGISTER_NAME mult#1:z:slc(mult:z:mul:cmp.z)(31-0).itm
directive set /peaseNTT/peaseNTT:core/core/mult:x#3.sva REGISTER_NAME mult#1:z:slc(mult:z:mul:cmp.z)(31-0).itm
directive set /peaseNTT/peaseNTT:core/core/mult:x.sva REGISTER_NAME mult#1:z:slc(mult:z:mul:cmp.z)(31-0).itm
