directive set /ntt_flat/ntt_flat:core/core/INNER_LOOP:j(13:0).sva#1 REGISTER_NAME INNER_LOOP:j(13:0).sva#1
directive set /ntt_flat/ntt_flat:core/core/for:i(14:0).sva(13:0) REGISTER_NAME INNER_LOOP:j(13:0).sva#1
directive set /ntt_flat/ntt_flat:core/core/INNER_LOOP:k(17:0).sva REGISTER_NAME INNER_LOOP:k(17:0).sva
directive set /ntt_flat/ntt_flat:core/core/INNER_LOOP:j(13:0).sva(12:0) REGISTER_NAME INNER_LOOP:k(17:0).sva
directive set /ntt_flat/ntt_flat:core/core/INNER_LOOP:idx1:acc.psp.sva REGISTER_NAME INNER_LOOP:idx1:acc.psp.sva
directive set /ntt_flat/ntt_flat:core/core/INNER_LOOP:g:rshift.psp.sva REGISTER_NAME INNER_LOOP:idx1:acc.psp.sva
directive set /ntt_flat/ntt_flat:core/core/modulo_add:base.sva REGISTER_NAME modulo_add:base.sva
directive set /ntt_flat/ntt_flat:core/core/mult:res.sva REGISTER_NAME modulo_add:base.sva
directive set /ntt_flat/ntt_flat:core/core/mult:z:asn.itm REGISTER_NAME modulo_add:base.sva
