directive set /inPlaceNTT_DIT_precomp/inPlaceNTT_DIT_precomp:core/inPlaceNTT_DIT_precomp:core:conc/COMP_LOOP-1:tmp:lshift RESOURCE_NAME COMP_LOOP-1:tmp:lshift:rg
directive set /inPlaceNTT_DIT_precomp/inPlaceNTT_DIT_precomp:core/inPlaceNTT_DIT_precomp:core:conc/STAGE_LOOP:lshift RESOURCE_NAME COMP_LOOP-1:tmp:lshift:rg
directive set /inPlaceNTT_DIT_precomp/inPlaceNTT_DIT_precomp:core/inPlaceNTT_DIT_precomp:core:conc/COMP_LOOP-2:tmp:lshift RESOURCE_NAME COMP_LOOP-1:tmp:lshift:rg
directive set /inPlaceNTT_DIT_precomp/inPlaceNTT_DIT_precomp:core/inPlaceNTT_DIT_precomp:core:conc/STAGE_LOOP:acc#1 RESOURCE_NAME COMP_LOOP-1:tmp:acc:rg
directive set /inPlaceNTT_DIT_precomp/inPlaceNTT_DIT_precomp:core/inPlaceNTT_DIT_precomp:core:conc/COMP_LOOP-1:tmp:acc RESOURCE_NAME COMP_LOOP-1:tmp:acc:rg
directive set /inPlaceNTT_DIT_precomp/inPlaceNTT_DIT_precomp:core/inPlaceNTT_DIT_precomp:core:conc/COMP_LOOP:slc(COMP_LOOP-2:COMP_LOOP:acc RESOURCE_NAME COMP_LOOP:slc(COMP_LOOP-2:COMP_LOOP:acc:rg
directive set /inPlaceNTT_DIT_precomp/inPlaceNTT_DIT_precomp:core/inPlaceNTT_DIT_precomp:core:conc/STAGE_LOOP:acc RESOURCE_NAME COMP_LOOP:slc(COMP_LOOP-2:COMP_LOOP:acc:rg
directive set /inPlaceNTT_DIT_precomp/inPlaceNTT_DIT_precomp:core/inPlaceNTT_DIT_precomp:core:conc/COMP_LOOP:acc RESOURCE_NAME COMP_LOOP:acc:rg
directive set /inPlaceNTT_DIT_precomp/inPlaceNTT_DIT_precomp:core/inPlaceNTT_DIT_precomp:core:conc/VEC_LOOP:acc#1 RESOURCE_NAME COMP_LOOP:acc:rg
directive set /inPlaceNTT_DIT_precomp/inPlaceNTT_DIT_precomp:core/inPlaceNTT_DIT_precomp:core:conc/COMP_LOOP-1:tmp:mul RESOURCE_NAME COMP_LOOP-1:mul:rg
directive set /inPlaceNTT_DIT_precomp/inPlaceNTT_DIT_precomp:core/inPlaceNTT_DIT_precomp:core:conc/COMP_LOOP-1:mul RESOURCE_NAME COMP_LOOP-1:mul:rg
directive set /inPlaceNTT_DIT_precomp/inPlaceNTT_DIT_precomp:core/inPlaceNTT_DIT_precomp:core:conc/COMP_LOOP-2:mul RESOURCE_NAME COMP_LOOP-1:mul:rg
directive set /inPlaceNTT_DIT_precomp/inPlaceNTT_DIT_precomp:core/inPlaceNTT_DIT_precomp:core:conc/COMP_LOOP-2:tmp:mul RESOURCE_NAME COMP_LOOP-1:mul:rg
