directive set /inPlaceNTT_DIF/inPlaceNTT_DIF:core/core/COMP_LOOP:COMP_LOOP:nor#1.itm REGISTER_NAME COMP_LOOP:COMP_LOOP:nor#1.itm
directive set /inPlaceNTT_DIF/inPlaceNTT_DIF:core/core/COMP_LOOP:COMP_LOOP:nor#9.itm REGISTER_NAME COMP_LOOP:COMP_LOOP:nor#1.itm
directive set /inPlaceNTT_DIF/inPlaceNTT_DIF:core/core/COMP_LOOP:COMP_LOOP:and#11.itm REGISTER_NAME COMP_LOOP:COMP_LOOP:and#11.itm
directive set /inPlaceNTT_DIF/inPlaceNTT_DIF:core/core/COMP_LOOP:COMP_LOOP:and#65.itm REGISTER_NAME COMP_LOOP:COMP_LOOP:and#11.itm
directive set /inPlaceNTT_DIF/inPlaceNTT_DIF:core/core/COMP_LOOP:COMP_LOOP:and#12.itm REGISTER_NAME COMP_LOOP:COMP_LOOP:and#12.itm
directive set /inPlaceNTT_DIF/inPlaceNTT_DIF:core/core/COMP_LOOP:COMP_LOOP:and#67.itm REGISTER_NAME COMP_LOOP:COMP_LOOP:and#12.itm
directive set /inPlaceNTT_DIF/inPlaceNTT_DIF:core/core/COMP_LOOP:COMP_LOOP:and#13.itm REGISTER_NAME COMP_LOOP:COMP_LOOP:and#13.itm
directive set /inPlaceNTT_DIF/inPlaceNTT_DIF:core/core/COMP_LOOP:COMP_LOOP:and#68.itm REGISTER_NAME COMP_LOOP:COMP_LOOP:and#13.itm
directive set /inPlaceNTT_DIF/inPlaceNTT_DIF:core/core/COMP_LOOP-2:tmp:lshift.ncse.sva REGISTER_NAME COMP_LOOP-2:tmp:lshift.ncse.sva
directive set /inPlaceNTT_DIF/inPlaceNTT_DIF:core/core/COMP_LOOP-8:tmp:mul.idiv.sva REGISTER_NAME COMP_LOOP-2:tmp:lshift.ncse.sva
directive set /inPlaceNTT_DIF/inPlaceNTT_DIF:core/core/COMP_LOOP-2:tmp:mul.idiv.sva REGISTER_NAME COMP_LOOP-2:tmp:mul.idiv.sva
directive set /inPlaceNTT_DIF/inPlaceNTT_DIF:core/core/COMP_LOOP-4:tmp:mul.idiv.sva REGISTER_NAME COMP_LOOP-2:tmp:mul.idiv.sva
directive set /inPlaceNTT_DIF/inPlaceNTT_DIF:core/core/COMP_LOOP-6:tmp:mul.idiv.sva REGISTER_NAME COMP_LOOP-2:tmp:mul.idiv.sva
directive set /inPlaceNTT_DIF/inPlaceNTT_DIF:core/core/COMP_LOOP:COMP_LOOP:and#69.itm REGISTER_NAME COMP_LOOP:COMP_LOOP:and#69.itm
directive set /inPlaceNTT_DIF/inPlaceNTT_DIF:core/core/COMP_LOOP:COMP_LOOP:and#9.itm REGISTER_NAME COMP_LOOP:COMP_LOOP:and#69.itm
directive set /inPlaceNTT_DIF/inPlaceNTT_DIF:core/core/COMP_LOOP-3:tmp:lshift.ncse.sva REGISTER_NAME COMP_LOOP-3:tmp:lshift.ncse.sva
directive set /inPlaceNTT_DIF/inPlaceNTT_DIF:core/core/COMP_LOOP-7:tmp:mul.idiv.sva REGISTER_NAME COMP_LOOP-3:tmp:lshift.ncse.sva
directive set /inPlaceNTT_DIF/inPlaceNTT_DIF:core/core/COMP_LOOP-1:acc#8.itm REGISTER_NAME COMP_LOOP-1:acc#8.itm
directive set /inPlaceNTT_DIF/inPlaceNTT_DIF:core/core/COMP_LOOP-2:acc#8.itm REGISTER_NAME COMP_LOOP-1:acc#8.itm
directive set /inPlaceNTT_DIF/inPlaceNTT_DIF:core/core/COMP_LOOP-3:acc#8.itm REGISTER_NAME COMP_LOOP-1:acc#8.itm
directive set /inPlaceNTT_DIF/inPlaceNTT_DIF:core/core/COMP_LOOP-4:acc#8.itm REGISTER_NAME COMP_LOOP-1:acc#8.itm
directive set /inPlaceNTT_DIF/inPlaceNTT_DIF:core/core/COMP_LOOP-5:acc#8.itm REGISTER_NAME COMP_LOOP-1:acc#8.itm
directive set /inPlaceNTT_DIF/inPlaceNTT_DIF:core/core/COMP_LOOP-6:acc#8.itm REGISTER_NAME COMP_LOOP-1:acc#8.itm
directive set /inPlaceNTT_DIF/inPlaceNTT_DIF:core/core/COMP_LOOP-7:acc#8.itm REGISTER_NAME COMP_LOOP-1:acc#8.itm
directive set /inPlaceNTT_DIF/inPlaceNTT_DIF:core/core/COMP_LOOP-8:acc#8.itm REGISTER_NAME COMP_LOOP-1:acc#8.itm
directive set /inPlaceNTT_DIF/inPlaceNTT_DIF:core/core/COMP_LOOP:modulo(return)#17.sva REGISTER_NAME COMP_LOOP-1:acc#8.itm
directive set /inPlaceNTT_DIF/inPlaceNTT_DIF:core/core/COMP_LOOP:modulo(return)#18.sva REGISTER_NAME COMP_LOOP-1:acc#8.itm
directive set /inPlaceNTT_DIF/inPlaceNTT_DIF:core/core/COMP_LOOP:modulo(return)#19.sva REGISTER_NAME COMP_LOOP-1:acc#8.itm
directive set /inPlaceNTT_DIF/inPlaceNTT_DIF:core/core/COMP_LOOP:modulo(return)#2.sva REGISTER_NAME COMP_LOOP-1:acc#8.itm
directive set /inPlaceNTT_DIF/inPlaceNTT_DIF:core/core/COMP_LOOP:modulo(return)#20.sva REGISTER_NAME COMP_LOOP-1:acc#8.itm
directive set /inPlaceNTT_DIF/inPlaceNTT_DIF:core/core/COMP_LOOP:modulo(return)#21.sva REGISTER_NAME COMP_LOOP-1:acc#8.itm
directive set /inPlaceNTT_DIF/inPlaceNTT_DIF:core/core/COMP_LOOP:modulo(return)#22.sva REGISTER_NAME COMP_LOOP-1:acc#8.itm
directive set /inPlaceNTT_DIF/inPlaceNTT_DIF:core/core/COMP_LOOP:modulo(return)#23.sva REGISTER_NAME COMP_LOOP-1:acc#8.itm
directive set /inPlaceNTT_DIF/inPlaceNTT_DIF:core/core/COMP_LOOP-1:mul.itm REGISTER_NAME COMP_LOOP-1:acc#8.itm
directive set /inPlaceNTT_DIF/inPlaceNTT_DIF:core/core/COMP_LOOP-2:mul.itm REGISTER_NAME COMP_LOOP-1:acc#8.itm
directive set /inPlaceNTT_DIF/inPlaceNTT_DIF:core/core/COMP_LOOP-3:mul.itm REGISTER_NAME COMP_LOOP-1:acc#8.itm
directive set /inPlaceNTT_DIF/inPlaceNTT_DIF:core/core/COMP_LOOP-4:mul.itm REGISTER_NAME COMP_LOOP-1:acc#8.itm
directive set /inPlaceNTT_DIF/inPlaceNTT_DIF:core/core/COMP_LOOP-5:mul.itm REGISTER_NAME COMP_LOOP-1:acc#8.itm
directive set /inPlaceNTT_DIF/inPlaceNTT_DIF:core/core/COMP_LOOP-6:mul.itm REGISTER_NAME COMP_LOOP-1:acc#8.itm
directive set /inPlaceNTT_DIF/inPlaceNTT_DIF:core/core/COMP_LOOP-7:mul.itm REGISTER_NAME COMP_LOOP-1:acc#8.itm
directive set /inPlaceNTT_DIF/inPlaceNTT_DIF:core/core/COMP_LOOP-8:mul.itm REGISTER_NAME COMP_LOOP-1:acc#8.itm
directive set /inPlaceNTT_DIF/inPlaceNTT_DIF:core/core/tmp#1.lpi#4.dfm REGISTER_NAME COMP_LOOP-1:acc#8.itm
directive set /inPlaceNTT_DIF/inPlaceNTT_DIF:core/core/tmp#10.lpi#4.dfm REGISTER_NAME COMP_LOOP-1:acc#8.itm
directive set /inPlaceNTT_DIF/inPlaceNTT_DIF:core/core/tmp#12.lpi#4.dfm REGISTER_NAME COMP_LOOP-1:acc#8.itm
directive set /inPlaceNTT_DIF/inPlaceNTT_DIF:core/core/tmp#14.lpi#4.dfm REGISTER_NAME COMP_LOOP-1:acc#8.itm
directive set /inPlaceNTT_DIF/inPlaceNTT_DIF:core/core/tmp#2.lpi#4.dfm REGISTER_NAME COMP_LOOP-1:acc#8.itm
directive set /inPlaceNTT_DIF/inPlaceNTT_DIF:core/core/tmp#4.lpi#4.dfm REGISTER_NAME COMP_LOOP-1:acc#8.itm
directive set /inPlaceNTT_DIF/inPlaceNTT_DIF:core/core/tmp#6.lpi#4.dfm REGISTER_NAME COMP_LOOP-1:acc#8.itm
directive set /inPlaceNTT_DIF/inPlaceNTT_DIF:core/core/tmp#8.lpi#4.dfm REGISTER_NAME COMP_LOOP-1:acc#8.itm
directive set /inPlaceNTT_DIF/inPlaceNTT_DIF:core/core/tmp#21.sva#5 REGISTER_NAME COMP_LOOP-1:acc#8.itm
directive set /inPlaceNTT_DIF/inPlaceNTT_DIF:core/core/tmp#23.sva#5 REGISTER_NAME COMP_LOOP-1:acc#8.itm
directive set /inPlaceNTT_DIF/inPlaceNTT_DIF:core/core/COMP_LOOP:tmp:COMP_LOOP:tmp:nor#2.itm REGISTER_NAME COMP_LOOP:tmp:COMP_LOOP:tmp:nor#2.itm
directive set /inPlaceNTT_DIF/inPlaceNTT_DIF:core/core/COMP_LOOP:tmp:COMP_LOOP:tmp:nor#3.itm REGISTER_NAME COMP_LOOP:tmp:COMP_LOOP:tmp:nor#2.itm
directive set /inPlaceNTT_DIF/inPlaceNTT_DIF:core/core/COMP_LOOP:tmp:COMP_LOOP:tmp:nor#5.itm REGISTER_NAME COMP_LOOP:tmp:COMP_LOOP:tmp:nor#2.itm
directive set /inPlaceNTT_DIF/inPlaceNTT_DIF:core/core/COMP_LOOP:tmp:COMP_LOOP:tmp:nor.itm REGISTER_NAME COMP_LOOP:tmp:COMP_LOOP:tmp:nor#2.itm
directive set /inPlaceNTT_DIF/inPlaceNTT_DIF:core/core/COMP_LOOP:tmp:COMP_LOOP:tmp:and#12.itm REGISTER_NAME COMP_LOOP:tmp:COMP_LOOP:tmp:and#12.itm
directive set /inPlaceNTT_DIF/inPlaceNTT_DIF:core/core/COMP_LOOP:tmp:COMP_LOOP:tmp:and#19.itm REGISTER_NAME COMP_LOOP:tmp:COMP_LOOP:tmp:and#12.itm
directive set /inPlaceNTT_DIF/inPlaceNTT_DIF:core/core/COMP_LOOP:tmp:COMP_LOOP:tmp:and#2.itm REGISTER_NAME COMP_LOOP:tmp:COMP_LOOP:tmp:and#12.itm
directive set /inPlaceNTT_DIF/inPlaceNTT_DIF:core/core/COMP_LOOP:tmp:COMP_LOOP:tmp:and#29.itm REGISTER_NAME COMP_LOOP:tmp:COMP_LOOP:tmp:and#12.itm
directive set /inPlaceNTT_DIF/inPlaceNTT_DIF:core/core/COMP_LOOP:tmp:COMP_LOOP:tmp:and#14.itm REGISTER_NAME COMP_LOOP:tmp:COMP_LOOP:tmp:and#14.itm
directive set /inPlaceNTT_DIF/inPlaceNTT_DIF:core/core/COMP_LOOP:tmp:COMP_LOOP:tmp:and#21.itm REGISTER_NAME COMP_LOOP:tmp:COMP_LOOP:tmp:and#14.itm
directive set /inPlaceNTT_DIF/inPlaceNTT_DIF:core/core/COMP_LOOP:tmp:COMP_LOOP:tmp:and#31.itm REGISTER_NAME COMP_LOOP:tmp:COMP_LOOP:tmp:and#14.itm
directive set /inPlaceNTT_DIF/inPlaceNTT_DIF:core/core/COMP_LOOP:tmp:COMP_LOOP:tmp:and#4.itm REGISTER_NAME COMP_LOOP:tmp:COMP_LOOP:tmp:and#14.itm
directive set /inPlaceNTT_DIF/inPlaceNTT_DIF:core/core/COMP_LOOP:tmp:COMP_LOOP:tmp:and#15.itm REGISTER_NAME COMP_LOOP:tmp:COMP_LOOP:tmp:and#15.itm
directive set /inPlaceNTT_DIF/inPlaceNTT_DIF:core/core/COMP_LOOP:tmp:COMP_LOOP:tmp:and#22.itm REGISTER_NAME COMP_LOOP:tmp:COMP_LOOP:tmp:and#15.itm
directive set /inPlaceNTT_DIF/inPlaceNTT_DIF:core/core/COMP_LOOP:tmp:COMP_LOOP:tmp:and#32.itm REGISTER_NAME COMP_LOOP:tmp:COMP_LOOP:tmp:and#15.itm
directive set /inPlaceNTT_DIF/inPlaceNTT_DIF:core/core/COMP_LOOP:tmp:COMP_LOOP:tmp:and#5.itm REGISTER_NAME COMP_LOOP:tmp:COMP_LOOP:tmp:and#15.itm
directive set /inPlaceNTT_DIF/inPlaceNTT_DIF:core/core/COMP_LOOP:tmp:COMP_LOOP:tmp:and#16.itm REGISTER_NAME COMP_LOOP:tmp:COMP_LOOP:tmp:and#16.itm
directive set /inPlaceNTT_DIF/inPlaceNTT_DIF:core/core/COMP_LOOP:tmp:COMP_LOOP:tmp:and#23.itm REGISTER_NAME COMP_LOOP:tmp:COMP_LOOP:tmp:and#16.itm
directive set /inPlaceNTT_DIF/inPlaceNTT_DIF:core/core/COMP_LOOP:tmp:COMP_LOOP:tmp:and#33.itm REGISTER_NAME COMP_LOOP:tmp:COMP_LOOP:tmp:and#16.itm
directive set /inPlaceNTT_DIF/inPlaceNTT_DIF:core/core/COMP_LOOP:tmp:COMP_LOOP:tmp:and#6.itm REGISTER_NAME COMP_LOOP:tmp:COMP_LOOP:tmp:and#16.itm
directive set /inPlaceNTT_DIF/inPlaceNTT_DIF:core/core/tmp#21.sva#3 REGISTER_NAME tmp#21.sva#3
directive set /inPlaceNTT_DIF/inPlaceNTT_DIF:core/core/tmp#23.sva#3 REGISTER_NAME tmp#21.sva#3
directive set /inPlaceNTT_DIF/inPlaceNTT_DIF:core/core/COMP_LOOP:tmp:mux1h#5.itm REGISTER_NAME tmp#21.sva#3
directive set /inPlaceNTT_DIF/inPlaceNTT_DIF:core/core/tmp#22.sva#3 REGISTER_NAME tmp#21.sva#3
directive set /inPlaceNTT_DIF/inPlaceNTT_DIF:core/core/tmp#21.sva#6 REGISTER_NAME tmp#21.sva#6
directive set /inPlaceNTT_DIF/inPlaceNTT_DIF:core/core/tmp#23.sva#6 REGISTER_NAME tmp#21.sva#6
directive set /inPlaceNTT_DIF/inPlaceNTT_DIF:core/core/tmp#21.sva#7 REGISTER_NAME tmp#21.sva#7
directive set /inPlaceNTT_DIF/inPlaceNTT_DIF:core/core/tmp#23.sva#7 REGISTER_NAME tmp#21.sva#7
directive set /inPlaceNTT_DIF/inPlaceNTT_DIF:core/core/COMP_LOOP:tmp:mux1h#3.itm REGISTER_NAME COMP_LOOP:tmp:mux1h#3.itm
directive set /inPlaceNTT_DIF/inPlaceNTT_DIF:core/core/tmp#21.sva#1 REGISTER_NAME COMP_LOOP:tmp:mux1h#3.itm
directive set /inPlaceNTT_DIF/inPlaceNTT_DIF:core/core/tmp#21.sva#2 REGISTER_NAME COMP_LOOP:tmp:mux1h#3.itm
directive set /inPlaceNTT_DIF/inPlaceNTT_DIF:core/core/COMP_LOOP:tmp:mux1h#4.itm REGISTER_NAME COMP_LOOP:tmp:mux1h#4.itm
directive set /inPlaceNTT_DIF/inPlaceNTT_DIF:core/core/tmp#22.sva#1 REGISTER_NAME COMP_LOOP:tmp:mux1h#4.itm
