directive set /stockham_DIT/stockham_DIT:core/stockham_DIT:core:conc/INNER_LOOP:b:acc#2 RESOURCE_NAME INNER_LOOP:b:acc#2:rg
directive set /stockham_DIT/stockham_DIT:core/stockham_DIT:core:conc/OUTER_LOOP:acc RESOURCE_NAME INNER_LOOP:b:acc#2:rg
directive set /stockham_DIT/stockham_DIT:core/stockham_DIT:core:conc/INNER_LOOP-1:modulo_dev:qelse:acc RESOURCE_NAME INNER_LOOP-1:acc#5:rg
directive set /stockham_DIT/stockham_DIT:core/stockham_DIT:core:conc/INNER_LOOP-1:acc#5 RESOURCE_NAME INNER_LOOP-1:acc#5:rg
directive set /stockham_DIT/stockham_DIT:core/stockham_DIT:core:conc/INNER_LOOP-1:b:mul RESOURCE_NAME INNER_LOOP-1:b:mul:rg
directive set /stockham_DIT/stockham_DIT:core/stockham_DIT:core:conc/INNER_LOOP-1:mul RESOURCE_NAME INNER_LOOP-1:b:mul:rg
directive set /stockham_DIT/stockham_DIT:core/stockham_DIT:core:conc/INNER_LOOP-1:w:rshift RESOURCE_NAME INNER_LOOP-1:w:rshift:rg
directive set /stockham_DIT/stockham_DIT:core/stockham_DIT:core:conc/INNER_LOOP-2:w:rshift RESOURCE_NAME INNER_LOOP-1:w:rshift:rg
directive set /stockham_DIT/stockham_DIT:core/stockham_DIT:core:conc/INNER_LOOP-1:w:lshift RESOURCE_NAME INNER_LOOP-1:w:lshift:rg
directive set /stockham_DIT/stockham_DIT:core/stockham_DIT:core:conc/INNER_LOOP-2:w:lshift RESOURCE_NAME INNER_LOOP-1:w:lshift:rg
