directive set /inPlaceNTT_DIF_precomp/inPlaceNTT_DIF_precomp:core/inPlaceNTT_DIF_precomp:core:conc/STAGE_LOOP:lshift RESOURCE_NAME COMP_LOOP:twiddle_f:lshift:rg
directive set /inPlaceNTT_DIF_precomp/inPlaceNTT_DIF_precomp:core/inPlaceNTT_DIF_precomp:core:conc/COMP_LOOP:twiddle_f:lshift RESOURCE_NAME COMP_LOOP:twiddle_f:lshift:rg
