directive set /ntt_flat/ntt_flat:core/core/mult:res.lpi#3.dfm.1 REGISTER_NAME mult:res.lpi#3.dfm.1
directive set /ntt_flat/ntt_flat:core/core/mult:z:asn.itm REGISTER_NAME mult:res.lpi#3.dfm.1
directive set /ntt_flat/ntt_flat:core/core/butterFly:idx2(17:0).sva.4(13:0) REGISTER_NAME butterFly:idx2(17:0).sva.4(13:0)
directive set /ntt_flat/ntt_flat:core/core/INNER_LOOP:g:rshift.psp.sva REGISTER_NAME butterFly:idx2(17:0).sva.4(13:0)
directive set /ntt_flat/ntt_flat:core/core/INNER_LOOP.stage_0 REGISTER_NAME INNER_LOOP.stage_0
directive set /ntt_flat/ntt_flat:core/core/for.stage_0 REGISTER_NAME INNER_LOOP.stage_0
directive set /ntt_flat/ntt_flat:core/core/INNER_LOOP.stage_0.1 REGISTER_NAME INNER_LOOP.stage_0.1
directive set /ntt_flat/ntt_flat:core/core/for.stage_0.2 REGISTER_NAME INNER_LOOP.stage_0.1
directive set /ntt_flat/ntt_flat:core/core/butterFly:idx2(17:0).sva.3(13:0) REGISTER_NAME butterFly:idx2(17:0).sva.3(13:0)
directive set /ntt_flat/ntt_flat:core/core/for:i:slc(for:i(14:0))(13-0)#1.itm.1 REGISTER_NAME butterFly:idx2(17:0).sva.3(13:0)
directive set /ntt_flat/ntt_flat:core/core/butterFly:idx2(17:0).sva.2(13:0) REGISTER_NAME butterFly:idx2(17:0).sva.2(13:0)
directive set /ntt_flat/ntt_flat:core/core/for:i(14:0).sva(13:0) REGISTER_NAME butterFly:idx2(17:0).sva.2(13:0)
directive set /ntt_flat/ntt_flat:core/core/INNER_LOOP:tf:slc(twiddle:rsci.qa_d)(31-0).itm REGISTER_NAME INNER_LOOP:tf:slc(twiddle:rsci.qa_d)(31-0).itm
directive set /ntt_flat/ntt_flat:core/core/operator>><96,false>:operator>><96,false>:slc(mult:t:mul)(51-20).itm REGISTER_NAME INNER_LOOP:tf:slc(twiddle:rsci.qa_d)(31-0).itm
