directive set /stockham_dit/stockham_dit:core/stockham_dit:core:conc/mult:if:acc#1 RESOURCE_NAME modulo_add:acc#1:rg
directive set /stockham_dit/stockham_dit:core/stockham_dit:core:conc/modulo_add:acc#1 RESOURCE_NAME modulo_add:acc#1:rg
directive set /stockham_dit/stockham_dit:core/stockham_dit:core:conc/mult:if:acc RESOURCE_NAME modulo_sub:qif:acc:rg
directive set /stockham_dit/stockham_dit:core/stockham_dit:core:conc/modulo_sub:qif:acc RESOURCE_NAME modulo_sub:qif:acc:rg
directive set /stockham_dit/stockham_dit:core/stockham_dit:core:conc/mult:res:acc RESOURCE_NAME modulo_add:qif:acc:rg
directive set /stockham_dit/stockham_dit:core/stockham_dit:core:conc/modulo_add:qif:acc RESOURCE_NAME modulo_add:qif:acc:rg
directive set /stockham_dit/stockham_dit:core/stockham_dit:core:conc/for:for:mul RESOURCE_NAME for:for:mul:rg
directive set /stockham_dit/stockham_dit:core/stockham_dit:core:conc/mult:z_:mul RESOURCE_NAME for:for:mul:rg
directive set /stockham_dit/stockham_dit:core/stockham_dit:core:conc/for:for:acc#6 RESOURCE_NAME for:for:acc#6:rg
directive set /stockham_dit/stockham_dit:core/stockham_dit:core:conc/operator<<32,false>:acc RESOURCE_NAME for:for:acc#6:rg
