directive set /inPlaceNTT_DIF_precomp/inPlaceNTT_DIF_precomp:core/inPlaceNTT_DIF_precomp:core:conc/COMP_LOOP-1:twiddle_f:lshift RESOURCE_NAME COMP_LOOP-1:twiddle_f:lshift:rg
directive set /inPlaceNTT_DIF_precomp/inPlaceNTT_DIF_precomp:core/inPlaceNTT_DIF_precomp:core:conc/COMP_LOOP-2:twiddle_f:lshift RESOURCE_NAME COMP_LOOP-1:twiddle_f:lshift:rg
directive set /inPlaceNTT_DIF_precomp/inPlaceNTT_DIF_precomp:core/inPlaceNTT_DIF_precomp:core:conc/STAGE_LOOP:lshift RESOURCE_NAME COMP_LOOP-3:twiddle_f:lshift:rg
directive set /inPlaceNTT_DIF_precomp/inPlaceNTT_DIF_precomp:core/inPlaceNTT_DIF_precomp:core:conc/COMP_LOOP-3:twiddle_f:lshift RESOURCE_NAME COMP_LOOP-3:twiddle_f:lshift:rg
directive set /inPlaceNTT_DIF_precomp/inPlaceNTT_DIF_precomp:core/inPlaceNTT_DIF_precomp:core:conc/COMP_LOOP-3:twiddle_f:mul RESOURCE_NAME COMP_LOOP-2:twiddle_f:mul:rg
directive set /inPlaceNTT_DIF_precomp/inPlaceNTT_DIF_precomp:core/inPlaceNTT_DIF_precomp:core:conc/COMP_LOOP-2:twiddle_f:mul RESOURCE_NAME COMP_LOOP-2:twiddle_f:mul:rg
directive set /inPlaceNTT_DIF_precomp/inPlaceNTT_DIF_precomp:core/inPlaceNTT_DIF_precomp:core:conc/COMP_LOOP-1:twiddle_f:mul RESOURCE_NAME COMP_LOOP-1:twiddle_f:mul:rg
directive set /inPlaceNTT_DIF_precomp/inPlaceNTT_DIF_precomp:core/inPlaceNTT_DIF_precomp:core:conc/COMP_LOOP-4:twiddle_f:mul RESOURCE_NAME COMP_LOOP-1:twiddle_f:mul:rg
directive set /inPlaceNTT_DIF_precomp/inPlaceNTT_DIF_precomp:core/inPlaceNTT_DIF_precomp:core:conc/VEC_LOOP:acc#12 RESOURCE_NAME VEC_LOOP:acc#12:rg
directive set /inPlaceNTT_DIF_precomp/inPlaceNTT_DIF_precomp:core/inPlaceNTT_DIF_precomp:core:conc/VEC_LOOP:acc#13 RESOURCE_NAME VEC_LOOP:acc#12:rg
directive set /inPlaceNTT_DIF_precomp/inPlaceNTT_DIF_precomp:core/inPlaceNTT_DIF_precomp:core:conc/VEC_LOOP:acc#14 RESOURCE_NAME VEC_LOOP:acc#12:rg
directive set /inPlaceNTT_DIF_precomp/inPlaceNTT_DIF_precomp:core/inPlaceNTT_DIF_precomp:core:conc/VEC_LOOP:acc#15 RESOURCE_NAME VEC_LOOP:acc#12:rg
directive set /inPlaceNTT_DIF_precomp/inPlaceNTT_DIF_precomp:core/inPlaceNTT_DIF_precomp:core:conc/COMP_LOOP-1:VEC_LOOP:acc#10 RESOURCE_NAME COMP_LOOP-1:VEC_LOOP:acc#10:rg
directive set /inPlaceNTT_DIF_precomp/inPlaceNTT_DIF_precomp:core/inPlaceNTT_DIF_precomp:core:conc/COMP_LOOP-2:VEC_LOOP:acc#10 RESOURCE_NAME COMP_LOOP-1:VEC_LOOP:acc#10:rg
directive set /inPlaceNTT_DIF_precomp/inPlaceNTT_DIF_precomp:core/inPlaceNTT_DIF_precomp:core:conc/COMP_LOOP-2:VEC_LOOP:acc#1 RESOURCE_NAME COMP_LOOP-2:VEC_LOOP:acc#1:rg
directive set /inPlaceNTT_DIF_precomp/inPlaceNTT_DIF_precomp:core/inPlaceNTT_DIF_precomp:core:conc/COMP_LOOP-4:VEC_LOOP:acc#1 RESOURCE_NAME COMP_LOOP-2:VEC_LOOP:acc#1:rg
directive set /inPlaceNTT_DIF_precomp/inPlaceNTT_DIF_precomp:core/inPlaceNTT_DIF_precomp:core:conc/COMP_LOOP-3:VEC_LOOP:acc#10 RESOURCE_NAME COMP_LOOP-3:VEC_LOOP:acc#10:rg
directive set /inPlaceNTT_DIF_precomp/inPlaceNTT_DIF_precomp:core/inPlaceNTT_DIF_precomp:core:conc/COMP_LOOP-4:VEC_LOOP:acc#10 RESOURCE_NAME COMP_LOOP-3:VEC_LOOP:acc#10:rg
directive set /inPlaceNTT_DIF_precomp/inPlaceNTT_DIF_precomp:core/inPlaceNTT_DIF_precomp:core:conc/VEC_LOOP:acc RESOURCE_NAME COMP_LOOP:acc#2:rg
directive set /inPlaceNTT_DIF_precomp/inPlaceNTT_DIF_precomp:core/inPlaceNTT_DIF_precomp:core:conc/COMP_LOOP:acc#2 RESOURCE_NAME COMP_LOOP:acc#2:rg
directive set /inPlaceNTT_DIF_precomp/inPlaceNTT_DIF_precomp:core/inPlaceNTT_DIF_precomp:core:conc/VEC_LOOP:acc#11 RESOURCE_NAME COMP_LOOP:acc:rg
directive set /inPlaceNTT_DIF_precomp/inPlaceNTT_DIF_precomp:core/inPlaceNTT_DIF_precomp:core:conc/COMP_LOOP:acc RESOURCE_NAME COMP_LOOP:acc:rg
directive set /inPlaceNTT_DIF_precomp/inPlaceNTT_DIF_precomp:core/inPlaceNTT_DIF_precomp:core:conc/COMP_LOOP-3:acc RESOURCE_NAME COMP_LOOP-2:acc:rg
directive set /inPlaceNTT_DIF_precomp/inPlaceNTT_DIF_precomp:core/inPlaceNTT_DIF_precomp:core:conc/COMP_LOOP-2:acc RESOURCE_NAME COMP_LOOP-2:acc:rg
