directive set /inPlaceNTT_DIF_precomp/inPlaceNTT_DIF_precomp:core/inPlaceNTT_DIF_precomp:core:conc/COMP_LOOP-1:twiddle_f:lshift RESOURCE_NAME COMP_LOOP-1:twiddle_f:lshift:rg
directive set /inPlaceNTT_DIF_precomp/inPlaceNTT_DIF_precomp:core/inPlaceNTT_DIF_precomp:core:conc/COMP_LOOP-5:twiddle_f:lshift RESOURCE_NAME COMP_LOOP-1:twiddle_f:lshift:rg
directive set /inPlaceNTT_DIF_precomp/inPlaceNTT_DIF_precomp:core/inPlaceNTT_DIF_precomp:core:conc/COMP_LOOP-5:twiddle_f:mul RESOURCE_NAME COMP_LOOP-13:twiddle_f:mul:rg
directive set /inPlaceNTT_DIF_precomp/inPlaceNTT_DIF_precomp:core/inPlaceNTT_DIF_precomp:core:conc/COMP_LOOP-2:twiddle_f:mul RESOURCE_NAME COMP_LOOP-13:twiddle_f:mul:rg
directive set /inPlaceNTT_DIF_precomp/inPlaceNTT_DIF_precomp:core/inPlaceNTT_DIF_precomp:core:conc/COMP_LOOP-3:twiddle_f:mul RESOURCE_NAME COMP_LOOP-13:twiddle_f:mul:rg
directive set /inPlaceNTT_DIF_precomp/inPlaceNTT_DIF_precomp:core/inPlaceNTT_DIF_precomp:core:conc/COMP_LOOP-4:twiddle_f:mul RESOURCE_NAME COMP_LOOP-13:twiddle_f:mul:rg
directive set /inPlaceNTT_DIF_precomp/inPlaceNTT_DIF_precomp:core/inPlaceNTT_DIF_precomp:core:conc/COMP_LOOP-6:twiddle_f:mul RESOURCE_NAME COMP_LOOP-13:twiddle_f:mul:rg
directive set /inPlaceNTT_DIF_precomp/inPlaceNTT_DIF_precomp:core/inPlaceNTT_DIF_precomp:core:conc/COMP_LOOP-8:twiddle_f:mul RESOURCE_NAME COMP_LOOP-13:twiddle_f:mul:rg
directive set /inPlaceNTT_DIF_precomp/inPlaceNTT_DIF_precomp:core/inPlaceNTT_DIF_precomp:core:conc/COMP_LOOP-13:twiddle_f:mul RESOURCE_NAME COMP_LOOP-13:twiddle_f:mul:rg
directive set /inPlaceNTT_DIF_precomp/inPlaceNTT_DIF_precomp:core/inPlaceNTT_DIF_precomp:core:conc/COMP_LOOP-14:twiddle_f:mul RESOURCE_NAME COMP_LOOP-13:twiddle_f:mul:rg
directive set /inPlaceNTT_DIF_precomp/inPlaceNTT_DIF_precomp:core/inPlaceNTT_DIF_precomp:core:conc/COMP_LOOP-9:twiddle_f:mul RESOURCE_NAME COMP_LOOP-10:twiddle_f:mul:rg
directive set /inPlaceNTT_DIF_precomp/inPlaceNTT_DIF_precomp:core/inPlaceNTT_DIF_precomp:core:conc/COMP_LOOP-7:twiddle_f:mul RESOURCE_NAME COMP_LOOP-10:twiddle_f:mul:rg
directive set /inPlaceNTT_DIF_precomp/inPlaceNTT_DIF_precomp:core/inPlaceNTT_DIF_precomp:core:conc/COMP_LOOP-10:twiddle_f:mul RESOURCE_NAME COMP_LOOP-10:twiddle_f:mul:rg
directive set /inPlaceNTT_DIF_precomp/inPlaceNTT_DIF_precomp:core/inPlaceNTT_DIF_precomp:core:conc/COMP_LOOP-11:twiddle_f:mul RESOURCE_NAME COMP_LOOP-10:twiddle_f:mul:rg
directive set /inPlaceNTT_DIF_precomp/inPlaceNTT_DIF_precomp:core/inPlaceNTT_DIF_precomp:core:conc/COMP_LOOP-12:twiddle_f:mul RESOURCE_NAME COMP_LOOP-10:twiddle_f:mul:rg
directive set /inPlaceNTT_DIF_precomp/inPlaceNTT_DIF_precomp:core/inPlaceNTT_DIF_precomp:core:conc/COMP_LOOP-15:twiddle_f:mul RESOURCE_NAME COMP_LOOP-10:twiddle_f:mul:rg
directive set /inPlaceNTT_DIF_precomp/inPlaceNTT_DIF_precomp:core/inPlaceNTT_DIF_precomp:core:conc/COMP_LOOP-16:twiddle_f:mul RESOURCE_NAME COMP_LOOP-10:twiddle_f:mul:rg
directive set /inPlaceNTT_DIF_precomp/inPlaceNTT_DIF_precomp:core/inPlaceNTT_DIF_precomp:core:conc/COMP_LOOP-2:VEC_LOOP:acc#1 RESOURCE_NAME COMP_LOOP-10:VEC_LOOP:acc#1:rg
directive set /inPlaceNTT_DIF_precomp/inPlaceNTT_DIF_precomp:core/inPlaceNTT_DIF_precomp:core:conc/COMP_LOOP-4:VEC_LOOP:acc#1 RESOURCE_NAME COMP_LOOP-10:VEC_LOOP:acc#1:rg
directive set /inPlaceNTT_DIF_precomp/inPlaceNTT_DIF_precomp:core/inPlaceNTT_DIF_precomp:core:conc/COMP_LOOP-6:VEC_LOOP:acc#1 RESOURCE_NAME COMP_LOOP-10:VEC_LOOP:acc#1:rg
directive set /inPlaceNTT_DIF_precomp/inPlaceNTT_DIF_precomp:core/inPlaceNTT_DIF_precomp:core:conc/COMP_LOOP-8:VEC_LOOP:acc#1 RESOURCE_NAME COMP_LOOP-10:VEC_LOOP:acc#1:rg
directive set /inPlaceNTT_DIF_precomp/inPlaceNTT_DIF_precomp:core/inPlaceNTT_DIF_precomp:core:conc/COMP_LOOP-10:VEC_LOOP:acc#1 RESOURCE_NAME COMP_LOOP-10:VEC_LOOP:acc#1:rg
directive set /inPlaceNTT_DIF_precomp/inPlaceNTT_DIF_precomp:core/inPlaceNTT_DIF_precomp:core:conc/COMP_LOOP-12:VEC_LOOP:acc#1 RESOURCE_NAME COMP_LOOP-10:VEC_LOOP:acc#1:rg
directive set /inPlaceNTT_DIF_precomp/inPlaceNTT_DIF_precomp:core/inPlaceNTT_DIF_precomp:core:conc/COMP_LOOP-14:VEC_LOOP:acc#1 RESOURCE_NAME COMP_LOOP-10:VEC_LOOP:acc#1:rg
directive set /inPlaceNTT_DIF_precomp/inPlaceNTT_DIF_precomp:core/inPlaceNTT_DIF_precomp:core:conc/COMP_LOOP-16:VEC_LOOP:acc#1 RESOURCE_NAME COMP_LOOP-10:VEC_LOOP:acc#1:rg
directive set /inPlaceNTT_DIF_precomp/inPlaceNTT_DIF_precomp:core/inPlaceNTT_DIF_precomp:core:conc/COMP_LOOP-11:VEC_LOOP:acc#10 RESOURCE_NAME COMP_LOOP-10:VEC_LOOP:acc#1:rg
directive set /inPlaceNTT_DIF_precomp/inPlaceNTT_DIF_precomp:core/inPlaceNTT_DIF_precomp:core:conc/COMP_LOOP-8:VEC_LOOP:acc#10 RESOURCE_NAME COMP_LOOP-12:VEC_LOOP:acc#10:rg
directive set /inPlaceNTT_DIF_precomp/inPlaceNTT_DIF_precomp:core/inPlaceNTT_DIF_precomp:core:conc/COMP_LOOP-12:VEC_LOOP:acc#10 RESOURCE_NAME COMP_LOOP-12:VEC_LOOP:acc#10:rg
directive set /inPlaceNTT_DIF_precomp/inPlaceNTT_DIF_precomp:core/inPlaceNTT_DIF_precomp:core:conc/VEC_LOOP:acc#20 RESOURCE_NAME VEC_LOOP:acc#20:rg
directive set /inPlaceNTT_DIF_precomp/inPlaceNTT_DIF_precomp:core/inPlaceNTT_DIF_precomp:core:conc/VEC_LOOP:acc#21 RESOURCE_NAME VEC_LOOP:acc#20:rg
directive set /inPlaceNTT_DIF_precomp/inPlaceNTT_DIF_precomp:core/inPlaceNTT_DIF_precomp:core:conc/VEC_LOOP:acc#22 RESOURCE_NAME VEC_LOOP:acc#20:rg
directive set /inPlaceNTT_DIF_precomp/inPlaceNTT_DIF_precomp:core/inPlaceNTT_DIF_precomp:core:conc/VEC_LOOP:acc#23 RESOURCE_NAME VEC_LOOP:acc#20:rg
directive set /inPlaceNTT_DIF_precomp/inPlaceNTT_DIF_precomp:core/inPlaceNTT_DIF_precomp:core:conc/VEC_LOOP:acc#24 RESOURCE_NAME VEC_LOOP:acc#20:rg
directive set /inPlaceNTT_DIF_precomp/inPlaceNTT_DIF_precomp:core/inPlaceNTT_DIF_precomp:core:conc/VEC_LOOP:acc#25 RESOURCE_NAME VEC_LOOP:acc#20:rg
directive set /inPlaceNTT_DIF_precomp/inPlaceNTT_DIF_precomp:core/inPlaceNTT_DIF_precomp:core:conc/VEC_LOOP:acc#26 RESOURCE_NAME VEC_LOOP:acc#20:rg
directive set /inPlaceNTT_DIF_precomp/inPlaceNTT_DIF_precomp:core/inPlaceNTT_DIF_precomp:core:conc/VEC_LOOP:acc#28 RESOURCE_NAME VEC_LOOP:acc#20:rg
directive set /inPlaceNTT_DIF_precomp/inPlaceNTT_DIF_precomp:core/inPlaceNTT_DIF_precomp:core:conc/VEC_LOOP:acc#29 RESOURCE_NAME VEC_LOOP:acc#20:rg
directive set /inPlaceNTT_DIF_precomp/inPlaceNTT_DIF_precomp:core/inPlaceNTT_DIF_precomp:core:conc/VEC_LOOP:acc#30 RESOURCE_NAME VEC_LOOP:acc#20:rg
directive set /inPlaceNTT_DIF_precomp/inPlaceNTT_DIF_precomp:core/inPlaceNTT_DIF_precomp:core:conc/VEC_LOOP:acc#31 RESOURCE_NAME VEC_LOOP:acc#20:rg
directive set /inPlaceNTT_DIF_precomp/inPlaceNTT_DIF_precomp:core/inPlaceNTT_DIF_precomp:core:conc/VEC_LOOP:acc#32 RESOURCE_NAME VEC_LOOP:acc#20:rg
directive set /inPlaceNTT_DIF_precomp/inPlaceNTT_DIF_precomp:core/inPlaceNTT_DIF_precomp:core:conc/VEC_LOOP:acc#33 RESOURCE_NAME VEC_LOOP:acc#20:rg
directive set /inPlaceNTT_DIF_precomp/inPlaceNTT_DIF_precomp:core/inPlaceNTT_DIF_precomp:core:conc/VEC_LOOP:acc#34 RESOURCE_NAME VEC_LOOP:acc#20:rg
directive set /inPlaceNTT_DIF_precomp/inPlaceNTT_DIF_precomp:core/inPlaceNTT_DIF_precomp:core:conc/COMP_LOOP-1:VEC_LOOP:acc#10 RESOURCE_NAME COMP_LOOP-1:VEC_LOOP:acc#10:rg
directive set /inPlaceNTT_DIF_precomp/inPlaceNTT_DIF_precomp:core/inPlaceNTT_DIF_precomp:core:conc/COMP_LOOP-7:VEC_LOOP:acc#10 RESOURCE_NAME COMP_LOOP-1:VEC_LOOP:acc#10:rg
directive set /inPlaceNTT_DIF_precomp/inPlaceNTT_DIF_precomp:core/inPlaceNTT_DIF_precomp:core:conc/COMP_LOOP-9:VEC_LOOP:acc#10 RESOURCE_NAME COMP_LOOP-1:VEC_LOOP:acc#10:rg
directive set /inPlaceNTT_DIF_precomp/inPlaceNTT_DIF_precomp:core/inPlaceNTT_DIF_precomp:core:conc/COMP_LOOP-10:VEC_LOOP:acc#10 RESOURCE_NAME COMP_LOOP-10:VEC_LOOP:acc#10:rg
directive set /inPlaceNTT_DIF_precomp/inPlaceNTT_DIF_precomp:core/inPlaceNTT_DIF_precomp:core:conc/COMP_LOOP-16:VEC_LOOP:acc#10 RESOURCE_NAME COMP_LOOP-10:VEC_LOOP:acc#10:rg
directive set /inPlaceNTT_DIF_precomp/inPlaceNTT_DIF_precomp:core/inPlaceNTT_DIF_precomp:core:conc/COMP_LOOP-5:VEC_LOOP:acc#10 RESOURCE_NAME COMP_LOOP-15:VEC_LOOP:acc#10:rg
directive set /inPlaceNTT_DIF_precomp/inPlaceNTT_DIF_precomp:core/inPlaceNTT_DIF_precomp:core:conc/COMP_LOOP-15:VEC_LOOP:acc#10 RESOURCE_NAME COMP_LOOP-15:VEC_LOOP:acc#10:rg
directive set /inPlaceNTT_DIF_precomp/inPlaceNTT_DIF_precomp:core/inPlaceNTT_DIF_precomp:core:conc/COMP_LOOP-4:VEC_LOOP:acc#10 RESOURCE_NAME COMP_LOOP-14:VEC_LOOP:acc#10:rg
directive set /inPlaceNTT_DIF_precomp/inPlaceNTT_DIF_precomp:core/inPlaceNTT_DIF_precomp:core:conc/COMP_LOOP-14:VEC_LOOP:acc#10 RESOURCE_NAME COMP_LOOP-14:VEC_LOOP:acc#10:rg
directive set /inPlaceNTT_DIF_precomp/inPlaceNTT_DIF_precomp:core/inPlaceNTT_DIF_precomp:core:conc/COMP_LOOP-3:VEC_LOOP:acc#10 RESOURCE_NAME COMP_LOOP-13:VEC_LOOP:acc#10:rg
directive set /inPlaceNTT_DIF_precomp/inPlaceNTT_DIF_precomp:core/inPlaceNTT_DIF_precomp:core:conc/COMP_LOOP-13:VEC_LOOP:acc#10 RESOURCE_NAME COMP_LOOP-13:VEC_LOOP:acc#10:rg
directive set /inPlaceNTT_DIF_precomp/inPlaceNTT_DIF_precomp:core/inPlaceNTT_DIF_precomp:core:conc/COMP_LOOP-2:VEC_LOOP:acc#10 RESOURCE_NAME COMP_LOOP-2:VEC_LOOP:acc#10:rg
directive set /inPlaceNTT_DIF_precomp/inPlaceNTT_DIF_precomp:core/inPlaceNTT_DIF_precomp:core:conc/COMP_LOOP-6:VEC_LOOP:acc#10 RESOURCE_NAME COMP_LOOP-2:VEC_LOOP:acc#10:rg
directive set /inPlaceNTT_DIF_precomp/inPlaceNTT_DIF_precomp:core/inPlaceNTT_DIF_precomp:core:conc/COMP_LOOP-2:VEC_LOOP:acc#9 RESOURCE_NAME COMP_LOOP-10:acc:rg
directive set /inPlaceNTT_DIF_precomp/inPlaceNTT_DIF_precomp:core/inPlaceNTT_DIF_precomp:core:conc/COMP_LOOP-14:acc RESOURCE_NAME COMP_LOOP-10:acc:rg
directive set /inPlaceNTT_DIF_precomp/inPlaceNTT_DIF_precomp:core/inPlaceNTT_DIF_precomp:core:conc/COMP_LOOP-15:acc RESOURCE_NAME COMP_LOOP-10:acc:rg
directive set /inPlaceNTT_DIF_precomp/inPlaceNTT_DIF_precomp:core/inPlaceNTT_DIF_precomp:core:conc/COMP_LOOP-13:acc RESOURCE_NAME COMP_LOOP-10:acc:rg
directive set /inPlaceNTT_DIF_precomp/inPlaceNTT_DIF_precomp:core/inPlaceNTT_DIF_precomp:core:conc/COMP_LOOP-11:acc RESOURCE_NAME COMP_LOOP-10:acc:rg
directive set /inPlaceNTT_DIF_precomp/inPlaceNTT_DIF_precomp:core/inPlaceNTT_DIF_precomp:core:conc/COMP_LOOP-10:acc RESOURCE_NAME COMP_LOOP-10:acc:rg
directive set /inPlaceNTT_DIF_precomp/inPlaceNTT_DIF_precomp:core/inPlaceNTT_DIF_precomp:core:conc/COMP_LOOP-3:acc RESOURCE_NAME COMP_LOOP-10:acc:rg
directive set /inPlaceNTT_DIF_precomp/inPlaceNTT_DIF_precomp:core/inPlaceNTT_DIF_precomp:core:conc/COMP_LOOP-9:acc RESOURCE_NAME COMP_LOOP-10:acc:rg
directive set /inPlaceNTT_DIF_precomp/inPlaceNTT_DIF_precomp:core/inPlaceNTT_DIF_precomp:core:conc/COMP_LOOP-6:acc RESOURCE_NAME COMP_LOOP-10:acc:rg
directive set /inPlaceNTT_DIF_precomp/inPlaceNTT_DIF_precomp:core/inPlaceNTT_DIF_precomp:core:conc/COMP_LOOP-5:acc RESOURCE_NAME COMP_LOOP-10:acc:rg
directive set /inPlaceNTT_DIF_precomp/inPlaceNTT_DIF_precomp:core/inPlaceNTT_DIF_precomp:core:conc/COMP_LOOP-7:acc RESOURCE_NAME COMP_LOOP-10:acc:rg
directive set /inPlaceNTT_DIF_precomp/inPlaceNTT_DIF_precomp:core/inPlaceNTT_DIF_precomp:core:conc/COMP_LOOP-2:acc RESOURCE_NAME COMP_LOOP-10:acc:rg
directive set /inPlaceNTT_DIF_precomp/inPlaceNTT_DIF_precomp:core/inPlaceNTT_DIF_precomp:core:conc/VEC_LOOP:acc RESOURCE_NAME COMP_LOOP:acc#2:rg
directive set /inPlaceNTT_DIF_precomp/inPlaceNTT_DIF_precomp:core/inPlaceNTT_DIF_precomp:core:conc/VEC_LOOP:acc#15 RESOURCE_NAME COMP_LOOP:acc#2:rg
directive set /inPlaceNTT_DIF_precomp/inPlaceNTT_DIF_precomp:core/inPlaceNTT_DIF_precomp:core:conc/VEC_LOOP:acc#13 RESOURCE_NAME COMP_LOOP:acc#2:rg
directive set /inPlaceNTT_DIF_precomp/inPlaceNTT_DIF_precomp:core/inPlaceNTT_DIF_precomp:core:conc/VEC_LOOP:acc#17 RESOURCE_NAME COMP_LOOP:acc#2:rg
directive set /inPlaceNTT_DIF_precomp/inPlaceNTT_DIF_precomp:core/inPlaceNTT_DIF_precomp:core:conc/COMP_LOOP:acc#4 RESOURCE_NAME COMP_LOOP:acc#2:rg
directive set /inPlaceNTT_DIF_precomp/inPlaceNTT_DIF_precomp:core/inPlaceNTT_DIF_precomp:core:conc/COMP_LOOP:acc#2 RESOURCE_NAME COMP_LOOP:acc#2:rg
directive set /inPlaceNTT_DIF_precomp/inPlaceNTT_DIF_precomp:core/inPlaceNTT_DIF_precomp:core:conc/VEC_LOOP:acc#35 RESOURCE_NAME COMP_LOOP:acc#5:rg
directive set /inPlaceNTT_DIF_precomp/inPlaceNTT_DIF_precomp:core/inPlaceNTT_DIF_precomp:core:conc/VEC_LOOP:acc#36 RESOURCE_NAME COMP_LOOP:acc#5:rg
directive set /inPlaceNTT_DIF_precomp/inPlaceNTT_DIF_precomp:core/inPlaceNTT_DIF_precomp:core:conc/COMP_LOOP:acc#5 RESOURCE_NAME COMP_LOOP:acc#5:rg
directive set /inPlaceNTT_DIF_precomp/inPlaceNTT_DIF_precomp:core/inPlaceNTT_DIF_precomp:core:conc/VEC_LOOP:acc#12 RESOURCE_NAME COMP_LOOP:acc:rg
directive set /inPlaceNTT_DIF_precomp/inPlaceNTT_DIF_precomp:core/inPlaceNTT_DIF_precomp:core:conc/VEC_LOOP:acc#14 RESOURCE_NAME COMP_LOOP:acc:rg
directive set /inPlaceNTT_DIF_precomp/inPlaceNTT_DIF_precomp:core/inPlaceNTT_DIF_precomp:core:conc/VEC_LOOP:acc#16 RESOURCE_NAME COMP_LOOP:acc:rg
directive set /inPlaceNTT_DIF_precomp/inPlaceNTT_DIF_precomp:core/inPlaceNTT_DIF_precomp:core:conc/VEC_LOOP:acc#18 RESOURCE_NAME COMP_LOOP:acc:rg
directive set /inPlaceNTT_DIF_precomp/inPlaceNTT_DIF_precomp:core/inPlaceNTT_DIF_precomp:core:conc/COMP_LOOP:acc#3 RESOURCE_NAME COMP_LOOP:acc:rg
directive set /inPlaceNTT_DIF_precomp/inPlaceNTT_DIF_precomp:core/inPlaceNTT_DIF_precomp:core:conc/COMP_LOOP:acc RESOURCE_NAME COMP_LOOP:acc:rg
directive set /inPlaceNTT_DIF_precomp/inPlaceNTT_DIF_precomp:core/inPlaceNTT_DIF_precomp:core:conc/COMP_LOOP-1:VEC_LOOP:acc#8 RESOURCE_NAME COMP_LOOP-1:VEC_LOOP:acc#8:rg
directive set /inPlaceNTT_DIF_precomp/inPlaceNTT_DIF_precomp:core/inPlaceNTT_DIF_precomp:core:conc/COMP_LOOP-3:VEC_LOOP:acc#8 RESOURCE_NAME COMP_LOOP-1:VEC_LOOP:acc#8:rg
directive set /inPlaceNTT_DIF_precomp/inPlaceNTT_DIF_precomp:core/inPlaceNTT_DIF_precomp:core:conc/COMP_LOOP-1:VEC_LOOP:acc#5 RESOURCE_NAME COMP_LOOP-1:VEC_LOOP:acc#5:rg
directive set /inPlaceNTT_DIF_precomp/inPlaceNTT_DIF_precomp:core/inPlaceNTT_DIF_precomp:core:conc/COMP_LOOP-3:VEC_LOOP:acc#5 RESOURCE_NAME COMP_LOOP-1:VEC_LOOP:acc#5:rg
