directive set /inPlaceNTT_DIF/inPlaceNTT_DIF:core/inPlaceNTT_DIF:core:conc/COMP_LOOP-2:acc RESOURCE_NAME COMP_LOOP-2:acc:rg
directive set /inPlaceNTT_DIF/inPlaceNTT_DIF:core/inPlaceNTT_DIF:core:conc/VEC_LOOP:acc#1 RESOURCE_NAME COMP_LOOP-2:acc:rg
directive set /inPlaceNTT_DIF/inPlaceNTT_DIF:core/inPlaceNTT_DIF:core:conc/COMP_LOOP-1:acc#8 RESOURCE_NAME COMP_LOOP-1:acc#6:rg
directive set /inPlaceNTT_DIF/inPlaceNTT_DIF:core/inPlaceNTT_DIF:core:conc/COMP_LOOP-1:acc#6 RESOURCE_NAME COMP_LOOP-1:acc#6:rg
directive set /inPlaceNTT_DIF/inPlaceNTT_DIF:core/inPlaceNTT_DIF:core:conc/COMP_LOOP-2:acc#6 RESOURCE_NAME COMP_LOOP-1:acc#6:rg
directive set /inPlaceNTT_DIF/inPlaceNTT_DIF:core/inPlaceNTT_DIF:core:conc/STAGE_LOOP:acc#1 RESOURCE_NAME COMP_LOOP-1:tmp:acc:rg
directive set /inPlaceNTT_DIF/inPlaceNTT_DIF:core/inPlaceNTT_DIF:core:conc/COMP_LOOP-1:tmp:acc RESOURCE_NAME COMP_LOOP-1:tmp:acc:rg
directive set /inPlaceNTT_DIF/inPlaceNTT_DIF:core/inPlaceNTT_DIF:core:conc/COMP_LOOP:slc(COMP_LOOP-2:COMP_LOOP:acc RESOURCE_NAME COMP_LOOP:slc(COMP_LOOP-2:COMP_LOOP:acc:rg
directive set /inPlaceNTT_DIF/inPlaceNTT_DIF:core/inPlaceNTT_DIF:core:conc/STAGE_LOOP:acc RESOURCE_NAME COMP_LOOP:slc(COMP_LOOP-2:COMP_LOOP:acc:rg
directive set /inPlaceNTT_DIF/inPlaceNTT_DIF:core/inPlaceNTT_DIF:core:conc/STAGE_LOOP:lshift RESOURCE_NAME COMP_LOOP-1:tmp:lshift:rg
directive set /inPlaceNTT_DIF/inPlaceNTT_DIF:core/inPlaceNTT_DIF:core:conc/COMP_LOOP-1:tmp:lshift RESOURCE_NAME COMP_LOOP-1:tmp:lshift:rg
directive set /inPlaceNTT_DIF/inPlaceNTT_DIF:core/inPlaceNTT_DIF:core:conc/COMP_LOOP-2:tmp:lshift RESOURCE_NAME COMP_LOOP-1:tmp:lshift:rg
directive set /inPlaceNTT_DIF/inPlaceNTT_DIF:core/inPlaceNTT_DIF:core:conc/COMP_LOOP-1:mul RESOURCE_NAME COMP_LOOP-1:mul:rg
directive set /inPlaceNTT_DIF/inPlaceNTT_DIF:core/inPlaceNTT_DIF:core:conc/COMP_LOOP-2:mul RESOURCE_NAME COMP_LOOP-1:mul:rg
directive set /inPlaceNTT_DIF/inPlaceNTT_DIF:core/inPlaceNTT_DIF:core:conc/COMP_LOOP-1:tmp:mul RESOURCE_NAME COMP_LOOP-1:mul:rg
directive set /inPlaceNTT_DIF/inPlaceNTT_DIF:core/inPlaceNTT_DIF:core:conc/COMP_LOOP-2:tmp:mul RESOURCE_NAME COMP_LOOP-1:mul:rg
