directive set /ntt_flat/ntt_flat:core/ntt_flat:core:conc/butterFly:f1:acc RESOURCE_NAME butterFly:f1:acc:rg
directive set /ntt_flat/ntt_flat:core/ntt_flat:core:conc/for:acc RESOURCE_NAME butterFly:f1:acc:rg
directive set /ntt_flat/ntt_flat:core/ntt_flat:core:conc/operator>><20,false>:rshift RESOURCE_NAME INNER_LOOP:g:rshift:rg
directive set /ntt_flat/ntt_flat:core/ntt_flat:core:conc/INNER_LOOP:g:rshift RESOURCE_NAME INNER_LOOP:g:rshift:rg
directive set /ntt_flat/ntt_flat:core/ntt_flat:core:conc/operator-<20,false>#1:acc RESOURCE_NAME STAGE_LOOP:acc:rg
directive set /ntt_flat/ntt_flat:core/ntt_flat:core:conc/STAGE_LOOP:acc RESOURCE_NAME STAGE_LOOP:acc:rg
directive set /ntt_flat/ntt_flat:core/ntt_flat:core:conc/INNER_LOOP:k:acc RESOURCE_NAME INNER_LOOP:idx2:acc:rg
directive set /ntt_flat/ntt_flat:core/ntt_flat:core:conc/INNER_LOOP:idx2:acc RESOURCE_NAME INNER_LOOP:idx2:acc:rg
directive set /ntt_flat/ntt_flat:core/ntt_flat:core:conc/mult:if:acc RESOURCE_NAME mult:if:acc:rg
directive set /ntt_flat/ntt_flat:core/ntt_flat:core:conc/mult:res:acc RESOURCE_NAME mult:if:acc:rg
directive set /ntt_flat/ntt_flat:core/ntt_flat:core:conc/butterFly:acc#3 RESOURCE_NAME butterFly:acc#3:rg
directive set /ntt_flat/ntt_flat:core/ntt_flat:core:conc/modulo_add:qif:acc RESOURCE_NAME butterFly:acc#3:rg
