directive set /stockham_DIT/stockham_DIT:core/core/drf(y).smx.lpi#3 REGISTER_NAME drf(y).smx.lpi#3
directive set /stockham_DIT/stockham_DIT:core/core/drf(y).smx.lpi#3.dfm REGISTER_NAME drf(y).smx.lpi#3
directive set /stockham_DIT/stockham_DIT:core/core/INNER_LOOP:a:acc.psp.sva REGISTER_NAME INNER_LOOP:a:acc.psp.sva
directive set /stockham_DIT/stockham_DIT:core/core/INNER_LOOP:t(9:0).sva(8:0) REGISTER_NAME INNER_LOOP:a:acc.psp.sva
directive set /stockham_DIT/stockham_DIT:core/core/INNER_LOOP:a:slc(INNER_LOOP:q:and.psp)(0)#1.itm REGISTER_NAME INNER_LOOP:a:slc(INNER_LOOP:q:and.psp)(0)#1.itm
directive set /stockham_DIT/stockham_DIT:core/core/INNER_LOOP:a:slc(INNER_LOOP:q:and.psp)(0).itm REGISTER_NAME INNER_LOOP:a:slc(INNER_LOOP:q:and.psp)(0)#1.itm
directive set /stockham_DIT/stockham_DIT:core/core/INNER_LOOP:a.lpi#3.dfm REGISTER_NAME INNER_LOOP:a.lpi#3.dfm
directive set /stockham_DIT/stockham_DIT:core/core/INNER_LOOP:acc#2.psp REGISTER_NAME INNER_LOOP:a.lpi#3.dfm
directive set /stockham_DIT/stockham_DIT:core/core/INNER_LOOP:w:asn.itm REGISTER_NAME INNER_LOOP:a.lpi#3.dfm
