directive set /inPlaceNTT_DIF/inPlaceNTT_DIF:core/core/COMP_LOOP-1:acc#6.mut REGISTER_NAME COMP_LOOP-1:acc#6.mut
directive set /inPlaceNTT_DIF/inPlaceNTT_DIF:core/core/COMP_LOOP-1:mul.itm REGISTER_NAME COMP_LOOP-1:acc#6.mut
directive set /inPlaceNTT_DIF/inPlaceNTT_DIF:core/core/COMP_LOOP-2:acc#6.mut REGISTER_NAME COMP_LOOP-1:acc#6.mut
directive set /inPlaceNTT_DIF/inPlaceNTT_DIF:core/core/COMP_LOOP-2:mul.mut REGISTER_NAME COMP_LOOP-1:acc#6.mut
directive set /inPlaceNTT_DIF/inPlaceNTT_DIF:core/core/COMP_LOOP-1:acc#8.itm REGISTER_NAME COMP_LOOP-1:acc#8.itm
directive set /inPlaceNTT_DIF/inPlaceNTT_DIF:core/core/COMP_LOOP-1:modulo_dev#2:result:rem.cmx.sva REGISTER_NAME COMP_LOOP-1:acc#8.itm
directive set /inPlaceNTT_DIF/inPlaceNTT_DIF:core/core/COMP_LOOP-2:acc#8.itm REGISTER_NAME COMP_LOOP-1:acc#8.itm
directive set /inPlaceNTT_DIF/inPlaceNTT_DIF:core/core/tmp#1.lpi#4.dfm REGISTER_NAME COMP_LOOP-1:acc#8.itm
directive set /inPlaceNTT_DIF/inPlaceNTT_DIF:core/core/tmp#3.lpi#4.dfm REGISTER_NAME COMP_LOOP-1:acc#8.itm
directive set /inPlaceNTT_DIF/inPlaceNTT_DIF:core/core/tmp#2.lpi#4.dfm REGISTER_NAME tmp#2.lpi#4.dfm
directive set /inPlaceNTT_DIF/inPlaceNTT_DIF:core/core/tmp.lpi#4.dfm REGISTER_NAME tmp#2.lpi#4.dfm
