
# Loop constraints
directive set /inPlaceNTT_DIF/core/core:rlp CSTEPS_FROM {{. == 0}}
directive set /inPlaceNTT_DIF/core/core:rlp/main CSTEPS_FROM {{. == 2} {.. == 0}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP CSTEPS_FROM {{. == 5} {.. == 1}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/modExp_dev:while CSTEPS_FROM {{. == 12} {.. == 4}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/STAGE_VEC_LOOP CSTEPS_FROM {{. == 2} {.. == 4}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/STAGE_VEC_LOOP/COMP_LOOP CSTEPS_FROM {{. == 361} {.. == 1}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/STAGE_VEC_LOOP/COMP_LOOP/COMP_LOOP-1:modExp_dev#1:while CSTEPS_FROM {{. == 12} {.. == 17}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/STAGE_VEC_LOOP/COMP_LOOP/COMP_LOOP-2:modExp_dev#1:while CSTEPS_FROM {{. == 12} {.. == 62}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/STAGE_VEC_LOOP/COMP_LOOP/COMP_LOOP-3:modExp_dev#1:while CSTEPS_FROM {{. == 12} {.. == 107}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/STAGE_VEC_LOOP/COMP_LOOP/COMP_LOOP-4:modExp_dev#1:while CSTEPS_FROM {{. == 12} {.. == 152}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/STAGE_VEC_LOOP/COMP_LOOP/COMP_LOOP-5:modExp_dev#1:while CSTEPS_FROM {{. == 12} {.. == 197}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/STAGE_VEC_LOOP/COMP_LOOP/COMP_LOOP-6:modExp_dev#1:while CSTEPS_FROM {{. == 12} {.. == 242}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/STAGE_VEC_LOOP/COMP_LOOP/COMP_LOOP-7:modExp_dev#1:while CSTEPS_FROM {{. == 12} {.. == 287}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/STAGE_VEC_LOOP/COMP_LOOP/COMP_LOOP-8:modExp_dev#1:while CSTEPS_FROM {{. == 12} {.. == 332}}

# IO operation constraints
directive set /inPlaceNTT_DIF/core/core:rlp/main/p:io_read(p:rsc.@) CSTEPS_FROM {{.. == 1}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/r:io_read(r:rsc.@) CSTEPS_FROM {{.. == 1}}

# Sync operation constraints

# Real operation constraints
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/STAGE_MAIN_LOOP:acc#1 CSTEPS_FROM {{.. == 1}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/STAGE_MAIN_LOOP:lshift CSTEPS_FROM {{.. == 1}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/operator-<64,false>:acc CSTEPS_FROM {{.. == 1}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/STAGE_MAIN_LOOP:div CSTEPS_FROM {{.. == 1}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/operator><64,false>:acc#1 CSTEPS_FROM {{.. == 4}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/modExp_dev:while/modExp_dev:while:acc CSTEPS_FROM {{.. == 1}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/modExp_dev:while/modExp_dev:while:mul CSTEPS_FROM {{.. == 1}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/modExp_dev:while/modExp_dev:while:rem CSTEPS_FROM {{.. == 1}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/modExp_dev:while/operator><64,false>:acc CSTEPS_FROM {{.. == 1}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/STAGE_VEC_LOOP/COMP_LOOP-1:operator<<64,false>:acc#1 CSTEPS_FROM {{.. == 1}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/STAGE_VEC_LOOP/COMP_LOOP/COMP_LOOP:acc CSTEPS_FROM {{.. == 1}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/STAGE_VEC_LOOP/COMP_LOOP/COMP_LOOP:read_mem(vec:rsc(0)(0).@) CSTEPS_FROM {{.. == 2}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/STAGE_VEC_LOOP/COMP_LOOP/COMP_LOOP:read_mem(vec:rsc(0)(1).@) CSTEPS_FROM {{.. == 2}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/STAGE_VEC_LOOP/COMP_LOOP/COMP_LOOP:read_mem(vec:rsc(0)(2).@) CSTEPS_FROM {{.. == 2}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/STAGE_VEC_LOOP/COMP_LOOP/COMP_LOOP:read_mem(vec:rsc(0)(3).@) CSTEPS_FROM {{.. == 2}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/STAGE_VEC_LOOP/COMP_LOOP/COMP_LOOP:read_mem(vec:rsc(0)(4).@) CSTEPS_FROM {{.. == 2}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/STAGE_VEC_LOOP/COMP_LOOP/COMP_LOOP:read_mem(vec:rsc(0)(5).@) CSTEPS_FROM {{.. == 2}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/STAGE_VEC_LOOP/COMP_LOOP/COMP_LOOP:read_mem(vec:rsc(0)(6).@) CSTEPS_FROM {{.. == 2}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/STAGE_VEC_LOOP/COMP_LOOP/COMP_LOOP:read_mem(vec:rsc(0)(7).@) CSTEPS_FROM {{.. == 2}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/STAGE_VEC_LOOP/COMP_LOOP/COMP_LOOP:mux1h#85 CSTEPS_FROM {{.. == 3}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/STAGE_VEC_LOOP/COMP_LOOP/COMP_LOOP-1:operator+<64,false>:acc CSTEPS_FROM {{.. == 1}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/STAGE_VEC_LOOP/COMP_LOOP/COMP_LOOP:read_mem(vec:rsc(0)(0).@)#1 CSTEPS_FROM {{.. == 1}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/STAGE_VEC_LOOP/COMP_LOOP/COMP_LOOP:read_mem(vec:rsc(0)(1).@)#1 CSTEPS_FROM {{.. == 1}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/STAGE_VEC_LOOP/COMP_LOOP/COMP_LOOP:read_mem(vec:rsc(0)(2).@)#1 CSTEPS_FROM {{.. == 1}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/STAGE_VEC_LOOP/COMP_LOOP/COMP_LOOP:read_mem(vec:rsc(0)(3).@)#1 CSTEPS_FROM {{.. == 1}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/STAGE_VEC_LOOP/COMP_LOOP/COMP_LOOP:read_mem(vec:rsc(0)(4).@)#1 CSTEPS_FROM {{.. == 1}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/STAGE_VEC_LOOP/COMP_LOOP/COMP_LOOP:read_mem(vec:rsc(0)(5).@)#1 CSTEPS_FROM {{.. == 1}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/STAGE_VEC_LOOP/COMP_LOOP/COMP_LOOP:read_mem(vec:rsc(0)(6).@)#1 CSTEPS_FROM {{.. == 1}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/STAGE_VEC_LOOP/COMP_LOOP/COMP_LOOP:read_mem(vec:rsc(0)(7).@)#1 CSTEPS_FROM {{.. == 1}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/STAGE_VEC_LOOP/COMP_LOOP/COMP_LOOP:mux1h#1 CSTEPS_FROM {{.. == 2}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/STAGE_VEC_LOOP/COMP_LOOP/COMP_LOOP-1:acc#3 CSTEPS_FROM {{.. == 3}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/STAGE_VEC_LOOP/COMP_LOOP/COMP_LOOP-1:modulo_dev() CSTEPS_FROM {{.. == 3}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/STAGE_VEC_LOOP/COMP_LOOP/COMP_LOOP:write_mem(vec:rsc(0)(0).@) CSTEPS_FROM {{.. == 16}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/STAGE_VEC_LOOP/COMP_LOOP/COMP_LOOP:write_mem(vec:rsc(0)(1).@) CSTEPS_FROM {{.. == 16}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/STAGE_VEC_LOOP/COMP_LOOP/COMP_LOOP:write_mem(vec:rsc(0)(2).@) CSTEPS_FROM {{.. == 16}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/STAGE_VEC_LOOP/COMP_LOOP/COMP_LOOP:write_mem(vec:rsc(0)(3).@) CSTEPS_FROM {{.. == 16}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/STAGE_VEC_LOOP/COMP_LOOP/COMP_LOOP:write_mem(vec:rsc(0)(4).@) CSTEPS_FROM {{.. == 16}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/STAGE_VEC_LOOP/COMP_LOOP/COMP_LOOP:write_mem(vec:rsc(0)(5).@) CSTEPS_FROM {{.. == 16}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/STAGE_VEC_LOOP/COMP_LOOP/COMP_LOOP:write_mem(vec:rsc(0)(6).@) CSTEPS_FROM {{.. == 16}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/STAGE_VEC_LOOP/COMP_LOOP/COMP_LOOP:write_mem(vec:rsc(0)(7).@) CSTEPS_FROM {{.. == 16}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/STAGE_VEC_LOOP/COMP_LOOP/operator><64,false>#1:acc CSTEPS_FROM {{.. == 1}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/STAGE_VEC_LOOP/COMP_LOOP/COMP_LOOP-1:modExp_dev#1:while/COMP_LOOP-1:modExp_dev#1:while:acc CSTEPS_FROM {{.. == 1}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/STAGE_VEC_LOOP/COMP_LOOP/COMP_LOOP-1:modExp_dev#1:while/COMP_LOOP-1:modExp_dev#1:while:mul CSTEPS_FROM {{.. == 1}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/STAGE_VEC_LOOP/COMP_LOOP/COMP_LOOP-1:modExp_dev#1:while/COMP_LOOP-1:modExp_dev#1:while:rem CSTEPS_FROM {{.. == 1}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/STAGE_VEC_LOOP/COMP_LOOP/COMP_LOOP-1:modExp_dev#1:while/COMP_LOOP-1:operator><64,false>#1:acc CSTEPS_FROM {{.. == 1}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/STAGE_VEC_LOOP/COMP_LOOP/COMP_LOOP-1:acc#5 CSTEPS_FROM {{.. == 18}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/STAGE_VEC_LOOP/COMP_LOOP/COMP_LOOP-1:modulo_dev()#1 CSTEPS_FROM {{.. == 18}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/STAGE_VEC_LOOP/COMP_LOOP/COMP_LOOP-1:mul CSTEPS_FROM {{.. == 31}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/STAGE_VEC_LOOP/COMP_LOOP/COMP_LOOP-1:modulo_dev()#2 CSTEPS_FROM {{.. == 32}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/STAGE_VEC_LOOP/COMP_LOOP/COMP_LOOP:write_mem(vec:rsc(0)(0).@)#1 CSTEPS_FROM {{.. == 45}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/STAGE_VEC_LOOP/COMP_LOOP/COMP_LOOP:write_mem(vec:rsc(0)(1).@)#1 CSTEPS_FROM {{.. == 45}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/STAGE_VEC_LOOP/COMP_LOOP/COMP_LOOP:write_mem(vec:rsc(0)(2).@)#1 CSTEPS_FROM {{.. == 45}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/STAGE_VEC_LOOP/COMP_LOOP/COMP_LOOP:write_mem(vec:rsc(0)(3).@)#1 CSTEPS_FROM {{.. == 45}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/STAGE_VEC_LOOP/COMP_LOOP/COMP_LOOP:write_mem(vec:rsc(0)(4).@)#1 CSTEPS_FROM {{.. == 45}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/STAGE_VEC_LOOP/COMP_LOOP/COMP_LOOP:write_mem(vec:rsc(0)(5).@)#1 CSTEPS_FROM {{.. == 45}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/STAGE_VEC_LOOP/COMP_LOOP/COMP_LOOP:write_mem(vec:rsc(0)(6).@)#1 CSTEPS_FROM {{.. == 45}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/STAGE_VEC_LOOP/COMP_LOOP/COMP_LOOP:write_mem(vec:rsc(0)(7).@)#1 CSTEPS_FROM {{.. == 45}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/STAGE_VEC_LOOP/COMP_LOOP/COMP_LOOP-2:operator<<64,false>:acc CSTEPS_FROM {{.. == 18}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/STAGE_VEC_LOOP/COMP_LOOP/COMP_LOOP-2:acc CSTEPS_FROM {{.. == 1}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/STAGE_VEC_LOOP/COMP_LOOP/COMP_LOOP:read_mem(vec:rsc(0)(0).@)#2 CSTEPS_FROM {{.. == 46}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/STAGE_VEC_LOOP/COMP_LOOP/COMP_LOOP:read_mem(vec:rsc(0)(1).@)#2 CSTEPS_FROM {{.. == 46}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/STAGE_VEC_LOOP/COMP_LOOP/COMP_LOOP:read_mem(vec:rsc(0)(2).@)#2 CSTEPS_FROM {{.. == 46}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/STAGE_VEC_LOOP/COMP_LOOP/COMP_LOOP:read_mem(vec:rsc(0)(3).@)#2 CSTEPS_FROM {{.. == 46}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/STAGE_VEC_LOOP/COMP_LOOP/COMP_LOOP:read_mem(vec:rsc(0)(4).@)#2 CSTEPS_FROM {{.. == 46}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/STAGE_VEC_LOOP/COMP_LOOP/COMP_LOOP:read_mem(vec:rsc(0)(5).@)#2 CSTEPS_FROM {{.. == 46}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/STAGE_VEC_LOOP/COMP_LOOP/COMP_LOOP:read_mem(vec:rsc(0)(6).@)#2 CSTEPS_FROM {{.. == 46}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/STAGE_VEC_LOOP/COMP_LOOP/COMP_LOOP:read_mem(vec:rsc(0)(7).@)#2 CSTEPS_FROM {{.. == 46}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/STAGE_VEC_LOOP/COMP_LOOP/COMP_LOOP:mux1h#2 CSTEPS_FROM {{.. == 47}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/STAGE_VEC_LOOP/COMP_LOOP/COMP_LOOP-2:operator+<64,false>:acc CSTEPS_FROM {{.. == 1}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/STAGE_VEC_LOOP/COMP_LOOP/COMP_LOOP:read_mem(vec:rsc(0)(0).@)#3 CSTEPS_FROM {{.. == 47}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/STAGE_VEC_LOOP/COMP_LOOP/COMP_LOOP:read_mem(vec:rsc(0)(1).@)#3 CSTEPS_FROM {{.. == 47}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/STAGE_VEC_LOOP/COMP_LOOP/COMP_LOOP:read_mem(vec:rsc(0)(2).@)#3 CSTEPS_FROM {{.. == 47}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/STAGE_VEC_LOOP/COMP_LOOP/COMP_LOOP:read_mem(vec:rsc(0)(3).@)#3 CSTEPS_FROM {{.. == 47}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/STAGE_VEC_LOOP/COMP_LOOP/COMP_LOOP:read_mem(vec:rsc(0)(4).@)#3 CSTEPS_FROM {{.. == 47}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/STAGE_VEC_LOOP/COMP_LOOP/COMP_LOOP:read_mem(vec:rsc(0)(5).@)#3 CSTEPS_FROM {{.. == 47}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/STAGE_VEC_LOOP/COMP_LOOP/COMP_LOOP:read_mem(vec:rsc(0)(6).@)#3 CSTEPS_FROM {{.. == 47}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/STAGE_VEC_LOOP/COMP_LOOP/COMP_LOOP:read_mem(vec:rsc(0)(7).@)#3 CSTEPS_FROM {{.. == 47}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/STAGE_VEC_LOOP/COMP_LOOP/COMP_LOOP:mux1h#3 CSTEPS_FROM {{.. == 48}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/STAGE_VEC_LOOP/COMP_LOOP/COMP_LOOP-2:acc#3 CSTEPS_FROM {{.. == 48}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/STAGE_VEC_LOOP/COMP_LOOP/COMP_LOOP-2:modulo_dev() CSTEPS_FROM {{.. == 48}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/STAGE_VEC_LOOP/COMP_LOOP/COMP_LOOP:write_mem(vec:rsc(0)(0).@)#2 CSTEPS_FROM {{.. == 61}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/STAGE_VEC_LOOP/COMP_LOOP/COMP_LOOP:write_mem(vec:rsc(0)(1).@)#2 CSTEPS_FROM {{.. == 61}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/STAGE_VEC_LOOP/COMP_LOOP/COMP_LOOP:write_mem(vec:rsc(0)(2).@)#2 CSTEPS_FROM {{.. == 61}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/STAGE_VEC_LOOP/COMP_LOOP/COMP_LOOP:write_mem(vec:rsc(0)(3).@)#2 CSTEPS_FROM {{.. == 61}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/STAGE_VEC_LOOP/COMP_LOOP/COMP_LOOP:write_mem(vec:rsc(0)(4).@)#2 CSTEPS_FROM {{.. == 61}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/STAGE_VEC_LOOP/COMP_LOOP/COMP_LOOP:write_mem(vec:rsc(0)(5).@)#2 CSTEPS_FROM {{.. == 61}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/STAGE_VEC_LOOP/COMP_LOOP/COMP_LOOP:write_mem(vec:rsc(0)(6).@)#2 CSTEPS_FROM {{.. == 61}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/STAGE_VEC_LOOP/COMP_LOOP/COMP_LOOP:write_mem(vec:rsc(0)(7).@)#2 CSTEPS_FROM {{.. == 61}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/STAGE_VEC_LOOP/COMP_LOOP/COMP_LOOP-2:modExp_dev#1:while/COMP_LOOP-2:modExp_dev#1:while:acc CSTEPS_FROM {{.. == 1}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/STAGE_VEC_LOOP/COMP_LOOP/COMP_LOOP-2:modExp_dev#1:while/COMP_LOOP-2:modExp_dev#1:while:mul CSTEPS_FROM {{.. == 1}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/STAGE_VEC_LOOP/COMP_LOOP/COMP_LOOP-2:modExp_dev#1:while/COMP_LOOP-2:modExp_dev#1:while:rem CSTEPS_FROM {{.. == 1}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/STAGE_VEC_LOOP/COMP_LOOP/COMP_LOOP-2:modExp_dev#1:while/COMP_LOOP-2:operator><64,false>#1:acc CSTEPS_FROM {{.. == 1}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/STAGE_VEC_LOOP/COMP_LOOP/COMP_LOOP-2:acc#5 CSTEPS_FROM {{.. == 63}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/STAGE_VEC_LOOP/COMP_LOOP/COMP_LOOP-2:modulo_dev()#1 CSTEPS_FROM {{.. == 63}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/STAGE_VEC_LOOP/COMP_LOOP/COMP_LOOP-2:mul CSTEPS_FROM {{.. == 76}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/STAGE_VEC_LOOP/COMP_LOOP/COMP_LOOP-2:modulo_dev()#2 CSTEPS_FROM {{.. == 77}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/STAGE_VEC_LOOP/COMP_LOOP/COMP_LOOP:write_mem(vec:rsc(0)(0).@)#3 CSTEPS_FROM {{.. == 90}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/STAGE_VEC_LOOP/COMP_LOOP/COMP_LOOP:write_mem(vec:rsc(0)(1).@)#3 CSTEPS_FROM {{.. == 90}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/STAGE_VEC_LOOP/COMP_LOOP/COMP_LOOP:write_mem(vec:rsc(0)(2).@)#3 CSTEPS_FROM {{.. == 90}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/STAGE_VEC_LOOP/COMP_LOOP/COMP_LOOP:write_mem(vec:rsc(0)(3).@)#3 CSTEPS_FROM {{.. == 90}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/STAGE_VEC_LOOP/COMP_LOOP/COMP_LOOP:write_mem(vec:rsc(0)(4).@)#3 CSTEPS_FROM {{.. == 90}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/STAGE_VEC_LOOP/COMP_LOOP/COMP_LOOP:write_mem(vec:rsc(0)(5).@)#3 CSTEPS_FROM {{.. == 90}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/STAGE_VEC_LOOP/COMP_LOOP/COMP_LOOP:write_mem(vec:rsc(0)(6).@)#3 CSTEPS_FROM {{.. == 90}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/STAGE_VEC_LOOP/COMP_LOOP/COMP_LOOP:write_mem(vec:rsc(0)(7).@)#3 CSTEPS_FROM {{.. == 90}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/STAGE_VEC_LOOP/COMP_LOOP/COMP_LOOP-3:operator<<64,false>:acc CSTEPS_FROM {{.. == 63}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/STAGE_VEC_LOOP/COMP_LOOP/COMP_LOOP:acc#7 CSTEPS_FROM {{.. == 1}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/STAGE_VEC_LOOP/COMP_LOOP/COMP_LOOP:read_mem(vec:rsc(0)(0).@)#4 CSTEPS_FROM {{.. == 91}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/STAGE_VEC_LOOP/COMP_LOOP/COMP_LOOP:read_mem(vec:rsc(0)(1).@)#4 CSTEPS_FROM {{.. == 91}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/STAGE_VEC_LOOP/COMP_LOOP/COMP_LOOP:read_mem(vec:rsc(0)(2).@)#4 CSTEPS_FROM {{.. == 91}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/STAGE_VEC_LOOP/COMP_LOOP/COMP_LOOP:read_mem(vec:rsc(0)(3).@)#4 CSTEPS_FROM {{.. == 91}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/STAGE_VEC_LOOP/COMP_LOOP/COMP_LOOP:read_mem(vec:rsc(0)(4).@)#4 CSTEPS_FROM {{.. == 91}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/STAGE_VEC_LOOP/COMP_LOOP/COMP_LOOP:read_mem(vec:rsc(0)(5).@)#4 CSTEPS_FROM {{.. == 91}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/STAGE_VEC_LOOP/COMP_LOOP/COMP_LOOP:read_mem(vec:rsc(0)(6).@)#4 CSTEPS_FROM {{.. == 91}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/STAGE_VEC_LOOP/COMP_LOOP/COMP_LOOP:read_mem(vec:rsc(0)(7).@)#4 CSTEPS_FROM {{.. == 91}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/STAGE_VEC_LOOP/COMP_LOOP/COMP_LOOP:mux1h#4 CSTEPS_FROM {{.. == 92}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/STAGE_VEC_LOOP/COMP_LOOP/COMP_LOOP-3:operator+<64,false>:acc CSTEPS_FROM {{.. == 1}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/STAGE_VEC_LOOP/COMP_LOOP/COMP_LOOP:read_mem(vec:rsc(0)(0).@)#5 CSTEPS_FROM {{.. == 92}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/STAGE_VEC_LOOP/COMP_LOOP/COMP_LOOP:read_mem(vec:rsc(0)(1).@)#5 CSTEPS_FROM {{.. == 92}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/STAGE_VEC_LOOP/COMP_LOOP/COMP_LOOP:read_mem(vec:rsc(0)(2).@)#5 CSTEPS_FROM {{.. == 92}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/STAGE_VEC_LOOP/COMP_LOOP/COMP_LOOP:read_mem(vec:rsc(0)(3).@)#5 CSTEPS_FROM {{.. == 92}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/STAGE_VEC_LOOP/COMP_LOOP/COMP_LOOP:read_mem(vec:rsc(0)(4).@)#5 CSTEPS_FROM {{.. == 92}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/STAGE_VEC_LOOP/COMP_LOOP/COMP_LOOP:read_mem(vec:rsc(0)(5).@)#5 CSTEPS_FROM {{.. == 92}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/STAGE_VEC_LOOP/COMP_LOOP/COMP_LOOP:read_mem(vec:rsc(0)(6).@)#5 CSTEPS_FROM {{.. == 92}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/STAGE_VEC_LOOP/COMP_LOOP/COMP_LOOP:read_mem(vec:rsc(0)(7).@)#5 CSTEPS_FROM {{.. == 92}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/STAGE_VEC_LOOP/COMP_LOOP/COMP_LOOP:mux1h#5 CSTEPS_FROM {{.. == 93}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/STAGE_VEC_LOOP/COMP_LOOP/COMP_LOOP-3:acc#3 CSTEPS_FROM {{.. == 93}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/STAGE_VEC_LOOP/COMP_LOOP/COMP_LOOP-3:modulo_dev() CSTEPS_FROM {{.. == 93}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/STAGE_VEC_LOOP/COMP_LOOP/COMP_LOOP:write_mem(vec:rsc(0)(0).@)#4 CSTEPS_FROM {{.. == 106}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/STAGE_VEC_LOOP/COMP_LOOP/COMP_LOOP:write_mem(vec:rsc(0)(1).@)#4 CSTEPS_FROM {{.. == 106}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/STAGE_VEC_LOOP/COMP_LOOP/COMP_LOOP:write_mem(vec:rsc(0)(2).@)#4 CSTEPS_FROM {{.. == 106}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/STAGE_VEC_LOOP/COMP_LOOP/COMP_LOOP:write_mem(vec:rsc(0)(3).@)#4 CSTEPS_FROM {{.. == 106}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/STAGE_VEC_LOOP/COMP_LOOP/COMP_LOOP:write_mem(vec:rsc(0)(4).@)#4 CSTEPS_FROM {{.. == 106}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/STAGE_VEC_LOOP/COMP_LOOP/COMP_LOOP:write_mem(vec:rsc(0)(5).@)#4 CSTEPS_FROM {{.. == 106}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/STAGE_VEC_LOOP/COMP_LOOP/COMP_LOOP:write_mem(vec:rsc(0)(6).@)#4 CSTEPS_FROM {{.. == 106}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/STAGE_VEC_LOOP/COMP_LOOP/COMP_LOOP:write_mem(vec:rsc(0)(7).@)#4 CSTEPS_FROM {{.. == 106}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/STAGE_VEC_LOOP/COMP_LOOP/COMP_LOOP-3:modExp_dev#1:while/COMP_LOOP-3:modExp_dev#1:while:acc CSTEPS_FROM {{.. == 1}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/STAGE_VEC_LOOP/COMP_LOOP/COMP_LOOP-3:modExp_dev#1:while/COMP_LOOP-3:modExp_dev#1:while:mul CSTEPS_FROM {{.. == 1}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/STAGE_VEC_LOOP/COMP_LOOP/COMP_LOOP-3:modExp_dev#1:while/COMP_LOOP-3:modExp_dev#1:while:rem CSTEPS_FROM {{.. == 1}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/STAGE_VEC_LOOP/COMP_LOOP/COMP_LOOP-3:modExp_dev#1:while/COMP_LOOP-3:operator><64,false>#1:acc CSTEPS_FROM {{.. == 1}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/STAGE_VEC_LOOP/COMP_LOOP/COMP_LOOP-3:acc#5 CSTEPS_FROM {{.. == 108}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/STAGE_VEC_LOOP/COMP_LOOP/COMP_LOOP-3:modulo_dev()#1 CSTEPS_FROM {{.. == 108}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/STAGE_VEC_LOOP/COMP_LOOP/COMP_LOOP-3:mul CSTEPS_FROM {{.. == 121}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/STAGE_VEC_LOOP/COMP_LOOP/COMP_LOOP-3:modulo_dev()#2 CSTEPS_FROM {{.. == 122}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/STAGE_VEC_LOOP/COMP_LOOP/COMP_LOOP:write_mem(vec:rsc(0)(0).@)#5 CSTEPS_FROM {{.. == 135}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/STAGE_VEC_LOOP/COMP_LOOP/COMP_LOOP:write_mem(vec:rsc(0)(1).@)#5 CSTEPS_FROM {{.. == 135}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/STAGE_VEC_LOOP/COMP_LOOP/COMP_LOOP:write_mem(vec:rsc(0)(2).@)#5 CSTEPS_FROM {{.. == 135}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/STAGE_VEC_LOOP/COMP_LOOP/COMP_LOOP:write_mem(vec:rsc(0)(3).@)#5 CSTEPS_FROM {{.. == 135}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/STAGE_VEC_LOOP/COMP_LOOP/COMP_LOOP:write_mem(vec:rsc(0)(4).@)#5 CSTEPS_FROM {{.. == 135}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/STAGE_VEC_LOOP/COMP_LOOP/COMP_LOOP:write_mem(vec:rsc(0)(5).@)#5 CSTEPS_FROM {{.. == 135}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/STAGE_VEC_LOOP/COMP_LOOP/COMP_LOOP:write_mem(vec:rsc(0)(6).@)#5 CSTEPS_FROM {{.. == 135}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/STAGE_VEC_LOOP/COMP_LOOP/COMP_LOOP:write_mem(vec:rsc(0)(7).@)#5 CSTEPS_FROM {{.. == 135}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/STAGE_VEC_LOOP/COMP_LOOP/operator<<64,false>:acc CSTEPS_FROM {{.. == 108}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/STAGE_VEC_LOOP/COMP_LOOP/COMP_LOOP-4:acc CSTEPS_FROM {{.. == 1}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/STAGE_VEC_LOOP/COMP_LOOP/COMP_LOOP:read_mem(vec:rsc(0)(0).@)#6 CSTEPS_FROM {{.. == 136}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/STAGE_VEC_LOOP/COMP_LOOP/COMP_LOOP:read_mem(vec:rsc(0)(1).@)#6 CSTEPS_FROM {{.. == 136}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/STAGE_VEC_LOOP/COMP_LOOP/COMP_LOOP:read_mem(vec:rsc(0)(2).@)#6 CSTEPS_FROM {{.. == 136}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/STAGE_VEC_LOOP/COMP_LOOP/COMP_LOOP:read_mem(vec:rsc(0)(3).@)#6 CSTEPS_FROM {{.. == 136}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/STAGE_VEC_LOOP/COMP_LOOP/COMP_LOOP:read_mem(vec:rsc(0)(4).@)#6 CSTEPS_FROM {{.. == 136}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/STAGE_VEC_LOOP/COMP_LOOP/COMP_LOOP:read_mem(vec:rsc(0)(5).@)#6 CSTEPS_FROM {{.. == 136}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/STAGE_VEC_LOOP/COMP_LOOP/COMP_LOOP:read_mem(vec:rsc(0)(6).@)#6 CSTEPS_FROM {{.. == 136}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/STAGE_VEC_LOOP/COMP_LOOP/COMP_LOOP:read_mem(vec:rsc(0)(7).@)#6 CSTEPS_FROM {{.. == 136}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/STAGE_VEC_LOOP/COMP_LOOP/COMP_LOOP:mux1h#6 CSTEPS_FROM {{.. == 137}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/STAGE_VEC_LOOP/COMP_LOOP/COMP_LOOP-4:operator+<64,false>:acc CSTEPS_FROM {{.. == 1}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/STAGE_VEC_LOOP/COMP_LOOP/COMP_LOOP:read_mem(vec:rsc(0)(0).@)#7 CSTEPS_FROM {{.. == 137}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/STAGE_VEC_LOOP/COMP_LOOP/COMP_LOOP:read_mem(vec:rsc(0)(1).@)#7 CSTEPS_FROM {{.. == 137}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/STAGE_VEC_LOOP/COMP_LOOP/COMP_LOOP:read_mem(vec:rsc(0)(2).@)#7 CSTEPS_FROM {{.. == 137}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/STAGE_VEC_LOOP/COMP_LOOP/COMP_LOOP:read_mem(vec:rsc(0)(3).@)#7 CSTEPS_FROM {{.. == 137}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/STAGE_VEC_LOOP/COMP_LOOP/COMP_LOOP:read_mem(vec:rsc(0)(4).@)#7 CSTEPS_FROM {{.. == 137}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/STAGE_VEC_LOOP/COMP_LOOP/COMP_LOOP:read_mem(vec:rsc(0)(5).@)#7 CSTEPS_FROM {{.. == 137}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/STAGE_VEC_LOOP/COMP_LOOP/COMP_LOOP:read_mem(vec:rsc(0)(6).@)#7 CSTEPS_FROM {{.. == 137}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/STAGE_VEC_LOOP/COMP_LOOP/COMP_LOOP:read_mem(vec:rsc(0)(7).@)#7 CSTEPS_FROM {{.. == 137}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/STAGE_VEC_LOOP/COMP_LOOP/COMP_LOOP:mux1h#7 CSTEPS_FROM {{.. == 138}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/STAGE_VEC_LOOP/COMP_LOOP/COMP_LOOP-4:acc#3 CSTEPS_FROM {{.. == 138}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/STAGE_VEC_LOOP/COMP_LOOP/COMP_LOOP-4:modulo_dev() CSTEPS_FROM {{.. == 138}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/STAGE_VEC_LOOP/COMP_LOOP/COMP_LOOP:write_mem(vec:rsc(0)(0).@)#6 CSTEPS_FROM {{.. == 151}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/STAGE_VEC_LOOP/COMP_LOOP/COMP_LOOP:write_mem(vec:rsc(0)(1).@)#6 CSTEPS_FROM {{.. == 151}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/STAGE_VEC_LOOP/COMP_LOOP/COMP_LOOP:write_mem(vec:rsc(0)(2).@)#6 CSTEPS_FROM {{.. == 151}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/STAGE_VEC_LOOP/COMP_LOOP/COMP_LOOP:write_mem(vec:rsc(0)(3).@)#6 CSTEPS_FROM {{.. == 151}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/STAGE_VEC_LOOP/COMP_LOOP/COMP_LOOP:write_mem(vec:rsc(0)(4).@)#6 CSTEPS_FROM {{.. == 151}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/STAGE_VEC_LOOP/COMP_LOOP/COMP_LOOP:write_mem(vec:rsc(0)(5).@)#6 CSTEPS_FROM {{.. == 151}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/STAGE_VEC_LOOP/COMP_LOOP/COMP_LOOP:write_mem(vec:rsc(0)(6).@)#6 CSTEPS_FROM {{.. == 151}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/STAGE_VEC_LOOP/COMP_LOOP/COMP_LOOP:write_mem(vec:rsc(0)(7).@)#6 CSTEPS_FROM {{.. == 151}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/STAGE_VEC_LOOP/COMP_LOOP/COMP_LOOP-4:modExp_dev#1:while/COMP_LOOP-4:modExp_dev#1:while:acc CSTEPS_FROM {{.. == 1}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/STAGE_VEC_LOOP/COMP_LOOP/COMP_LOOP-4:modExp_dev#1:while/COMP_LOOP-4:modExp_dev#1:while:mul CSTEPS_FROM {{.. == 1}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/STAGE_VEC_LOOP/COMP_LOOP/COMP_LOOP-4:modExp_dev#1:while/COMP_LOOP-4:modExp_dev#1:while:rem CSTEPS_FROM {{.. == 1}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/STAGE_VEC_LOOP/COMP_LOOP/COMP_LOOP-4:modExp_dev#1:while/COMP_LOOP-4:operator><64,false>#1:acc CSTEPS_FROM {{.. == 1}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/STAGE_VEC_LOOP/COMP_LOOP/COMP_LOOP-4:acc#5 CSTEPS_FROM {{.. == 153}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/STAGE_VEC_LOOP/COMP_LOOP/COMP_LOOP-4:modulo_dev()#1 CSTEPS_FROM {{.. == 153}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/STAGE_VEC_LOOP/COMP_LOOP/COMP_LOOP-4:mul CSTEPS_FROM {{.. == 166}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/STAGE_VEC_LOOP/COMP_LOOP/COMP_LOOP-4:modulo_dev()#2 CSTEPS_FROM {{.. == 167}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/STAGE_VEC_LOOP/COMP_LOOP/COMP_LOOP:write_mem(vec:rsc(0)(0).@)#7 CSTEPS_FROM {{.. == 180}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/STAGE_VEC_LOOP/COMP_LOOP/COMP_LOOP:write_mem(vec:rsc(0)(1).@)#7 CSTEPS_FROM {{.. == 180}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/STAGE_VEC_LOOP/COMP_LOOP/COMP_LOOP:write_mem(vec:rsc(0)(2).@)#7 CSTEPS_FROM {{.. == 180}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/STAGE_VEC_LOOP/COMP_LOOP/COMP_LOOP:write_mem(vec:rsc(0)(3).@)#7 CSTEPS_FROM {{.. == 180}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/STAGE_VEC_LOOP/COMP_LOOP/COMP_LOOP:write_mem(vec:rsc(0)(4).@)#7 CSTEPS_FROM {{.. == 180}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/STAGE_VEC_LOOP/COMP_LOOP/COMP_LOOP:write_mem(vec:rsc(0)(5).@)#7 CSTEPS_FROM {{.. == 180}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/STAGE_VEC_LOOP/COMP_LOOP/COMP_LOOP:write_mem(vec:rsc(0)(6).@)#7 CSTEPS_FROM {{.. == 180}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/STAGE_VEC_LOOP/COMP_LOOP/COMP_LOOP:write_mem(vec:rsc(0)(7).@)#7 CSTEPS_FROM {{.. == 180}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/STAGE_VEC_LOOP/COMP_LOOP/COMP_LOOP-5:operator<<64,false>:acc CSTEPS_FROM {{.. == 153}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/STAGE_VEC_LOOP/COMP_LOOP/COMP_LOOP:acc#8 CSTEPS_FROM {{.. == 1}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/STAGE_VEC_LOOP/COMP_LOOP/COMP_LOOP:read_mem(vec:rsc(0)(0).@)#8 CSTEPS_FROM {{.. == 181}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/STAGE_VEC_LOOP/COMP_LOOP/COMP_LOOP:read_mem(vec:rsc(0)(1).@)#8 CSTEPS_FROM {{.. == 181}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/STAGE_VEC_LOOP/COMP_LOOP/COMP_LOOP:read_mem(vec:rsc(0)(2).@)#8 CSTEPS_FROM {{.. == 181}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/STAGE_VEC_LOOP/COMP_LOOP/COMP_LOOP:read_mem(vec:rsc(0)(3).@)#8 CSTEPS_FROM {{.. == 181}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/STAGE_VEC_LOOP/COMP_LOOP/COMP_LOOP:read_mem(vec:rsc(0)(4).@)#8 CSTEPS_FROM {{.. == 181}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/STAGE_VEC_LOOP/COMP_LOOP/COMP_LOOP:read_mem(vec:rsc(0)(5).@)#8 CSTEPS_FROM {{.. == 181}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/STAGE_VEC_LOOP/COMP_LOOP/COMP_LOOP:read_mem(vec:rsc(0)(6).@)#8 CSTEPS_FROM {{.. == 181}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/STAGE_VEC_LOOP/COMP_LOOP/COMP_LOOP:read_mem(vec:rsc(0)(7).@)#8 CSTEPS_FROM {{.. == 181}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/STAGE_VEC_LOOP/COMP_LOOP/COMP_LOOP:mux1h#8 CSTEPS_FROM {{.. == 182}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/STAGE_VEC_LOOP/COMP_LOOP/COMP_LOOP-5:operator+<64,false>:acc CSTEPS_FROM {{.. == 1}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/STAGE_VEC_LOOP/COMP_LOOP/COMP_LOOP:read_mem(vec:rsc(0)(0).@)#9 CSTEPS_FROM {{.. == 182}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/STAGE_VEC_LOOP/COMP_LOOP/COMP_LOOP:read_mem(vec:rsc(0)(1).@)#9 CSTEPS_FROM {{.. == 182}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/STAGE_VEC_LOOP/COMP_LOOP/COMP_LOOP:read_mem(vec:rsc(0)(2).@)#9 CSTEPS_FROM {{.. == 182}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/STAGE_VEC_LOOP/COMP_LOOP/COMP_LOOP:read_mem(vec:rsc(0)(3).@)#9 CSTEPS_FROM {{.. == 182}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/STAGE_VEC_LOOP/COMP_LOOP/COMP_LOOP:read_mem(vec:rsc(0)(4).@)#9 CSTEPS_FROM {{.. == 182}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/STAGE_VEC_LOOP/COMP_LOOP/COMP_LOOP:read_mem(vec:rsc(0)(5).@)#9 CSTEPS_FROM {{.. == 182}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/STAGE_VEC_LOOP/COMP_LOOP/COMP_LOOP:read_mem(vec:rsc(0)(6).@)#9 CSTEPS_FROM {{.. == 182}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/STAGE_VEC_LOOP/COMP_LOOP/COMP_LOOP:read_mem(vec:rsc(0)(7).@)#9 CSTEPS_FROM {{.. == 182}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/STAGE_VEC_LOOP/COMP_LOOP/COMP_LOOP:mux1h#9 CSTEPS_FROM {{.. == 183}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/STAGE_VEC_LOOP/COMP_LOOP/COMP_LOOP-5:acc#3 CSTEPS_FROM {{.. == 183}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/STAGE_VEC_LOOP/COMP_LOOP/COMP_LOOP-5:modulo_dev() CSTEPS_FROM {{.. == 183}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/STAGE_VEC_LOOP/COMP_LOOP/COMP_LOOP:write_mem(vec:rsc(0)(0).@)#8 CSTEPS_FROM {{.. == 196}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/STAGE_VEC_LOOP/COMP_LOOP/COMP_LOOP:write_mem(vec:rsc(0)(1).@)#8 CSTEPS_FROM {{.. == 196}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/STAGE_VEC_LOOP/COMP_LOOP/COMP_LOOP:write_mem(vec:rsc(0)(2).@)#8 CSTEPS_FROM {{.. == 196}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/STAGE_VEC_LOOP/COMP_LOOP/COMP_LOOP:write_mem(vec:rsc(0)(3).@)#8 CSTEPS_FROM {{.. == 196}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/STAGE_VEC_LOOP/COMP_LOOP/COMP_LOOP:write_mem(vec:rsc(0)(4).@)#8 CSTEPS_FROM {{.. == 196}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/STAGE_VEC_LOOP/COMP_LOOP/COMP_LOOP:write_mem(vec:rsc(0)(5).@)#8 CSTEPS_FROM {{.. == 196}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/STAGE_VEC_LOOP/COMP_LOOP/COMP_LOOP:write_mem(vec:rsc(0)(6).@)#8 CSTEPS_FROM {{.. == 196}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/STAGE_VEC_LOOP/COMP_LOOP/COMP_LOOP:write_mem(vec:rsc(0)(7).@)#8 CSTEPS_FROM {{.. == 196}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/STAGE_VEC_LOOP/COMP_LOOP/COMP_LOOP-5:modExp_dev#1:while/COMP_LOOP-5:modExp_dev#1:while:acc CSTEPS_FROM {{.. == 1}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/STAGE_VEC_LOOP/COMP_LOOP/COMP_LOOP-5:modExp_dev#1:while/COMP_LOOP-5:modExp_dev#1:while:mul CSTEPS_FROM {{.. == 1}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/STAGE_VEC_LOOP/COMP_LOOP/COMP_LOOP-5:modExp_dev#1:while/COMP_LOOP-5:modExp_dev#1:while:rem CSTEPS_FROM {{.. == 1}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/STAGE_VEC_LOOP/COMP_LOOP/COMP_LOOP-5:modExp_dev#1:while/COMP_LOOP-5:operator><64,false>#1:acc CSTEPS_FROM {{.. == 1}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/STAGE_VEC_LOOP/COMP_LOOP/COMP_LOOP-5:acc#5 CSTEPS_FROM {{.. == 198}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/STAGE_VEC_LOOP/COMP_LOOP/COMP_LOOP-5:modulo_dev()#1 CSTEPS_FROM {{.. == 198}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/STAGE_VEC_LOOP/COMP_LOOP/COMP_LOOP-5:mul CSTEPS_FROM {{.. == 211}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/STAGE_VEC_LOOP/COMP_LOOP/COMP_LOOP-5:modulo_dev()#2 CSTEPS_FROM {{.. == 212}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/STAGE_VEC_LOOP/COMP_LOOP/COMP_LOOP:write_mem(vec:rsc(0)(0).@)#9 CSTEPS_FROM {{.. == 225}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/STAGE_VEC_LOOP/COMP_LOOP/COMP_LOOP:write_mem(vec:rsc(0)(1).@)#9 CSTEPS_FROM {{.. == 225}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/STAGE_VEC_LOOP/COMP_LOOP/COMP_LOOP:write_mem(vec:rsc(0)(2).@)#9 CSTEPS_FROM {{.. == 225}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/STAGE_VEC_LOOP/COMP_LOOP/COMP_LOOP:write_mem(vec:rsc(0)(3).@)#9 CSTEPS_FROM {{.. == 225}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/STAGE_VEC_LOOP/COMP_LOOP/COMP_LOOP:write_mem(vec:rsc(0)(4).@)#9 CSTEPS_FROM {{.. == 225}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/STAGE_VEC_LOOP/COMP_LOOP/COMP_LOOP:write_mem(vec:rsc(0)(5).@)#9 CSTEPS_FROM {{.. == 225}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/STAGE_VEC_LOOP/COMP_LOOP/COMP_LOOP:write_mem(vec:rsc(0)(6).@)#9 CSTEPS_FROM {{.. == 225}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/STAGE_VEC_LOOP/COMP_LOOP/COMP_LOOP:write_mem(vec:rsc(0)(7).@)#9 CSTEPS_FROM {{.. == 225}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/STAGE_VEC_LOOP/COMP_LOOP/COMP_LOOP-6:operator<<64,false>:acc CSTEPS_FROM {{.. == 198}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/STAGE_VEC_LOOP/COMP_LOOP/COMP_LOOP-6:acc CSTEPS_FROM {{.. == 1}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/STAGE_VEC_LOOP/COMP_LOOP/COMP_LOOP:read_mem(vec:rsc(0)(0).@)#10 CSTEPS_FROM {{.. == 226}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/STAGE_VEC_LOOP/COMP_LOOP/COMP_LOOP:read_mem(vec:rsc(0)(1).@)#10 CSTEPS_FROM {{.. == 226}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/STAGE_VEC_LOOP/COMP_LOOP/COMP_LOOP:read_mem(vec:rsc(0)(2).@)#10 CSTEPS_FROM {{.. == 226}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/STAGE_VEC_LOOP/COMP_LOOP/COMP_LOOP:read_mem(vec:rsc(0)(3).@)#10 CSTEPS_FROM {{.. == 226}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/STAGE_VEC_LOOP/COMP_LOOP/COMP_LOOP:read_mem(vec:rsc(0)(4).@)#10 CSTEPS_FROM {{.. == 226}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/STAGE_VEC_LOOP/COMP_LOOP/COMP_LOOP:read_mem(vec:rsc(0)(5).@)#10 CSTEPS_FROM {{.. == 226}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/STAGE_VEC_LOOP/COMP_LOOP/COMP_LOOP:read_mem(vec:rsc(0)(6).@)#10 CSTEPS_FROM {{.. == 226}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/STAGE_VEC_LOOP/COMP_LOOP/COMP_LOOP:read_mem(vec:rsc(0)(7).@)#10 CSTEPS_FROM {{.. == 226}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/STAGE_VEC_LOOP/COMP_LOOP/COMP_LOOP:mux1h#10 CSTEPS_FROM {{.. == 227}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/STAGE_VEC_LOOP/COMP_LOOP/COMP_LOOP-6:operator+<64,false>:acc CSTEPS_FROM {{.. == 1}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/STAGE_VEC_LOOP/COMP_LOOP/COMP_LOOP:read_mem(vec:rsc(0)(0).@)#11 CSTEPS_FROM {{.. == 227}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/STAGE_VEC_LOOP/COMP_LOOP/COMP_LOOP:read_mem(vec:rsc(0)(1).@)#11 CSTEPS_FROM {{.. == 227}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/STAGE_VEC_LOOP/COMP_LOOP/COMP_LOOP:read_mem(vec:rsc(0)(2).@)#11 CSTEPS_FROM {{.. == 227}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/STAGE_VEC_LOOP/COMP_LOOP/COMP_LOOP:read_mem(vec:rsc(0)(3).@)#11 CSTEPS_FROM {{.. == 227}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/STAGE_VEC_LOOP/COMP_LOOP/COMP_LOOP:read_mem(vec:rsc(0)(4).@)#11 CSTEPS_FROM {{.. == 227}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/STAGE_VEC_LOOP/COMP_LOOP/COMP_LOOP:read_mem(vec:rsc(0)(5).@)#11 CSTEPS_FROM {{.. == 227}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/STAGE_VEC_LOOP/COMP_LOOP/COMP_LOOP:read_mem(vec:rsc(0)(6).@)#11 CSTEPS_FROM {{.. == 227}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/STAGE_VEC_LOOP/COMP_LOOP/COMP_LOOP:read_mem(vec:rsc(0)(7).@)#11 CSTEPS_FROM {{.. == 227}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/STAGE_VEC_LOOP/COMP_LOOP/COMP_LOOP:mux1h#11 CSTEPS_FROM {{.. == 228}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/STAGE_VEC_LOOP/COMP_LOOP/COMP_LOOP-6:acc#3 CSTEPS_FROM {{.. == 228}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/STAGE_VEC_LOOP/COMP_LOOP/COMP_LOOP-6:modulo_dev() CSTEPS_FROM {{.. == 228}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/STAGE_VEC_LOOP/COMP_LOOP/COMP_LOOP:write_mem(vec:rsc(0)(0).@)#10 CSTEPS_FROM {{.. == 241}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/STAGE_VEC_LOOP/COMP_LOOP/COMP_LOOP:write_mem(vec:rsc(0)(1).@)#10 CSTEPS_FROM {{.. == 241}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/STAGE_VEC_LOOP/COMP_LOOP/COMP_LOOP:write_mem(vec:rsc(0)(2).@)#10 CSTEPS_FROM {{.. == 241}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/STAGE_VEC_LOOP/COMP_LOOP/COMP_LOOP:write_mem(vec:rsc(0)(3).@)#10 CSTEPS_FROM {{.. == 241}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/STAGE_VEC_LOOP/COMP_LOOP/COMP_LOOP:write_mem(vec:rsc(0)(4).@)#10 CSTEPS_FROM {{.. == 241}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/STAGE_VEC_LOOP/COMP_LOOP/COMP_LOOP:write_mem(vec:rsc(0)(5).@)#10 CSTEPS_FROM {{.. == 241}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/STAGE_VEC_LOOP/COMP_LOOP/COMP_LOOP:write_mem(vec:rsc(0)(6).@)#10 CSTEPS_FROM {{.. == 241}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/STAGE_VEC_LOOP/COMP_LOOP/COMP_LOOP:write_mem(vec:rsc(0)(7).@)#10 CSTEPS_FROM {{.. == 241}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/STAGE_VEC_LOOP/COMP_LOOP/COMP_LOOP-6:modExp_dev#1:while/COMP_LOOP-6:modExp_dev#1:while:acc CSTEPS_FROM {{.. == 1}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/STAGE_VEC_LOOP/COMP_LOOP/COMP_LOOP-6:modExp_dev#1:while/COMP_LOOP-6:modExp_dev#1:while:mul CSTEPS_FROM {{.. == 1}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/STAGE_VEC_LOOP/COMP_LOOP/COMP_LOOP-6:modExp_dev#1:while/COMP_LOOP-6:modExp_dev#1:while:rem CSTEPS_FROM {{.. == 1}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/STAGE_VEC_LOOP/COMP_LOOP/COMP_LOOP-6:modExp_dev#1:while/COMP_LOOP-6:operator><64,false>#1:acc CSTEPS_FROM {{.. == 1}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/STAGE_VEC_LOOP/COMP_LOOP/COMP_LOOP-6:acc#5 CSTEPS_FROM {{.. == 243}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/STAGE_VEC_LOOP/COMP_LOOP/COMP_LOOP-6:modulo_dev()#1 CSTEPS_FROM {{.. == 243}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/STAGE_VEC_LOOP/COMP_LOOP/COMP_LOOP-6:mul CSTEPS_FROM {{.. == 256}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/STAGE_VEC_LOOP/COMP_LOOP/COMP_LOOP-6:modulo_dev()#2 CSTEPS_FROM {{.. == 257}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/STAGE_VEC_LOOP/COMP_LOOP/COMP_LOOP:write_mem(vec:rsc(0)(0).@)#11 CSTEPS_FROM {{.. == 270}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/STAGE_VEC_LOOP/COMP_LOOP/COMP_LOOP:write_mem(vec:rsc(0)(1).@)#11 CSTEPS_FROM {{.. == 270}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/STAGE_VEC_LOOP/COMP_LOOP/COMP_LOOP:write_mem(vec:rsc(0)(2).@)#11 CSTEPS_FROM {{.. == 270}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/STAGE_VEC_LOOP/COMP_LOOP/COMP_LOOP:write_mem(vec:rsc(0)(3).@)#11 CSTEPS_FROM {{.. == 270}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/STAGE_VEC_LOOP/COMP_LOOP/COMP_LOOP:write_mem(vec:rsc(0)(4).@)#11 CSTEPS_FROM {{.. == 270}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/STAGE_VEC_LOOP/COMP_LOOP/COMP_LOOP:write_mem(vec:rsc(0)(5).@)#11 CSTEPS_FROM {{.. == 270}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/STAGE_VEC_LOOP/COMP_LOOP/COMP_LOOP:write_mem(vec:rsc(0)(6).@)#11 CSTEPS_FROM {{.. == 270}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/STAGE_VEC_LOOP/COMP_LOOP/COMP_LOOP:write_mem(vec:rsc(0)(7).@)#11 CSTEPS_FROM {{.. == 270}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/STAGE_VEC_LOOP/COMP_LOOP/COMP_LOOP-7:operator<<64,false>:acc CSTEPS_FROM {{.. == 243}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/STAGE_VEC_LOOP/COMP_LOOP/COMP_LOOP:acc#9 CSTEPS_FROM {{.. == 1}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/STAGE_VEC_LOOP/COMP_LOOP/COMP_LOOP:read_mem(vec:rsc(0)(0).@)#12 CSTEPS_FROM {{.. == 271}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/STAGE_VEC_LOOP/COMP_LOOP/COMP_LOOP:read_mem(vec:rsc(0)(1).@)#12 CSTEPS_FROM {{.. == 271}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/STAGE_VEC_LOOP/COMP_LOOP/COMP_LOOP:read_mem(vec:rsc(0)(2).@)#12 CSTEPS_FROM {{.. == 271}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/STAGE_VEC_LOOP/COMP_LOOP/COMP_LOOP:read_mem(vec:rsc(0)(3).@)#12 CSTEPS_FROM {{.. == 271}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/STAGE_VEC_LOOP/COMP_LOOP/COMP_LOOP:read_mem(vec:rsc(0)(4).@)#12 CSTEPS_FROM {{.. == 271}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/STAGE_VEC_LOOP/COMP_LOOP/COMP_LOOP:read_mem(vec:rsc(0)(5).@)#12 CSTEPS_FROM {{.. == 271}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/STAGE_VEC_LOOP/COMP_LOOP/COMP_LOOP:read_mem(vec:rsc(0)(6).@)#12 CSTEPS_FROM {{.. == 271}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/STAGE_VEC_LOOP/COMP_LOOP/COMP_LOOP:read_mem(vec:rsc(0)(7).@)#12 CSTEPS_FROM {{.. == 271}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/STAGE_VEC_LOOP/COMP_LOOP/COMP_LOOP:mux1h#12 CSTEPS_FROM {{.. == 272}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/STAGE_VEC_LOOP/COMP_LOOP/COMP_LOOP-7:operator+<64,false>:acc CSTEPS_FROM {{.. == 1}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/STAGE_VEC_LOOP/COMP_LOOP/COMP_LOOP:read_mem(vec:rsc(0)(0).@)#13 CSTEPS_FROM {{.. == 272}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/STAGE_VEC_LOOP/COMP_LOOP/COMP_LOOP:read_mem(vec:rsc(0)(1).@)#13 CSTEPS_FROM {{.. == 272}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/STAGE_VEC_LOOP/COMP_LOOP/COMP_LOOP:read_mem(vec:rsc(0)(2).@)#13 CSTEPS_FROM {{.. == 272}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/STAGE_VEC_LOOP/COMP_LOOP/COMP_LOOP:read_mem(vec:rsc(0)(3).@)#13 CSTEPS_FROM {{.. == 272}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/STAGE_VEC_LOOP/COMP_LOOP/COMP_LOOP:read_mem(vec:rsc(0)(4).@)#13 CSTEPS_FROM {{.. == 272}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/STAGE_VEC_LOOP/COMP_LOOP/COMP_LOOP:read_mem(vec:rsc(0)(5).@)#13 CSTEPS_FROM {{.. == 272}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/STAGE_VEC_LOOP/COMP_LOOP/COMP_LOOP:read_mem(vec:rsc(0)(6).@)#13 CSTEPS_FROM {{.. == 272}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/STAGE_VEC_LOOP/COMP_LOOP/COMP_LOOP:read_mem(vec:rsc(0)(7).@)#13 CSTEPS_FROM {{.. == 272}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/STAGE_VEC_LOOP/COMP_LOOP/COMP_LOOP:mux1h#13 CSTEPS_FROM {{.. == 273}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/STAGE_VEC_LOOP/COMP_LOOP/COMP_LOOP-7:acc#3 CSTEPS_FROM {{.. == 273}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/STAGE_VEC_LOOP/COMP_LOOP/COMP_LOOP-7:modulo_dev() CSTEPS_FROM {{.. == 273}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/STAGE_VEC_LOOP/COMP_LOOP/COMP_LOOP:write_mem(vec:rsc(0)(0).@)#12 CSTEPS_FROM {{.. == 286}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/STAGE_VEC_LOOP/COMP_LOOP/COMP_LOOP:write_mem(vec:rsc(0)(1).@)#12 CSTEPS_FROM {{.. == 286}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/STAGE_VEC_LOOP/COMP_LOOP/COMP_LOOP:write_mem(vec:rsc(0)(2).@)#12 CSTEPS_FROM {{.. == 286}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/STAGE_VEC_LOOP/COMP_LOOP/COMP_LOOP:write_mem(vec:rsc(0)(3).@)#12 CSTEPS_FROM {{.. == 286}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/STAGE_VEC_LOOP/COMP_LOOP/COMP_LOOP:write_mem(vec:rsc(0)(4).@)#12 CSTEPS_FROM {{.. == 286}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/STAGE_VEC_LOOP/COMP_LOOP/COMP_LOOP:write_mem(vec:rsc(0)(5).@)#12 CSTEPS_FROM {{.. == 286}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/STAGE_VEC_LOOP/COMP_LOOP/COMP_LOOP:write_mem(vec:rsc(0)(6).@)#12 CSTEPS_FROM {{.. == 286}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/STAGE_VEC_LOOP/COMP_LOOP/COMP_LOOP:write_mem(vec:rsc(0)(7).@)#12 CSTEPS_FROM {{.. == 286}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/STAGE_VEC_LOOP/COMP_LOOP/COMP_LOOP-7:modExp_dev#1:while/COMP_LOOP-7:modExp_dev#1:while:acc CSTEPS_FROM {{.. == 1}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/STAGE_VEC_LOOP/COMP_LOOP/COMP_LOOP-7:modExp_dev#1:while/COMP_LOOP-7:modExp_dev#1:while:mul CSTEPS_FROM {{.. == 1}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/STAGE_VEC_LOOP/COMP_LOOP/COMP_LOOP-7:modExp_dev#1:while/COMP_LOOP-7:modExp_dev#1:while:rem CSTEPS_FROM {{.. == 1}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/STAGE_VEC_LOOP/COMP_LOOP/COMP_LOOP-7:modExp_dev#1:while/COMP_LOOP-7:operator><64,false>#1:acc CSTEPS_FROM {{.. == 1}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/STAGE_VEC_LOOP/COMP_LOOP/COMP_LOOP-7:acc#5 CSTEPS_FROM {{.. == 288}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/STAGE_VEC_LOOP/COMP_LOOP/COMP_LOOP-7:modulo_dev()#1 CSTEPS_FROM {{.. == 288}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/STAGE_VEC_LOOP/COMP_LOOP/COMP_LOOP-7:mul CSTEPS_FROM {{.. == 301}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/STAGE_VEC_LOOP/COMP_LOOP/COMP_LOOP-7:modulo_dev()#2 CSTEPS_FROM {{.. == 302}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/STAGE_VEC_LOOP/COMP_LOOP/COMP_LOOP:write_mem(vec:rsc(0)(0).@)#13 CSTEPS_FROM {{.. == 315}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/STAGE_VEC_LOOP/COMP_LOOP/COMP_LOOP:write_mem(vec:rsc(0)(1).@)#13 CSTEPS_FROM {{.. == 315}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/STAGE_VEC_LOOP/COMP_LOOP/COMP_LOOP:write_mem(vec:rsc(0)(2).@)#13 CSTEPS_FROM {{.. == 315}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/STAGE_VEC_LOOP/COMP_LOOP/COMP_LOOP:write_mem(vec:rsc(0)(3).@)#13 CSTEPS_FROM {{.. == 315}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/STAGE_VEC_LOOP/COMP_LOOP/COMP_LOOP:write_mem(vec:rsc(0)(4).@)#13 CSTEPS_FROM {{.. == 315}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/STAGE_VEC_LOOP/COMP_LOOP/COMP_LOOP:write_mem(vec:rsc(0)(5).@)#13 CSTEPS_FROM {{.. == 315}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/STAGE_VEC_LOOP/COMP_LOOP/COMP_LOOP:write_mem(vec:rsc(0)(6).@)#13 CSTEPS_FROM {{.. == 315}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/STAGE_VEC_LOOP/COMP_LOOP/COMP_LOOP:write_mem(vec:rsc(0)(7).@)#13 CSTEPS_FROM {{.. == 315}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/STAGE_VEC_LOOP/COMP_LOOP/operator<<64,false>:acc#1 CSTEPS_FROM {{.. == 288}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/STAGE_VEC_LOOP/COMP_LOOP/COMP_LOOP-8:acc CSTEPS_FROM {{.. == 1}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/STAGE_VEC_LOOP/COMP_LOOP/COMP_LOOP:read_mem(vec:rsc(0)(0).@)#14 CSTEPS_FROM {{.. == 316}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/STAGE_VEC_LOOP/COMP_LOOP/COMP_LOOP:read_mem(vec:rsc(0)(1).@)#14 CSTEPS_FROM {{.. == 316}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/STAGE_VEC_LOOP/COMP_LOOP/COMP_LOOP:read_mem(vec:rsc(0)(2).@)#14 CSTEPS_FROM {{.. == 316}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/STAGE_VEC_LOOP/COMP_LOOP/COMP_LOOP:read_mem(vec:rsc(0)(3).@)#14 CSTEPS_FROM {{.. == 316}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/STAGE_VEC_LOOP/COMP_LOOP/COMP_LOOP:read_mem(vec:rsc(0)(4).@)#14 CSTEPS_FROM {{.. == 316}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/STAGE_VEC_LOOP/COMP_LOOP/COMP_LOOP:read_mem(vec:rsc(0)(5).@)#14 CSTEPS_FROM {{.. == 316}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/STAGE_VEC_LOOP/COMP_LOOP/COMP_LOOP:read_mem(vec:rsc(0)(6).@)#14 CSTEPS_FROM {{.. == 316}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/STAGE_VEC_LOOP/COMP_LOOP/COMP_LOOP:read_mem(vec:rsc(0)(7).@)#14 CSTEPS_FROM {{.. == 316}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/STAGE_VEC_LOOP/COMP_LOOP/COMP_LOOP:mux1h#14 CSTEPS_FROM {{.. == 317}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/STAGE_VEC_LOOP/COMP_LOOP/COMP_LOOP-8:operator+<64,false>:acc CSTEPS_FROM {{.. == 1}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/STAGE_VEC_LOOP/COMP_LOOP/COMP_LOOP:read_mem(vec:rsc(0)(0).@)#15 CSTEPS_FROM {{.. == 317}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/STAGE_VEC_LOOP/COMP_LOOP/COMP_LOOP:read_mem(vec:rsc(0)(1).@)#15 CSTEPS_FROM {{.. == 317}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/STAGE_VEC_LOOP/COMP_LOOP/COMP_LOOP:read_mem(vec:rsc(0)(2).@)#15 CSTEPS_FROM {{.. == 317}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/STAGE_VEC_LOOP/COMP_LOOP/COMP_LOOP:read_mem(vec:rsc(0)(3).@)#15 CSTEPS_FROM {{.. == 317}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/STAGE_VEC_LOOP/COMP_LOOP/COMP_LOOP:read_mem(vec:rsc(0)(4).@)#15 CSTEPS_FROM {{.. == 317}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/STAGE_VEC_LOOP/COMP_LOOP/COMP_LOOP:read_mem(vec:rsc(0)(5).@)#15 CSTEPS_FROM {{.. == 317}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/STAGE_VEC_LOOP/COMP_LOOP/COMP_LOOP:read_mem(vec:rsc(0)(6).@)#15 CSTEPS_FROM {{.. == 317}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/STAGE_VEC_LOOP/COMP_LOOP/COMP_LOOP:read_mem(vec:rsc(0)(7).@)#15 CSTEPS_FROM {{.. == 317}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/STAGE_VEC_LOOP/COMP_LOOP/COMP_LOOP:mux1h#15 CSTEPS_FROM {{.. == 318}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/STAGE_VEC_LOOP/COMP_LOOP/COMP_LOOP-8:acc#3 CSTEPS_FROM {{.. == 318}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/STAGE_VEC_LOOP/COMP_LOOP/COMP_LOOP-8:modulo_dev() CSTEPS_FROM {{.. == 318}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/STAGE_VEC_LOOP/COMP_LOOP/COMP_LOOP:write_mem(vec:rsc(0)(0).@)#14 CSTEPS_FROM {{.. == 331}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/STAGE_VEC_LOOP/COMP_LOOP/COMP_LOOP:write_mem(vec:rsc(0)(1).@)#14 CSTEPS_FROM {{.. == 331}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/STAGE_VEC_LOOP/COMP_LOOP/COMP_LOOP:write_mem(vec:rsc(0)(2).@)#14 CSTEPS_FROM {{.. == 331}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/STAGE_VEC_LOOP/COMP_LOOP/COMP_LOOP:write_mem(vec:rsc(0)(3).@)#14 CSTEPS_FROM {{.. == 331}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/STAGE_VEC_LOOP/COMP_LOOP/COMP_LOOP:write_mem(vec:rsc(0)(4).@)#14 CSTEPS_FROM {{.. == 331}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/STAGE_VEC_LOOP/COMP_LOOP/COMP_LOOP:write_mem(vec:rsc(0)(5).@)#14 CSTEPS_FROM {{.. == 331}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/STAGE_VEC_LOOP/COMP_LOOP/COMP_LOOP:write_mem(vec:rsc(0)(6).@)#14 CSTEPS_FROM {{.. == 331}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/STAGE_VEC_LOOP/COMP_LOOP/COMP_LOOP:write_mem(vec:rsc(0)(7).@)#14 CSTEPS_FROM {{.. == 331}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/STAGE_VEC_LOOP/COMP_LOOP/COMP_LOOP-8:modExp_dev#1:while/COMP_LOOP-8:modExp_dev#1:while:acc CSTEPS_FROM {{.. == 1}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/STAGE_VEC_LOOP/COMP_LOOP/COMP_LOOP-8:modExp_dev#1:while/COMP_LOOP-8:modExp_dev#1:while:mul CSTEPS_FROM {{.. == 1}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/STAGE_VEC_LOOP/COMP_LOOP/COMP_LOOP-8:modExp_dev#1:while/COMP_LOOP-8:modExp_dev#1:while:rem CSTEPS_FROM {{.. == 1}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/STAGE_VEC_LOOP/COMP_LOOP/COMP_LOOP-8:modExp_dev#1:while/COMP_LOOP-8:operator><64,false>#1:acc CSTEPS_FROM {{.. == 1}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/STAGE_VEC_LOOP/COMP_LOOP/COMP_LOOP-8:acc#5 CSTEPS_FROM {{.. == 333}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/STAGE_VEC_LOOP/COMP_LOOP/COMP_LOOP-8:modulo_dev()#1 CSTEPS_FROM {{.. == 333}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/STAGE_VEC_LOOP/COMP_LOOP/COMP_LOOP-8:mul CSTEPS_FROM {{.. == 346}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/STAGE_VEC_LOOP/COMP_LOOP/COMP_LOOP-8:modulo_dev()#2 CSTEPS_FROM {{.. == 347}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/STAGE_VEC_LOOP/COMP_LOOP/COMP_LOOP:write_mem(vec:rsc(0)(0).@)#15 CSTEPS_FROM {{.. == 360}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/STAGE_VEC_LOOP/COMP_LOOP/COMP_LOOP:write_mem(vec:rsc(0)(1).@)#15 CSTEPS_FROM {{.. == 360}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/STAGE_VEC_LOOP/COMP_LOOP/COMP_LOOP:write_mem(vec:rsc(0)(2).@)#15 CSTEPS_FROM {{.. == 360}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/STAGE_VEC_LOOP/COMP_LOOP/COMP_LOOP:write_mem(vec:rsc(0)(3).@)#15 CSTEPS_FROM {{.. == 360}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/STAGE_VEC_LOOP/COMP_LOOP/COMP_LOOP:write_mem(vec:rsc(0)(4).@)#15 CSTEPS_FROM {{.. == 360}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/STAGE_VEC_LOOP/COMP_LOOP/COMP_LOOP:write_mem(vec:rsc(0)(5).@)#15 CSTEPS_FROM {{.. == 360}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/STAGE_VEC_LOOP/COMP_LOOP/COMP_LOOP:write_mem(vec:rsc(0)(6).@)#15 CSTEPS_FROM {{.. == 360}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/STAGE_VEC_LOOP/COMP_LOOP/COMP_LOOP:write_mem(vec:rsc(0)(7).@)#15 CSTEPS_FROM {{.. == 360}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/STAGE_VEC_LOOP/COMP_LOOP/COMP_LOOP:acc#10 CSTEPS_FROM {{.. == 333}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/STAGE_VEC_LOOP/COMP_LOOP/COMP_LOOP-1:operator<<64,false>:acc CSTEPS_FROM {{.. == 333}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/STAGE_VEC_LOOP/STAGE_VEC_LOOP:acc#1 CSTEPS_FROM {{.. == 2}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/STAGE_VEC_LOOP/STAGE_VEC_LOOP:acc CSTEPS_FROM {{.. == 2}}
directive set /inPlaceNTT_DIF/core/core:rlp/main/STAGE_MAIN_LOOP/STAGE_MAIN_LOOP:acc CSTEPS_FROM {{.. == 5}}

# Probe constraints
