directive set /inPlaceNTT_DIF/inPlaceNTT_DIF:core/inPlaceNTT_DIF:core:conc/COMP_LOOP-1:mul RESOURCE_NAME COMP_LOOP-1:modExp_dev#1:while:mul:rg
directive set /inPlaceNTT_DIF/inPlaceNTT_DIF:core/inPlaceNTT_DIF:core:conc/modExp_dev:while:mul RESOURCE_NAME COMP_LOOP-1:modExp_dev#1:while:mul:rg
directive set /inPlaceNTT_DIF/inPlaceNTT_DIF:core/inPlaceNTT_DIF:core:conc/COMP_LOOP-1:modExp_dev#1:while:mul RESOURCE_NAME COMP_LOOP-1:modExp_dev#1:while:mul:rg
directive set /inPlaceNTT_DIF/inPlaceNTT_DIF:core/inPlaceNTT_DIF:core:conc/COMP_LOOP-8:acc RESOURCE_NAME COMP_LOOP-8:acc:rg
directive set /inPlaceNTT_DIF/inPlaceNTT_DIF:core/inPlaceNTT_DIF:core:conc/operator<<64,false>:acc RESOURCE_NAME COMP_LOOP-8:acc:rg
directive set /inPlaceNTT_DIF/inPlaceNTT_DIF:core/inPlaceNTT_DIF:core:conc/COMP_LOOP-2:operator<<64,false>:acc RESOURCE_NAME COMP_LOOP-1:operator<<64,false>:acc:rg
directive set /inPlaceNTT_DIF/inPlaceNTT_DIF:core/inPlaceNTT_DIF:core:conc/COMP_LOOP-3:operator<<64,false>:acc RESOURCE_NAME COMP_LOOP-1:operator<<64,false>:acc:rg
directive set /inPlaceNTT_DIF/inPlaceNTT_DIF:core/inPlaceNTT_DIF:core:conc/COMP_LOOP-5:operator<<64,false>:acc RESOURCE_NAME COMP_LOOP-1:operator<<64,false>:acc:rg
directive set /inPlaceNTT_DIF/inPlaceNTT_DIF:core/inPlaceNTT_DIF:core:conc/COMP_LOOP-6:operator<<64,false>:acc RESOURCE_NAME COMP_LOOP-1:operator<<64,false>:acc:rg
directive set /inPlaceNTT_DIF/inPlaceNTT_DIF:core/inPlaceNTT_DIF:core:conc/COMP_LOOP-7:operator<<64,false>:acc RESOURCE_NAME COMP_LOOP-1:operator<<64,false>:acc:rg
directive set /inPlaceNTT_DIF/inPlaceNTT_DIF:core/inPlaceNTT_DIF:core:conc/COMP_LOOP:acc RESOURCE_NAME COMP_LOOP-1:operator<<64,false>:acc:rg
directive set /inPlaceNTT_DIF/inPlaceNTT_DIF:core/inPlaceNTT_DIF:core:conc/STAGE_VEC_LOOP:acc#1 RESOURCE_NAME COMP_LOOP-1:operator<<64,false>:acc:rg
directive set /inPlaceNTT_DIF/inPlaceNTT_DIF:core/inPlaceNTT_DIF:core:conc/COMP_LOOP-1:operator><64,false>#1:acc#1 RESOURCE_NAME COMP_LOOP-1:operator<<64,false>:acc:rg
directive set /inPlaceNTT_DIF/inPlaceNTT_DIF:core/inPlaceNTT_DIF:core:conc/STAGE_MAIN_LOOP:acc RESOURCE_NAME COMP_LOOP-1:operator<<64,false>:acc:rg
directive set /inPlaceNTT_DIF/inPlaceNTT_DIF:core/inPlaceNTT_DIF:core:conc/operator><64,false>:acc#1 RESOURCE_NAME COMP_LOOP-1:operator<<64,false>:acc:rg
directive set /inPlaceNTT_DIF/inPlaceNTT_DIF:core/inPlaceNTT_DIF:core:conc/operator><64,false>:acc RESOURCE_NAME COMP_LOOP-1:operator<<64,false>:acc:rg
directive set /inPlaceNTT_DIF/inPlaceNTT_DIF:core/inPlaceNTT_DIF:core:conc/COMP_LOOP-1:operator<<64,false>:acc#1 RESOURCE_NAME COMP_LOOP-1:operator<<64,false>:acc:rg
directive set /inPlaceNTT_DIF/inPlaceNTT_DIF:core/inPlaceNTT_DIF:core:conc/COMP_LOOP-1:operator<<64,false>:acc RESOURCE_NAME COMP_LOOP-1:operator<<64,false>:acc:rg
directive set /inPlaceNTT_DIF/inPlaceNTT_DIF:core/inPlaceNTT_DIF:core:conc/operator-<64,false>:acc RESOURCE_NAME COMP_LOOP-1:acc#3:rg
directive set /inPlaceNTT_DIF/inPlaceNTT_DIF:core/inPlaceNTT_DIF:core:conc/modExp_dev:while:acc RESOURCE_NAME COMP_LOOP-1:acc#3:rg
directive set /inPlaceNTT_DIF/inPlaceNTT_DIF:core/inPlaceNTT_DIF:core:conc/COMP_LOOP-1:modExp_dev#1:while:acc RESOURCE_NAME COMP_LOOP-1:acc#3:rg
directive set /inPlaceNTT_DIF/inPlaceNTT_DIF:core/inPlaceNTT_DIF:core:conc/COMP_LOOP-1:acc#3 RESOURCE_NAME COMP_LOOP-1:acc#3:rg
directive set /inPlaceNTT_DIF/inPlaceNTT_DIF:core/inPlaceNTT_DIF:core:conc/COMP_LOOP-1:acc#5 RESOURCE_NAME COMP_LOOP-1:acc#3:rg
directive set /inPlaceNTT_DIF/inPlaceNTT_DIF:core/inPlaceNTT_DIF:core:conc/COMP_LOOP-2:acc#3 RESOURCE_NAME COMP_LOOP-1:acc#3:rg
directive set /inPlaceNTT_DIF/inPlaceNTT_DIF:core/inPlaceNTT_DIF:core:conc/COMP_LOOP-3:acc#3 RESOURCE_NAME COMP_LOOP-1:acc#3:rg
directive set /inPlaceNTT_DIF/inPlaceNTT_DIF:core/inPlaceNTT_DIF:core:conc/COMP_LOOP-4:acc#3 RESOURCE_NAME COMP_LOOP-1:acc#3:rg
directive set /inPlaceNTT_DIF/inPlaceNTT_DIF:core/inPlaceNTT_DIF:core:conc/COMP_LOOP-5:acc#3 RESOURCE_NAME COMP_LOOP-1:acc#3:rg
directive set /inPlaceNTT_DIF/inPlaceNTT_DIF:core/inPlaceNTT_DIF:core:conc/COMP_LOOP-6:acc#3 RESOURCE_NAME COMP_LOOP-1:acc#3:rg
directive set /inPlaceNTT_DIF/inPlaceNTT_DIF:core/inPlaceNTT_DIF:core:conc/COMP_LOOP-7:acc#3 RESOURCE_NAME COMP_LOOP-1:acc#3:rg
directive set /inPlaceNTT_DIF/inPlaceNTT_DIF:core/inPlaceNTT_DIF:core:conc/COMP_LOOP-8:acc#3 RESOURCE_NAME COMP_LOOP-1:acc#3:rg
directive set /inPlaceNTT_DIF/inPlaceNTT_DIF:core/inPlaceNTT_DIF:core:conc/operator><64,false>#1:acc RESOURCE_NAME COMP_LOOP:acc#10:rg
directive set /inPlaceNTT_DIF/inPlaceNTT_DIF:core/inPlaceNTT_DIF:core:conc/operator<<64,false>:acc#1 RESOURCE_NAME COMP_LOOP:acc#10:rg
directive set /inPlaceNTT_DIF/inPlaceNTT_DIF:core/inPlaceNTT_DIF:core:conc/STAGE_MAIN_LOOP:acc#1 RESOURCE_NAME COMP_LOOP:acc#10:rg
directive set /inPlaceNTT_DIF/inPlaceNTT_DIF:core/inPlaceNTT_DIF:core:conc/COMP_LOOP:acc#10 RESOURCE_NAME COMP_LOOP:acc#10:rg
directive set /inPlaceNTT_DIF/inPlaceNTT_DIF:core/inPlaceNTT_DIF:core:conc/COMP_LOOP:mux1h#85 RESOURCE_NAME COMP_LOOP:mux1h#13:rg
directive set /inPlaceNTT_DIF/inPlaceNTT_DIF:core/inPlaceNTT_DIF:core:conc/COMP_LOOP:mux1h#152 RESOURCE_NAME COMP_LOOP:mux1h#13:rg
directive set /inPlaceNTT_DIF/inPlaceNTT_DIF:core/inPlaceNTT_DIF:core:conc/COMP_LOOP:mux1h#153 RESOURCE_NAME COMP_LOOP:mux1h#13:rg
directive set /inPlaceNTT_DIF/inPlaceNTT_DIF:core/inPlaceNTT_DIF:core:conc/COMP_LOOP:mux1h#154 RESOURCE_NAME COMP_LOOP:mux1h#13:rg
directive set /inPlaceNTT_DIF/inPlaceNTT_DIF:core/inPlaceNTT_DIF:core:conc/COMP_LOOP:mux1h#155 RESOURCE_NAME COMP_LOOP:mux1h#13:rg
directive set /inPlaceNTT_DIF/inPlaceNTT_DIF:core/inPlaceNTT_DIF:core:conc/COMP_LOOP:mux1h#156 RESOURCE_NAME COMP_LOOP:mux1h#13:rg
directive set /inPlaceNTT_DIF/inPlaceNTT_DIF:core/inPlaceNTT_DIF:core:conc/COMP_LOOP:mux1h#13 RESOURCE_NAME COMP_LOOP:mux1h#13:rg
directive set /inPlaceNTT_DIF/inPlaceNTT_DIF:core/inPlaceNTT_DIF:core:conc/COMP_LOOP:mux1h#15 RESOURCE_NAME COMP_LOOP:mux1h#13:rg
