directive set /peaceNTT/peaceNTT:core/core/operator-<64,false>:acc.psp.sva REGISTER_NAME operator-<64,false>:acc.psp.sva
directive set /peaceNTT/peaceNTT:core/core/COMP_LOOP:f1.sva REGISTER_NAME operator-<64,false>:acc.psp.sva
directive set /peaceNTT/peaceNTT:core/core/TWIDDLE_LOOP:i(3:0).sva REGISTER_NAME TWIDDLE_LOOP:i(3:0).sva
directive set /peaceNTT/peaceNTT:core/core/TWIDDLE_LOOP:i(3:0).sva#1 REGISTER_NAME TWIDDLE_LOOP:i(3:0).sva
directive set /peaceNTT/peaceNTT:core/core/STAGE_LOOP:c(3:0).sva REGISTER_NAME TWIDDLE_LOOP:i(3:0).sva
directive set /peaceNTT/peaceNTT:core/core/COPY_LOOP#1:i(10:0).sva(9:0) REGISTER_NAME COPY_LOOP#1:i(10:0).sva(9:0)
directive set /peaceNTT/peaceNTT:core/core/COPY_LOOP:i(10:0).sva(9:0) REGISTER_NAME COPY_LOOP#1:i(10:0).sva(9:0)
directive set /peaceNTT/peaceNTT:core/core/COMP_LOOP:f2:lshift.itm REGISTER_NAME COPY_LOOP#1:i(10:0).sva(9:0)
directive set /peaceNTT/peaceNTT:core/core/COPY_LOOP#1:i(10:0).sva#1 REGISTER_NAME COPY_LOOP#1:i(10:0).sva#1
directive set /peaceNTT/peaceNTT:core/core/COPY_LOOP:i(10:0).sva#1 REGISTER_NAME COPY_LOOP#1:i(10:0).sva#1
directive set /peaceNTT/peaceNTT:core/core/COMP_LOOP:r(9:0).sva(8:0) REGISTER_NAME COPY_LOOP#1:i(10:0).sva#1
directive set /peaceNTT/peaceNTT:core/core/operator_<66,true>:mul#1.itm REGISTER_NAME COPY_LOOP#1:i(10:0).sva#1
