directive set /peaceNTT/peaceNTT:core/peaceNTT:core:conc/operator_<66,true>:mul#10 RESOURCE_NAME operator_<66,true>:mul#10:rg
directive set /peaceNTT/peaceNTT:core/peaceNTT:core:conc/operator_<66,true>:mul#11 RESOURCE_NAME operator_<66,true>:mul#10:rg
directive set /peaceNTT/peaceNTT:core/peaceNTT:core:conc/operator_<66,true>:mul#19 RESOURCE_NAME operator_<66,true>:mul#19:rg
directive set /peaceNTT/peaceNTT:core/peaceNTT:core:conc/operator_<66,true>:mul#20 RESOURCE_NAME operator_<66,true>:mul#19:rg
directive set /peaceNTT/peaceNTT:core/peaceNTT:core:conc/operator_<66,true>:acc#32 RESOURCE_NAME TWIDDLE_LOOP:acc:rg
directive set /peaceNTT/peaceNTT:core/peaceNTT:core:conc/TWIDDLE_LOOP:acc RESOURCE_NAME TWIDDLE_LOOP:acc:rg
directive set /peaceNTT/peaceNTT:core/peaceNTT:core:conc/operator_<66,true>:acc#5 RESOURCE_NAME operator_<66,true>:acc#40:rg
directive set /peaceNTT/peaceNTT:core/peaceNTT:core:conc/operator_<66,true>:acc#40 RESOURCE_NAME operator_<66,true>:acc#40:rg
directive set /peaceNTT/peaceNTT:core/peaceNTT:core:conc/operator_<66,true>:acc#35 RESOURCE_NAME operator_<66,true>:acc#35:rg
directive set /peaceNTT/peaceNTT:core/peaceNTT:core:conc/operator_<66,true>:acc#44 RESOURCE_NAME operator_<66,true>:acc#35:rg
directive set /peaceNTT/peaceNTT:core/peaceNTT:core:conc/COPY_LOOP#1:acc#1 RESOURCE_NAME COMP_LOOP:f2:acc#1:rg
directive set /peaceNTT/peaceNTT:core/peaceNTT:core:conc/operator_<66,true>:acc#46 RESOURCE_NAME COMP_LOOP:f2:acc#1:rg
directive set /peaceNTT/peaceNTT:core/peaceNTT:core:conc/TWIDDLE_LOOP:acc#1 RESOURCE_NAME COMP_LOOP:f2:acc#1:rg
directive set /peaceNTT/peaceNTT:core/peaceNTT:core:conc/COMP_LOOP:f2:acc#1 RESOURCE_NAME COMP_LOOP:f2:acc#1:rg
directive set /peaceNTT/peaceNTT:core/peaceNTT:core:conc/operator_<66,true>:mul#27 RESOURCE_NAME MODEXP_WHILE:mul:rg
directive set /peaceNTT/peaceNTT:core/peaceNTT:core:conc/MODEXP_WHILE:mul RESOURCE_NAME MODEXP_WHILE:mul:rg
directive set /peaceNTT/peaceNTT:core/peaceNTT:core:conc/TWIDDLE_LOOP:mul RESOURCE_NAME COMP_LOOP:f2:mul:rg
directive set /peaceNTT/peaceNTT:core/peaceNTT:core:conc/COMP_LOOP:f2:mul RESOURCE_NAME COMP_LOOP:f2:mul:rg
directive set /peaceNTT/peaceNTT:core/peaceNTT:core:conc/operator_<66,true>:acc#71 RESOURCE_NAME COMP_LOOP:acc:rg
directive set /peaceNTT/peaceNTT:core/peaceNTT:core:conc/COMP_LOOP:acc RESOURCE_NAME COMP_LOOP:acc:rg
directive set /peaceNTT/peaceNTT:core/peaceNTT:core:conc/operator><64,false>:acc#1 RESOURCE_NAME operator><64,false>:acc:rg
directive set /peaceNTT/peaceNTT:core/peaceNTT:core:conc/operator><64,false>:acc RESOURCE_NAME operator><64,false>:acc:rg
directive set /peaceNTT/peaceNTT:core/peaceNTT:core:conc/operator_<66,true>:acc#38 RESOURCE_NAME STAGE_LOOP:acc:rg
directive set /peaceNTT/peaceNTT:core/peaceNTT:core:conc/STAGE_LOOP:acc RESOURCE_NAME STAGE_LOOP:acc:rg
directive set /peaceNTT/peaceNTT:core/peaceNTT:core:conc/operator_<66,true>:acc#28 RESOURCE_NAME operator_<66,true>:acc#28:rg
directive set /peaceNTT/peaceNTT:core/peaceNTT:core:conc/operator_<66,true>:acc#41 RESOURCE_NAME operator_<66,true>:acc#28:rg
