directive set /inPlaceNTT_DIT/inPlaceNTT_DIT:core/core/operator-<64,false>:acc.mut REGISTER_NAME operator-<64,false>:acc.mut
directive set /inPlaceNTT_DIT/inPlaceNTT_DIT:core/core/COMP_LOOP-1:acc#8.itm REGISTER_NAME operator-<64,false>:acc.mut
directive set /inPlaceNTT_DIT/inPlaceNTT_DIT:core/core/COMP_LOOP-2:acc#8.itm REGISTER_NAME operator-<64,false>:acc.mut
directive set /inPlaceNTT_DIT/inPlaceNTT_DIT:core/core/COMP_LOOP-1:modExp_dev#1:while:mul.itm REGISTER_NAME operator-<64,false>:acc.mut
directive set /inPlaceNTT_DIT/inPlaceNTT_DIT:core/core/COMP_LOOP-2:modExp_dev#1:while:mul.itm REGISTER_NAME operator-<64,false>:acc.mut
directive set /inPlaceNTT_DIT/inPlaceNTT_DIT:core/core/modExp_dev:while:mul.itm REGISTER_NAME operator-<64,false>:acc.mut
directive set /inPlaceNTT_DIT/inPlaceNTT_DIT:core/core/COMP_LOOP-1:mul.itm REGISTER_NAME operator-<64,false>:acc.mut
directive set /inPlaceNTT_DIT/inPlaceNTT_DIT:core/core/COMP_LOOP-2:mul.itm REGISTER_NAME operator-<64,false>:acc.mut
directive set /inPlaceNTT_DIT/inPlaceNTT_DIT:core/core/modExp_dev#1:result#1.sva REGISTER_NAME operator-<64,false>:acc.mut
directive set /inPlaceNTT_DIT/inPlaceNTT_DIT:core/core/modExp_dev#1:result.sva REGISTER_NAME operator-<64,false>:acc.mut
directive set /inPlaceNTT_DIT/inPlaceNTT_DIT:core/core/exit:COMP_LOOP-1:modExp_dev#1:while.sva REGISTER_NAME exit:COMP_LOOP-1:modExp_dev#1:while.sva
directive set /inPlaceNTT_DIT/inPlaceNTT_DIT:core/core/exit:COMP_LOOP-2:modExp_dev#1:while.sva REGISTER_NAME exit:COMP_LOOP-1:modExp_dev#1:while.sva
directive set /inPlaceNTT_DIT/inPlaceNTT_DIT:core/core/exit:modExp_dev:while.sva REGISTER_NAME exit:COMP_LOOP-1:modExp_dev#1:while.sva
directive set /inPlaceNTT_DIT/inPlaceNTT_DIT:core/core/exit:COMP_LOOP.sva REGISTER_NAME exit:COMP_LOOP-1:modExp_dev#1:while.sva
directive set /inPlaceNTT_DIT/inPlaceNTT_DIT:core/core/COMP_LOOP:acc#10.cse(10:1)#1.sva REGISTER_NAME COMP_LOOP:acc#10.cse(10:1)#1.sva
directive set /inPlaceNTT_DIT/inPlaceNTT_DIT:core/core/COMP_LOOP:acc#10.cse(10:1).sva REGISTER_NAME COMP_LOOP:acc#10.cse(10:1)#1.sva
directive set /inPlaceNTT_DIT/inPlaceNTT_DIT:core/core/modExp_dev:exp#1.sva(8:1) REGISTER_NAME COMP_LOOP:acc#10.cse(10:1)#1.sva
directive set /inPlaceNTT_DIT/inPlaceNTT_DIT:core/core/modExp_dev:exp#2.sva(8:1) REGISTER_NAME COMP_LOOP:acc#10.cse(10:1)#1.sva
directive set /inPlaceNTT_DIT/inPlaceNTT_DIT:core/core/COMP_LOOP-2:slc(COMP_LOOP:acc)(9).itm REGISTER_NAME COMP_LOOP-2:slc(COMP_LOOP:acc)(9).itm
directive set /inPlaceNTT_DIT/inPlaceNTT_DIT:core/core/operator><64,false>#1:slc(operator><64,false>#1:acc)(8).itm REGISTER_NAME COMP_LOOP-2:slc(COMP_LOOP:acc)(9).itm
directive set /inPlaceNTT_DIT/inPlaceNTT_DIT:core/core/tmp#2.lpi#4.dfm REGISTER_NAME tmp#2.lpi#4.dfm
directive set /inPlaceNTT_DIT/inPlaceNTT_DIT:core/core/tmp.lpi#4.dfm REGISTER_NAME tmp#2.lpi#4.dfm
directive set /inPlaceNTT_DIT/inPlaceNTT_DIT:core/core/modExp_dev:exp#1.sva(63:9) REGISTER_NAME modExp_dev:exp#1.sva(63:9)
directive set /inPlaceNTT_DIT/inPlaceNTT_DIT:core/core/modExp_dev:exp#2.sva(63:9) REGISTER_NAME modExp_dev:exp#1.sva(63:9)
directive set /inPlaceNTT_DIT/inPlaceNTT_DIT:core/core/modExp_dev:exp#1.sva(0) REGISTER_NAME modExp_dev:exp#1.sva(0)
directive set /inPlaceNTT_DIT/inPlaceNTT_DIT:core/core/modExp_dev:exp#2.sva(0) REGISTER_NAME modExp_dev:exp#1.sva(0)
