directive set /inPlaceNTT_DIT/inPlaceNTT_DIT:core/core/operator-<64,false>:acc.mut REGISTER_NAME operator-<64,false>:acc.mut
directive set /inPlaceNTT_DIT/inPlaceNTT_DIT:core/core/operator>><64,false>:slc(modExp:exp)(63-1).itm REGISTER_NAME operator-<64,false>:acc.mut
directive set /inPlaceNTT_DIT/inPlaceNTT_DIT:core/core/COMP_LOOP:acc#8.itm REGISTER_NAME operator-<64,false>:acc.mut
directive set /inPlaceNTT_DIT/inPlaceNTT_DIT:core/core/modExp#1:result.sva REGISTER_NAME operator-<64,false>:acc.mut
directive set /inPlaceNTT_DIT/inPlaceNTT_DIT:core/core/modExp:base#1.sva REGISTER_NAME modExp:base#1.sva
directive set /inPlaceNTT_DIT/inPlaceNTT_DIT:core/core/modExp:base.sva REGISTER_NAME modExp:base#1.sva
directive set /inPlaceNTT_DIT/inPlaceNTT_DIT:core/core/COMP_LOOP:asn#7.itm REGISTER_NAME modExp:base#1.sva
directive set /inPlaceNTT_DIT/inPlaceNTT_DIT:core/core/modulo#2:result.sva REGISTER_NAME modExp:base#1.sva
directive set /inPlaceNTT_DIT/inPlaceNTT_DIT:core/core/modulo:result.sva REGISTER_NAME modExp:base#1.sva
directive set /inPlaceNTT_DIT/inPlaceNTT_DIT:core/core/modulo#1:result.sva REGISTER_NAME modExp:base#1.sva
directive set /inPlaceNTT_DIT/inPlaceNTT_DIT:core/core/modulo#3:result.sva REGISTER_NAME modExp:base#1.sva
directive set /inPlaceNTT_DIT/inPlaceNTT_DIT:core/core/modulo#4:result.sva REGISTER_NAME modExp:base#1.sva
directive set /inPlaceNTT_DIT/inPlaceNTT_DIT:core/core/modulo#5:result.sva REGISTER_NAME modExp:base#1.sva
directive set /inPlaceNTT_DIT/inPlaceNTT_DIT:core/core/modulo#6:result.sva REGISTER_NAME modExp:base#1.sva
directive set /inPlaceNTT_DIT/inPlaceNTT_DIT:core/core/modExp:exp#1(0).sva REGISTER_NAME modExp:exp#1(0).sva
directive set /inPlaceNTT_DIT/inPlaceNTT_DIT:core/core/operator%<64,false>:slc(modExp:exp)(0)#1.itm REGISTER_NAME modExp:exp#1(0).sva
directive set /inPlaceNTT_DIT/inPlaceNTT_DIT:core/core/exit:modExp#1:while.sva REGISTER_NAME exit:modExp#1:while.sva
directive set /inPlaceNTT_DIT/inPlaceNTT_DIT:core/core/exit:modExp:while.sva REGISTER_NAME exit:modExp#1:while.sva
directive set /inPlaceNTT_DIT/inPlaceNTT_DIT:core/core/exit:COMP_LOOP.sva REGISTER_NAME exit:modExp#1:while.sva
directive set /inPlaceNTT_DIT/inPlaceNTT_DIT:core/core/modExp:exp#1(1).sva REGISTER_NAME modExp:exp#1(1).sva
directive set /inPlaceNTT_DIT/inPlaceNTT_DIT:core/core/modExp:exp#1(8).sva REGISTER_NAME modExp:exp#1(1).sva
directive set /inPlaceNTT_DIT/inPlaceNTT_DIT:core/core/COMP_LOOP:acc#5.mut REGISTER_NAME COMP_LOOP:acc#5.mut
directive set /inPlaceNTT_DIT/inPlaceNTT_DIT:core/core/factor1.sva REGISTER_NAME COMP_LOOP:acc#5.mut
directive set /inPlaceNTT_DIT/inPlaceNTT_DIT:core/core/modExp:exp.sva REGISTER_NAME COMP_LOOP:acc#5.mut
