# ----------------------------------------------------------------------------
# RTL VHDL output 'rtl.vhdl' vs Untimed C++
#
#    HLS version: 10.5c/896140 Production Release
#       HLS date: Sun Sep  6 22:45:38 PDT 2020
#  Flow Packages: HDL_Tcl 8.0a, SCVerify 10.4.1
#
#   Generated by: yl7897@newnano.poly.edu
# Generated date: Mon Sep 13 20:51:49 EDT 2021
#
# ----------------------------------------------------------------------------
# ===================================================
# DEFAULT GOAL is the help target
.PHONY: all
all: help

# ===================================================
# Directories (at the time this makefile was created)
#   MGC_HOME      /opt/mentorgraphics/Catapult_10.5c/Mgc_home
#   PROJECT_HOME  /home/yl7897/NTT_Xilinx/Catapult/inplaceNTT_DIF_precomp_md
#   SOLUTION_DIR  /home/yl7897/NTT_Xilinx/Catapult/inplaceNTT_DIF_precomp_md/Catapult/inPlaceNTT_DIF_precomp.v13
#   WORKING_DIR   /home/yl7897/NTT_Xilinx/Catapult/inplaceNTT_DIF_precomp_md/Catapult/inPlaceNTT_DIF_precomp.v13/.

# ===================================================
# VARIABLES
# 
MGC_HOME          = /opt/mentorgraphics/Catapult_10.5c/Mgc_home
export MGC_HOME

WORK_DIR  = $(CURDIR)
WORK2PROJ = ../..
WORK2SOLN = .
PROJ2WORK = ./Catapult/inPlaceNTT_DIF_precomp.v13
PROJ2SOLN = ./Catapult/inPlaceNTT_DIF_precomp.v13
export WORK_DIR
export WORK2PROJ
export WORK2SOLN
export PROJ2WORK
export PROJ2SOLN

# Variables that can be overridden from the make command line
ifeq "$(INCL_DIRS)" ""
INCL_DIRS                   = ./scverify . ../..
endif
export INCL_DIRS
ifeq "$(STAGE)" ""
STAGE                       = rtl
endif
export STAGE
ifeq "$(NETLIST_LEAF)" ""
NETLIST_LEAF                = rtl
endif
export NETLIST_LEAF
ifeq "$(SIMTOOL)" ""
SIMTOOL                     = msim
endif
export SIMTOOL
ifeq "$(NETLIST)" ""
NETLIST                     = vhdl
endif
export NETLIST
ifeq "$(RTL_NETLIST_FNAME)" ""
RTL_NETLIST_FNAME           = /home/yl7897/NTT_Xilinx/Catapult/inplaceNTT_DIF_precomp_md/Catapult/inPlaceNTT_DIF_precomp.v13/rtl.vhdl
endif
export RTL_NETLIST_FNAME
ifeq "$(INVOKE_ARGS)" ""
INVOKE_ARGS                 = 
endif
export INVOKE_ARGS
ifeq "$(FAMILY)" ""
FAMILY                      = virtex-7
endif
export FAMILY
export SCVLIBS
export MODELSIM
TOP_HDL_ENTITY           := inPlaceNTT_DIF_precomp
TOP_DU                   := scverify_top
CXX_TYPE                 := gcc
MSIM_SCRIPT              := ./Catapult/inPlaceNTT_DIF_precomp.v13/scverify_msim.tcl
TARGET                   := scverify/$(NETLIST_LEAF)_$(NETLIST)_$(SIMTOOL)
export TOP_HDL_ENTITY
export TARGET

ifeq ($(RECUR),)
ifeq ($(STAGE),mapped)
ifeq ($(RTLTOOL),)
   $(error This makefile requires specifying the RTLTOOL variable on the make command line)
endif
endif
endif
# ===================================================
# Include environment variables set by flow options
include ./ccs_env.mk

# ===================================================
# Include makefile for default commands and variables
include $(MGC_HOME)/shared/include/mkfiles/ccs_default_cmds.mk

SYNTHESIS_FLOWPKG := Vivado
SYN_FLOW          := Vivado
# ===================================================
# SOURCES
# 
# Specify list of Questa SIM libraries to create
HDL_LIB_NAMES = mgc_hls amba_lib work
# ===================================================
# Simulation libraries required by loaded Catapult libraries or gate simulation
SIMLIBS_V   += 
SIMLIBS_VHD += 
# 
# Specify list of source files - MUST be ordered properly
ifeq ($(STAGE),gate)
ifeq ($(RTLTOOL),)
# Unless overridden on make command line, GATE_*_DEP is the last item in the netlist dependency list
ifeq ($(GATE_VHDL_DEP),)
GATE_VHDL_DEP = ./rtl.vhdl/rtl.vhdl_16.vhdlts
endif
ifeq ($(GATE_VLOG_DEP),)
GATE_VLOG_DEP = 
endif
endif
VHDL_SRC += $(MGC_HOME)/pkgs/siflibs/ccs_sync_in_wait_v1.vhd/ccs_sync_in_wait_v1.vhd.vhdlts $(MGC_HOME)/pkgs/ccs_libs/interfaces/amba/amba_comps.vhd/amba_comps.vhd.vhdlts $(MGC_HOME)/pkgs/ccs_libs/interfaces/amba/ccs_axi4_master_read_core.vhd/ccs_axi4_master_read_core.vhd.vhdlts $(MGC_HOME)/pkgs/ccs_libs/interfaces/amba/ccs_axi4_master_write_core.vhd/ccs_axi4_master_write_core.vhd.vhdlts $(MGC_HOME)/pkgs/ccs_libs/interfaces/amba/ccs_axi4_master_core.vhd/ccs_axi4_master_core.vhd.vhdlts $(MGC_HOME)/pkgs/ccs_libs/interfaces/amba/ccs_axi4_master.vhd/ccs_axi4_master.vhd.vhdlts $(MGC_HOME)/pkgs/siflibs/ccs_sync_out_wait_v1.vhd/ccs_sync_out_wait_v1.vhd.vhdlts $(MGC_HOME)/pkgs/siflibs/mgc_io_sync_v2.vhd/mgc_io_sync_v2.vhd.vhdlts $(MGC_HOME)/pkgs/siflibs/ccs_in_v1.vhd/ccs_in_v1.vhd.vhdlts $(MGC_HOME)/pkgs/siflibs/mgc_out_dreg_v2.vhd/mgc_out_dreg_v2.vhd.vhdlts ../td_ccore_solutions/mult_f73ea71ea7ffbd1e4fbfa712b6b85de770f1_0/rtl.vhdl/rtl.vhdl.vhdlts ../td_ccore_solutions/modulo_sub_07838c82f6990156c8a5816c10673c6c6382_0/rtl.vhdl/rtl.vhdl_11.vhdlts ../td_ccore_solutions/modulo_add_47661927f6b7de2843654159756fee1660f9_0/rtl.vhdl/rtl.vhdl_12.vhdlts $(MGC_HOME)/pkgs/hls_pkgs/src/funcs.vhd/funcs.vhd.vhdlts $(MGC_HOME)/pkgs/siflibs/mgc_shift_comps_v5.vhd/mgc_shift_comps_v5.vhd.vhdlts $(MGC_HOME)/pkgs/siflibs/mgc_shift_l_beh_v5.vhd/mgc_shift_l_beh_v5.vhd.vhdlts $(GATE_VHDL_DEP)
VLOG_SRC +=  $(GATE_VLOG_DEP)
else
VHDL_SRC += $(MGC_HOME)/pkgs/siflibs/ccs_sync_in_wait_v1.vhd/ccs_sync_in_wait_v1.vhd.vhdlts $(MGC_HOME)/pkgs/ccs_libs/interfaces/amba/amba_comps.vhd/amba_comps.vhd.vhdlts $(MGC_HOME)/pkgs/ccs_libs/interfaces/amba/ccs_axi4_master_read_core.vhd/ccs_axi4_master_read_core.vhd.vhdlts $(MGC_HOME)/pkgs/ccs_libs/interfaces/amba/ccs_axi4_master_write_core.vhd/ccs_axi4_master_write_core.vhd.vhdlts $(MGC_HOME)/pkgs/ccs_libs/interfaces/amba/ccs_axi4_master_core.vhd/ccs_axi4_master_core.vhd.vhdlts $(MGC_HOME)/pkgs/ccs_libs/interfaces/amba/ccs_axi4_master.vhd/ccs_axi4_master.vhd.vhdlts $(MGC_HOME)/pkgs/siflibs/ccs_sync_out_wait_v1.vhd/ccs_sync_out_wait_v1.vhd.vhdlts $(MGC_HOME)/pkgs/siflibs/mgc_io_sync_v2.vhd/mgc_io_sync_v2.vhd.vhdlts $(MGC_HOME)/pkgs/siflibs/ccs_in_v1.vhd/ccs_in_v1.vhd.vhdlts $(MGC_HOME)/pkgs/siflibs/mgc_out_dreg_v2.vhd/mgc_out_dreg_v2.vhd.vhdlts ../td_ccore_solutions/mult_f73ea71ea7ffbd1e4fbfa712b6b85de770f1_0/rtl.vhdl/rtl.vhdl.vhdlts ../td_ccore_solutions/modulo_sub_07838c82f6990156c8a5816c10673c6c6382_0/rtl.vhdl/rtl.vhdl_11.vhdlts ../td_ccore_solutions/modulo_add_47661927f6b7de2843654159756fee1660f9_0/rtl.vhdl/rtl.vhdl_12.vhdlts $(MGC_HOME)/pkgs/hls_pkgs/src/funcs.vhd/funcs.vhd.vhdlts $(MGC_HOME)/pkgs/siflibs/mgc_shift_comps_v5.vhd/mgc_shift_comps_v5.vhd.vhdlts $(MGC_HOME)/pkgs/siflibs/mgc_shift_l_beh_v5.vhd/mgc_shift_l_beh_v5.vhd.vhdlts ./rtl.vhdl/rtl.vhdl_16.vhdlts
VLOG_SRC += 
endif
CXX_SRC  = ../../src/utils.cpp/utils.cpp.cxxts ../../src/ntt.cpp/ntt.cpp.cxxts ../../src/main.cpp/main.cpp.cxxts ./scverify/mc_testbench.cpp/mc_testbench.cpp.cxxts ./scverify/scverify_top.cpp/scverify_top.cpp.cxxts
# Specify RTL synthesis scripts (if any)
RTL_SCRIPT = 

# Specify hold time file name (for verifying synthesized netlists)
HLD_CONSTRAINT_FNAME = top_gate_constraints.cpp

# ===================================================
# GLOBAL OPTIONS
# 
# CXXFLAGS - global C++ options (apply to all C++ compilations) except for include file search paths
CXXFLAGS += -DCCS_SCVERIFY -DSC_INCLUDE_DYNAMIC_PROCESSES -DSC_USE_STD_STRING -DTOP_HDL_ENTITY=$(TOP_HDL_ENTITY) -DCCS_DESIGN_FUNC_inPlaceNTT_DIF_precomp -DCCS_DESIGN_TOP_$(TOP_HDL_ENTITY) -DCCS_MISMATCHED_OUTPUTS_ONLY $(F_WRAP_OPT)
# 
# If the make command line includes a definition of the special variable MC_DEFAULT_TRANSACTOR_LOG
# then define that value for all compilations as well
ifneq "$(MC_DEFAULT_TRANSACTOR_LOG)" ""
CXXFLAGS += -DMC_DEFAULT_TRANSACTOR_LOG=$(MC_DEFAULT_TRANSACTOR_LOG)
endif
# 
# CXX_INCLUDES - include file search paths
CXX_INCLUDES = ./scverify . ../..
# 
# TCL shell
TCLSH_CMD = /opt/mentorgraphics/Catapult_10.5c/Mgc_home/bin/tclsh8.5

# Pass along SCVerify_DEADLOCK_DETECTION option
ifneq "$(SCVerify_DEADLOCK_DETECTION)" "false"
CXXFLAGS += -DDEADLOCK_DETECTION
endif
# ===================================================
# PER SOURCE FILE SPECIALIZATIONS
# 
# Specify source file paths
$(TARGET)/ccs_sync_in_wait_v1.vhd.vhdlts: $(MGC_HOME)/pkgs/siflibs/ccs_sync_in_wait_v1.vhd
$(TARGET)/amba_comps.vhd.vhdlts: $(MGC_HOME)/pkgs/ccs_libs/interfaces/amba/amba_comps.vhd
$(TARGET)/ccs_axi4_master_read_core.vhd.vhdlts: $(MGC_HOME)/pkgs/ccs_libs/interfaces/amba/ccs_axi4_master_read_core.vhd
$(TARGET)/ccs_axi4_master_write_core.vhd.vhdlts: $(MGC_HOME)/pkgs/ccs_libs/interfaces/amba/ccs_axi4_master_write_core.vhd
$(TARGET)/ccs_axi4_master_core.vhd.vhdlts: $(MGC_HOME)/pkgs/ccs_libs/interfaces/amba/ccs_axi4_master_core.vhd
$(TARGET)/ccs_axi4_master.vhd.vhdlts: $(MGC_HOME)/pkgs/ccs_libs/interfaces/amba/ccs_axi4_master.vhd
$(TARGET)/ccs_sync_out_wait_v1.vhd.vhdlts: $(MGC_HOME)/pkgs/siflibs/ccs_sync_out_wait_v1.vhd
$(TARGET)/mgc_io_sync_v2.vhd.vhdlts: $(MGC_HOME)/pkgs/siflibs/mgc_io_sync_v2.vhd
$(TARGET)/ccs_in_v1.vhd.vhdlts: $(MGC_HOME)/pkgs/siflibs/ccs_in_v1.vhd
$(TARGET)/mgc_out_dreg_v2.vhd.vhdlts: $(MGC_HOME)/pkgs/siflibs/mgc_out_dreg_v2.vhd
$(TARGET)/rtl.vhdl.vhdlts: ../td_ccore_solutions/mult_f73ea71ea7ffbd1e4fbfa712b6b85de770f1_0/rtl.vhdl
$(TARGET)/rtl.vhdl_11.vhdlts: ../td_ccore_solutions/modulo_sub_07838c82f6990156c8a5816c10673c6c6382_0/rtl.vhdl
$(TARGET)/rtl.vhdl_12.vhdlts: ../td_ccore_solutions/modulo_add_47661927f6b7de2843654159756fee1660f9_0/rtl.vhdl
$(TARGET)/funcs.vhd.vhdlts: $(MGC_HOME)/pkgs/hls_pkgs/src/funcs.vhd
$(TARGET)/mgc_shift_comps_v5.vhd.vhdlts: $(MGC_HOME)/pkgs/siflibs/mgc_shift_comps_v5.vhd
$(TARGET)/mgc_shift_l_beh_v5.vhd.vhdlts: $(MGC_HOME)/pkgs/siflibs/mgc_shift_l_beh_v5.vhd
$(TARGET)/rtl.vhdl_16.vhdlts: ./rtl.vhdl
ifeq ($(STAGE),gate)
ifneq ($(GATE_VHDL_DEP),)
$(TARGET)/$(notdir $(GATE_VHDL_DEP)): $(dir $(GATE_VHDL_DEP))
endif
ifneq ($(GATE_VLOG_DEP),)
$(TARGET)/$(notdir $(GATE_VLOG_DEP)): $(dir $(GATE_VLOG_DEP))
endif
endif
$(TARGET)/utils.cpp.cxxts: ../../src/utils.cpp
$(TARGET)/ntt.cpp.cxxts: ../../src/ntt.cpp
$(TARGET)/main.cpp.cxxts: ../../src/main.cpp
$(TARGET)/mc_testbench.cpp.cxxts: ./scverify/mc_testbench.cpp
$(TARGET)/scverify_top.cpp.cxxts: ./scverify/scverify_top.cpp
# 
# Specify additional C++ options per C++ source by setting CXX_OPTS
$(TARGET)/main.cpp.cxxts: CXX_OPTS=
$(TARGET)/utils.cpp.cxxts: CXX_OPTS=
$(TARGET)/scverify_top.cpp.cxxts: CXX_OPTS=
$(TARGET)/mc_testbench.cpp.cxxts: CXX_OPTS=$(F_WRAP_OPT)
$(TARGET)/ntt.cpp.cxxts: CXX_OPTS=
# 
# Specify dependencies
$(TARGET)/utils.cpp.cxxts: .ccs_env_opts/SCVerify_USE_CCS_BLOCK.ts
$(TARGET)/ntt.cpp.cxxts: .ccs_env_opts/SCVerify_USE_CCS_BLOCK.ts
$(TARGET)/main.cpp.cxxts: .ccs_env_opts/SCVerify_USE_CCS_BLOCK.ts
$(TARGET)/mc_testbench.cpp.cxxts: .ccs_env_opts/SCVerify_USE_CCS_BLOCK.ts
$(TARGET)/scverify_top.cpp.cxxts: .ccs_env_opts/SCVerify_USE_CCS_BLOCK.ts .ccs_env_opts/SCVerify_DEADLOCK_DETECTION.ts
# 
# Specify compilation library for HDL source
$(TARGET)/funcs.vhd.vhdlts: HDL_LIB=mgc_hls
$(TARGET)/mgc_out_dreg_v2.vhd.vhdlts: HDL_LIB=mgc_hls
$(TARGET)/rtl.vhdl_16.vhdlts: HDL_LIB=work
$(TARGET)/mgc_shift_l_beh_v5.vhd.vhdlts: HDL_LIB=mgc_hls
$(TARGET)/mgc_shift_comps_v5.vhd.vhdlts: HDL_LIB=mgc_hls
$(TARGET)/ccs_axi4_master_write_core.vhd.vhdlts: HDL_LIB=amba_lib
$(TARGET)/ccs_axi4_master_read_core.vhd.vhdlts: HDL_LIB=amba_lib
$(TARGET)/mgc_io_sync_v2.vhd.vhdlts: HDL_LIB=mgc_hls
$(TARGET)/rtl.vhdl.vhdlts: HDL_LIB=work
$(TARGET)/ccs_sync_out_wait_v1.vhd.vhdlts: HDL_LIB=mgc_hls
$(TARGET)/amba_comps.vhd.vhdlts: HDL_LIB=amba_lib
$(TARGET)/rtl.vhdl_11.vhdlts: HDL_LIB=work
$(TARGET)/rtl.vhdl_12.vhdlts: HDL_LIB=work
$(TARGET)/ccs_sync_in_wait_v1.vhd.vhdlts: HDL_LIB=mgc_hls
$(TARGET)/ccs_in_v1.vhd.vhdlts: HDL_LIB=mgc_hls
$(TARGET)/ccs_axi4_master_core.vhd.vhdlts: HDL_LIB=amba_lib
$(TARGET)/ccs_axi4_master.vhd.vhdlts: HDL_LIB=amba_lib
ifeq ($(STAGE),gate)
ifneq ($(GATE_VHDL_DEP),)
$(TARGET)/$(notdir $(GATE_VHDL_DEP)): HDL_LIB=work
endif
ifneq ($(GATE_VLOG_DEP),)
$(TARGET)/$(notdir $(GATE_VLOG_DEP)): HDL_LIB=work
endif
endif
# 
# Specify additional HDL source compilation options if any
$(TARGET)/funcs.vhd.vhdlts: VHDL_F_OPTS=
$(TARGET)/mgc_out_dreg_v2.vhd.vhdlts: VHDL_F_OPTS=
$(TARGET)/rtl.vhdl_16.vhdlts: VHDL_F_OPTS=
$(TARGET)/mgc_shift_l_beh_v5.vhd.vhdlts: VHDL_F_OPTS=
$(TARGET)/mgc_shift_comps_v5.vhd.vhdlts: VHDL_F_OPTS=
$(TARGET)/ccs_axi4_master_write_core.vhd.vhdlts: VHDL_F_OPTS=
$(TARGET)/ccs_axi4_master_read_core.vhd.vhdlts: VHDL_F_OPTS=
$(TARGET)/mgc_io_sync_v2.vhd.vhdlts: VHDL_F_OPTS=
$(TARGET)/rtl.vhdl.vhdlts: VHDL_F_OPTS=
$(TARGET)/ccs_sync_out_wait_v1.vhd.vhdlts: VHDL_F_OPTS=
$(TARGET)/amba_comps.vhd.vhdlts: VHDL_F_OPTS=
$(TARGET)/rtl.vhdl_11.vhdlts: VHDL_F_OPTS=
$(TARGET)/rtl.vhdl_12.vhdlts: VHDL_F_OPTS=
$(TARGET)/ccs_sync_in_wait_v1.vhd.vhdlts: VHDL_F_OPTS=
$(TARGET)/ccs_in_v1.vhd.vhdlts: VHDL_F_OPTS=
$(TARGET)/ccs_axi4_master_core.vhd.vhdlts: VHDL_F_OPTS=
$(TARGET)/ccs_axi4_master.vhd.vhdlts: VHDL_F_OPTS=
# 
# Specify top design unit for HDL source
$(TARGET)/rtl.vhdl_16.vhdlts: DUT_E=inPlaceNTT_DIF_precomp
$(TARGET)/rtl.vhdl_11.vhdlts: DUT_E=modulo_sub
$(TARGET)/rtl.vhdl_12.vhdlts: DUT_E=modulo_add
$(TARGET)/rtl.vhdl.vhdlts: DUT_E=mult

# Specify top design unit
$(TARGET)/rtl.vhdl_16.vhdlts: VHDL_TOP=1

ifneq "$(RTLTOOL)" ""
# ===================================================
# Include makefile for RTL synthesis
include $(MGC_HOME)/shared/include/mkfiles/ccs_$(RTLTOOL).mk
else
# ===================================================
# Include makefile for simulator
include $(MGC_HOME)/shared/include/mkfiles/ccs_questasim.mk
endif

