set_property SRC_FILE_INFO {cfile:/home/ls5382/project/forPython/ctype/pythonSelfUseCtype/stockham/stockham/stockham_dit.v15/vivado_concat_v/concat_rtl.v.xv.sdc rfile:../../../../stockham/stockham_dit.v15/vivado_concat_v/concat_rtl.v.xv.sdc id:1} [current_design]
set_property SRC_FILE_INFO {cfile:/home/ls5382/project/forPython/ctype/pythonSelfUseCtype/stockham/stockham/stockham_dit.v15/vivado_concat_v/concat_rtl.v.xv.signoff.sdc rfile:../../../../stockham/stockham_dit.v15/vivado_concat_v/concat_rtl.v.xv.signoff.sdc id:2} [current_design]
set_property src_info {type:XDC file:1 line:5 export:INPUT save:INPUT read:READ} [current_design]
set_clock_uncertainty 0.0 [get_clocks {clk}]
set_property src_info {type:XDC file:2 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_clock_uncertainty 0.0 [get_clocks {clk}]
