directive set /ntt_flat/ntt_flat:core/ntt_flat:core:conc/for:acc RESOURCE_NAME INNER_LOOP:k:acc:rg
directive set /ntt_flat/ntt_flat:core/ntt_flat:core:conc/INNER_LOOP:k:acc RESOURCE_NAME INNER_LOOP:k:acc:rg
directive set /ntt_flat/ntt_flat:core/ntt_flat:core:conc/operator-<20,false>#1:acc RESOURCE_NAME STAGE_LOOP:acc:rg
directive set /ntt_flat/ntt_flat:core/ntt_flat:core:conc/STAGE_LOOP:acc RESOURCE_NAME STAGE_LOOP:acc:rg
directive set /ntt_flat/ntt_flat:core/ntt_flat:core:conc/modulo_add:qif:acc RESOURCE_NAME modulo_add:qif:acc:rg
directive set /ntt_flat/ntt_flat:core/ntt_flat:core:conc/mult:if:acc RESOURCE_NAME modulo_add:qif:acc:rg
directive set /ntt_flat/ntt_flat:core/ntt_flat:core:conc/butterFly:acc#1 RESOURCE_NAME butterFly:acc#1:rg
directive set /ntt_flat/ntt_flat:core/ntt_flat:core:conc/mult:res:acc RESOURCE_NAME butterFly:acc#1:rg
directive set /ntt_flat/ntt_flat:core/ntt_flat:core:conc/mult:if:acc#1 RESOURCE_NAME modulo_add:acc#1:rg
directive set /ntt_flat/ntt_flat:core/ntt_flat:core:conc/modulo_add:acc#1 RESOURCE_NAME modulo_add:acc#1:rg
directive set /ntt_flat/ntt_flat:core/ntt_flat:core:conc/operator<<<33,true>:lshift RESOURCE_NAME INNER_LOOP:k:lshift:rg
directive set /ntt_flat/ntt_flat:core/ntt_flat:core:conc/INNER_LOOP:k:lshift RESOURCE_NAME INNER_LOOP:k:lshift:rg
directive set /ntt_flat/ntt_flat:core/ntt_flat:core:conc/operator>><20,false>:rshift RESOURCE_NAME INNER_LOOP:g:rshift:rg
directive set /ntt_flat/ntt_flat:core/ntt_flat:core:conc/INNER_LOOP:g:rshift RESOURCE_NAME INNER_LOOP:g:rshift:rg
directive set /ntt_flat/ntt_flat:core/ntt_flat:core:conc/INNER_LOOP:idx1:mul RESOURCE_NAME INNER_LOOP:idx1:mul:rg
directive set /ntt_flat/ntt_flat:core/ntt_flat:core:conc/mult:z_:mul RESOURCE_NAME INNER_LOOP:idx1:mul:rg
directive set /ntt_flat/ntt_flat:core/ntt_flat:core:conc/mult:z:mul RESOURCE_NAME mult:t:mul:rg
directive set /ntt_flat/ntt_flat:core/ntt_flat:core:conc/mult:t:mul RESOURCE_NAME mult:t:mul:rg
