directive set /peaceNTT/peaceNTT:core/core/STAGE_LOOP:base:acc.cse.sva REGISTER_NAME STAGE_LOOP:base:acc.cse.sva
directive set /peaceNTT/peaceNTT:core/core/STAGE_LOOP:c(3:0).sva REGISTER_NAME STAGE_LOOP:base:acc.cse.sva
directive set /peaceNTT/peaceNTT:core/core/COMP_LOOP:f2:mux1h#6.itm REGISTER_NAME COMP_LOOP:f2:mux1h#6.itm
directive set /peaceNTT/peaceNTT:core/core/tmp#10(127:64).lpi#3.dfm REGISTER_NAME COMP_LOOP:f2:mux1h#6.itm
directive set /peaceNTT/peaceNTT:core/core/COMP_LOOP:f2:slc(COMP_LOOP:f2:read_mem(xt:rsc(0)(7).@)#7)(63-0).itm REGISTER_NAME COMP_LOOP:f2:slc(COMP_LOOP:f2:read_mem(xt:rsc(0)(7).@)#7)(63-0).itm
directive set /peaceNTT/peaceNTT:core/core/tmp#12(63:0).lpi#3.dfm REGISTER_NAME COMP_LOOP:f2:slc(COMP_LOOP:f2:read_mem(xt:rsc(0)(7).@)#7)(63-0).itm
directive set /peaceNTT/peaceNTT:core/core/COMP_LOOP-8:acc#1.itm REGISTER_NAME COMP_LOOP-8:acc#1.itm
directive set /peaceNTT/peaceNTT:core/core/COMP_LOOP:f2:mux1h.itm REGISTER_NAME COMP_LOOP-8:acc#1.itm
directive set /peaceNTT/peaceNTT:core/core/COMP_LOOP-1:acc#1.itm REGISTER_NAME COMP_LOOP-1:acc#1.itm
directive set /peaceNTT/peaceNTT:core/core/COMP_LOOP:f2:mux#2.itm REGISTER_NAME COMP_LOOP-1:acc#1.itm
directive set /peaceNTT/peaceNTT:core/core/COMP_LOOP-2:acc#1.itm REGISTER_NAME COMP_LOOP-2:acc#1.itm
directive set /peaceNTT/peaceNTT:core/core/COMP_LOOP:f2:mux#4.itm REGISTER_NAME COMP_LOOP-2:acc#1.itm
directive set /peaceNTT/peaceNTT:core/core/COMP_LOOP:acc#6.itm REGISTER_NAME COMP_LOOP:acc#6.itm
directive set /peaceNTT/peaceNTT:core/core/COMP_LOOP:acc#9.itm REGISTER_NAME COMP_LOOP:acc#6.itm
directive set /peaceNTT/peaceNTT:core/core/COMP_LOOP-7:acc#1.itm REGISTER_NAME COMP_LOOP:acc#6.itm
directive set /peaceNTT/peaceNTT:core/core/COMP_LOOP:f2:slc(COMP_LOOP:f2:read_mem(xt:rsc(0)(0).@))(63-0).itm REGISTER_NAME COMP_LOOP:acc#6.itm
directive set /peaceNTT/peaceNTT:core/core/COMP_LOOP-3:acc#1.itm REGISTER_NAME COMP_LOOP-3:acc#1.itm
directive set /peaceNTT/peaceNTT:core/core/COMP_LOOP:f2:mux.itm REGISTER_NAME COMP_LOOP-3:acc#1.itm
directive set /peaceNTT/peaceNTT:core/core/COMP_LOOP:acc#7.itm REGISTER_NAME COMP_LOOP:acc#7.itm
directive set /peaceNTT/peaceNTT:core/core/COMP_LOOP:acc#8.itm REGISTER_NAME COMP_LOOP:acc#7.itm
directive set /peaceNTT/peaceNTT:core/core/COMP_LOOP-6:acc#1.itm REGISTER_NAME COMP_LOOP:acc#7.itm
directive set /peaceNTT/peaceNTT:core/core/COMP_LOOP:f2:slc(COMP_LOOP:f2:read_mem(xt:rsc(0)(1).@)#1)(63-0).itm REGISTER_NAME COMP_LOOP:acc#7.itm
directive set /peaceNTT/peaceNTT:core/core/COMP_LOOP-4:acc#1.itm REGISTER_NAME COMP_LOOP-4:acc#1.itm
directive set /peaceNTT/peaceNTT:core/core/COMP_LOOP:f2:mux1h#2.itm REGISTER_NAME COMP_LOOP-4:acc#1.itm
directive set /peaceNTT/peaceNTT:core/core/COMP_LOOP-5:acc#1.itm REGISTER_NAME COMP_LOOP-5:acc#1.itm
directive set /peaceNTT/peaceNTT:core/core/COMP_LOOP:f2:mux1h#4.itm REGISTER_NAME COMP_LOOP-5:acc#1.itm
directive set /peaceNTT/peaceNTT:core/core/COMP_LOOP:acc#10.itm REGISTER_NAME COMP_LOOP:acc#10.itm
directive set /peaceNTT/peaceNTT:core/core/COMP_LOOP:acc#11.mut REGISTER_NAME COMP_LOOP:acc#10.itm
directive set /peaceNTT/peaceNTT:core/core/COMP_LOOP:acc#12.mut REGISTER_NAME COMP_LOOP:acc#10.itm
directive set /peaceNTT/peaceNTT:core/core/COMP_LOOP:acc#5.itm REGISTER_NAME COMP_LOOP:acc#10.itm
directive set /peaceNTT/peaceNTT:core/core/COMP_LOOP:f2:read_mem(twiddle:rsc(0)(0).@).ncse.sva REGISTER_NAME COMP_LOOP:acc#10.itm
directive set /peaceNTT/peaceNTT:core/core/COPY_LOOP#1:i(12:3).sva(8:0) REGISTER_NAME COPY_LOOP#1:i(12:3).sva(8:0)
directive set /peaceNTT/peaceNTT:core/core/COPY_LOOP:i(12:3).sva(8:0) REGISTER_NAME COPY_LOOP#1:i(12:3).sva(8:0)
directive set /peaceNTT/peaceNTT:core/core/COMP_LOOP:slc(COMP_LOOP-8:acc#4)(11-3).psp.sva REGISTER_NAME COPY_LOOP#1:i(12:3).sva(8:0)
directive set /peaceNTT/peaceNTT:core/core/COPY_LOOP#1:i(12:3).sva#1 REGISTER_NAME COPY_LOOP#1:i(12:3).sva#1
directive set /peaceNTT/peaceNTT:core/core/COPY_LOOP:i(12:3).sva#1 REGISTER_NAME COPY_LOOP#1:i(12:3).sva#1
