directive set /peaceNTT/peaceNTT:core/core/COMP_LOOP:r(10:2).sva REGISTER_NAME COMP_LOOP:r(10:2).sva
directive set /peaceNTT/peaceNTT:core/core/COPY_LOOP#1:i(12:3).sva(8:0) REGISTER_NAME COMP_LOOP:r(10:2).sva
directive set /peaceNTT/peaceNTT:core/core/STAGE_LOOP:base:acc.cse.sva REGISTER_NAME STAGE_LOOP:base:acc.cse.sva
directive set /peaceNTT/peaceNTT:core/core/STAGE_LOOP:c(3:0).sva REGISTER_NAME STAGE_LOOP:base:acc.cse.sva
directive set /peaceNTT/peaceNTT:core/core/COMP_LOOP-4:acc#1.itm REGISTER_NAME COMP_LOOP-4:acc#1.itm
directive set /peaceNTT/peaceNTT:core/core/COMP_LOOP:f2:mux#4.itm REGISTER_NAME COMP_LOOP-4:acc#1.itm
directive set /peaceNTT/peaceNTT:core/core/tmp#15.sva#1 REGISTER_NAME COMP_LOOP-4:acc#1.itm
directive set /peaceNTT/peaceNTT:core/core/COMP_LOOP-1:acc#1.itm REGISTER_NAME COMP_LOOP-1:acc#1.itm
directive set /peaceNTT/peaceNTT:core/core/COMP_LOOP:f2:mux#1.itm REGISTER_NAME COMP_LOOP-1:acc#1.itm
directive set /peaceNTT/peaceNTT:core/core/COMP_LOOP:f2:mux1h#1.itm REGISTER_NAME COMP_LOOP-1:acc#1.itm
directive set /peaceNTT/peaceNTT:core/core/COMP_LOOP:f2:mux1h#2.itm REGISTER_NAME COMP_LOOP-1:acc#1.itm
directive set /peaceNTT/peaceNTT:core/core/COMP_LOOP:f2:mux1h.itm REGISTER_NAME COMP_LOOP-1:acc#1.itm
directive set /peaceNTT/peaceNTT:core/core/COMP_LOOP:acc#5.mut REGISTER_NAME COMP_LOOP:acc#5.mut
directive set /peaceNTT/peaceNTT:core/core/COMP_LOOP:acc#6.mut REGISTER_NAME COMP_LOOP:acc#5.mut
directive set /peaceNTT/peaceNTT:core/core/COMP_LOOP:acc#7.mut REGISTER_NAME COMP_LOOP:acc#5.mut
directive set /peaceNTT/peaceNTT:core/core/COMP_LOOP:acc#8.mut REGISTER_NAME COMP_LOOP:acc#5.mut
directive set /peaceNTT/peaceNTT:core/core/COMP_LOOP:f2:mux.itm REGISTER_NAME COMP_LOOP:acc#5.mut
directive set /peaceNTT/peaceNTT:core/core/COMP_LOOP-2:acc#1.itm REGISTER_NAME COMP_LOOP-2:acc#1.itm
directive set /peaceNTT/peaceNTT:core/core/COMP_LOOP:f2:mux#2.itm REGISTER_NAME COMP_LOOP-2:acc#1.itm
directive set /peaceNTT/peaceNTT:core/core/COMP_LOOP-3:acc#1.itm REGISTER_NAME COMP_LOOP-3:acc#1.itm
directive set /peaceNTT/peaceNTT:core/core/COMP_LOOP:f2:mux#3.itm REGISTER_NAME COMP_LOOP-3:acc#1.itm
directive set /peaceNTT/peaceNTT:core/core/COPY_LOOP#1:i(12:3).sva#1 REGISTER_NAME COPY_LOOP#1:i(12:3).sva#1
directive set /peaceNTT/peaceNTT:core/core/COPY_LOOP:i(12:2).sva(9:0) REGISTER_NAME COPY_LOOP#1:i(12:3).sva#1
directive set /peaceNTT/peaceNTT:core/core/COMP_LOOP:slc(COMP_LOOP-4:acc#4)(11-2).psp.sva REGISTER_NAME COPY_LOOP#1:i(12:3).sva#1
