directive set /ntt_flat/ntt_flat:core/ntt_flat:core:conc/for:acc RESOURCE_NAME INNER_LOOP:k:acc:rg
directive set /ntt_flat/ntt_flat:core/ntt_flat:core:conc/INNER_LOOP:k:acc RESOURCE_NAME INNER_LOOP:k:acc:rg
directive set /ntt_flat/ntt_flat:core/ntt_flat:core:conc/mult:res:acc RESOURCE_NAME modulo_add:qif:acc:rg
directive set /ntt_flat/ntt_flat:core/ntt_flat:core:conc/modulo_add:qif:acc RESOURCE_NAME modulo_add:qif:acc:rg
directive set /ntt_flat/ntt_flat:core/ntt_flat:core:conc/operator<<<33,true>:lshift RESOURCE_NAME INNER_LOOP:k:lshift:rg
directive set /ntt_flat/ntt_flat:core/ntt_flat:core:conc/INNER_LOOP:k:lshift RESOURCE_NAME INNER_LOOP:k:lshift:rg
directive set /ntt_flat/ntt_flat:core/ntt_flat:core:conc/operator>><20,false>:rshift RESOURCE_NAME INNER_LOOP:g:rshift:rg
directive set /ntt_flat/ntt_flat:core/ntt_flat:core:conc/INNER_LOOP:g:rshift RESOURCE_NAME INNER_LOOP:g:rshift:rg
directive set /ntt_flat/ntt_flat:core/ntt_flat:core:conc/INNER_LOOP:idx1:mul RESOURCE_NAME INNER_LOOP:idx1:mul:rg
directive set /ntt_flat/ntt_flat:core/ntt_flat:core:conc/INNER_LOOP:tf:mul RESOURCE_NAME INNER_LOOP:idx1:mul:rg
