directive set /DIT_RELOOP/DIT_RELOOP:core/core/IDX_LOOP-1:lshift.idiv.sva REGISTER_NAME IDX_LOOP-1:lshift.idiv.sva
directive set /DIT_RELOOP/DIT_RELOOP:core/core/IDX_LOOP-2:lshift.idiv.sva REGISTER_NAME IDX_LOOP-1:lshift.idiv.sva
directive set /DIT_RELOOP/DIT_RELOOP:core/core/IDX_LOOP-3:lshift.idiv.sva REGISTER_NAME IDX_LOOP-1:lshift.idiv.sva
directive set /DIT_RELOOP/DIT_RELOOP:core/core/IDX_LOOP-4:lshift.idiv.sva REGISTER_NAME IDX_LOOP-1:lshift.idiv.sva
directive set /DIT_RELOOP/DIT_RELOOP:core/core/IDX_LOOP:f1:IDX_LOOP:f1:nor.itm REGISTER_NAME IDX_LOOP:f1:IDX_LOOP:f1:nor.itm
directive set /DIT_RELOOP/DIT_RELOOP:core/core/IDX_LOOP:f1:and#9.itm REGISTER_NAME IDX_LOOP:f1:IDX_LOOP:f1:nor.itm
directive set /DIT_RELOOP/DIT_RELOOP:core/core/tmp#1.lpi#4.dfm#2 REGISTER_NAME tmp#1.lpi#4.dfm#2
directive set /DIT_RELOOP/DIT_RELOOP:core/core/tmp#3.lpi#4.dfm#2 REGISTER_NAME tmp#1.lpi#4.dfm#2
directive set /DIT_RELOOP/DIT_RELOOP:core/core/tmp#5.lpi#4.dfm#2 REGISTER_NAME tmp#1.lpi#4.dfm#2
directive set /DIT_RELOOP/DIT_RELOOP:core/core/tmp#7.lpi#4.dfm#2 REGISTER_NAME tmp#1.lpi#4.dfm#2
directive set /DIT_RELOOP/DIT_RELOOP:core/core/tmp#3.sva#3 REGISTER_NAME tmp#1.lpi#4.dfm#2
directive set /DIT_RELOOP/DIT_RELOOP:core/core/tmp#7.sva#3 REGISTER_NAME tmp#1.lpi#4.dfm#2
directive set /DIT_RELOOP/DIT_RELOOP:core/core/tmp#5.sva#2 REGISTER_NAME tmp#1.lpi#4.dfm#2
directive set /DIT_RELOOP/DIT_RELOOP:core/core/IDX_LOOP-1:mul.mut REGISTER_NAME IDX_LOOP-1:mul.mut
directive set /DIT_RELOOP/DIT_RELOOP:core/core/IDX_LOOP-2:mul.mut REGISTER_NAME IDX_LOOP-1:mul.mut
directive set /DIT_RELOOP/DIT_RELOOP:core/core/IDX_LOOP-3:mul.mut REGISTER_NAME IDX_LOOP-1:mul.mut
directive set /DIT_RELOOP/DIT_RELOOP:core/core/IDX_LOOP-4:mul.mut REGISTER_NAME IDX_LOOP-1:mul.mut
directive set /DIT_RELOOP/DIT_RELOOP:core/core/tmp#2.lpi#4.dfm REGISTER_NAME tmp#2.lpi#4.dfm
directive set /DIT_RELOOP/DIT_RELOOP:core/core/tmp#4.lpi#4.dfm REGISTER_NAME tmp#2.lpi#4.dfm
directive set /DIT_RELOOP/DIT_RELOOP:core/core/tmp#6.lpi#4.dfm REGISTER_NAME tmp#2.lpi#4.dfm
directive set /DIT_RELOOP/DIT_RELOOP:core/core/tmp.lpi#4.dfm REGISTER_NAME tmp#2.lpi#4.dfm
directive set /DIT_RELOOP/DIT_RELOOP:core/core/IDX_LOOP:modulo_dev(return)#1.sva REGISTER_NAME IDX_LOOP:modulo_dev(return)#1.sva
directive set /DIT_RELOOP/DIT_RELOOP:core/core/IDX_LOOP:modulo_dev(return)#5.sva REGISTER_NAME IDX_LOOP:modulo_dev(return)#1.sva
directive set /DIT_RELOOP/DIT_RELOOP:core/core/IDX_LOOP:modulo_dev(return)#6.sva REGISTER_NAME IDX_LOOP:modulo_dev(return)#1.sva
directive set /DIT_RELOOP/DIT_RELOOP:core/core/IDX_LOOP:modulo_dev(return)#7.sva REGISTER_NAME IDX_LOOP:modulo_dev(return)#1.sva
directive set /DIT_RELOOP/DIT_RELOOP:core/core/IDX_LOOP:mux1h#30.itm REGISTER_NAME IDX_LOOP:modulo_dev(return)#1.sva
directive set /DIT_RELOOP/DIT_RELOOP:core/core/tmp#3.sva#5 REGISTER_NAME IDX_LOOP:modulo_dev(return)#1.sva
directive set /DIT_RELOOP/DIT_RELOOP:core/core/tmp#7.sva#5 REGISTER_NAME IDX_LOOP:modulo_dev(return)#1.sva
directive set /DIT_RELOOP/DIT_RELOOP:core/core/tmp#5.sva#4 REGISTER_NAME IDX_LOOP:modulo_dev(return)#1.sva
