directive set /inPlaceNTT_DIF/inPlaceNTT_DIF:core/core/COMP_LOOP-2:tmp:lshift.ncse.sva REGISTER_NAME COMP_LOOP-2:tmp:lshift.ncse.sva
directive set /inPlaceNTT_DIF/inPlaceNTT_DIF:core/core/COMP_LOOP-4:tmp:mul.idiv.sva REGISTER_NAME COMP_LOOP-2:tmp:lshift.ncse.sva
directive set /inPlaceNTT_DIF/inPlaceNTT_DIF:core/core/COMP_LOOP-1:acc#8.itm REGISTER_NAME COMP_LOOP-1:acc#8.itm
directive set /inPlaceNTT_DIF/inPlaceNTT_DIF:core/core/COMP_LOOP-2:acc#8.itm REGISTER_NAME COMP_LOOP-1:acc#8.itm
directive set /inPlaceNTT_DIF/inPlaceNTT_DIF:core/core/COMP_LOOP-3:acc#8.itm REGISTER_NAME COMP_LOOP-1:acc#8.itm
directive set /inPlaceNTT_DIF/inPlaceNTT_DIF:core/core/COMP_LOOP-4:acc#8.itm REGISTER_NAME COMP_LOOP-1:acc#8.itm
directive set /inPlaceNTT_DIF/inPlaceNTT_DIF:core/core/COMP_LOOP:modulo(return)#10.sva REGISTER_NAME COMP_LOOP-1:acc#8.itm
directive set /inPlaceNTT_DIF/inPlaceNTT_DIF:core/core/COMP_LOOP:modulo(return)#11.sva REGISTER_NAME COMP_LOOP-1:acc#8.itm
directive set /inPlaceNTT_DIF/inPlaceNTT_DIF:core/core/COMP_LOOP:modulo(return)#2.sva REGISTER_NAME COMP_LOOP-1:acc#8.itm
directive set /inPlaceNTT_DIF/inPlaceNTT_DIF:core/core/COMP_LOOP:modulo(return)#9.sva REGISTER_NAME COMP_LOOP-1:acc#8.itm
directive set /inPlaceNTT_DIF/inPlaceNTT_DIF:core/core/COMP_LOOP-1:mul.itm REGISTER_NAME COMP_LOOP-1:acc#8.itm
directive set /inPlaceNTT_DIF/inPlaceNTT_DIF:core/core/COMP_LOOP-2:mul.itm REGISTER_NAME COMP_LOOP-1:acc#8.itm
directive set /inPlaceNTT_DIF/inPlaceNTT_DIF:core/core/COMP_LOOP-3:mul.itm REGISTER_NAME COMP_LOOP-1:acc#8.itm
directive set /inPlaceNTT_DIF/inPlaceNTT_DIF:core/core/COMP_LOOP-4:mul.itm REGISTER_NAME COMP_LOOP-1:acc#8.itm
directive set /inPlaceNTT_DIF/inPlaceNTT_DIF:core/core/tmp#1.lpi#4.dfm REGISTER_NAME COMP_LOOP-1:acc#8.itm
directive set /inPlaceNTT_DIF/inPlaceNTT_DIF:core/core/tmp#11.sva#3 REGISTER_NAME COMP_LOOP-1:acc#8.itm
directive set /inPlaceNTT_DIF/inPlaceNTT_DIF:core/core/tmp#2.lpi#4.dfm REGISTER_NAME COMP_LOOP-1:acc#8.itm
directive set /inPlaceNTT_DIF/inPlaceNTT_DIF:core/core/tmp#4.lpi#4.dfm REGISTER_NAME COMP_LOOP-1:acc#8.itm
directive set /inPlaceNTT_DIF/inPlaceNTT_DIF:core/core/tmp#6.lpi#4.dfm REGISTER_NAME COMP_LOOP-1:acc#8.itm
directive set /inPlaceNTT_DIF/inPlaceNTT_DIF:core/core/COMP_LOOP:tmp:mux1h#1.itm REGISTER_NAME COMP_LOOP:tmp:mux1h#1.itm
directive set /inPlaceNTT_DIF/inPlaceNTT_DIF:core/core/tmp#11.sva#1 REGISTER_NAME COMP_LOOP:tmp:mux1h#1.itm
