directive set /stockham_DIT/stockham_DIT:core/stockham_DIT:core:conc/OUTER_LOOP:acc#2 RESOURCE_NAME INNER_LOOP:acc#6:rg
directive set /stockham_DIT/stockham_DIT:core/stockham_DIT:core:conc/OUTER_LOOP:m:acc RESOURCE_NAME INNER_LOOP:acc#6:rg
directive set /stockham_DIT/stockham_DIT:core/stockham_DIT:core:conc/OUTER_LOOP:acc#1 RESOURCE_NAME INNER_LOOP:acc#6:rg
directive set /stockham_DIT/stockham_DIT:core/stockham_DIT:core:conc/INNER_LOOP:acc#6 RESOURCE_NAME INNER_LOOP:acc#6:rg
directive set /stockham_DIT/stockham_DIT:core/stockham_DIT:core:conc/OUTER_LOOP:m:lshift RESOURCE_NAME INNER_LOOP:w:lshift:rg
directive set /stockham_DIT/stockham_DIT:core/stockham_DIT:core:conc/INNER_LOOP:w:lshift RESOURCE_NAME INNER_LOOP:w:lshift:rg
directive set /stockham_DIT/stockham_DIT:core/stockham_DIT:core:conc/INNER_LOOP:mul RESOURCE_NAME INNER_LOOP:b:mul:rg
directive set /stockham_DIT/stockham_DIT:core/stockham_DIT:core:conc/INNER_LOOP:b:mul RESOURCE_NAME INNER_LOOP:b:mul:rg
directive set /stockham_DIT/stockham_DIT:core/stockham_DIT:core:conc/INNER_LOOP:acc#5 RESOURCE_NAME INNER_LOOP:acc#5:rg
directive set /stockham_DIT/stockham_DIT:core/stockham_DIT:core:conc/modulo_dev:qelse:acc RESOURCE_NAME INNER_LOOP:acc#5:rg
