directive set /peaseNTT/peaseNTT:core/core/INNER_LOOP1.stage_0.2 REGISTER_NAME INNER_LOOP1.stage_0.2
directive set /peaseNTT/peaseNTT:core/core/INNER_LOOP3.stage_0.2 REGISTER_NAME INNER_LOOP1.stage_0.2
directive set /peaseNTT/peaseNTT:core/core/INNER_LOOP1.stage_0.3 REGISTER_NAME INNER_LOOP1.stage_0.3
directive set /peaseNTT/peaseNTT:core/core/INNER_LOOP3.stage_0.3 REGISTER_NAME INNER_LOOP1.stage_0.3
directive set /peaseNTT/peaseNTT:core/core/INNER_LOOP1.stage_0.4 REGISTER_NAME INNER_LOOP1.stage_0.4
directive set /peaseNTT/peaseNTT:core/core/INNER_LOOP3.stage_0.4 REGISTER_NAME INNER_LOOP1.stage_0.4
directive set /peaseNTT/peaseNTT:core/core/INNER_LOOP1.stage_0.5 REGISTER_NAME INNER_LOOP1.stage_0.5
directive set /peaseNTT/peaseNTT:core/core/INNER_LOOP3.stage_0.5 REGISTER_NAME INNER_LOOP1.stage_0.5
directive set /peaseNTT/peaseNTT:core/core/INNER_LOOP1.stage_0.6 REGISTER_NAME INNER_LOOP1.stage_0.6
directive set /peaseNTT/peaseNTT:core/core/INNER_LOOP3.stage_0.6 REGISTER_NAME INNER_LOOP1.stage_0.6
directive set /peaseNTT/peaseNTT:core/core/INNER_LOOP1.stage_0.7 REGISTER_NAME INNER_LOOP1.stage_0.7
directive set /peaseNTT/peaseNTT:core/core/INNER_LOOP3.stage_0.7 REGISTER_NAME INNER_LOOP1.stage_0.7
directive set /peaseNTT/peaseNTT:core/core/INNER_LOOP1.stage_0.8 REGISTER_NAME INNER_LOOP1.stage_0.8
directive set /peaseNTT/peaseNTT:core/core/INNER_LOOP3.stage_0.8 REGISTER_NAME INNER_LOOP1.stage_0.8
directive set /peaseNTT/peaseNTT:core/core/INNER_LOOP1.stage_0.9 REGISTER_NAME INNER_LOOP1.stage_0.9
directive set /peaseNTT/peaseNTT:core/core/INNER_LOOP3.stage_0.9 REGISTER_NAME INNER_LOOP1.stage_0.9
directive set /peaseNTT/peaseNTT:core/core/INNER_LOOP1.stage_0.10 REGISTER_NAME INNER_LOOP1.stage_0.10
directive set /peaseNTT/peaseNTT:core/core/INNER_LOOP3.stage_0.10 REGISTER_NAME INNER_LOOP1.stage_0.10
