directive set /inPlaceNTT_DIT_precomp/inPlaceNTT_DIT_precomp:core/core/COMP_LOOP:twiddle_f#1.sva REGISTER_NAME COMP_LOOP:twiddle_f#1.sva
directive set /inPlaceNTT_DIT_precomp/inPlaceNTT_DIT_precomp:core/core/COMP_LOOP:twiddle_f.sva REGISTER_NAME COMP_LOOP:twiddle_f#1.sva
directive set /inPlaceNTT_DIT_precomp/inPlaceNTT_DIT_precomp:core/core/COMP_LOOP:twiddle_help#1.sva REGISTER_NAME COMP_LOOP:twiddle_help#1.sva
directive set /inPlaceNTT_DIT_precomp/inPlaceNTT_DIT_precomp:core/core/COMP_LOOP:twiddle_help.sva REGISTER_NAME COMP_LOOP:twiddle_help#1.sva
directive set /inPlaceNTT_DIT_precomp/inPlaceNTT_DIT_precomp:core/core/COMP_LOOP-1:VEC_LOOP:slc(VEC_LOOP:acc)(22).itm REGISTER_NAME COMP_LOOP-1:VEC_LOOP:slc(VEC_LOOP:acc)(22).itm
directive set /inPlaceNTT_DIT_precomp/inPlaceNTT_DIT_precomp:core/core/run_ac_sync_tmp_dobj.sva REGISTER_NAME COMP_LOOP-1:VEC_LOOP:slc(VEC_LOOP:acc)(22).itm
directive set /inPlaceNTT_DIT_precomp/inPlaceNTT_DIT_precomp:core/core/VEC_LOOP:acc#10.cse#1.sva REGISTER_NAME VEC_LOOP:acc#10.cse#1.sva
directive set /inPlaceNTT_DIT_precomp/inPlaceNTT_DIT_precomp:core/core/VEC_LOOP:acc#10.cse.sva REGISTER_NAME VEC_LOOP:acc#10.cse#1.sva
directive set /inPlaceNTT_DIT_precomp/inPlaceNTT_DIT_precomp:core/core/factor1#1.sva REGISTER_NAME factor1#1.sva
directive set /inPlaceNTT_DIT_precomp/inPlaceNTT_DIT_precomp:core/core/factor1.sva REGISTER_NAME factor1#1.sva
directive set /inPlaceNTT_DIT_precomp/inPlaceNTT_DIT_precomp:core/core/COMP_LOOP-1:mult:z:mul.itm REGISTER_NAME COMP_LOOP-1:mult:z:mul.itm
directive set /inPlaceNTT_DIT_precomp/inPlaceNTT_DIT_precomp:core/core/COMP_LOOP-2:mult:z:mul.itm REGISTER_NAME COMP_LOOP-1:mult:z:mul.itm
directive set /inPlaceNTT_DIT_precomp/inPlaceNTT_DIT_precomp:core/core/VEC_LOOP:modulo_sub(return)#1.sva REGISTER_NAME COMP_LOOP-1:mult:z:mul.itm
directive set /inPlaceNTT_DIT_precomp/inPlaceNTT_DIT_precomp:core/core/VEC_LOOP:modulo_sub(return).sva REGISTER_NAME COMP_LOOP-1:mult:z:mul.itm
directive set /inPlaceNTT_DIT_precomp/inPlaceNTT_DIT_precomp:core/core/mult:x#1.sva REGISTER_NAME COMP_LOOP-1:mult:z:mul.itm
directive set /inPlaceNTT_DIT_precomp/inPlaceNTT_DIT_precomp:core/core/mult:x.sva REGISTER_NAME COMP_LOOP-1:mult:z:mul.itm
directive set /inPlaceNTT_DIT_precomp/inPlaceNTT_DIT_precomp:core/core/VEC_LOOP:acc#1.cse.sva REGISTER_NAME VEC_LOOP:acc#1.cse.sva
directive set /inPlaceNTT_DIT_precomp/inPlaceNTT_DIT_precomp:core/core/VEC_LOOP:j(10:0).sva(9:0) REGISTER_NAME VEC_LOOP:acc#1.cse.sva
directive set /inPlaceNTT_DIT_precomp/inPlaceNTT_DIT_precomp:core/core/VEC_LOOP:acc.psp.sva REGISTER_NAME VEC_LOOP:acc#1.cse.sva
