directive set /inPlaceNTT_DIF/inPlaceNTT_DIF:core/core/STAGE_MAIN_LOOP:acc#1.psp.sva REGISTER_NAME STAGE_MAIN_LOOP:acc#1.psp.sva
directive set /inPlaceNTT_DIF/inPlaceNTT_DIF:core/core/STAGE_MAIN_LOOP:i(3:0).sva REGISTER_NAME STAGE_MAIN_LOOP:acc#1.psp.sva
directive set /inPlaceNTT_DIF/inPlaceNTT_DIF:core/core/COMP_LOOP:acc.psp.sva REGISTER_NAME COMP_LOOP:acc.psp.sva
directive set /inPlaceNTT_DIF/inPlaceNTT_DIF:core/core/modExp_dev:exp#1.sva(8:3) REGISTER_NAME COMP_LOOP:acc.psp.sva
directive set /inPlaceNTT_DIF/inPlaceNTT_DIF:core/core/modExp_dev:exp#2.sva(8:3) REGISTER_NAME COMP_LOOP:acc.psp.sva
directive set /inPlaceNTT_DIF/inPlaceNTT_DIF:core/core/modExp_dev:exp#3.sva(8:3) REGISTER_NAME COMP_LOOP:acc.psp.sva
directive set /inPlaceNTT_DIF/inPlaceNTT_DIF:core/core/modExp_dev:exp#4.sva(8:3) REGISTER_NAME COMP_LOOP:acc.psp.sva
directive set /inPlaceNTT_DIF/inPlaceNTT_DIF:core/core/modExp_dev:exp#5.sva(8:3) REGISTER_NAME COMP_LOOP:acc.psp.sva
directive set /inPlaceNTT_DIF/inPlaceNTT_DIF:core/core/modExp_dev:exp#6.sva(8:3) REGISTER_NAME COMP_LOOP:acc.psp.sva
directive set /inPlaceNTT_DIF/inPlaceNTT_DIF:core/core/modExp_dev:exp#7.sva(8:3) REGISTER_NAME COMP_LOOP:acc.psp.sva
directive set /inPlaceNTT_DIF/inPlaceNTT_DIF:core/core/modExp_dev:exp#8.sva(8:3) REGISTER_NAME COMP_LOOP:acc.psp.sva
directive set /inPlaceNTT_DIF/inPlaceNTT_DIF:core/core/COMP_LOOP:COMP_LOOP:and#11.itm REGISTER_NAME COMP_LOOP:COMP_LOOP:and#11.itm
directive set /inPlaceNTT_DIF/inPlaceNTT_DIF:core/core/COMP_LOOP:COMP_LOOP:and#65.itm REGISTER_NAME COMP_LOOP:COMP_LOOP:and#11.itm
directive set /inPlaceNTT_DIF/inPlaceNTT_DIF:core/core/tmp#1.lpi#4.dfm REGISTER_NAME tmp#1.lpi#4.dfm
directive set /inPlaceNTT_DIF/inPlaceNTT_DIF:core/core/tmp#11.lpi#4.dfm REGISTER_NAME tmp#1.lpi#4.dfm
directive set /inPlaceNTT_DIF/inPlaceNTT_DIF:core/core/tmp#13.lpi#4.dfm REGISTER_NAME tmp#1.lpi#4.dfm
directive set /inPlaceNTT_DIF/inPlaceNTT_DIF:core/core/tmp#15.lpi#4.dfm REGISTER_NAME tmp#1.lpi#4.dfm
directive set /inPlaceNTT_DIF/inPlaceNTT_DIF:core/core/tmp#3.lpi#4.dfm REGISTER_NAME tmp#1.lpi#4.dfm
directive set /inPlaceNTT_DIF/inPlaceNTT_DIF:core/core/tmp#5.lpi#4.dfm REGISTER_NAME tmp#1.lpi#4.dfm
directive set /inPlaceNTT_DIF/inPlaceNTT_DIF:core/core/tmp#7.lpi#4.dfm REGISTER_NAME tmp#1.lpi#4.dfm
directive set /inPlaceNTT_DIF/inPlaceNTT_DIF:core/core/tmp#9.lpi#4.dfm REGISTER_NAME tmp#1.lpi#4.dfm
directive set /inPlaceNTT_DIF/inPlaceNTT_DIF:core/core/COMP_LOOP-1:modExp_dev#1:while:mul.mut REGISTER_NAME COMP_LOOP-1:modExp_dev#1:while:mul.mut
directive set /inPlaceNTT_DIF/inPlaceNTT_DIF:core/core/COMP_LOOP-2:modExp_dev#1:while:mul.mut REGISTER_NAME COMP_LOOP-1:modExp_dev#1:while:mul.mut
directive set /inPlaceNTT_DIF/inPlaceNTT_DIF:core/core/COMP_LOOP-3:modExp_dev#1:while:mul.mut REGISTER_NAME COMP_LOOP-1:modExp_dev#1:while:mul.mut
directive set /inPlaceNTT_DIF/inPlaceNTT_DIF:core/core/COMP_LOOP-4:modExp_dev#1:while:mul.mut REGISTER_NAME COMP_LOOP-1:modExp_dev#1:while:mul.mut
directive set /inPlaceNTT_DIF/inPlaceNTT_DIF:core/core/COMP_LOOP-5:modExp_dev#1:while:mul.mut REGISTER_NAME COMP_LOOP-1:modExp_dev#1:while:mul.mut
directive set /inPlaceNTT_DIF/inPlaceNTT_DIF:core/core/COMP_LOOP-6:modExp_dev#1:while:mul.mut REGISTER_NAME COMP_LOOP-1:modExp_dev#1:while:mul.mut
directive set /inPlaceNTT_DIF/inPlaceNTT_DIF:core/core/COMP_LOOP-7:modExp_dev#1:while:mul.mut REGISTER_NAME COMP_LOOP-1:modExp_dev#1:while:mul.mut
directive set /inPlaceNTT_DIF/inPlaceNTT_DIF:core/core/COMP_LOOP-8:modExp_dev#1:while:mul.mut REGISTER_NAME COMP_LOOP-1:modExp_dev#1:while:mul.mut
directive set /inPlaceNTT_DIF/inPlaceNTT_DIF:core/core/modExp_dev:while:mul.mut REGISTER_NAME COMP_LOOP-1:modExp_dev#1:while:mul.mut
directive set /inPlaceNTT_DIF/inPlaceNTT_DIF:core/core/modExp_dev#1:result#1.sva REGISTER_NAME COMP_LOOP-1:modExp_dev#1:while:mul.mut
directive set /inPlaceNTT_DIF/inPlaceNTT_DIF:core/core/modExp_dev#1:result#2.sva REGISTER_NAME COMP_LOOP-1:modExp_dev#1:while:mul.mut
directive set /inPlaceNTT_DIF/inPlaceNTT_DIF:core/core/modExp_dev#1:result#3.sva REGISTER_NAME COMP_LOOP-1:modExp_dev#1:while:mul.mut
directive set /inPlaceNTT_DIF/inPlaceNTT_DIF:core/core/modExp_dev#1:result#4.sva REGISTER_NAME COMP_LOOP-1:modExp_dev#1:while:mul.mut
directive set /inPlaceNTT_DIF/inPlaceNTT_DIF:core/core/modExp_dev#1:result#5.sva REGISTER_NAME COMP_LOOP-1:modExp_dev#1:while:mul.mut
directive set /inPlaceNTT_DIF/inPlaceNTT_DIF:core/core/modExp_dev#1:result#6.sva REGISTER_NAME COMP_LOOP-1:modExp_dev#1:while:mul.mut
directive set /inPlaceNTT_DIF/inPlaceNTT_DIF:core/core/modExp_dev#1:result#7.sva REGISTER_NAME COMP_LOOP-1:modExp_dev#1:while:mul.mut
directive set /inPlaceNTT_DIF/inPlaceNTT_DIF:core/core/modExp_dev#1:result.sva REGISTER_NAME COMP_LOOP-1:modExp_dev#1:while:mul.mut
directive set /inPlaceNTT_DIF/inPlaceNTT_DIF:core/core/operator-<64,false>:acc.mut REGISTER_NAME COMP_LOOP-1:modExp_dev#1:while:mul.mut
directive set /inPlaceNTT_DIF/inPlaceNTT_DIF:core/core/COMP_LOOP-2:operator<<64,false>:slc(operator<<64,false>:acc)(63).itm REGISTER_NAME COMP_LOOP-2:operator<<64,false>:slc(operator<<64,false>:acc)(63).itm
directive set /inPlaceNTT_DIF/inPlaceNTT_DIF:core/core/COMP_LOOP-3:operator<<64,false>:slc(operator<<64,false>:acc)(63).itm REGISTER_NAME COMP_LOOP-2:operator<<64,false>:slc(operator<<64,false>:acc)(63).itm
directive set /inPlaceNTT_DIF/inPlaceNTT_DIF:core/core/COMP_LOOP-5:operator<<64,false>:slc(operator<<64,false>:acc)(63).itm REGISTER_NAME COMP_LOOP-2:operator<<64,false>:slc(operator<<64,false>:acc)(63).itm
directive set /inPlaceNTT_DIF/inPlaceNTT_DIF:core/core/COMP_LOOP-6:operator<<64,false>:slc(operator<<64,false>:acc)(63).itm REGISTER_NAME COMP_LOOP-2:operator<<64,false>:slc(operator<<64,false>:acc)(63).itm
directive set /inPlaceNTT_DIF/inPlaceNTT_DIF:core/core/COMP_LOOP-7:operator<<64,false>:slc(operator<<64,false>:acc)(63).itm REGISTER_NAME COMP_LOOP-2:operator<<64,false>:slc(operator<<64,false>:acc)(63).itm
directive set /inPlaceNTT_DIF/inPlaceNTT_DIF:core/core/COMP_LOOP:COMP_LOOP:and#12.itm REGISTER_NAME COMP_LOOP-2:operator<<64,false>:slc(operator<<64,false>:acc)(63).itm
directive set /inPlaceNTT_DIF/inPlaceNTT_DIF:core/core/exit:COMP_LOOP-1:modExp_dev#1:while.sva REGISTER_NAME COMP_LOOP-2:operator<<64,false>:slc(operator<<64,false>:acc)(63).itm
directive set /inPlaceNTT_DIF/inPlaceNTT_DIF:core/core/exit:COMP_LOOP-2:modExp_dev#1:while.sva REGISTER_NAME COMP_LOOP-2:operator<<64,false>:slc(operator<<64,false>:acc)(63).itm
directive set /inPlaceNTT_DIF/inPlaceNTT_DIF:core/core/exit:COMP_LOOP-3:modExp_dev#1:while.sva REGISTER_NAME COMP_LOOP-2:operator<<64,false>:slc(operator<<64,false>:acc)(63).itm
directive set /inPlaceNTT_DIF/inPlaceNTT_DIF:core/core/exit:COMP_LOOP-4:modExp_dev#1:while.sva REGISTER_NAME COMP_LOOP-2:operator<<64,false>:slc(operator<<64,false>:acc)(63).itm
directive set /inPlaceNTT_DIF/inPlaceNTT_DIF:core/core/exit:COMP_LOOP-5:modExp_dev#1:while.sva REGISTER_NAME COMP_LOOP-2:operator<<64,false>:slc(operator<<64,false>:acc)(63).itm
directive set /inPlaceNTT_DIF/inPlaceNTT_DIF:core/core/exit:COMP_LOOP-6:modExp_dev#1:while.sva REGISTER_NAME COMP_LOOP-2:operator<<64,false>:slc(operator<<64,false>:acc)(63).itm
directive set /inPlaceNTT_DIF/inPlaceNTT_DIF:core/core/exit:COMP_LOOP-7:modExp_dev#1:while.sva REGISTER_NAME COMP_LOOP-2:operator<<64,false>:slc(operator<<64,false>:acc)(63).itm
directive set /inPlaceNTT_DIF/inPlaceNTT_DIF:core/core/exit:COMP_LOOP-8:modExp_dev#1:while.sva REGISTER_NAME COMP_LOOP-2:operator<<64,false>:slc(operator<<64,false>:acc)(63).itm
directive set /inPlaceNTT_DIF/inPlaceNTT_DIF:core/core/exit:modExp_dev:while.sva REGISTER_NAME COMP_LOOP-2:operator<<64,false>:slc(operator<<64,false>:acc)(63).itm
directive set /inPlaceNTT_DIF/inPlaceNTT_DIF:core/core/exit:COMP_LOOP.sva REGISTER_NAME COMP_LOOP-2:operator<<64,false>:slc(operator<<64,false>:acc)(63).itm
directive set /inPlaceNTT_DIF/inPlaceNTT_DIF:core/core/tmp#10.lpi#4.dfm REGISTER_NAME tmp#10.lpi#4.dfm
directive set /inPlaceNTT_DIF/inPlaceNTT_DIF:core/core/tmp#12.lpi#4.dfm REGISTER_NAME tmp#10.lpi#4.dfm
directive set /inPlaceNTT_DIF/inPlaceNTT_DIF:core/core/tmp#14.lpi#4.dfm REGISTER_NAME tmp#10.lpi#4.dfm
directive set /inPlaceNTT_DIF/inPlaceNTT_DIF:core/core/tmp#2.lpi#4.dfm REGISTER_NAME tmp#10.lpi#4.dfm
directive set /inPlaceNTT_DIF/inPlaceNTT_DIF:core/core/tmp#4.lpi#4.dfm REGISTER_NAME tmp#10.lpi#4.dfm
directive set /inPlaceNTT_DIF/inPlaceNTT_DIF:core/core/tmp#6.lpi#4.dfm REGISTER_NAME tmp#10.lpi#4.dfm
directive set /inPlaceNTT_DIF/inPlaceNTT_DIF:core/core/tmp#8.lpi#4.dfm REGISTER_NAME tmp#10.lpi#4.dfm
directive set /inPlaceNTT_DIF/inPlaceNTT_DIF:core/core/tmp.lpi#4.dfm REGISTER_NAME tmp#10.lpi#4.dfm
directive set /inPlaceNTT_DIF/inPlaceNTT_DIF:core/core/modExp_dev:exp.sva REGISTER_NAME tmp#10.lpi#4.dfm
directive set /inPlaceNTT_DIF/inPlaceNTT_DIF:core/core/operator<<64,false>:slc(operator<<64,false>:acc#1)(60).itm REGISTER_NAME operator<<64,false>:slc(operator<<64,false>:acc#1)(60).itm
directive set /inPlaceNTT_DIF/inPlaceNTT_DIF:core/core/operator<<64,false>:slc(operator<<64,false>:acc)(61).itm REGISTER_NAME operator<<64,false>:slc(operator<<64,false>:acc#1)(60).itm
directive set /inPlaceNTT_DIF/inPlaceNTT_DIF:core/core/operator><64,false>#1:slc(operator><64,false>#1:acc)(6).itm REGISTER_NAME operator<<64,false>:slc(operator<<64,false>:acc#1)(60).itm
directive set /inPlaceNTT_DIF/inPlaceNTT_DIF:core/core/modExp_dev:exp#1.sva(63:9) REGISTER_NAME modExp_dev:exp#1.sva(63:9)
directive set /inPlaceNTT_DIF/inPlaceNTT_DIF:core/core/modExp_dev:exp#2.sva(63:9) REGISTER_NAME modExp_dev:exp#1.sva(63:9)
directive set /inPlaceNTT_DIF/inPlaceNTT_DIF:core/core/modExp_dev:exp#3.sva(63:9) REGISTER_NAME modExp_dev:exp#1.sva(63:9)
directive set /inPlaceNTT_DIF/inPlaceNTT_DIF:core/core/modExp_dev:exp#4.sva(63:9) REGISTER_NAME modExp_dev:exp#1.sva(63:9)
directive set /inPlaceNTT_DIF/inPlaceNTT_DIF:core/core/modExp_dev:exp#5.sva(63:9) REGISTER_NAME modExp_dev:exp#1.sva(63:9)
directive set /inPlaceNTT_DIF/inPlaceNTT_DIF:core/core/modExp_dev:exp#6.sva(63:9) REGISTER_NAME modExp_dev:exp#1.sva(63:9)
directive set /inPlaceNTT_DIF/inPlaceNTT_DIF:core/core/modExp_dev:exp#7.sva(63:9) REGISTER_NAME modExp_dev:exp#1.sva(63:9)
directive set /inPlaceNTT_DIF/inPlaceNTT_DIF:core/core/modExp_dev:exp#8.sva(63:9) REGISTER_NAME modExp_dev:exp#1.sva(63:9)
directive set /inPlaceNTT_DIF/inPlaceNTT_DIF:core/core/modExp_dev:exp#1.sva(2:0) REGISTER_NAME modExp_dev:exp#1.sva(2:0)
directive set /inPlaceNTT_DIF/inPlaceNTT_DIF:core/core/modExp_dev:exp#2.sva(2:0) REGISTER_NAME modExp_dev:exp#1.sva(2:0)
directive set /inPlaceNTT_DIF/inPlaceNTT_DIF:core/core/modExp_dev:exp#3.sva(2:0) REGISTER_NAME modExp_dev:exp#1.sva(2:0)
directive set /inPlaceNTT_DIF/inPlaceNTT_DIF:core/core/modExp_dev:exp#4.sva(2:0) REGISTER_NAME modExp_dev:exp#1.sva(2:0)
directive set /inPlaceNTT_DIF/inPlaceNTT_DIF:core/core/modExp_dev:exp#5.sva(2:0) REGISTER_NAME modExp_dev:exp#1.sva(2:0)
directive set /inPlaceNTT_DIF/inPlaceNTT_DIF:core/core/modExp_dev:exp#6.sva(2:0) REGISTER_NAME modExp_dev:exp#1.sva(2:0)
directive set /inPlaceNTT_DIF/inPlaceNTT_DIF:core/core/modExp_dev:exp#7.sva(2:0) REGISTER_NAME modExp_dev:exp#1.sva(2:0)
directive set /inPlaceNTT_DIF/inPlaceNTT_DIF:core/core/modExp_dev:exp#8.sva(2:0) REGISTER_NAME modExp_dev:exp#1.sva(2:0)
