directive set /inPlaceNTT_DIT_precomp/inPlaceNTT_DIT_precomp:core/inPlaceNTT_DIT_precomp:core:conc/COMP_LOOP-1:twiddle_f:mul RESOURCE_NAME COMP_LOOP-1:twiddle_f:mul:rg
directive set /inPlaceNTT_DIT_precomp/inPlaceNTT_DIT_precomp:core/inPlaceNTT_DIT_precomp:core:conc/COMP_LOOP-2:twiddle_f:mul RESOURCE_NAME COMP_LOOP-1:twiddle_f:mul:rg
directive set /inPlaceNTT_DIT_precomp/inPlaceNTT_DIT_precomp:core/inPlaceNTT_DIT_precomp:core:conc/STAGE_LOOP:lshift RESOURCE_NAME COMP_LOOP-2:twiddle_f:lshift:rg
directive set /inPlaceNTT_DIT_precomp/inPlaceNTT_DIT_precomp:core/inPlaceNTT_DIT_precomp:core:conc/COMP_LOOP-2:twiddle_f:lshift RESOURCE_NAME COMP_LOOP-2:twiddle_f:lshift:rg
directive set /inPlaceNTT_DIT_precomp/inPlaceNTT_DIT_precomp:core/inPlaceNTT_DIT_precomp:core:conc/VEC_LOOP:acc RESOURCE_NAME COMP_LOOP-2:VEC_LOOP:acc#1:rg
directive set /inPlaceNTT_DIT_precomp/inPlaceNTT_DIT_precomp:core/inPlaceNTT_DIT_precomp:core:conc/COMP_LOOP-2:VEC_LOOP:acc#1 RESOURCE_NAME COMP_LOOP-2:VEC_LOOP:acc#1:rg
directive set /inPlaceNTT_DIT_precomp/inPlaceNTT_DIT_precomp:core/inPlaceNTT_DIT_precomp:core:conc/COMP_LOOP:slc(COMP_LOOP-2:COMP_LOOP:acc RESOURCE_NAME COMP_LOOP-2:VEC_LOOP:acc#1:rg
directive set /inPlaceNTT_DIT_precomp/inPlaceNTT_DIT_precomp:core/inPlaceNTT_DIT_precomp:core:conc/VEC_LOOP:acc#11 RESOURCE_NAME VEC_LOOP:acc#11:rg
directive set /inPlaceNTT_DIT_precomp/inPlaceNTT_DIT_precomp:core/inPlaceNTT_DIT_precomp:core:conc/VEC_LOOP:acc#12 RESOURCE_NAME VEC_LOOP:acc#11:rg
directive set /inPlaceNTT_DIT_precomp/inPlaceNTT_DIT_precomp:core/inPlaceNTT_DIT_precomp:core:conc/COMP_LOOP-1:VEC_LOOP:acc#10 RESOURCE_NAME COMP_LOOP-1:VEC_LOOP:acc#10:rg
directive set /inPlaceNTT_DIT_precomp/inPlaceNTT_DIT_precomp:core/inPlaceNTT_DIT_precomp:core:conc/COMP_LOOP-2:VEC_LOOP:acc#10 RESOURCE_NAME COMP_LOOP-1:VEC_LOOP:acc#10:rg
directive set /inPlaceNTT_DIT_precomp/inPlaceNTT_DIT_precomp:core/inPlaceNTT_DIT_precomp:core:conc/STAGE_LOOP:acc#1 RESOURCE_NAME COMP_LOOP-1:twiddle_f:acc:rg
directive set /inPlaceNTT_DIT_precomp/inPlaceNTT_DIT_precomp:core/inPlaceNTT_DIT_precomp:core:conc/COMP_LOOP-1:twiddle_f:acc RESOURCE_NAME COMP_LOOP-1:twiddle_f:acc:rg
directive set /inPlaceNTT_DIT_precomp/inPlaceNTT_DIT_precomp:core/inPlaceNTT_DIT_precomp:core:conc/COMP_LOOP-1:VEC_LOOP:acc RESOURCE_NAME COMP_LOOP-1:VEC_LOOP:acc:rg
directive set /inPlaceNTT_DIT_precomp/inPlaceNTT_DIT_precomp:core/inPlaceNTT_DIT_precomp:core:conc/COMP_LOOP-2:VEC_LOOP:acc#9 RESOURCE_NAME COMP_LOOP-1:VEC_LOOP:acc:rg
directive set /inPlaceNTT_DIT_precomp/inPlaceNTT_DIT_precomp:core/inPlaceNTT_DIT_precomp:core:conc/COMP_LOOP-1:acc RESOURCE_NAME COMP_LOOP-1:VEC_LOOP:acc:rg
directive set /inPlaceNTT_DIT_precomp/inPlaceNTT_DIT_precomp:core/inPlaceNTT_DIT_precomp:core:conc/COMP_LOOP-2:acc RESOURCE_NAME COMP_LOOP-1:VEC_LOOP:acc:rg
directive set /inPlaceNTT_DIT_precomp/inPlaceNTT_DIT_precomp:core/inPlaceNTT_DIT_precomp:core:conc/COMP_LOOP-1:VEC_LOOP:acc#9 RESOURCE_NAME COMP_LOOP-1:VEC_LOOP:acc#8:rg
directive set /inPlaceNTT_DIT_precomp/inPlaceNTT_DIT_precomp:core/inPlaceNTT_DIT_precomp:core:conc/COMP_LOOP-1:VEC_LOOP:acc#8 RESOURCE_NAME COMP_LOOP-1:VEC_LOOP:acc#8:rg
