directive set /inPlaceNTT_DIF/inPlaceNTT_DIF:core/core/COPY_LOOP:i(10:0).sva(9:0) REGISTER_NAME COPY_LOOP:i(10:0).sva(9:0)
directive set /inPlaceNTT_DIF/inPlaceNTT_DIF:core/core/STAGE_VEC_LOOP:j.sva(9:0) REGISTER_NAME COPY_LOOP:i(10:0).sva(9:0)
directive set /inPlaceNTT_DIF/inPlaceNTT_DIF:core/core/factor1.sva REGISTER_NAME factor1.sva
directive set /inPlaceNTT_DIF/inPlaceNTT_DIF:core/core/operator-<64,false>:acc.mut REGISTER_NAME factor1.sva
directive set /inPlaceNTT_DIF/inPlaceNTT_DIF:core/core/modExp#1:while:asn#2.itm REGISTER_NAME modExp#1:while:asn#2.itm
directive set /inPlaceNTT_DIF/inPlaceNTT_DIF:core/core/operator%<64,false>:slc(modExp:exp(31:0))(0)#1.itm REGISTER_NAME modExp#1:while:asn#2.itm
directive set /inPlaceNTT_DIF/inPlaceNTT_DIF:core/core/exit:modExp#1:while.sva REGISTER_NAME exit:modExp#1:while.sva
directive set /inPlaceNTT_DIF/inPlaceNTT_DIF:core/core/exit:modExp:while.sva REGISTER_NAME exit:modExp#1:while.sva
directive set /inPlaceNTT_DIF/inPlaceNTT_DIF:core/core/exit:COMP_LOOP.sva REGISTER_NAME exit:modExp#1:while.sva
directive set /inPlaceNTT_DIF/inPlaceNTT_DIF:core/core/modExp:exp#1(0).sva REGISTER_NAME modExp:exp#1(0).sva
directive set /inPlaceNTT_DIF/inPlaceNTT_DIF:core/core/modExp:exp#1(2).sva REGISTER_NAME modExp:exp#1(0).sva
directive set /inPlaceNTT_DIF/inPlaceNTT_DIF:core/core/modExp#1:while:slc(modExp:while:mul:cmp.z.oreg)(127-0).psp REGISTER_NAME modExp#1:while:slc(modExp:while:mul:cmp.z.oreg)(127-0).psp
directive set /inPlaceNTT_DIF/inPlaceNTT_DIF:core/core/modExp:while:slc(modExp:while:mul:cmp.z.oreg)(127-0).psp REGISTER_NAME modExp#1:while:slc(modExp:while:mul:cmp.z.oreg)(127-0).psp
directive set /inPlaceNTT_DIF/inPlaceNTT_DIF:core/core/COMP_LOOP:acc#12.psp REGISTER_NAME COMP_LOOP:acc#12.psp
directive set /inPlaceNTT_DIF/inPlaceNTT_DIF:core/core/COMP_LOOP:acc#5.psp REGISTER_NAME COMP_LOOP:acc#12.psp
directive set /inPlaceNTT_DIF/inPlaceNTT_DIF:core/core/COMP_LOOP:mul.mut REGISTER_NAME COMP_LOOP:mul.mut
directive set /inPlaceNTT_DIF/inPlaceNTT_DIF:core/core/modExp#1:while:if:mul.mut REGISTER_NAME COMP_LOOP:mul.mut
directive set /inPlaceNTT_DIF/inPlaceNTT_DIF:core/core/modExp:while:if:mul.mut REGISTER_NAME COMP_LOOP:mul.mut
