
# Loop constraints
directive set /inPlaceNTT_DIT_precomp/core/core:rlp CSTEPS_FROM {{. == 0}}
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main CSTEPS_FROM {{. == 3} {.. == 0}}
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/STAGE_LOOP CSTEPS_FROM {{. == 2} {.. == 1}}
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/STAGE_LOOP/COMP_LOOP CSTEPS_FROM {{. == 18} {.. == 1}}
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/STAGE_LOOP/COMP_LOOP/COMP_LOOP-1:VEC_LOOP CSTEPS_FROM {{. == 9} {.. == 2}}
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/STAGE_LOOP/COMP_LOOP/COMP_LOOP-2:VEC_LOOP CSTEPS_FROM {{. == 9} {.. == 3}}
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/STAGE_LOOP/COMP_LOOP/COMP_LOOP-3:VEC_LOOP CSTEPS_FROM {{. == 9} {.. == 4}}
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/STAGE_LOOP/COMP_LOOP/COMP_LOOP-4:VEC_LOOP CSTEPS_FROM {{. == 9} {.. == 5}}
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/STAGE_LOOP/COMP_LOOP/COMP_LOOP-5:VEC_LOOP CSTEPS_FROM {{. == 9} {.. == 6}}
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/STAGE_LOOP/COMP_LOOP/COMP_LOOP-6:VEC_LOOP CSTEPS_FROM {{. == 9} {.. == 7}}
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/STAGE_LOOP/COMP_LOOP/COMP_LOOP-7:VEC_LOOP CSTEPS_FROM {{. == 9} {.. == 8}}
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/STAGE_LOOP/COMP_LOOP/COMP_LOOP-8:VEC_LOOP CSTEPS_FROM {{. == 9} {.. == 9}}
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/STAGE_LOOP/COMP_LOOP/COMP_LOOP-9:VEC_LOOP CSTEPS_FROM {{. == 9} {.. == 10}}
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/STAGE_LOOP/COMP_LOOP/COMP_LOOP-10:VEC_LOOP CSTEPS_FROM {{. == 9} {.. == 11}}
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/STAGE_LOOP/COMP_LOOP/COMP_LOOP-11:VEC_LOOP CSTEPS_FROM {{. == 9} {.. == 12}}
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/STAGE_LOOP/COMP_LOOP/COMP_LOOP-12:VEC_LOOP CSTEPS_FROM {{. == 9} {.. == 13}}
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/STAGE_LOOP/COMP_LOOP/COMP_LOOP-13:VEC_LOOP CSTEPS_FROM {{. == 9} {.. == 14}}
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/STAGE_LOOP/COMP_LOOP/COMP_LOOP-14:VEC_LOOP CSTEPS_FROM {{. == 9} {.. == 15}}
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/STAGE_LOOP/COMP_LOOP/COMP_LOOP-15:VEC_LOOP CSTEPS_FROM {{. == 9} {.. == 16}}
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/STAGE_LOOP/COMP_LOOP/COMP_LOOP-16:VEC_LOOP CSTEPS_FROM {{. == 9} {.. == 17}}

# IO operation constraints
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/p:io_read(p:rsc.@) CSTEPS_FROM {{.. == 1}}
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/r:io_read(r:rsc.@) CSTEPS_FROM {{.. == 1}}

# Sync operation constraints
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/io_read(run) CSTEPS_FROM {{.. == 1}}
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/if:io_write(complete) CSTEPS_FROM {{.. == 1}}

# Real operation constraints
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/io_read(run) CSTEPS_FROM {{.. == 1}}
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/STAGE_LOOP/STAGE_LOOP:lshift CSTEPS_FROM {{.. == 1}}
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/STAGE_LOOP/COMP_LOOP/COMP_LOOP-1:twiddle_f:acc CSTEPS_FROM {{.. == 1}}
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/STAGE_LOOP/COMP_LOOP/COMP_LOOP-1:twiddle_f:lshift CSTEPS_FROM {{.. == 1}}
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/STAGE_LOOP/COMP_LOOP/COMP_LOOP-1:twiddle_f:mul CSTEPS_FROM {{.. == 1}}
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/STAGE_LOOP/COMP_LOOP/COMP_LOOP:twiddle_f:read_mem(twiddle:rsc.@) CSTEPS_FROM {{.. == 1}}
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/STAGE_LOOP/COMP_LOOP/COMP_LOOP:twiddle_help:read_mem(twiddle_h:rsc.@) CSTEPS_FROM {{.. == 1}}
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/STAGE_LOOP/COMP_LOOP/COMP_LOOP-1:VEC_LOOP/VEC_LOOP:acc CSTEPS_FROM {{.. == 1}}
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/STAGE_LOOP/COMP_LOOP/COMP_LOOP-1:VEC_LOOP/VEC_LOOP:read_mem(vec:rsc.@) CSTEPS_FROM {{.. == 1}}
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/STAGE_LOOP/COMP_LOOP/COMP_LOOP-1:VEC_LOOP/VEC_LOOP:acc#18 CSTEPS_FROM {{.. == 1}}
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/STAGE_LOOP/COMP_LOOP/COMP_LOOP-1:VEC_LOOP/COMP_LOOP-1:VEC_LOOP:acc#10 CSTEPS_FROM {{.. == 1}}
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/STAGE_LOOP/COMP_LOOP/COMP_LOOP-1:VEC_LOOP/VEC_LOOP:read_mem(vec:rsc.@)#1 CSTEPS_FROM {{.. == 1}}
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/STAGE_LOOP/COMP_LOOP/COMP_LOOP-1:VEC_LOOP/COMP_LOOP-1:mult:z:mul CSTEPS_FROM {{.. == 4}}
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/STAGE_LOOP/COMP_LOOP/COMP_LOOP-1:VEC_LOOP/COMP_LOOP-1:mult:t:mul CSTEPS_FROM {{.. == 3}}
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/STAGE_LOOP/COMP_LOOP/COMP_LOOP-1:VEC_LOOP/COMP_LOOP-1:mult:z_:mul CSTEPS_FROM {{.. == 5}}
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/STAGE_LOOP/COMP_LOOP/COMP_LOOP-1:VEC_LOOP/COMP_LOOP-1:mult:res:acc CSTEPS_FROM {{.. == 5}}
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/STAGE_LOOP/COMP_LOOP/COMP_LOOP-1:VEC_LOOP/mult:if:acc CSTEPS_FROM {{.. == 6}}
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/STAGE_LOOP/COMP_LOOP/COMP_LOOP-1:VEC_LOOP/COMP_LOOP-1:mult:if:acc CSTEPS_FROM {{.. == 6}}
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/STAGE_LOOP/COMP_LOOP/COMP_LOOP-1:VEC_LOOP/mult:mux CSTEPS_FROM {{.. == 6}}
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/STAGE_LOOP/COMP_LOOP/COMP_LOOP-1:VEC_LOOP/COMP_LOOP-1:VEC_LOOP:acc#5 CSTEPS_FROM {{.. == 6}}
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/STAGE_LOOP/COMP_LOOP/COMP_LOOP-1:VEC_LOOP/COMP_LOOP-1:modulo_add() CSTEPS_FROM {{.. == 6}}
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/STAGE_LOOP/COMP_LOOP/COMP_LOOP-1:VEC_LOOP/VEC_LOOP:write_mem(vec:rsc.@) CSTEPS_FROM {{.. == 7}}
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/STAGE_LOOP/COMP_LOOP/COMP_LOOP-1:VEC_LOOP/COMP_LOOP-1:VEC_LOOP:acc#8 CSTEPS_FROM {{.. == 6}}
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/STAGE_LOOP/COMP_LOOP/COMP_LOOP-1:VEC_LOOP/COMP_LOOP-1:modulo_sub() CSTEPS_FROM {{.. == 6}}
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/STAGE_LOOP/COMP_LOOP/COMP_LOOP-1:VEC_LOOP/VEC_LOOP:write_mem(vec:rsc.@)#1 CSTEPS_FROM {{.. == 8}}
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/STAGE_LOOP/COMP_LOOP/COMP_LOOP-1:VEC_LOOP/COMP_LOOP-1:VEC_LOOP:acc#9 CSTEPS_FROM {{.. == 1}}
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/STAGE_LOOP/COMP_LOOP/COMP_LOOP-1:VEC_LOOP/COMP_LOOP-1:VEC_LOOP:acc CSTEPS_FROM {{.. == 1}}
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/STAGE_LOOP/COMP_LOOP/COMP_LOOP-2:acc CSTEPS_FROM {{.. == 3}}
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/STAGE_LOOP/COMP_LOOP/COMP_LOOP-2:twiddle_f:lshift CSTEPS_FROM {{.. == 1}}
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/STAGE_LOOP/COMP_LOOP/COMP_LOOP-2:twiddle_f:mul CSTEPS_FROM {{.. == 1}}
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/STAGE_LOOP/COMP_LOOP/COMP_LOOP:twiddle_f:read_mem(twiddle:rsc.@)#1 CSTEPS_FROM {{.. == 1}}
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/STAGE_LOOP/COMP_LOOP/COMP_LOOP:twiddle_help:read_mem(twiddle_h:rsc.@)#1 CSTEPS_FROM {{.. == 1}}
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/STAGE_LOOP/COMP_LOOP/COMP_LOOP-2:VEC_LOOP/COMP_LOOP-2:VEC_LOOP:acc#1 CSTEPS_FROM {{.. == 1}}
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/STAGE_LOOP/COMP_LOOP/COMP_LOOP-2:VEC_LOOP/VEC_LOOP:read_mem(vec:rsc.@)#2 CSTEPS_FROM {{.. == 1}}
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/STAGE_LOOP/COMP_LOOP/COMP_LOOP-2:VEC_LOOP/VEC_LOOP:acc#19 CSTEPS_FROM {{.. == 1}}
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/STAGE_LOOP/COMP_LOOP/COMP_LOOP-2:VEC_LOOP/COMP_LOOP-2:VEC_LOOP:acc#10 CSTEPS_FROM {{.. == 1}}
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/STAGE_LOOP/COMP_LOOP/COMP_LOOP-2:VEC_LOOP/VEC_LOOP:read_mem(vec:rsc.@)#3 CSTEPS_FROM {{.. == 1}}
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/STAGE_LOOP/COMP_LOOP/COMP_LOOP-2:VEC_LOOP/COMP_LOOP-2:mult:z:mul CSTEPS_FROM {{.. == 4}}
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/STAGE_LOOP/COMP_LOOP/COMP_LOOP-2:VEC_LOOP/COMP_LOOP-2:mult:t:mul CSTEPS_FROM {{.. == 3}}
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/STAGE_LOOP/COMP_LOOP/COMP_LOOP-2:VEC_LOOP/COMP_LOOP-2:mult:z_:mul CSTEPS_FROM {{.. == 5}}
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/STAGE_LOOP/COMP_LOOP/COMP_LOOP-2:VEC_LOOP/COMP_LOOP-2:mult:res:acc CSTEPS_FROM {{.. == 5}}
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/STAGE_LOOP/COMP_LOOP/COMP_LOOP-2:VEC_LOOP/mult:if:acc#1 CSTEPS_FROM {{.. == 6}}
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/STAGE_LOOP/COMP_LOOP/COMP_LOOP-2:VEC_LOOP/COMP_LOOP-2:mult:if:acc CSTEPS_FROM {{.. == 6}}
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/STAGE_LOOP/COMP_LOOP/COMP_LOOP-2:VEC_LOOP/mult:mux#1 CSTEPS_FROM {{.. == 6}}
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/STAGE_LOOP/COMP_LOOP/COMP_LOOP-2:VEC_LOOP/COMP_LOOP-2:VEC_LOOP:acc#5 CSTEPS_FROM {{.. == 6}}
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/STAGE_LOOP/COMP_LOOP/COMP_LOOP-2:VEC_LOOP/COMP_LOOP-2:modulo_add() CSTEPS_FROM {{.. == 6}}
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/STAGE_LOOP/COMP_LOOP/COMP_LOOP-2:VEC_LOOP/VEC_LOOP:write_mem(vec:rsc.@)#2 CSTEPS_FROM {{.. == 7}}
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/STAGE_LOOP/COMP_LOOP/COMP_LOOP-2:VEC_LOOP/COMP_LOOP-2:VEC_LOOP:acc#8 CSTEPS_FROM {{.. == 6}}
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/STAGE_LOOP/COMP_LOOP/COMP_LOOP-2:VEC_LOOP/COMP_LOOP-2:modulo_sub() CSTEPS_FROM {{.. == 6}}
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/STAGE_LOOP/COMP_LOOP/COMP_LOOP-2:VEC_LOOP/VEC_LOOP:write_mem(vec:rsc.@)#3 CSTEPS_FROM {{.. == 8}}
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/STAGE_LOOP/COMP_LOOP/COMP_LOOP-2:VEC_LOOP/COMP_LOOP-2:VEC_LOOP:acc#9 CSTEPS_FROM {{.. == 1}}
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/STAGE_LOOP/COMP_LOOP/COMP_LOOP-3:acc CSTEPS_FROM {{.. == 4}}
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/STAGE_LOOP/COMP_LOOP/COMP_LOOP-3:twiddle_f:lshift CSTEPS_FROM {{.. == 2}}
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/STAGE_LOOP/COMP_LOOP/COMP_LOOP-3:twiddle_f:mul CSTEPS_FROM {{.. == 2}}
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/STAGE_LOOP/COMP_LOOP/COMP_LOOP:twiddle_f:read_mem(twiddle:rsc.@)#2 CSTEPS_FROM {{.. == 2}}
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/STAGE_LOOP/COMP_LOOP/COMP_LOOP:twiddle_help:read_mem(twiddle_h:rsc.@)#2 CSTEPS_FROM {{.. == 2}}
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/STAGE_LOOP/COMP_LOOP/COMP_LOOP-3:VEC_LOOP/VEC_LOOP:acc#11 CSTEPS_FROM {{.. == 1}}
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/STAGE_LOOP/COMP_LOOP/COMP_LOOP-3:VEC_LOOP/VEC_LOOP:read_mem(vec:rsc.@)#4 CSTEPS_FROM {{.. == 1}}
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/STAGE_LOOP/COMP_LOOP/COMP_LOOP-3:VEC_LOOP/VEC_LOOP:acc#20 CSTEPS_FROM {{.. == 1}}
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/STAGE_LOOP/COMP_LOOP/COMP_LOOP-3:VEC_LOOP/COMP_LOOP-3:VEC_LOOP:acc#10 CSTEPS_FROM {{.. == 1}}
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/STAGE_LOOP/COMP_LOOP/COMP_LOOP-3:VEC_LOOP/VEC_LOOP:read_mem(vec:rsc.@)#5 CSTEPS_FROM {{.. == 1}}
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/STAGE_LOOP/COMP_LOOP/COMP_LOOP-3:VEC_LOOP/COMP_LOOP-3:mult:z:mul CSTEPS_FROM {{.. == 4}}
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/STAGE_LOOP/COMP_LOOP/COMP_LOOP-3:VEC_LOOP/COMP_LOOP-3:mult:t:mul CSTEPS_FROM {{.. == 3}}
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/STAGE_LOOP/COMP_LOOP/COMP_LOOP-3:VEC_LOOP/COMP_LOOP-3:mult:z_:mul CSTEPS_FROM {{.. == 5}}
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/STAGE_LOOP/COMP_LOOP/COMP_LOOP-3:VEC_LOOP/COMP_LOOP-3:mult:res:acc CSTEPS_FROM {{.. == 5}}
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/STAGE_LOOP/COMP_LOOP/COMP_LOOP-3:VEC_LOOP/mult:if:acc#2 CSTEPS_FROM {{.. == 6}}
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/STAGE_LOOP/COMP_LOOP/COMP_LOOP-3:VEC_LOOP/COMP_LOOP-3:mult:if:acc CSTEPS_FROM {{.. == 6}}
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/STAGE_LOOP/COMP_LOOP/COMP_LOOP-3:VEC_LOOP/mult:mux#2 CSTEPS_FROM {{.. == 6}}
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/STAGE_LOOP/COMP_LOOP/COMP_LOOP-3:VEC_LOOP/COMP_LOOP-3:VEC_LOOP:acc#5 CSTEPS_FROM {{.. == 6}}
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/STAGE_LOOP/COMP_LOOP/COMP_LOOP-3:VEC_LOOP/COMP_LOOP-3:modulo_add() CSTEPS_FROM {{.. == 6}}
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/STAGE_LOOP/COMP_LOOP/COMP_LOOP-3:VEC_LOOP/VEC_LOOP:write_mem(vec:rsc.@)#4 CSTEPS_FROM {{.. == 7}}
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/STAGE_LOOP/COMP_LOOP/COMP_LOOP-3:VEC_LOOP/COMP_LOOP-3:VEC_LOOP:acc#8 CSTEPS_FROM {{.. == 6}}
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/STAGE_LOOP/COMP_LOOP/COMP_LOOP-3:VEC_LOOP/COMP_LOOP-3:modulo_sub() CSTEPS_FROM {{.. == 6}}
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/STAGE_LOOP/COMP_LOOP/COMP_LOOP-3:VEC_LOOP/VEC_LOOP:write_mem(vec:rsc.@)#5 CSTEPS_FROM {{.. == 8}}
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/STAGE_LOOP/COMP_LOOP/COMP_LOOP-3:VEC_LOOP/COMP_LOOP-3:VEC_LOOP:acc#9 CSTEPS_FROM {{.. == 1}}
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/STAGE_LOOP/COMP_LOOP/COMP_LOOP:acc CSTEPS_FROM {{.. == 5}}
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/STAGE_LOOP/COMP_LOOP/COMP_LOOP-4:twiddle_f:mul CSTEPS_FROM {{.. == 3}}
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/STAGE_LOOP/COMP_LOOP/COMP_LOOP:twiddle_f:read_mem(twiddle:rsc.@)#3 CSTEPS_FROM {{.. == 3}}
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/STAGE_LOOP/COMP_LOOP/COMP_LOOP:twiddle_help:read_mem(twiddle_h:rsc.@)#3 CSTEPS_FROM {{.. == 3}}
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/STAGE_LOOP/COMP_LOOP/COMP_LOOP-4:VEC_LOOP/COMP_LOOP-4:VEC_LOOP:acc#1 CSTEPS_FROM {{.. == 1}}
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/STAGE_LOOP/COMP_LOOP/COMP_LOOP-4:VEC_LOOP/VEC_LOOP:read_mem(vec:rsc.@)#6 CSTEPS_FROM {{.. == 1}}
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/STAGE_LOOP/COMP_LOOP/COMP_LOOP-4:VEC_LOOP/VEC_LOOP:acc#21 CSTEPS_FROM {{.. == 1}}
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/STAGE_LOOP/COMP_LOOP/COMP_LOOP-4:VEC_LOOP/COMP_LOOP-4:VEC_LOOP:acc#10 CSTEPS_FROM {{.. == 1}}
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/STAGE_LOOP/COMP_LOOP/COMP_LOOP-4:VEC_LOOP/VEC_LOOP:read_mem(vec:rsc.@)#7 CSTEPS_FROM {{.. == 1}}
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/STAGE_LOOP/COMP_LOOP/COMP_LOOP-4:VEC_LOOP/COMP_LOOP-4:mult:z:mul CSTEPS_FROM {{.. == 4}}
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/STAGE_LOOP/COMP_LOOP/COMP_LOOP-4:VEC_LOOP/COMP_LOOP-4:mult:t:mul CSTEPS_FROM {{.. == 3}}
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/STAGE_LOOP/COMP_LOOP/COMP_LOOP-4:VEC_LOOP/COMP_LOOP-4:mult:z_:mul CSTEPS_FROM {{.. == 5}}
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/STAGE_LOOP/COMP_LOOP/COMP_LOOP-4:VEC_LOOP/COMP_LOOP-4:mult:res:acc CSTEPS_FROM {{.. == 5}}
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/STAGE_LOOP/COMP_LOOP/COMP_LOOP-4:VEC_LOOP/mult:if:acc#3 CSTEPS_FROM {{.. == 6}}
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/STAGE_LOOP/COMP_LOOP/COMP_LOOP-4:VEC_LOOP/COMP_LOOP-4:mult:if:acc CSTEPS_FROM {{.. == 6}}
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/STAGE_LOOP/COMP_LOOP/COMP_LOOP-4:VEC_LOOP/mult:mux#3 CSTEPS_FROM {{.. == 6}}
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/STAGE_LOOP/COMP_LOOP/COMP_LOOP-4:VEC_LOOP/COMP_LOOP-4:VEC_LOOP:acc#5 CSTEPS_FROM {{.. == 6}}
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/STAGE_LOOP/COMP_LOOP/COMP_LOOP-4:VEC_LOOP/COMP_LOOP-4:modulo_add() CSTEPS_FROM {{.. == 6}}
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/STAGE_LOOP/COMP_LOOP/COMP_LOOP-4:VEC_LOOP/VEC_LOOP:write_mem(vec:rsc.@)#6 CSTEPS_FROM {{.. == 7}}
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/STAGE_LOOP/COMP_LOOP/COMP_LOOP-4:VEC_LOOP/COMP_LOOP-4:VEC_LOOP:acc#8 CSTEPS_FROM {{.. == 6}}
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/STAGE_LOOP/COMP_LOOP/COMP_LOOP-4:VEC_LOOP/COMP_LOOP-4:modulo_sub() CSTEPS_FROM {{.. == 6}}
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/STAGE_LOOP/COMP_LOOP/COMP_LOOP-4:VEC_LOOP/VEC_LOOP:write_mem(vec:rsc.@)#7 CSTEPS_FROM {{.. == 8}}
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/STAGE_LOOP/COMP_LOOP/COMP_LOOP-4:VEC_LOOP/COMP_LOOP-4:VEC_LOOP:acc#9 CSTEPS_FROM {{.. == 1}}
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/STAGE_LOOP/COMP_LOOP/COMP_LOOP-5:acc CSTEPS_FROM {{.. == 6}}
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/STAGE_LOOP/COMP_LOOP/COMP_LOOP-5:twiddle_f:lshift CSTEPS_FROM {{.. == 3}}
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/STAGE_LOOP/COMP_LOOP/COMP_LOOP-5:twiddle_f:mul CSTEPS_FROM {{.. == 4}}
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/STAGE_LOOP/COMP_LOOP/COMP_LOOP:twiddle_f:read_mem(twiddle:rsc.@)#4 CSTEPS_FROM {{.. == 4}}
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/STAGE_LOOP/COMP_LOOP/COMP_LOOP:twiddle_help:read_mem(twiddle_h:rsc.@)#4 CSTEPS_FROM {{.. == 4}}
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/STAGE_LOOP/COMP_LOOP/COMP_LOOP-5:VEC_LOOP/VEC_LOOP:acc#12 CSTEPS_FROM {{.. == 1}}
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/STAGE_LOOP/COMP_LOOP/COMP_LOOP-5:VEC_LOOP/VEC_LOOP:read_mem(vec:rsc.@)#8 CSTEPS_FROM {{.. == 1}}
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/STAGE_LOOP/COMP_LOOP/COMP_LOOP-5:VEC_LOOP/VEC_LOOP:acc#22 CSTEPS_FROM {{.. == 1}}
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/STAGE_LOOP/COMP_LOOP/COMP_LOOP-5:VEC_LOOP/COMP_LOOP-5:VEC_LOOP:acc#10 CSTEPS_FROM {{.. == 1}}
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/STAGE_LOOP/COMP_LOOP/COMP_LOOP-5:VEC_LOOP/VEC_LOOP:read_mem(vec:rsc.@)#9 CSTEPS_FROM {{.. == 1}}
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/STAGE_LOOP/COMP_LOOP/COMP_LOOP-5:VEC_LOOP/COMP_LOOP-5:mult:z:mul CSTEPS_FROM {{.. == 4}}
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/STAGE_LOOP/COMP_LOOP/COMP_LOOP-5:VEC_LOOP/COMP_LOOP-5:mult:t:mul CSTEPS_FROM {{.. == 3}}
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/STAGE_LOOP/COMP_LOOP/COMP_LOOP-5:VEC_LOOP/COMP_LOOP-5:mult:z_:mul CSTEPS_FROM {{.. == 5}}
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/STAGE_LOOP/COMP_LOOP/COMP_LOOP-5:VEC_LOOP/COMP_LOOP-5:mult:res:acc CSTEPS_FROM {{.. == 5}}
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/STAGE_LOOP/COMP_LOOP/COMP_LOOP-5:VEC_LOOP/mult:if:acc#4 CSTEPS_FROM {{.. == 6}}
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/STAGE_LOOP/COMP_LOOP/COMP_LOOP-5:VEC_LOOP/COMP_LOOP-5:mult:if:acc CSTEPS_FROM {{.. == 6}}
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/STAGE_LOOP/COMP_LOOP/COMP_LOOP-5:VEC_LOOP/mult:mux#4 CSTEPS_FROM {{.. == 6}}
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/STAGE_LOOP/COMP_LOOP/COMP_LOOP-5:VEC_LOOP/COMP_LOOP-5:VEC_LOOP:acc#5 CSTEPS_FROM {{.. == 6}}
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/STAGE_LOOP/COMP_LOOP/COMP_LOOP-5:VEC_LOOP/COMP_LOOP-5:modulo_add() CSTEPS_FROM {{.. == 6}}
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/STAGE_LOOP/COMP_LOOP/COMP_LOOP-5:VEC_LOOP/VEC_LOOP:write_mem(vec:rsc.@)#8 CSTEPS_FROM {{.. == 7}}
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/STAGE_LOOP/COMP_LOOP/COMP_LOOP-5:VEC_LOOP/COMP_LOOP-5:VEC_LOOP:acc#8 CSTEPS_FROM {{.. == 6}}
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/STAGE_LOOP/COMP_LOOP/COMP_LOOP-5:VEC_LOOP/COMP_LOOP-5:modulo_sub() CSTEPS_FROM {{.. == 6}}
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/STAGE_LOOP/COMP_LOOP/COMP_LOOP-5:VEC_LOOP/VEC_LOOP:write_mem(vec:rsc.@)#9 CSTEPS_FROM {{.. == 8}}
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/STAGE_LOOP/COMP_LOOP/COMP_LOOP-5:VEC_LOOP/COMP_LOOP-5:VEC_LOOP:acc#9 CSTEPS_FROM {{.. == 1}}
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/STAGE_LOOP/COMP_LOOP/COMP_LOOP-6:acc CSTEPS_FROM {{.. == 7}}
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/STAGE_LOOP/COMP_LOOP/COMP_LOOP-6:twiddle_f:mul CSTEPS_FROM {{.. == 5}}
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/STAGE_LOOP/COMP_LOOP/COMP_LOOP:twiddle_f:read_mem(twiddle:rsc.@)#5 CSTEPS_FROM {{.. == 5}}
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/STAGE_LOOP/COMP_LOOP/COMP_LOOP:twiddle_help:read_mem(twiddle_h:rsc.@)#5 CSTEPS_FROM {{.. == 5}}
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/STAGE_LOOP/COMP_LOOP/COMP_LOOP-6:VEC_LOOP/COMP_LOOP-6:VEC_LOOP:acc#1 CSTEPS_FROM {{.. == 1}}
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/STAGE_LOOP/COMP_LOOP/COMP_LOOP-6:VEC_LOOP/VEC_LOOP:read_mem(vec:rsc.@)#10 CSTEPS_FROM {{.. == 1}}
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/STAGE_LOOP/COMP_LOOP/COMP_LOOP-6:VEC_LOOP/VEC_LOOP:acc#23 CSTEPS_FROM {{.. == 1}}
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/STAGE_LOOP/COMP_LOOP/COMP_LOOP-6:VEC_LOOP/COMP_LOOP-6:VEC_LOOP:acc#10 CSTEPS_FROM {{.. == 1}}
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/STAGE_LOOP/COMP_LOOP/COMP_LOOP-6:VEC_LOOP/VEC_LOOP:read_mem(vec:rsc.@)#11 CSTEPS_FROM {{.. == 1}}
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/STAGE_LOOP/COMP_LOOP/COMP_LOOP-6:VEC_LOOP/COMP_LOOP-6:mult:z:mul CSTEPS_FROM {{.. == 4}}
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/STAGE_LOOP/COMP_LOOP/COMP_LOOP-6:VEC_LOOP/COMP_LOOP-6:mult:t:mul CSTEPS_FROM {{.. == 3}}
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/STAGE_LOOP/COMP_LOOP/COMP_LOOP-6:VEC_LOOP/COMP_LOOP-6:mult:z_:mul CSTEPS_FROM {{.. == 5}}
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/STAGE_LOOP/COMP_LOOP/COMP_LOOP-6:VEC_LOOP/COMP_LOOP-6:mult:res:acc CSTEPS_FROM {{.. == 5}}
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/STAGE_LOOP/COMP_LOOP/COMP_LOOP-6:VEC_LOOP/mult:if:acc#5 CSTEPS_FROM {{.. == 6}}
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/STAGE_LOOP/COMP_LOOP/COMP_LOOP-6:VEC_LOOP/COMP_LOOP-6:mult:if:acc CSTEPS_FROM {{.. == 6}}
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/STAGE_LOOP/COMP_LOOP/COMP_LOOP-6:VEC_LOOP/mult:mux#5 CSTEPS_FROM {{.. == 6}}
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/STAGE_LOOP/COMP_LOOP/COMP_LOOP-6:VEC_LOOP/COMP_LOOP-6:VEC_LOOP:acc#5 CSTEPS_FROM {{.. == 6}}
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/STAGE_LOOP/COMP_LOOP/COMP_LOOP-6:VEC_LOOP/COMP_LOOP-6:modulo_add() CSTEPS_FROM {{.. == 6}}
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/STAGE_LOOP/COMP_LOOP/COMP_LOOP-6:VEC_LOOP/VEC_LOOP:write_mem(vec:rsc.@)#10 CSTEPS_FROM {{.. == 7}}
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/STAGE_LOOP/COMP_LOOP/COMP_LOOP-6:VEC_LOOP/COMP_LOOP-6:VEC_LOOP:acc#8 CSTEPS_FROM {{.. == 6}}
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/STAGE_LOOP/COMP_LOOP/COMP_LOOP-6:VEC_LOOP/COMP_LOOP-6:modulo_sub() CSTEPS_FROM {{.. == 6}}
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/STAGE_LOOP/COMP_LOOP/COMP_LOOP-6:VEC_LOOP/VEC_LOOP:write_mem(vec:rsc.@)#11 CSTEPS_FROM {{.. == 8}}
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/STAGE_LOOP/COMP_LOOP/COMP_LOOP-6:VEC_LOOP/COMP_LOOP-6:VEC_LOOP:acc#9 CSTEPS_FROM {{.. == 1}}
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/STAGE_LOOP/COMP_LOOP/COMP_LOOP-7:acc CSTEPS_FROM {{.. == 8}}
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/STAGE_LOOP/COMP_LOOP/COMP_LOOP-7:twiddle_f:mul CSTEPS_FROM {{.. == 6}}
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/STAGE_LOOP/COMP_LOOP/COMP_LOOP:twiddle_f:read_mem(twiddle:rsc.@)#6 CSTEPS_FROM {{.. == 6}}
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/STAGE_LOOP/COMP_LOOP/COMP_LOOP:twiddle_help:read_mem(twiddle_h:rsc.@)#6 CSTEPS_FROM {{.. == 6}}
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/STAGE_LOOP/COMP_LOOP/COMP_LOOP-7:VEC_LOOP/VEC_LOOP:acc#13 CSTEPS_FROM {{.. == 1}}
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/STAGE_LOOP/COMP_LOOP/COMP_LOOP-7:VEC_LOOP/VEC_LOOP:read_mem(vec:rsc.@)#12 CSTEPS_FROM {{.. == 1}}
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/STAGE_LOOP/COMP_LOOP/COMP_LOOP-7:VEC_LOOP/VEC_LOOP:acc#24 CSTEPS_FROM {{.. == 1}}
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/STAGE_LOOP/COMP_LOOP/COMP_LOOP-7:VEC_LOOP/COMP_LOOP-7:VEC_LOOP:acc#10 CSTEPS_FROM {{.. == 1}}
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/STAGE_LOOP/COMP_LOOP/COMP_LOOP-7:VEC_LOOP/VEC_LOOP:read_mem(vec:rsc.@)#13 CSTEPS_FROM {{.. == 1}}
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/STAGE_LOOP/COMP_LOOP/COMP_LOOP-7:VEC_LOOP/COMP_LOOP-7:mult:z:mul CSTEPS_FROM {{.. == 4}}
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/STAGE_LOOP/COMP_LOOP/COMP_LOOP-7:VEC_LOOP/COMP_LOOP-7:mult:t:mul CSTEPS_FROM {{.. == 3}}
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/STAGE_LOOP/COMP_LOOP/COMP_LOOP-7:VEC_LOOP/COMP_LOOP-7:mult:z_:mul CSTEPS_FROM {{.. == 5}}
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/STAGE_LOOP/COMP_LOOP/COMP_LOOP-7:VEC_LOOP/COMP_LOOP-7:mult:res:acc CSTEPS_FROM {{.. == 5}}
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/STAGE_LOOP/COMP_LOOP/COMP_LOOP-7:VEC_LOOP/mult:if:acc#6 CSTEPS_FROM {{.. == 6}}
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/STAGE_LOOP/COMP_LOOP/COMP_LOOP-7:VEC_LOOP/COMP_LOOP-7:mult:if:acc CSTEPS_FROM {{.. == 6}}
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/STAGE_LOOP/COMP_LOOP/COMP_LOOP-7:VEC_LOOP/mult:mux#6 CSTEPS_FROM {{.. == 6}}
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/STAGE_LOOP/COMP_LOOP/COMP_LOOP-7:VEC_LOOP/COMP_LOOP-7:VEC_LOOP:acc#5 CSTEPS_FROM {{.. == 6}}
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/STAGE_LOOP/COMP_LOOP/COMP_LOOP-7:VEC_LOOP/COMP_LOOP-7:modulo_add() CSTEPS_FROM {{.. == 6}}
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/STAGE_LOOP/COMP_LOOP/COMP_LOOP-7:VEC_LOOP/VEC_LOOP:write_mem(vec:rsc.@)#12 CSTEPS_FROM {{.. == 7}}
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/STAGE_LOOP/COMP_LOOP/COMP_LOOP-7:VEC_LOOP/COMP_LOOP-7:VEC_LOOP:acc#8 CSTEPS_FROM {{.. == 6}}
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/STAGE_LOOP/COMP_LOOP/COMP_LOOP-7:VEC_LOOP/COMP_LOOP-7:modulo_sub() CSTEPS_FROM {{.. == 6}}
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/STAGE_LOOP/COMP_LOOP/COMP_LOOP-7:VEC_LOOP/VEC_LOOP:write_mem(vec:rsc.@)#13 CSTEPS_FROM {{.. == 8}}
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/STAGE_LOOP/COMP_LOOP/COMP_LOOP-7:VEC_LOOP/COMP_LOOP-7:VEC_LOOP:acc#9 CSTEPS_FROM {{.. == 1}}
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/STAGE_LOOP/COMP_LOOP/COMP_LOOP:acc#2 CSTEPS_FROM {{.. == 9}}
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/STAGE_LOOP/COMP_LOOP/COMP_LOOP-8:twiddle_f:mul CSTEPS_FROM {{.. == 7}}
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/STAGE_LOOP/COMP_LOOP/COMP_LOOP:twiddle_f:read_mem(twiddle:rsc.@)#7 CSTEPS_FROM {{.. == 7}}
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/STAGE_LOOP/COMP_LOOP/COMP_LOOP:twiddle_help:read_mem(twiddle_h:rsc.@)#7 CSTEPS_FROM {{.. == 7}}
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/STAGE_LOOP/COMP_LOOP/COMP_LOOP-8:VEC_LOOP/COMP_LOOP-8:VEC_LOOP:acc#1 CSTEPS_FROM {{.. == 1}}
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/STAGE_LOOP/COMP_LOOP/COMP_LOOP-8:VEC_LOOP/VEC_LOOP:read_mem(vec:rsc.@)#14 CSTEPS_FROM {{.. == 1}}
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/STAGE_LOOP/COMP_LOOP/COMP_LOOP-8:VEC_LOOP/VEC_LOOP:acc#25 CSTEPS_FROM {{.. == 1}}
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/STAGE_LOOP/COMP_LOOP/COMP_LOOP-8:VEC_LOOP/COMP_LOOP-8:VEC_LOOP:acc#10 CSTEPS_FROM {{.. == 1}}
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/STAGE_LOOP/COMP_LOOP/COMP_LOOP-8:VEC_LOOP/VEC_LOOP:read_mem(vec:rsc.@)#15 CSTEPS_FROM {{.. == 1}}
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/STAGE_LOOP/COMP_LOOP/COMP_LOOP-8:VEC_LOOP/COMP_LOOP-8:mult:z:mul CSTEPS_FROM {{.. == 4}}
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/STAGE_LOOP/COMP_LOOP/COMP_LOOP-8:VEC_LOOP/COMP_LOOP-8:mult:t:mul CSTEPS_FROM {{.. == 3}}
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/STAGE_LOOP/COMP_LOOP/COMP_LOOP-8:VEC_LOOP/COMP_LOOP-8:mult:z_:mul CSTEPS_FROM {{.. == 5}}
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/STAGE_LOOP/COMP_LOOP/COMP_LOOP-8:VEC_LOOP/COMP_LOOP-8:mult:res:acc CSTEPS_FROM {{.. == 5}}
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/STAGE_LOOP/COMP_LOOP/COMP_LOOP-8:VEC_LOOP/mult:if:acc#7 CSTEPS_FROM {{.. == 6}}
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/STAGE_LOOP/COMP_LOOP/COMP_LOOP-8:VEC_LOOP/COMP_LOOP-8:mult:if:acc CSTEPS_FROM {{.. == 6}}
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/STAGE_LOOP/COMP_LOOP/COMP_LOOP-8:VEC_LOOP/mult:mux#7 CSTEPS_FROM {{.. == 6}}
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/STAGE_LOOP/COMP_LOOP/COMP_LOOP-8:VEC_LOOP/COMP_LOOP-8:VEC_LOOP:acc#5 CSTEPS_FROM {{.. == 6}}
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/STAGE_LOOP/COMP_LOOP/COMP_LOOP-8:VEC_LOOP/COMP_LOOP-8:modulo_add() CSTEPS_FROM {{.. == 6}}
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/STAGE_LOOP/COMP_LOOP/COMP_LOOP-8:VEC_LOOP/VEC_LOOP:write_mem(vec:rsc.@)#14 CSTEPS_FROM {{.. == 7}}
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/STAGE_LOOP/COMP_LOOP/COMP_LOOP-8:VEC_LOOP/COMP_LOOP-8:VEC_LOOP:acc#8 CSTEPS_FROM {{.. == 6}}
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/STAGE_LOOP/COMP_LOOP/COMP_LOOP-8:VEC_LOOP/COMP_LOOP-8:modulo_sub() CSTEPS_FROM {{.. == 6}}
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/STAGE_LOOP/COMP_LOOP/COMP_LOOP-8:VEC_LOOP/VEC_LOOP:write_mem(vec:rsc.@)#15 CSTEPS_FROM {{.. == 8}}
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/STAGE_LOOP/COMP_LOOP/COMP_LOOP-8:VEC_LOOP/COMP_LOOP-8:VEC_LOOP:acc#9 CSTEPS_FROM {{.. == 1}}
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/STAGE_LOOP/COMP_LOOP/COMP_LOOP-9:acc CSTEPS_FROM {{.. == 10}}
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/STAGE_LOOP/COMP_LOOP/COMP_LOOP-9:twiddle_f:lshift CSTEPS_FROM {{.. == 1}}
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/STAGE_LOOP/COMP_LOOP/COMP_LOOP-9:twiddle_f:mul CSTEPS_FROM {{.. == 8}}
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/STAGE_LOOP/COMP_LOOP/COMP_LOOP:twiddle_f:read_mem(twiddle:rsc.@)#8 CSTEPS_FROM {{.. == 8}}
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/STAGE_LOOP/COMP_LOOP/COMP_LOOP:twiddle_help:read_mem(twiddle_h:rsc.@)#8 CSTEPS_FROM {{.. == 8}}
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/STAGE_LOOP/COMP_LOOP/COMP_LOOP-9:VEC_LOOP/VEC_LOOP:acc#14 CSTEPS_FROM {{.. == 1}}
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/STAGE_LOOP/COMP_LOOP/COMP_LOOP-9:VEC_LOOP/VEC_LOOP:read_mem(vec:rsc.@)#16 CSTEPS_FROM {{.. == 1}}
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/STAGE_LOOP/COMP_LOOP/COMP_LOOP-9:VEC_LOOP/VEC_LOOP:acc#26 CSTEPS_FROM {{.. == 1}}
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/STAGE_LOOP/COMP_LOOP/COMP_LOOP-9:VEC_LOOP/COMP_LOOP-9:VEC_LOOP:acc#10 CSTEPS_FROM {{.. == 1}}
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/STAGE_LOOP/COMP_LOOP/COMP_LOOP-9:VEC_LOOP/VEC_LOOP:read_mem(vec:rsc.@)#17 CSTEPS_FROM {{.. == 1}}
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/STAGE_LOOP/COMP_LOOP/COMP_LOOP-9:VEC_LOOP/COMP_LOOP-9:mult:z:mul CSTEPS_FROM {{.. == 4}}
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/STAGE_LOOP/COMP_LOOP/COMP_LOOP-9:VEC_LOOP/COMP_LOOP-9:mult:t:mul CSTEPS_FROM {{.. == 3}}
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/STAGE_LOOP/COMP_LOOP/COMP_LOOP-9:VEC_LOOP/COMP_LOOP-9:mult:z_:mul CSTEPS_FROM {{.. == 5}}
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/STAGE_LOOP/COMP_LOOP/COMP_LOOP-9:VEC_LOOP/COMP_LOOP-9:mult:res:acc CSTEPS_FROM {{.. == 5}}
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/STAGE_LOOP/COMP_LOOP/COMP_LOOP-9:VEC_LOOP/mult:if:acc#8 CSTEPS_FROM {{.. == 6}}
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/STAGE_LOOP/COMP_LOOP/COMP_LOOP-9:VEC_LOOP/COMP_LOOP-9:mult:if:acc CSTEPS_FROM {{.. == 6}}
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/STAGE_LOOP/COMP_LOOP/COMP_LOOP-9:VEC_LOOP/mult:mux#8 CSTEPS_FROM {{.. == 6}}
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/STAGE_LOOP/COMP_LOOP/COMP_LOOP-9:VEC_LOOP/COMP_LOOP-9:VEC_LOOP:acc#5 CSTEPS_FROM {{.. == 6}}
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/STAGE_LOOP/COMP_LOOP/COMP_LOOP-9:VEC_LOOP/COMP_LOOP-9:modulo_add() CSTEPS_FROM {{.. == 6}}
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/STAGE_LOOP/COMP_LOOP/COMP_LOOP-9:VEC_LOOP/VEC_LOOP:write_mem(vec:rsc.@)#16 CSTEPS_FROM {{.. == 7}}
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/STAGE_LOOP/COMP_LOOP/COMP_LOOP-9:VEC_LOOP/COMP_LOOP-9:VEC_LOOP:acc#8 CSTEPS_FROM {{.. == 6}}
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/STAGE_LOOP/COMP_LOOP/COMP_LOOP-9:VEC_LOOP/COMP_LOOP-9:modulo_sub() CSTEPS_FROM {{.. == 6}}
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/STAGE_LOOP/COMP_LOOP/COMP_LOOP-9:VEC_LOOP/VEC_LOOP:write_mem(vec:rsc.@)#17 CSTEPS_FROM {{.. == 8}}
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/STAGE_LOOP/COMP_LOOP/COMP_LOOP-9:VEC_LOOP/COMP_LOOP-9:VEC_LOOP:acc#9 CSTEPS_FROM {{.. == 1}}
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/STAGE_LOOP/COMP_LOOP/COMP_LOOP-10:acc CSTEPS_FROM {{.. == 11}}
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/STAGE_LOOP/COMP_LOOP/COMP_LOOP-10:twiddle_f:mul CSTEPS_FROM {{.. == 9}}
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/STAGE_LOOP/COMP_LOOP/COMP_LOOP:twiddle_f:read_mem(twiddle:rsc.@)#9 CSTEPS_FROM {{.. == 9}}
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/STAGE_LOOP/COMP_LOOP/COMP_LOOP:twiddle_help:read_mem(twiddle_h:rsc.@)#9 CSTEPS_FROM {{.. == 9}}
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/STAGE_LOOP/COMP_LOOP/COMP_LOOP-10:VEC_LOOP/COMP_LOOP-10:VEC_LOOP:acc#1 CSTEPS_FROM {{.. == 1}}
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/STAGE_LOOP/COMP_LOOP/COMP_LOOP-10:VEC_LOOP/VEC_LOOP:read_mem(vec:rsc.@)#18 CSTEPS_FROM {{.. == 1}}
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/STAGE_LOOP/COMP_LOOP/COMP_LOOP-10:VEC_LOOP/VEC_LOOP:acc#27 CSTEPS_FROM {{.. == 1}}
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/STAGE_LOOP/COMP_LOOP/COMP_LOOP-10:VEC_LOOP/COMP_LOOP-10:VEC_LOOP:acc#10 CSTEPS_FROM {{.. == 1}}
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/STAGE_LOOP/COMP_LOOP/COMP_LOOP-10:VEC_LOOP/VEC_LOOP:read_mem(vec:rsc.@)#19 CSTEPS_FROM {{.. == 1}}
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/STAGE_LOOP/COMP_LOOP/COMP_LOOP-10:VEC_LOOP/COMP_LOOP-10:mult:z:mul CSTEPS_FROM {{.. == 4}}
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/STAGE_LOOP/COMP_LOOP/COMP_LOOP-10:VEC_LOOP/COMP_LOOP-10:mult:t:mul CSTEPS_FROM {{.. == 3}}
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/STAGE_LOOP/COMP_LOOP/COMP_LOOP-10:VEC_LOOP/COMP_LOOP-10:mult:z_:mul CSTEPS_FROM {{.. == 5}}
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/STAGE_LOOP/COMP_LOOP/COMP_LOOP-10:VEC_LOOP/COMP_LOOP-10:mult:res:acc CSTEPS_FROM {{.. == 5}}
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/STAGE_LOOP/COMP_LOOP/COMP_LOOP-10:VEC_LOOP/mult:if:acc#9 CSTEPS_FROM {{.. == 6}}
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/STAGE_LOOP/COMP_LOOP/COMP_LOOP-10:VEC_LOOP/COMP_LOOP-10:mult:if:acc CSTEPS_FROM {{.. == 6}}
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/STAGE_LOOP/COMP_LOOP/COMP_LOOP-10:VEC_LOOP/mult:mux#9 CSTEPS_FROM {{.. == 6}}
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/STAGE_LOOP/COMP_LOOP/COMP_LOOP-10:VEC_LOOP/COMP_LOOP-10:VEC_LOOP:acc#5 CSTEPS_FROM {{.. == 6}}
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/STAGE_LOOP/COMP_LOOP/COMP_LOOP-10:VEC_LOOP/COMP_LOOP-10:modulo_add() CSTEPS_FROM {{.. == 6}}
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/STAGE_LOOP/COMP_LOOP/COMP_LOOP-10:VEC_LOOP/VEC_LOOP:write_mem(vec:rsc.@)#18 CSTEPS_FROM {{.. == 7}}
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/STAGE_LOOP/COMP_LOOP/COMP_LOOP-10:VEC_LOOP/COMP_LOOP-10:VEC_LOOP:acc#8 CSTEPS_FROM {{.. == 6}}
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/STAGE_LOOP/COMP_LOOP/COMP_LOOP-10:VEC_LOOP/COMP_LOOP-10:modulo_sub() CSTEPS_FROM {{.. == 6}}
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/STAGE_LOOP/COMP_LOOP/COMP_LOOP-10:VEC_LOOP/VEC_LOOP:write_mem(vec:rsc.@)#19 CSTEPS_FROM {{.. == 8}}
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/STAGE_LOOP/COMP_LOOP/COMP_LOOP-10:VEC_LOOP/COMP_LOOP-10:VEC_LOOP:acc#9 CSTEPS_FROM {{.. == 1}}
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/STAGE_LOOP/COMP_LOOP/COMP_LOOP-11:acc CSTEPS_FROM {{.. == 12}}
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/STAGE_LOOP/COMP_LOOP/COMP_LOOP-11:twiddle_f:mul CSTEPS_FROM {{.. == 10}}
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/STAGE_LOOP/COMP_LOOP/COMP_LOOP:twiddle_f:read_mem(twiddle:rsc.@)#10 CSTEPS_FROM {{.. == 10}}
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/STAGE_LOOP/COMP_LOOP/COMP_LOOP:twiddle_help:read_mem(twiddle_h:rsc.@)#10 CSTEPS_FROM {{.. == 10}}
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/STAGE_LOOP/COMP_LOOP/COMP_LOOP-11:VEC_LOOP/VEC_LOOP:acc#15 CSTEPS_FROM {{.. == 1}}
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/STAGE_LOOP/COMP_LOOP/COMP_LOOP-11:VEC_LOOP/VEC_LOOP:read_mem(vec:rsc.@)#20 CSTEPS_FROM {{.. == 1}}
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/STAGE_LOOP/COMP_LOOP/COMP_LOOP-11:VEC_LOOP/VEC_LOOP:acc#28 CSTEPS_FROM {{.. == 1}}
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/STAGE_LOOP/COMP_LOOP/COMP_LOOP-11:VEC_LOOP/COMP_LOOP-11:VEC_LOOP:acc#10 CSTEPS_FROM {{.. == 1}}
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/STAGE_LOOP/COMP_LOOP/COMP_LOOP-11:VEC_LOOP/VEC_LOOP:read_mem(vec:rsc.@)#21 CSTEPS_FROM {{.. == 1}}
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/STAGE_LOOP/COMP_LOOP/COMP_LOOP-11:VEC_LOOP/COMP_LOOP-11:mult:z:mul CSTEPS_FROM {{.. == 4}}
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/STAGE_LOOP/COMP_LOOP/COMP_LOOP-11:VEC_LOOP/COMP_LOOP-11:mult:t:mul CSTEPS_FROM {{.. == 3}}
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/STAGE_LOOP/COMP_LOOP/COMP_LOOP-11:VEC_LOOP/COMP_LOOP-11:mult:z_:mul CSTEPS_FROM {{.. == 5}}
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/STAGE_LOOP/COMP_LOOP/COMP_LOOP-11:VEC_LOOP/COMP_LOOP-11:mult:res:acc CSTEPS_FROM {{.. == 5}}
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/STAGE_LOOP/COMP_LOOP/COMP_LOOP-11:VEC_LOOP/mult:if:acc#10 CSTEPS_FROM {{.. == 6}}
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/STAGE_LOOP/COMP_LOOP/COMP_LOOP-11:VEC_LOOP/COMP_LOOP-11:mult:if:acc CSTEPS_FROM {{.. == 6}}
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/STAGE_LOOP/COMP_LOOP/COMP_LOOP-11:VEC_LOOP/mult:mux#10 CSTEPS_FROM {{.. == 6}}
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/STAGE_LOOP/COMP_LOOP/COMP_LOOP-11:VEC_LOOP/COMP_LOOP-11:VEC_LOOP:acc#5 CSTEPS_FROM {{.. == 6}}
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/STAGE_LOOP/COMP_LOOP/COMP_LOOP-11:VEC_LOOP/COMP_LOOP-11:modulo_add() CSTEPS_FROM {{.. == 6}}
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/STAGE_LOOP/COMP_LOOP/COMP_LOOP-11:VEC_LOOP/VEC_LOOP:write_mem(vec:rsc.@)#20 CSTEPS_FROM {{.. == 7}}
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/STAGE_LOOP/COMP_LOOP/COMP_LOOP-11:VEC_LOOP/COMP_LOOP-11:VEC_LOOP:acc#8 CSTEPS_FROM {{.. == 6}}
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/STAGE_LOOP/COMP_LOOP/COMP_LOOP-11:VEC_LOOP/COMP_LOOP-11:modulo_sub() CSTEPS_FROM {{.. == 6}}
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/STAGE_LOOP/COMP_LOOP/COMP_LOOP-11:VEC_LOOP/VEC_LOOP:write_mem(vec:rsc.@)#21 CSTEPS_FROM {{.. == 8}}
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/STAGE_LOOP/COMP_LOOP/COMP_LOOP-11:VEC_LOOP/COMP_LOOP-11:VEC_LOOP:acc#9 CSTEPS_FROM {{.. == 1}}
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/STAGE_LOOP/COMP_LOOP/COMP_LOOP:acc#3 CSTEPS_FROM {{.. == 13}}
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/STAGE_LOOP/COMP_LOOP/COMP_LOOP-12:twiddle_f:mul CSTEPS_FROM {{.. == 11}}
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/STAGE_LOOP/COMP_LOOP/COMP_LOOP:twiddle_f:read_mem(twiddle:rsc.@)#11 CSTEPS_FROM {{.. == 11}}
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/STAGE_LOOP/COMP_LOOP/COMP_LOOP:twiddle_help:read_mem(twiddle_h:rsc.@)#11 CSTEPS_FROM {{.. == 11}}
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/STAGE_LOOP/COMP_LOOP/COMP_LOOP-12:VEC_LOOP/COMP_LOOP-12:VEC_LOOP:acc#1 CSTEPS_FROM {{.. == 1}}
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/STAGE_LOOP/COMP_LOOP/COMP_LOOP-12:VEC_LOOP/VEC_LOOP:read_mem(vec:rsc.@)#22 CSTEPS_FROM {{.. == 1}}
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/STAGE_LOOP/COMP_LOOP/COMP_LOOP-12:VEC_LOOP/VEC_LOOP:acc#29 CSTEPS_FROM {{.. == 1}}
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/STAGE_LOOP/COMP_LOOP/COMP_LOOP-12:VEC_LOOP/COMP_LOOP-12:VEC_LOOP:acc#10 CSTEPS_FROM {{.. == 1}}
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/STAGE_LOOP/COMP_LOOP/COMP_LOOP-12:VEC_LOOP/VEC_LOOP:read_mem(vec:rsc.@)#23 CSTEPS_FROM {{.. == 1}}
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/STAGE_LOOP/COMP_LOOP/COMP_LOOP-12:VEC_LOOP/COMP_LOOP-12:mult:z:mul CSTEPS_FROM {{.. == 4}}
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/STAGE_LOOP/COMP_LOOP/COMP_LOOP-12:VEC_LOOP/COMP_LOOP-12:mult:t:mul CSTEPS_FROM {{.. == 3}}
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/STAGE_LOOP/COMP_LOOP/COMP_LOOP-12:VEC_LOOP/COMP_LOOP-12:mult:z_:mul CSTEPS_FROM {{.. == 5}}
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/STAGE_LOOP/COMP_LOOP/COMP_LOOP-12:VEC_LOOP/COMP_LOOP-12:mult:res:acc CSTEPS_FROM {{.. == 5}}
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/STAGE_LOOP/COMP_LOOP/COMP_LOOP-12:VEC_LOOP/mult:if:acc#11 CSTEPS_FROM {{.. == 6}}
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/STAGE_LOOP/COMP_LOOP/COMP_LOOP-12:VEC_LOOP/COMP_LOOP-12:mult:if:acc CSTEPS_FROM {{.. == 6}}
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/STAGE_LOOP/COMP_LOOP/COMP_LOOP-12:VEC_LOOP/mult:mux#11 CSTEPS_FROM {{.. == 6}}
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/STAGE_LOOP/COMP_LOOP/COMP_LOOP-12:VEC_LOOP/COMP_LOOP-12:VEC_LOOP:acc#5 CSTEPS_FROM {{.. == 6}}
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/STAGE_LOOP/COMP_LOOP/COMP_LOOP-12:VEC_LOOP/COMP_LOOP-12:modulo_add() CSTEPS_FROM {{.. == 6}}
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/STAGE_LOOP/COMP_LOOP/COMP_LOOP-12:VEC_LOOP/VEC_LOOP:write_mem(vec:rsc.@)#22 CSTEPS_FROM {{.. == 7}}
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/STAGE_LOOP/COMP_LOOP/COMP_LOOP-12:VEC_LOOP/COMP_LOOP-12:VEC_LOOP:acc#8 CSTEPS_FROM {{.. == 6}}
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/STAGE_LOOP/COMP_LOOP/COMP_LOOP-12:VEC_LOOP/COMP_LOOP-12:modulo_sub() CSTEPS_FROM {{.. == 6}}
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/STAGE_LOOP/COMP_LOOP/COMP_LOOP-12:VEC_LOOP/VEC_LOOP:write_mem(vec:rsc.@)#23 CSTEPS_FROM {{.. == 8}}
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/STAGE_LOOP/COMP_LOOP/COMP_LOOP-12:VEC_LOOP/COMP_LOOP-12:VEC_LOOP:acc#9 CSTEPS_FROM {{.. == 1}}
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/STAGE_LOOP/COMP_LOOP/COMP_LOOP-13:acc CSTEPS_FROM {{.. == 14}}
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/STAGE_LOOP/COMP_LOOP/COMP_LOOP-13:twiddle_f:mul CSTEPS_FROM {{.. == 12}}
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/STAGE_LOOP/COMP_LOOP/COMP_LOOP:twiddle_f:read_mem(twiddle:rsc.@)#12 CSTEPS_FROM {{.. == 12}}
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/STAGE_LOOP/COMP_LOOP/COMP_LOOP:twiddle_help:read_mem(twiddle_h:rsc.@)#12 CSTEPS_FROM {{.. == 12}}
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/STAGE_LOOP/COMP_LOOP/COMP_LOOP-13:VEC_LOOP/VEC_LOOP:acc#16 CSTEPS_FROM {{.. == 1}}
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/STAGE_LOOP/COMP_LOOP/COMP_LOOP-13:VEC_LOOP/VEC_LOOP:read_mem(vec:rsc.@)#24 CSTEPS_FROM {{.. == 1}}
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/STAGE_LOOP/COMP_LOOP/COMP_LOOP-13:VEC_LOOP/VEC_LOOP:acc#30 CSTEPS_FROM {{.. == 1}}
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/STAGE_LOOP/COMP_LOOP/COMP_LOOP-13:VEC_LOOP/COMP_LOOP-13:VEC_LOOP:acc#10 CSTEPS_FROM {{.. == 1}}
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/STAGE_LOOP/COMP_LOOP/COMP_LOOP-13:VEC_LOOP/VEC_LOOP:read_mem(vec:rsc.@)#25 CSTEPS_FROM {{.. == 1}}
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/STAGE_LOOP/COMP_LOOP/COMP_LOOP-13:VEC_LOOP/COMP_LOOP-13:mult:z:mul CSTEPS_FROM {{.. == 4}}
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/STAGE_LOOP/COMP_LOOP/COMP_LOOP-13:VEC_LOOP/COMP_LOOP-13:mult:t:mul CSTEPS_FROM {{.. == 3}}
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/STAGE_LOOP/COMP_LOOP/COMP_LOOP-13:VEC_LOOP/COMP_LOOP-13:mult:z_:mul CSTEPS_FROM {{.. == 5}}
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/STAGE_LOOP/COMP_LOOP/COMP_LOOP-13:VEC_LOOP/COMP_LOOP-13:mult:res:acc CSTEPS_FROM {{.. == 5}}
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/STAGE_LOOP/COMP_LOOP/COMP_LOOP-13:VEC_LOOP/mult:if:acc#12 CSTEPS_FROM {{.. == 6}}
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/STAGE_LOOP/COMP_LOOP/COMP_LOOP-13:VEC_LOOP/COMP_LOOP-13:mult:if:acc CSTEPS_FROM {{.. == 6}}
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/STAGE_LOOP/COMP_LOOP/COMP_LOOP-13:VEC_LOOP/mult:mux#12 CSTEPS_FROM {{.. == 6}}
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/STAGE_LOOP/COMP_LOOP/COMP_LOOP-13:VEC_LOOP/COMP_LOOP-13:VEC_LOOP:acc#5 CSTEPS_FROM {{.. == 6}}
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/STAGE_LOOP/COMP_LOOP/COMP_LOOP-13:VEC_LOOP/COMP_LOOP-13:modulo_add() CSTEPS_FROM {{.. == 6}}
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/STAGE_LOOP/COMP_LOOP/COMP_LOOP-13:VEC_LOOP/VEC_LOOP:write_mem(vec:rsc.@)#24 CSTEPS_FROM {{.. == 7}}
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/STAGE_LOOP/COMP_LOOP/COMP_LOOP-13:VEC_LOOP/COMP_LOOP-13:VEC_LOOP:acc#8 CSTEPS_FROM {{.. == 6}}
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/STAGE_LOOP/COMP_LOOP/COMP_LOOP-13:VEC_LOOP/COMP_LOOP-13:modulo_sub() CSTEPS_FROM {{.. == 6}}
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/STAGE_LOOP/COMP_LOOP/COMP_LOOP-13:VEC_LOOP/VEC_LOOP:write_mem(vec:rsc.@)#25 CSTEPS_FROM {{.. == 8}}
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/STAGE_LOOP/COMP_LOOP/COMP_LOOP-13:VEC_LOOP/COMP_LOOP-13:VEC_LOOP:acc#9 CSTEPS_FROM {{.. == 1}}
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/STAGE_LOOP/COMP_LOOP/COMP_LOOP-14:acc CSTEPS_FROM {{.. == 15}}
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/STAGE_LOOP/COMP_LOOP/COMP_LOOP-14:twiddle_f:mul CSTEPS_FROM {{.. == 13}}
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/STAGE_LOOP/COMP_LOOP/COMP_LOOP:twiddle_f:read_mem(twiddle:rsc.@)#13 CSTEPS_FROM {{.. == 13}}
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/STAGE_LOOP/COMP_LOOP/COMP_LOOP:twiddle_help:read_mem(twiddle_h:rsc.@)#13 CSTEPS_FROM {{.. == 13}}
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/STAGE_LOOP/COMP_LOOP/COMP_LOOP-14:VEC_LOOP/COMP_LOOP-14:VEC_LOOP:acc#1 CSTEPS_FROM {{.. == 1}}
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/STAGE_LOOP/COMP_LOOP/COMP_LOOP-14:VEC_LOOP/VEC_LOOP:read_mem(vec:rsc.@)#26 CSTEPS_FROM {{.. == 1}}
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/STAGE_LOOP/COMP_LOOP/COMP_LOOP-14:VEC_LOOP/VEC_LOOP:acc#31 CSTEPS_FROM {{.. == 1}}
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/STAGE_LOOP/COMP_LOOP/COMP_LOOP-14:VEC_LOOP/COMP_LOOP-14:VEC_LOOP:acc#10 CSTEPS_FROM {{.. == 1}}
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/STAGE_LOOP/COMP_LOOP/COMP_LOOP-14:VEC_LOOP/VEC_LOOP:read_mem(vec:rsc.@)#27 CSTEPS_FROM {{.. == 1}}
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/STAGE_LOOP/COMP_LOOP/COMP_LOOP-14:VEC_LOOP/COMP_LOOP-14:mult:z:mul CSTEPS_FROM {{.. == 4}}
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/STAGE_LOOP/COMP_LOOP/COMP_LOOP-14:VEC_LOOP/COMP_LOOP-14:mult:t:mul CSTEPS_FROM {{.. == 3}}
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/STAGE_LOOP/COMP_LOOP/COMP_LOOP-14:VEC_LOOP/COMP_LOOP-14:mult:z_:mul CSTEPS_FROM {{.. == 5}}
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/STAGE_LOOP/COMP_LOOP/COMP_LOOP-14:VEC_LOOP/COMP_LOOP-14:mult:res:acc CSTEPS_FROM {{.. == 5}}
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/STAGE_LOOP/COMP_LOOP/COMP_LOOP-14:VEC_LOOP/mult:if:acc#13 CSTEPS_FROM {{.. == 6}}
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/STAGE_LOOP/COMP_LOOP/COMP_LOOP-14:VEC_LOOP/COMP_LOOP-14:mult:if:acc CSTEPS_FROM {{.. == 6}}
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/STAGE_LOOP/COMP_LOOP/COMP_LOOP-14:VEC_LOOP/mult:mux#13 CSTEPS_FROM {{.. == 6}}
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/STAGE_LOOP/COMP_LOOP/COMP_LOOP-14:VEC_LOOP/COMP_LOOP-14:VEC_LOOP:acc#5 CSTEPS_FROM {{.. == 6}}
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/STAGE_LOOP/COMP_LOOP/COMP_LOOP-14:VEC_LOOP/COMP_LOOP-14:modulo_add() CSTEPS_FROM {{.. == 6}}
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/STAGE_LOOP/COMP_LOOP/COMP_LOOP-14:VEC_LOOP/VEC_LOOP:write_mem(vec:rsc.@)#26 CSTEPS_FROM {{.. == 7}}
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/STAGE_LOOP/COMP_LOOP/COMP_LOOP-14:VEC_LOOP/COMP_LOOP-14:VEC_LOOP:acc#8 CSTEPS_FROM {{.. == 6}}
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/STAGE_LOOP/COMP_LOOP/COMP_LOOP-14:VEC_LOOP/COMP_LOOP-14:modulo_sub() CSTEPS_FROM {{.. == 6}}
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/STAGE_LOOP/COMP_LOOP/COMP_LOOP-14:VEC_LOOP/VEC_LOOP:write_mem(vec:rsc.@)#27 CSTEPS_FROM {{.. == 8}}
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/STAGE_LOOP/COMP_LOOP/COMP_LOOP-14:VEC_LOOP/COMP_LOOP-14:VEC_LOOP:acc#9 CSTEPS_FROM {{.. == 1}}
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/STAGE_LOOP/COMP_LOOP/COMP_LOOP-15:acc CSTEPS_FROM {{.. == 16}}
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/STAGE_LOOP/COMP_LOOP/COMP_LOOP-15:twiddle_f:mul CSTEPS_FROM {{.. == 14}}
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/STAGE_LOOP/COMP_LOOP/COMP_LOOP:twiddle_f:read_mem(twiddle:rsc.@)#14 CSTEPS_FROM {{.. == 14}}
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/STAGE_LOOP/COMP_LOOP/COMP_LOOP:twiddle_help:read_mem(twiddle_h:rsc.@)#14 CSTEPS_FROM {{.. == 14}}
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/STAGE_LOOP/COMP_LOOP/COMP_LOOP-15:VEC_LOOP/VEC_LOOP:acc#17 CSTEPS_FROM {{.. == 1}}
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/STAGE_LOOP/COMP_LOOP/COMP_LOOP-15:VEC_LOOP/VEC_LOOP:read_mem(vec:rsc.@)#28 CSTEPS_FROM {{.. == 1}}
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/STAGE_LOOP/COMP_LOOP/COMP_LOOP-15:VEC_LOOP/VEC_LOOP:acc#32 CSTEPS_FROM {{.. == 1}}
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/STAGE_LOOP/COMP_LOOP/COMP_LOOP-15:VEC_LOOP/COMP_LOOP-15:VEC_LOOP:acc#10 CSTEPS_FROM {{.. == 1}}
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/STAGE_LOOP/COMP_LOOP/COMP_LOOP-15:VEC_LOOP/VEC_LOOP:read_mem(vec:rsc.@)#29 CSTEPS_FROM {{.. == 1}}
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/STAGE_LOOP/COMP_LOOP/COMP_LOOP-15:VEC_LOOP/COMP_LOOP-15:mult:z:mul CSTEPS_FROM {{.. == 4}}
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/STAGE_LOOP/COMP_LOOP/COMP_LOOP-15:VEC_LOOP/COMP_LOOP-15:mult:t:mul CSTEPS_FROM {{.. == 3}}
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/STAGE_LOOP/COMP_LOOP/COMP_LOOP-15:VEC_LOOP/COMP_LOOP-15:mult:z_:mul CSTEPS_FROM {{.. == 5}}
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/STAGE_LOOP/COMP_LOOP/COMP_LOOP-15:VEC_LOOP/COMP_LOOP-15:mult:res:acc CSTEPS_FROM {{.. == 5}}
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/STAGE_LOOP/COMP_LOOP/COMP_LOOP-15:VEC_LOOP/mult:if:acc#14 CSTEPS_FROM {{.. == 6}}
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/STAGE_LOOP/COMP_LOOP/COMP_LOOP-15:VEC_LOOP/COMP_LOOP-15:mult:if:acc CSTEPS_FROM {{.. == 6}}
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/STAGE_LOOP/COMP_LOOP/COMP_LOOP-15:VEC_LOOP/mult:mux#14 CSTEPS_FROM {{.. == 6}}
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/STAGE_LOOP/COMP_LOOP/COMP_LOOP-15:VEC_LOOP/COMP_LOOP-15:VEC_LOOP:acc#5 CSTEPS_FROM {{.. == 6}}
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/STAGE_LOOP/COMP_LOOP/COMP_LOOP-15:VEC_LOOP/COMP_LOOP-15:modulo_add() CSTEPS_FROM {{.. == 6}}
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/STAGE_LOOP/COMP_LOOP/COMP_LOOP-15:VEC_LOOP/VEC_LOOP:write_mem(vec:rsc.@)#28 CSTEPS_FROM {{.. == 7}}
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/STAGE_LOOP/COMP_LOOP/COMP_LOOP-15:VEC_LOOP/COMP_LOOP-15:VEC_LOOP:acc#8 CSTEPS_FROM {{.. == 6}}
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/STAGE_LOOP/COMP_LOOP/COMP_LOOP-15:VEC_LOOP/COMP_LOOP-15:modulo_sub() CSTEPS_FROM {{.. == 6}}
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/STAGE_LOOP/COMP_LOOP/COMP_LOOP-15:VEC_LOOP/VEC_LOOP:write_mem(vec:rsc.@)#29 CSTEPS_FROM {{.. == 8}}
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/STAGE_LOOP/COMP_LOOP/COMP_LOOP-15:VEC_LOOP/COMP_LOOP-15:VEC_LOOP:acc#9 CSTEPS_FROM {{.. == 1}}
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/STAGE_LOOP/COMP_LOOP/COMP_LOOP:acc#4 CSTEPS_FROM {{.. == 17}}
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/STAGE_LOOP/COMP_LOOP/COMP_LOOP-16:twiddle_f:mul CSTEPS_FROM {{.. == 1}}
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/STAGE_LOOP/COMP_LOOP/COMP_LOOP:twiddle_f:read_mem(twiddle:rsc.@)#15 CSTEPS_FROM {{.. == 8}}
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/STAGE_LOOP/COMP_LOOP/COMP_LOOP:twiddle_help:read_mem(twiddle_h:rsc.@)#15 CSTEPS_FROM {{.. == 8}}
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/STAGE_LOOP/COMP_LOOP/COMP_LOOP-16:VEC_LOOP/COMP_LOOP-16:VEC_LOOP:acc#1 CSTEPS_FROM {{.. == 1}}
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/STAGE_LOOP/COMP_LOOP/COMP_LOOP-16:VEC_LOOP/VEC_LOOP:read_mem(vec:rsc.@)#30 CSTEPS_FROM {{.. == 1}}
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/STAGE_LOOP/COMP_LOOP/COMP_LOOP-16:VEC_LOOP/VEC_LOOP:acc#33 CSTEPS_FROM {{.. == 1}}
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/STAGE_LOOP/COMP_LOOP/COMP_LOOP-16:VEC_LOOP/COMP_LOOP-16:VEC_LOOP:acc#10 CSTEPS_FROM {{.. == 1}}
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/STAGE_LOOP/COMP_LOOP/COMP_LOOP-16:VEC_LOOP/VEC_LOOP:read_mem(vec:rsc.@)#31 CSTEPS_FROM {{.. == 1}}
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/STAGE_LOOP/COMP_LOOP/COMP_LOOP-16:VEC_LOOP/COMP_LOOP-16:mult:z:mul CSTEPS_FROM {{.. == 4}}
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/STAGE_LOOP/COMP_LOOP/COMP_LOOP-16:VEC_LOOP/COMP_LOOP-16:mult:t:mul CSTEPS_FROM {{.. == 3}}
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/STAGE_LOOP/COMP_LOOP/COMP_LOOP-16:VEC_LOOP/COMP_LOOP-16:mult:z_:mul CSTEPS_FROM {{.. == 5}}
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/STAGE_LOOP/COMP_LOOP/COMP_LOOP-16:VEC_LOOP/COMP_LOOP-16:mult:res:acc CSTEPS_FROM {{.. == 5}}
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/STAGE_LOOP/COMP_LOOP/COMP_LOOP-16:VEC_LOOP/mult:if:acc#15 CSTEPS_FROM {{.. == 6}}
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/STAGE_LOOP/COMP_LOOP/COMP_LOOP-16:VEC_LOOP/COMP_LOOP-16:mult:if:acc CSTEPS_FROM {{.. == 6}}
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/STAGE_LOOP/COMP_LOOP/COMP_LOOP-16:VEC_LOOP/mult:mux#15 CSTEPS_FROM {{.. == 6}}
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/STAGE_LOOP/COMP_LOOP/COMP_LOOP-16:VEC_LOOP/COMP_LOOP-16:VEC_LOOP:acc#5 CSTEPS_FROM {{.. == 6}}
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/STAGE_LOOP/COMP_LOOP/COMP_LOOP-16:VEC_LOOP/COMP_LOOP-16:modulo_add() CSTEPS_FROM {{.. == 6}}
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/STAGE_LOOP/COMP_LOOP/COMP_LOOP-16:VEC_LOOP/VEC_LOOP:write_mem(vec:rsc.@)#30 CSTEPS_FROM {{.. == 7}}
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/STAGE_LOOP/COMP_LOOP/COMP_LOOP-16:VEC_LOOP/COMP_LOOP-16:VEC_LOOP:acc#8 CSTEPS_FROM {{.. == 6}}
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/STAGE_LOOP/COMP_LOOP/COMP_LOOP-16:VEC_LOOP/COMP_LOOP-16:modulo_sub() CSTEPS_FROM {{.. == 6}}
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/STAGE_LOOP/COMP_LOOP/COMP_LOOP-16:VEC_LOOP/VEC_LOOP:write_mem(vec:rsc.@)#31 CSTEPS_FROM {{.. == 8}}
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/STAGE_LOOP/COMP_LOOP/COMP_LOOP-16:VEC_LOOP/COMP_LOOP-16:VEC_LOOP:acc#9 CSTEPS_FROM {{.. == 1}}
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/STAGE_LOOP/COMP_LOOP/COMP_LOOP:acc#5 CSTEPS_FROM {{.. == 18}}
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/STAGE_LOOP/COMP_LOOP/COMP_LOOP-1:acc CSTEPS_FROM {{.. == 18}}
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/STAGE_LOOP/STAGE_LOOP:acc#1 CSTEPS_FROM {{.. == 2}}
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/STAGE_LOOP/STAGE_LOOP:acc CSTEPS_FROM {{.. == 2}}
directive set /inPlaceNTT_DIT_precomp/core/core:rlp/main/if:io_write(complete) CSTEPS_FROM {{.. == 1}}

# Probe constraints
