set_property SRC_FILE_INFO {cfile:D:/NTT_Xilinx/NTT_Vivado/inplace_DIF_md_4096/inplace_DIF_md_4096.srcs/constrs_1/imports/vivado_v/rtl.v.xv.sdc rfile:../../../inplace_DIF_md_4096.srcs/constrs_1/imports/vivado_v/rtl.v.xv.sdc id:1} [current_design]
set_property SRC_FILE_INFO {cfile:D:/NTT_Xilinx/NTT_Vivado/inplace_DIF_md_4096/inplace_DIF_md_4096.srcs/constrs_1/imports/vivado_v/rtl.v.xv.signoff.sdc rfile:../../../inplace_DIF_md_4096.srcs/constrs_1/imports/vivado_v/rtl.v.xv.signoff.sdc id:2} [current_design]
set_property src_info {type:XDC file:1 line:5 export:INPUT save:INPUT read:READ} [current_design]
set_clock_uncertainty 0.0 [get_clocks {clk}]
set_property src_info {type:XDC file:1 line:10 export:INPUT save:INPUT read:READ} [current_design]
set_output_delay -clock [get_clocks {clk}] 0.0 [get_ports {run_rsc_rdy}]
set_property src_info {type:XDC file:1 line:12 export:INPUT save:INPUT read:READ} [current_design]
set_output_delay -clock [get_clocks {clk}] 0.5 [get_ports {vec_rsc_adra[*]}]
set_property src_info {type:XDC file:1 line:13 export:INPUT save:INPUT read:READ} [current_design]
set_output_delay -clock [get_clocks {clk}] 0.5 [get_ports {vec_rsc_da[*]}]
set_property src_info {type:XDC file:1 line:15 export:INPUT save:INPUT read:READ} [current_design]
set_output_delay -clock [get_clocks {clk}] 0.5 [get_ports {vec_rsc_wea}]
set_property src_info {type:XDC file:1 line:16 export:INPUT save:INPUT read:READ} [current_design]
set_input_delay -clock [get_clocks {clk}] 2.4 [get_ports {vec_rsc_qa[*]}]
set_property src_info {type:XDC file:1 line:17 export:INPUT save:INPUT read:READ} [current_design]
set_output_delay -clock [get_clocks {clk}] 0.5 [get_ports {vec_rsc_adrb[*]}]
set_property src_info {type:XDC file:1 line:18 export:INPUT save:INPUT read:READ} [current_design]
set_output_delay -clock [get_clocks {clk}] 0.5 [get_ports {vec_rsc_db[*]}]
set_property src_info {type:XDC file:1 line:19 export:INPUT save:INPUT read:READ} [current_design]
set_output_delay -clock [get_clocks {clk}] 0.5 [get_ports {vec_rsc_web}]
set_property src_info {type:XDC file:1 line:20 export:INPUT save:INPUT read:READ} [current_design]
set_input_delay -clock [get_clocks {clk}] 2.4 [get_ports {vec_rsc_qb[*]}]
set_property src_info {type:XDC file:1 line:21 export:INPUT save:INPUT read:READ} [current_design]
set_output_delay -clock [get_clocks {clk}] 0.0 [get_ports {vec_rsc_triosy_lz}]
set_property src_info {type:XDC file:1 line:23 export:INPUT save:INPUT read:READ} [current_design]
set_output_delay -clock [get_clocks {clk}] 0.0 [get_ports {p_rsc_triosy_lz}]
set_property src_info {type:XDC file:1 line:25 export:INPUT save:INPUT read:READ} [current_design]
set_output_delay -clock [get_clocks {clk}] 0.0 [get_ports {r_rsc_triosy_lz}]
set_property src_info {type:XDC file:1 line:26 export:INPUT save:INPUT read:READ} [current_design]
set_output_delay -clock [get_clocks {clk}] 0.5 [get_ports {twiddle_rsc_adra[*]}]
set_property src_info {type:XDC file:1 line:27 export:INPUT save:INPUT read:READ} [current_design]
set_output_delay -clock [get_clocks {clk}] 0.5 [get_ports {twiddle_rsc_da[*]}]
set_property src_info {type:XDC file:1 line:28 export:INPUT save:INPUT read:READ} [current_design]
set_output_delay -clock [get_clocks {clk}] 0.5 [get_ports {twiddle_rsc_wea}]
set_property src_info {type:XDC file:1 line:29 export:INPUT save:INPUT read:READ} [current_design]
set_input_delay -clock [get_clocks {clk}] 2.4 [get_ports {twiddle_rsc_qa[*]}]
set_property src_info {type:XDC file:1 line:30 export:INPUT save:INPUT read:READ} [current_design]
set_output_delay -clock [get_clocks {clk}] 0.5 [get_ports {twiddle_rsc_adrb[*]}]
set_property src_info {type:XDC file:1 line:31 export:INPUT save:INPUT read:READ} [current_design]
set_output_delay -clock [get_clocks {clk}] 0.5 [get_ports {twiddle_rsc_db[*]}]
set_property src_info {type:XDC file:1 line:32 export:INPUT save:INPUT read:READ} [current_design]
set_output_delay -clock [get_clocks {clk}] 0.5 [get_ports {twiddle_rsc_web}]
set_property src_info {type:XDC file:1 line:33 export:INPUT save:INPUT read:READ} [current_design]
set_input_delay -clock [get_clocks {clk}] 2.4 [get_ports {twiddle_rsc_qb[*]}]
set_property src_info {type:XDC file:1 line:34 export:INPUT save:INPUT read:READ} [current_design]
set_output_delay -clock [get_clocks {clk}] 0.0 [get_ports {twiddle_rsc_triosy_lz}]
set_property src_info {type:XDC file:1 line:35 export:INPUT save:INPUT read:READ} [current_design]
set_output_delay -clock [get_clocks {clk}] 0.5 [get_ports {twiddle_h_rsc_adra[*]}]
set_property src_info {type:XDC file:1 line:36 export:INPUT save:INPUT read:READ} [current_design]
set_output_delay -clock [get_clocks {clk}] 0.5 [get_ports {twiddle_h_rsc_da[*]}]
set_property src_info {type:XDC file:1 line:37 export:INPUT save:INPUT read:READ} [current_design]
set_output_delay -clock [get_clocks {clk}] 0.5 [get_ports {twiddle_h_rsc_wea}]
set_property src_info {type:XDC file:1 line:38 export:INPUT save:INPUT read:READ} [current_design]
set_input_delay -clock [get_clocks {clk}] 2.4 [get_ports {twiddle_h_rsc_qa[*]}]
set_property src_info {type:XDC file:1 line:39 export:INPUT save:INPUT read:READ} [current_design]
set_output_delay -clock [get_clocks {clk}] 0.5 [get_ports {twiddle_h_rsc_adrb[*]}]
set_property src_info {type:XDC file:1 line:40 export:INPUT save:INPUT read:READ} [current_design]
set_output_delay -clock [get_clocks {clk}] 0.5 [get_ports {twiddle_h_rsc_db[*]}]
set_property src_info {type:XDC file:1 line:41 export:INPUT save:INPUT read:READ} [current_design]
set_output_delay -clock [get_clocks {clk}] 0.5 [get_ports {twiddle_h_rsc_web}]
set_property src_info {type:XDC file:1 line:42 export:INPUT save:INPUT read:READ} [current_design]
set_input_delay -clock [get_clocks {clk}] 2.4 [get_ports {twiddle_h_rsc_qb[*]}]
set_property src_info {type:XDC file:1 line:43 export:INPUT save:INPUT read:READ} [current_design]
set_output_delay -clock [get_clocks {clk}] 0.0 [get_ports {twiddle_h_rsc_triosy_lz}]
set_property src_info {type:XDC file:1 line:44 export:INPUT save:INPUT read:READ} [current_design]
set_input_delay -clock [get_clocks {clk}] 0.0 [get_ports {complete_rsc_rdy}]
set_property src_info {type:XDC file:2 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_clock_uncertainty 0.0 [get_clocks {clk}]
