//  Catapult Ultra Synthesis 10.5c/896140 (Production Release) Sun Sep  6 22:45:38 PDT 2020
//  
//  Copyright (c) Mentor Graphics Corporation, 1996-2020, All Rights Reserved.
//                        UNPUBLISHED, LICENSED SOFTWARE.
//             CONFIDENTIAL AND PROPRIETARY INFORMATION WHICH IS THE
//                 PROPERTY OF MENTOR GRAPHICS OR ITS LICENSORS
//  
//  Running on Linux ls5382@newnano.poly.edu 3.10.0-1062.4.1.el7.x86_64 x86_64 aol
//  
//  Package information: SIFLIBS v23.5_3.0, HLS_PKGS v23.5_3.0, 
//                       SIF_TOOLKITS v23.5_3.0, SIF_XILINX v23.5_3.0, 
//                       SIF_ALTERA v23.5_3.0, CCS_LIBS v23.5_3.0, 
//                       CDS_PPRO v10.3c_2, CDS_DesigChecker v10.5c, 
//                       CDS_OASYS v19.1_3.7, CDS_PSR v20.1_0.0, 
//                       DesignPad v2.78_1.0
//  
solution new -state initial
solution options defaults
solution options set /Input/CppStandard c++11
solution options set /Input/TargetPlatform x86_64
solution options set /Output/GenerateCycleNetlist false
solution file add ./flat_md/src/utils.cpp -type C++
solution file add ./flat_md/src/ntt.cpp -type C++
solution file add ./flat_md/src/main.cpp -type C++ -exclude true
solution file add ./flat_md/include/utils.h -type CHEADER
solution file add ./flat_md/include/ntt.h -type CHEADER -exclude true
solution file add ./flat_md/include/config.h -type CHEADER
solution file add ./flat_md/directives.tcl -type TCL -exclude true
directive set -PIPELINE_RAMP_UP true
directive set -PROTOTYPING_ENGINE oasys
directive set -CLUSTER_TYPE combinational
directive set -CLUSTER_FAST_MODE false
directive set -CLUSTER_RTL_SYN false
directive set -CLUSTER_OPT_CONSTANT_INPUTS true
directive set -CLUSTER_ADDTREE_IN_COUNT_THRESHOLD 0
directive set -CLUSTER_ADDTREE_IN_WIDTH_THRESHOLD 0
directive set -ROM_THRESHOLD 64
directive set -PROTOTYPE_ROM true
directive set -CHARACTERIZE_ROM false
directive set -OPT_CONST_MULTS use_library
directive set -CLOCK_OVERHEAD 20.000000
directive set -RESET_CLEARS_ALL_REGS use_library
directive set -START_FLAG {}
directive set -READY_FLAG {}
directive set -DONE_FLAG {}
directive set -TRANSACTION_DONE_SIGNAL true
directive set -STALL_FLAG false
directive set -IDLE_SIGNAL {}
directive set -REGISTER_IDLE_SIGNAL false
directive set -ARRAY_SIZE 1024
directive set -CHAN_IO_PROTOCOL use_library
directive set -IO_MODE super
directive set -UNROLL no
directive set -REALLOC true
directive set -MUXPATH true
directive set -TIMING_CHECKS true
directive set -ASSIGN_OVERHEAD 0
directive set -REGISTER_SHARING_LIMIT 0
directive set -REGISTER_SHARING_MAX_WIDTH_DIFFERENCE 8
directive set -SAFE_FSM false
directive set -NO_X_ASSIGNMENTS true
directive set -REG_MAX_FANOUT 0
directive set -FSM_BINARY_ENCODING_THRESHOLD 64
directive set -FSM_ENCODING none
directive set -LOGIC_OPT false
directive set -MEM_MAP_THRESHOLD 32
directive set -REGISTER_THRESHOLD 256
directive set -MERGEABLE true
directive set -SPECULATE true
directive set -DESIGN_GOAL area
go new
solution library add mgc_Xilinx-VIRTEX-7-2_beh -- -rtlsyntool Vivado -manufacturer Xilinx -family VIRTEX-7 -speed -2 -part xc7vx690tffg1761-2
solution library add Xilinx_RAMS
go libraries
directive set -CLOCKS {clk {-CLOCK_PERIOD 5.95 -CLOCK_EDGE rising -CLOCK_UNCERTAINTY 0.0 -CLOCK_HIGH_TIME 2.975 -RESET_SYNC_NAME rst -RESET_ASYNC_NAME arst_n -RESET_KIND sync -RESET_SYNC_ACTIVE high -RESET_ASYNC_ACTIVE low -ENABLE_ACTIVE high}}
go assembly
directive set /ntt_flat/core/for -PIPELINE_INIT_INTERVAL 1
directive set /ntt_flat/core/INNER_LOOP -PIPELINE_INIT_INTERVAL 3
directive set /ntt_flat/result:rsc -BLOCK_SIZE 16384
go architect
directive set /ntt_flat/core/butterFly:f1:read_mem(result:rsc(0)(0).@) -IGNORE_DEPENDENCY_FROM {butterFly:write_mem(result:rsc(0)(0).@) butterFly:write_mem(result:rsc(1)(0).@) butterFly:write_mem(result:rsc(2)(0).@) butterFly:write_mem(result:rsc(3)(0).@) butterFly:write_mem(result:rsc(4)(0).@) butterFly:write_mem(result:rsc(5)(0).@) butterFly:write_mem(result:rsc(6)(0).@) butterFly:write_mem(result:rsc(7)(0).@) butterFly:write_mem(result:rsc(8)(0).@) butterFly:write_mem(result:rsc(9)(0).@) butterFly:write_mem(result:rsc(10)(0).@) butterFly:write_mem(result:rsc(11)(0).@) butterFly:write_mem(result:rsc(12)(0).@) butterFly:write_mem(result:rsc(0)(0).@)#1 butterFly:write_mem(result:rsc(1)(0).@)#1 butterFly:write_mem(result:rsc(2)(0).@)#1 butterFly:write_mem(result:rsc(3)(0).@)#1 butterFly:write_mem(result:rsc(4)(0).@)#1 butterFly:write_mem(result:rsc(5)(0).@)#1 butterFly:write_mem(result:rsc(6)(0).@)#1 butterFly:write_mem(result:rsc(7)(0).@)#1 butterFly:write_mem(result:rsc(8)(0).@)#1 butterFly:write_mem(result:rsc(9)(0).@)#1 butterFly:write_mem(result:rsc(10)(0).@)#1 butterFly:write_mem(result:rsc(11)(0).@)#1 butterFly:write_mem(result:rsc(12)(0).@)#1 butterFly:write_mem(result:rsc(13)(0).@) butterFly:write_mem(result:rsc(14)(0).@) butterFly:write_mem(result:rsc(13)(0).@)#1 butterFly:write_mem(result:rsc(14)(0).@)#1}
directive set /ntt_flat/core/butterFly:f1:read_mem(result:rsc(1)(0).@) -IGNORE_DEPENDENCY_FROM {butterFly:write_mem(result:rsc(0)(0).@) butterFly:write_mem(result:rsc(1)(0).@) butterFly:write_mem(result:rsc(2)(0).@) butterFly:write_mem(result:rsc(3)(0).@) butterFly:write_mem(result:rsc(4)(0).@) butterFly:write_mem(result:rsc(5)(0).@) butterFly:write_mem(result:rsc(6)(0).@) butterFly:write_mem(result:rsc(7)(0).@) butterFly:write_mem(result:rsc(8)(0).@) butterFly:write_mem(result:rsc(9)(0).@) butterFly:write_mem(result:rsc(10)(0).@) butterFly:write_mem(result:rsc(11)(0).@) butterFly:write_mem(result:rsc(12)(0).@) butterFly:write_mem(result:rsc(0)(0).@)#1 butterFly:write_mem(result:rsc(1)(0).@)#1 butterFly:write_mem(result:rsc(2)(0).@)#1 butterFly:write_mem(result:rsc(3)(0).@)#1 butterFly:write_mem(result:rsc(4)(0).@)#1 butterFly:write_mem(result:rsc(5)(0).@)#1 butterFly:write_mem(result:rsc(6)(0).@)#1 butterFly:write_mem(result:rsc(7)(0).@)#1 butterFly:write_mem(result:rsc(8)(0).@)#1 butterFly:write_mem(result:rsc(9)(0).@)#1 butterFly:write_mem(result:rsc(10)(0).@)#1 butterFly:write_mem(result:rsc(11)(0).@)#1 butterFly:write_mem(result:rsc(12)(0).@)#1 butterFly:write_mem(result:rsc(13)(0).@) butterFly:write_mem(result:rsc(14)(0).@) butterFly:write_mem(result:rsc(13)(0).@)#1 butterFly:write_mem(result:rsc(14)(0).@)#1}
directive set /ntt_flat/core/butterFly:f1:read_mem(result:rsc(2)(0).@) -IGNORE_DEPENDENCY_FROM {butterFly:write_mem(result:rsc(0)(0).@) butterFly:write_mem(result:rsc(1)(0).@) butterFly:write_mem(result:rsc(2)(0).@) butterFly:write_mem(result:rsc(3)(0).@) butterFly:write_mem(result:rsc(4)(0).@) butterFly:write_mem(result:rsc(5)(0).@) butterFly:write_mem(result:rsc(6)(0).@) butterFly:write_mem(result:rsc(7)(0).@) butterFly:write_mem(result:rsc(8)(0).@) butterFly:write_mem(result:rsc(9)(0).@) butterFly:write_mem(result:rsc(10)(0).@) butterFly:write_mem(result:rsc(11)(0).@) butterFly:write_mem(result:rsc(12)(0).@) butterFly:write_mem(result:rsc(0)(0).@)#1 butterFly:write_mem(result:rsc(1)(0).@)#1 butterFly:write_mem(result:rsc(2)(0).@)#1 butterFly:write_mem(result:rsc(3)(0).@)#1 butterFly:write_mem(result:rsc(4)(0).@)#1 butterFly:write_mem(result:rsc(5)(0).@)#1 butterFly:write_mem(result:rsc(6)(0).@)#1 butterFly:write_mem(result:rsc(7)(0).@)#1 butterFly:write_mem(result:rsc(8)(0).@)#1 butterFly:write_mem(result:rsc(9)(0).@)#1 butterFly:write_mem(result:rsc(10)(0).@)#1 butterFly:write_mem(result:rsc(11)(0).@)#1 butterFly:write_mem(result:rsc(12)(0).@)#1 butterFly:write_mem(result:rsc(13)(0).@) butterFly:write_mem(result:rsc(14)(0).@) butterFly:write_mem(result:rsc(13)(0).@)#1 butterFly:write_mem(result:rsc(14)(0).@)#1}
directive set /ntt_flat/core/butterFly:f1:read_mem(result:rsc(3)(0).@) -IGNORE_DEPENDENCY_FROM {butterFly:write_mem(result:rsc(0)(0).@) butterFly:write_mem(result:rsc(1)(0).@) butterFly:write_mem(result:rsc(2)(0).@) butterFly:write_mem(result:rsc(3)(0).@) butterFly:write_mem(result:rsc(4)(0).@) butterFly:write_mem(result:rsc(5)(0).@) butterFly:write_mem(result:rsc(6)(0).@) butterFly:write_mem(result:rsc(7)(0).@) butterFly:write_mem(result:rsc(8)(0).@) butterFly:write_mem(result:rsc(9)(0).@) butterFly:write_mem(result:rsc(10)(0).@) butterFly:write_mem(result:rsc(11)(0).@) butterFly:write_mem(result:rsc(12)(0).@) butterFly:write_mem(result:rsc(0)(0).@)#1 butterFly:write_mem(result:rsc(1)(0).@)#1 butterFly:write_mem(result:rsc(2)(0).@)#1 butterFly:write_mem(result:rsc(3)(0).@)#1 butterFly:write_mem(result:rsc(4)(0).@)#1 butterFly:write_mem(result:rsc(5)(0).@)#1 butterFly:write_mem(result:rsc(6)(0).@)#1 butterFly:write_mem(result:rsc(7)(0).@)#1 butterFly:write_mem(result:rsc(8)(0).@)#1 butterFly:write_mem(result:rsc(9)(0).@)#1 butterFly:write_mem(result:rsc(10)(0).@)#1 butterFly:write_mem(result:rsc(11)(0).@)#1 butterFly:write_mem(result:rsc(12)(0).@)#1 butterFly:write_mem(result:rsc(13)(0).@) butterFly:write_mem(result:rsc(14)(0).@) butterFly:write_mem(result:rsc(13)(0).@)#1 butterFly:write_mem(result:rsc(14)(0).@)#1}
directive set /ntt_flat/core/butterFly:f1:read_mem(result:rsc(4)(0).@) -IGNORE_DEPENDENCY_FROM {butterFly:write_mem(result:rsc(0)(0).@) butterFly:write_mem(result:rsc(1)(0).@) butterFly:write_mem(result:rsc(2)(0).@) butterFly:write_mem(result:rsc(3)(0).@) butterFly:write_mem(result:rsc(4)(0).@) butterFly:write_mem(result:rsc(5)(0).@) butterFly:write_mem(result:rsc(6)(0).@) butterFly:write_mem(result:rsc(7)(0).@) butterFly:write_mem(result:rsc(8)(0).@) butterFly:write_mem(result:rsc(9)(0).@) butterFly:write_mem(result:rsc(10)(0).@) butterFly:write_mem(result:rsc(11)(0).@) butterFly:write_mem(result:rsc(12)(0).@) butterFly:write_mem(result:rsc(0)(0).@)#1 butterFly:write_mem(result:rsc(1)(0).@)#1 butterFly:write_mem(result:rsc(2)(0).@)#1 butterFly:write_mem(result:rsc(3)(0).@)#1 butterFly:write_mem(result:rsc(4)(0).@)#1 butterFly:write_mem(result:rsc(5)(0).@)#1 butterFly:write_mem(result:rsc(6)(0).@)#1 butterFly:write_mem(result:rsc(7)(0).@)#1 butterFly:write_mem(result:rsc(8)(0).@)#1 butterFly:write_mem(result:rsc(9)(0).@)#1 butterFly:write_mem(result:rsc(10)(0).@)#1 butterFly:write_mem(result:rsc(11)(0).@)#1 butterFly:write_mem(result:rsc(12)(0).@)#1 butterFly:write_mem(result:rsc(13)(0).@) butterFly:write_mem(result:rsc(14)(0).@) butterFly:write_mem(result:rsc(13)(0).@)#1 butterFly:write_mem(result:rsc(14)(0).@)#1}
directive set /ntt_flat/core/butterFly:f1:read_mem(result:rsc(5)(0).@) -IGNORE_DEPENDENCY_FROM {butterFly:write_mem(result:rsc(0)(0).@) butterFly:write_mem(result:rsc(1)(0).@) butterFly:write_mem(result:rsc(2)(0).@) butterFly:write_mem(result:rsc(3)(0).@) butterFly:write_mem(result:rsc(4)(0).@) butterFly:write_mem(result:rsc(5)(0).@) butterFly:write_mem(result:rsc(6)(0).@) butterFly:write_mem(result:rsc(7)(0).@) butterFly:write_mem(result:rsc(8)(0).@) butterFly:write_mem(result:rsc(9)(0).@) butterFly:write_mem(result:rsc(10)(0).@) butterFly:write_mem(result:rsc(11)(0).@) butterFly:write_mem(result:rsc(12)(0).@) butterFly:write_mem(result:rsc(0)(0).@)#1 butterFly:write_mem(result:rsc(1)(0).@)#1 butterFly:write_mem(result:rsc(2)(0).@)#1 butterFly:write_mem(result:rsc(3)(0).@)#1 butterFly:write_mem(result:rsc(4)(0).@)#1 butterFly:write_mem(result:rsc(5)(0).@)#1 butterFly:write_mem(result:rsc(6)(0).@)#1 butterFly:write_mem(result:rsc(7)(0).@)#1 butterFly:write_mem(result:rsc(8)(0).@)#1 butterFly:write_mem(result:rsc(9)(0).@)#1 butterFly:write_mem(result:rsc(10)(0).@)#1 butterFly:write_mem(result:rsc(11)(0).@)#1 butterFly:write_mem(result:rsc(12)(0).@)#1 butterFly:write_mem(result:rsc(13)(0).@) butterFly:write_mem(result:rsc(14)(0).@) butterFly:write_mem(result:rsc(13)(0).@)#1 butterFly:write_mem(result:rsc(14)(0).@)#1}
directive set /ntt_flat/core/butterFly:f1:read_mem(result:rsc(6)(0).@) -IGNORE_DEPENDENCY_FROM {butterFly:write_mem(result:rsc(0)(0).@) butterFly:write_mem(result:rsc(1)(0).@) butterFly:write_mem(result:rsc(2)(0).@) butterFly:write_mem(result:rsc(3)(0).@) butterFly:write_mem(result:rsc(4)(0).@) butterFly:write_mem(result:rsc(5)(0).@) butterFly:write_mem(result:rsc(6)(0).@) butterFly:write_mem(result:rsc(7)(0).@) butterFly:write_mem(result:rsc(8)(0).@) butterFly:write_mem(result:rsc(9)(0).@) butterFly:write_mem(result:rsc(10)(0).@) butterFly:write_mem(result:rsc(11)(0).@) butterFly:write_mem(result:rsc(12)(0).@) butterFly:write_mem(result:rsc(0)(0).@)#1 butterFly:write_mem(result:rsc(1)(0).@)#1 butterFly:write_mem(result:rsc(2)(0).@)#1 butterFly:write_mem(result:rsc(3)(0).@)#1 butterFly:write_mem(result:rsc(4)(0).@)#1 butterFly:write_mem(result:rsc(5)(0).@)#1 butterFly:write_mem(result:rsc(6)(0).@)#1 butterFly:write_mem(result:rsc(7)(0).@)#1 butterFly:write_mem(result:rsc(8)(0).@)#1 butterFly:write_mem(result:rsc(9)(0).@)#1 butterFly:write_mem(result:rsc(10)(0).@)#1 butterFly:write_mem(result:rsc(11)(0).@)#1 butterFly:write_mem(result:rsc(12)(0).@)#1 butterFly:write_mem(result:rsc(13)(0).@) butterFly:write_mem(result:rsc(14)(0).@) butterFly:write_mem(result:rsc(13)(0).@)#1 butterFly:write_mem(result:rsc(14)(0).@)#1}
directive set /ntt_flat/core/butterFly:f1:read_mem(result:rsc(7)(0).@) -IGNORE_DEPENDENCY_FROM {butterFly:write_mem(result:rsc(0)(0).@) butterFly:write_mem(result:rsc(1)(0).@) butterFly:write_mem(result:rsc(2)(0).@) butterFly:write_mem(result:rsc(3)(0).@) butterFly:write_mem(result:rsc(4)(0).@) butterFly:write_mem(result:rsc(5)(0).@) butterFly:write_mem(result:rsc(6)(0).@) butterFly:write_mem(result:rsc(7)(0).@) butterFly:write_mem(result:rsc(8)(0).@) butterFly:write_mem(result:rsc(9)(0).@) butterFly:write_mem(result:rsc(10)(0).@) butterFly:write_mem(result:rsc(11)(0).@) butterFly:write_mem(result:rsc(12)(0).@) butterFly:write_mem(result:rsc(0)(0).@)#1 butterFly:write_mem(result:rsc(1)(0).@)#1 butterFly:write_mem(result:rsc(2)(0).@)#1 butterFly:write_mem(result:rsc(3)(0).@)#1 butterFly:write_mem(result:rsc(4)(0).@)#1 butterFly:write_mem(result:rsc(5)(0).@)#1 butterFly:write_mem(result:rsc(6)(0).@)#1 butterFly:write_mem(result:rsc(7)(0).@)#1 butterFly:write_mem(result:rsc(8)(0).@)#1 butterFly:write_mem(result:rsc(9)(0).@)#1 butterFly:write_mem(result:rsc(10)(0).@)#1 butterFly:write_mem(result:rsc(11)(0).@)#1 butterFly:write_mem(result:rsc(12)(0).@)#1 butterFly:write_mem(result:rsc(13)(0).@) butterFly:write_mem(result:rsc(14)(0).@) butterFly:write_mem(result:rsc(13)(0).@)#1 butterFly:write_mem(result:rsc(14)(0).@)#1}
directive set /ntt_flat/core/butterFly:f1:read_mem(result:rsc(8)(0).@) -IGNORE_DEPENDENCY_FROM {butterFly:write_mem(result:rsc(0)(0).@) butterFly:write_mem(result:rsc(1)(0).@) butterFly:write_mem(result:rsc(2)(0).@) butterFly:write_mem(result:rsc(3)(0).@) butterFly:write_mem(result:rsc(4)(0).@) butterFly:write_mem(result:rsc(5)(0).@) butterFly:write_mem(result:rsc(6)(0).@) butterFly:write_mem(result:rsc(7)(0).@) butterFly:write_mem(result:rsc(8)(0).@) butterFly:write_mem(result:rsc(9)(0).@) butterFly:write_mem(result:rsc(10)(0).@) butterFly:write_mem(result:rsc(11)(0).@) butterFly:write_mem(result:rsc(12)(0).@) butterFly:write_mem(result:rsc(0)(0).@)#1 butterFly:write_mem(result:rsc(1)(0).@)#1 butterFly:write_mem(result:rsc(2)(0).@)#1 butterFly:write_mem(result:rsc(3)(0).@)#1 butterFly:write_mem(result:rsc(4)(0).@)#1 butterFly:write_mem(result:rsc(5)(0).@)#1 butterFly:write_mem(result:rsc(6)(0).@)#1 butterFly:write_mem(result:rsc(7)(0).@)#1 butterFly:write_mem(result:rsc(8)(0).@)#1 butterFly:write_mem(result:rsc(9)(0).@)#1 butterFly:write_mem(result:rsc(10)(0).@)#1 butterFly:write_mem(result:rsc(11)(0).@)#1 butterFly:write_mem(result:rsc(12)(0).@)#1 butterFly:write_mem(result:rsc(13)(0).@) butterFly:write_mem(result:rsc(14)(0).@) butterFly:write_mem(result:rsc(13)(0).@)#1 butterFly:write_mem(result:rsc(14)(0).@)#1}
directive set /ntt_flat/core/butterFly:f1:read_mem(result:rsc(9)(0).@) -IGNORE_DEPENDENCY_FROM {butterFly:write_mem(result:rsc(0)(0).@) butterFly:write_mem(result:rsc(1)(0).@) butterFly:write_mem(result:rsc(2)(0).@) butterFly:write_mem(result:rsc(3)(0).@) butterFly:write_mem(result:rsc(4)(0).@) butterFly:write_mem(result:rsc(5)(0).@) butterFly:write_mem(result:rsc(6)(0).@) butterFly:write_mem(result:rsc(7)(0).@) butterFly:write_mem(result:rsc(8)(0).@) butterFly:write_mem(result:rsc(9)(0).@) butterFly:write_mem(result:rsc(10)(0).@) butterFly:write_mem(result:rsc(11)(0).@) butterFly:write_mem(result:rsc(12)(0).@) butterFly:write_mem(result:rsc(0)(0).@)#1 butterFly:write_mem(result:rsc(1)(0).@)#1 butterFly:write_mem(result:rsc(2)(0).@)#1 butterFly:write_mem(result:rsc(3)(0).@)#1 butterFly:write_mem(result:rsc(4)(0).@)#1 butterFly:write_mem(result:rsc(5)(0).@)#1 butterFly:write_mem(result:rsc(6)(0).@)#1 butterFly:write_mem(result:rsc(7)(0).@)#1 butterFly:write_mem(result:rsc(8)(0).@)#1 butterFly:write_mem(result:rsc(9)(0).@)#1 butterFly:write_mem(result:rsc(10)(0).@)#1 butterFly:write_mem(result:rsc(11)(0).@)#1 butterFly:write_mem(result:rsc(12)(0).@)#1 butterFly:write_mem(result:rsc(13)(0).@) butterFly:write_mem(result:rsc(14)(0).@) butterFly:write_mem(result:rsc(13)(0).@)#1 butterFly:write_mem(result:rsc(14)(0).@)#1}
directive set /ntt_flat/core/butterFly:f1:read_mem(result:rsc(10)(0).@) -IGNORE_DEPENDENCY_FROM {butterFly:write_mem(result:rsc(0)(0).@) butterFly:write_mem(result:rsc(1)(0).@) butterFly:write_mem(result:rsc(2)(0).@) butterFly:write_mem(result:rsc(3)(0).@) butterFly:write_mem(result:rsc(4)(0).@) butterFly:write_mem(result:rsc(5)(0).@) butterFly:write_mem(result:rsc(6)(0).@) butterFly:write_mem(result:rsc(7)(0).@) butterFly:write_mem(result:rsc(8)(0).@) butterFly:write_mem(result:rsc(9)(0).@) butterFly:write_mem(result:rsc(10)(0).@) butterFly:write_mem(result:rsc(11)(0).@) butterFly:write_mem(result:rsc(12)(0).@) butterFly:write_mem(result:rsc(0)(0).@)#1 butterFly:write_mem(result:rsc(1)(0).@)#1 butterFly:write_mem(result:rsc(2)(0).@)#1 butterFly:write_mem(result:rsc(3)(0).@)#1 butterFly:write_mem(result:rsc(4)(0).@)#1 butterFly:write_mem(result:rsc(5)(0).@)#1 butterFly:write_mem(result:rsc(6)(0).@)#1 butterFly:write_mem(result:rsc(7)(0).@)#1 butterFly:write_mem(result:rsc(8)(0).@)#1 butterFly:write_mem(result:rsc(9)(0).@)#1 butterFly:write_mem(result:rsc(10)(0).@)#1 butterFly:write_mem(result:rsc(11)(0).@)#1 butterFly:write_mem(result:rsc(12)(0).@)#1 butterFly:write_mem(result:rsc(13)(0).@) butterFly:write_mem(result:rsc(14)(0).@) butterFly:write_mem(result:rsc(13)(0).@)#1 butterFly:write_mem(result:rsc(14)(0).@)#1}
directive set /ntt_flat/core/butterFly:f1:read_mem(result:rsc(11)(0).@) -IGNORE_DEPENDENCY_FROM {butterFly:write_mem(result:rsc(0)(0).@) butterFly:write_mem(result:rsc(1)(0).@) butterFly:write_mem(result:rsc(2)(0).@) butterFly:write_mem(result:rsc(3)(0).@) butterFly:write_mem(result:rsc(4)(0).@) butterFly:write_mem(result:rsc(5)(0).@) butterFly:write_mem(result:rsc(6)(0).@) butterFly:write_mem(result:rsc(7)(0).@) butterFly:write_mem(result:rsc(8)(0).@) butterFly:write_mem(result:rsc(9)(0).@) butterFly:write_mem(result:rsc(10)(0).@) butterFly:write_mem(result:rsc(11)(0).@) butterFly:write_mem(result:rsc(12)(0).@) butterFly:write_mem(result:rsc(0)(0).@)#1 butterFly:write_mem(result:rsc(1)(0).@)#1 butterFly:write_mem(result:rsc(2)(0).@)#1 butterFly:write_mem(result:rsc(3)(0).@)#1 butterFly:write_mem(result:rsc(4)(0).@)#1 butterFly:write_mem(result:rsc(5)(0).@)#1 butterFly:write_mem(result:rsc(6)(0).@)#1 butterFly:write_mem(result:rsc(7)(0).@)#1 butterFly:write_mem(result:rsc(8)(0).@)#1 butterFly:write_mem(result:rsc(9)(0).@)#1 butterFly:write_mem(result:rsc(10)(0).@)#1 butterFly:write_mem(result:rsc(11)(0).@)#1 butterFly:write_mem(result:rsc(12)(0).@)#1 butterFly:write_mem(result:rsc(13)(0).@) butterFly:write_mem(result:rsc(14)(0).@) butterFly:write_mem(result:rsc(13)(0).@)#1 butterFly:write_mem(result:rsc(14)(0).@)#1}
directive set /ntt_flat/core/butterFly:f1:read_mem(result:rsc(12)(0).@) -IGNORE_DEPENDENCY_FROM {butterFly:write_mem(result:rsc(0)(0).@) butterFly:write_mem(result:rsc(1)(0).@) butterFly:write_mem(result:rsc(2)(0).@) butterFly:write_mem(result:rsc(3)(0).@) butterFly:write_mem(result:rsc(4)(0).@) butterFly:write_mem(result:rsc(5)(0).@) butterFly:write_mem(result:rsc(6)(0).@) butterFly:write_mem(result:rsc(7)(0).@) butterFly:write_mem(result:rsc(8)(0).@) butterFly:write_mem(result:rsc(9)(0).@) butterFly:write_mem(result:rsc(10)(0).@) butterFly:write_mem(result:rsc(11)(0).@) butterFly:write_mem(result:rsc(12)(0).@) butterFly:write_mem(result:rsc(0)(0).@)#1 butterFly:write_mem(result:rsc(1)(0).@)#1 butterFly:write_mem(result:rsc(2)(0).@)#1 butterFly:write_mem(result:rsc(3)(0).@)#1 butterFly:write_mem(result:rsc(4)(0).@)#1 butterFly:write_mem(result:rsc(5)(0).@)#1 butterFly:write_mem(result:rsc(6)(0).@)#1 butterFly:write_mem(result:rsc(7)(0).@)#1 butterFly:write_mem(result:rsc(8)(0).@)#1 butterFly:write_mem(result:rsc(9)(0).@)#1 butterFly:write_mem(result:rsc(10)(0).@)#1 butterFly:write_mem(result:rsc(11)(0).@)#1 butterFly:write_mem(result:rsc(12)(0).@)#1 butterFly:write_mem(result:rsc(13)(0).@) butterFly:write_mem(result:rsc(14)(0).@) butterFly:write_mem(result:rsc(13)(0).@)#1 butterFly:write_mem(result:rsc(14)(0).@)#1}
directive set /ntt_flat/core/butterFly:f1:read_mem(result:rsc(13)(0).@) -IGNORE_DEPENDENCY_FROM {butterFly:write_mem(result:rsc(0)(0).@) butterFly:write_mem(result:rsc(1)(0).@) butterFly:write_mem(result:rsc(2)(0).@) butterFly:write_mem(result:rsc(3)(0).@) butterFly:write_mem(result:rsc(4)(0).@) butterFly:write_mem(result:rsc(5)(0).@) butterFly:write_mem(result:rsc(6)(0).@) butterFly:write_mem(result:rsc(7)(0).@) butterFly:write_mem(result:rsc(8)(0).@) butterFly:write_mem(result:rsc(9)(0).@) butterFly:write_mem(result:rsc(10)(0).@) butterFly:write_mem(result:rsc(11)(0).@) butterFly:write_mem(result:rsc(12)(0).@) butterFly:write_mem(result:rsc(13)(0).@) butterFly:write_mem(result:rsc(14)(0).@) butterFly:write_mem(result:rsc(0)(0).@)#1 butterFly:write_mem(result:rsc(1)(0).@)#1 butterFly:write_mem(result:rsc(2)(0).@)#1 butterFly:write_mem(result:rsc(3)(0).@)#1 butterFly:write_mem(result:rsc(4)(0).@)#1 butterFly:write_mem(result:rsc(5)(0).@)#1 butterFly:write_mem(result:rsc(6)(0).@)#1 butterFly:write_mem(result:rsc(7)(0).@)#1 butterFly:write_mem(result:rsc(8)(0).@)#1 butterFly:write_mem(result:rsc(9)(0).@)#1 butterFly:write_mem(result:rsc(10)(0).@)#1 butterFly:write_mem(result:rsc(11)(0).@)#1 butterFly:write_mem(result:rsc(12)(0).@)#1 butterFly:write_mem(result:rsc(13)(0).@)#1 butterFly:write_mem(result:rsc(14)(0).@)#1}
directive set /ntt_flat/core/butterFly:f1:read_mem(result:rsc(14)(0).@) -IGNORE_DEPENDENCY_FROM {butterFly:write_mem(result:rsc(0)(0).@) butterFly:write_mem(result:rsc(1)(0).@) butterFly:write_mem(result:rsc(2)(0).@) butterFly:write_mem(result:rsc(3)(0).@) butterFly:write_mem(result:rsc(4)(0).@) butterFly:write_mem(result:rsc(5)(0).@) butterFly:write_mem(result:rsc(6)(0).@) butterFly:write_mem(result:rsc(7)(0).@) butterFly:write_mem(result:rsc(8)(0).@) butterFly:write_mem(result:rsc(9)(0).@) butterFly:write_mem(result:rsc(10)(0).@) butterFly:write_mem(result:rsc(11)(0).@) butterFly:write_mem(result:rsc(12)(0).@) butterFly:write_mem(result:rsc(13)(0).@) butterFly:write_mem(result:rsc(14)(0).@) butterFly:write_mem(result:rsc(0)(0).@)#1 butterFly:write_mem(result:rsc(1)(0).@)#1 butterFly:write_mem(result:rsc(2)(0).@)#1 butterFly:write_mem(result:rsc(3)(0).@)#1 butterFly:write_mem(result:rsc(4)(0).@)#1 butterFly:write_mem(result:rsc(5)(0).@)#1 butterFly:write_mem(result:rsc(6)(0).@)#1 butterFly:write_mem(result:rsc(7)(0).@)#1 butterFly:write_mem(result:rsc(8)(0).@)#1 butterFly:write_mem(result:rsc(9)(0).@)#1 butterFly:write_mem(result:rsc(10)(0).@)#1 butterFly:write_mem(result:rsc(11)(0).@)#1 butterFly:write_mem(result:rsc(12)(0).@)#1 butterFly:write_mem(result:rsc(13)(0).@)#1 butterFly:write_mem(result:rsc(14)(0).@)#1}
directive set /ntt_flat/core/butterFly:f2:read_mem(result:rsc(0)(0).@) -IGNORE_DEPENDENCY_FROM {butterFly:write_mem(result:rsc(0)(0).@) butterFly:write_mem(result:rsc(1)(0).@) butterFly:write_mem(result:rsc(2)(0).@) butterFly:write_mem(result:rsc(3)(0).@) butterFly:write_mem(result:rsc(4)(0).@) butterFly:write_mem(result:rsc(5)(0).@) butterFly:write_mem(result:rsc(6)(0).@) butterFly:write_mem(result:rsc(7)(0).@) butterFly:write_mem(result:rsc(8)(0).@) butterFly:write_mem(result:rsc(9)(0).@) butterFly:write_mem(result:rsc(10)(0).@) butterFly:write_mem(result:rsc(11)(0).@) butterFly:write_mem(result:rsc(12)(0).@) butterFly:write_mem(result:rsc(0)(0).@)#1 butterFly:write_mem(result:rsc(1)(0).@)#1 butterFly:write_mem(result:rsc(2)(0).@)#1 butterFly:write_mem(result:rsc(3)(0).@)#1 butterFly:write_mem(result:rsc(4)(0).@)#1 butterFly:write_mem(result:rsc(5)(0).@)#1 butterFly:write_mem(result:rsc(6)(0).@)#1 butterFly:write_mem(result:rsc(7)(0).@)#1 butterFly:write_mem(result:rsc(8)(0).@)#1 butterFly:write_mem(result:rsc(9)(0).@)#1 butterFly:write_mem(result:rsc(10)(0).@)#1 butterFly:write_mem(result:rsc(11)(0).@)#1 butterFly:write_mem(result:rsc(12)(0).@)#1 butterFly:write_mem(result:rsc(13)(0).@) butterFly:write_mem(result:rsc(14)(0).@) butterFly:write_mem(result:rsc(13)(0).@)#1 butterFly:write_mem(result:rsc(14)(0).@)#1}
directive set /ntt_flat/core/butterFly:f2:read_mem(result:rsc(1)(0).@) -IGNORE_DEPENDENCY_FROM {butterFly:write_mem(result:rsc(0)(0).@) butterFly:write_mem(result:rsc(1)(0).@) butterFly:write_mem(result:rsc(2)(0).@) butterFly:write_mem(result:rsc(3)(0).@) butterFly:write_mem(result:rsc(4)(0).@) butterFly:write_mem(result:rsc(5)(0).@) butterFly:write_mem(result:rsc(6)(0).@) butterFly:write_mem(result:rsc(7)(0).@) butterFly:write_mem(result:rsc(8)(0).@) butterFly:write_mem(result:rsc(9)(0).@) butterFly:write_mem(result:rsc(10)(0).@) butterFly:write_mem(result:rsc(11)(0).@) butterFly:write_mem(result:rsc(12)(0).@) butterFly:write_mem(result:rsc(0)(0).@)#1 butterFly:write_mem(result:rsc(1)(0).@)#1 butterFly:write_mem(result:rsc(2)(0).@)#1 butterFly:write_mem(result:rsc(3)(0).@)#1 butterFly:write_mem(result:rsc(4)(0).@)#1 butterFly:write_mem(result:rsc(5)(0).@)#1 butterFly:write_mem(result:rsc(6)(0).@)#1 butterFly:write_mem(result:rsc(7)(0).@)#1 butterFly:write_mem(result:rsc(8)(0).@)#1 butterFly:write_mem(result:rsc(9)(0).@)#1 butterFly:write_mem(result:rsc(10)(0).@)#1 butterFly:write_mem(result:rsc(11)(0).@)#1 butterFly:write_mem(result:rsc(12)(0).@)#1 butterFly:write_mem(result:rsc(13)(0).@) butterFly:write_mem(result:rsc(14)(0).@) butterFly:write_mem(result:rsc(13)(0).@)#1 butterFly:write_mem(result:rsc(14)(0).@)#1}
directive set /ntt_flat/core/butterFly:f2:read_mem(result:rsc(2)(0).@) -IGNORE_DEPENDENCY_FROM {butterFly:write_mem(result:rsc(0)(0).@) butterFly:write_mem(result:rsc(1)(0).@) butterFly:write_mem(result:rsc(2)(0).@) butterFly:write_mem(result:rsc(3)(0).@) butterFly:write_mem(result:rsc(4)(0).@) butterFly:write_mem(result:rsc(5)(0).@) butterFly:write_mem(result:rsc(6)(0).@) butterFly:write_mem(result:rsc(7)(0).@) butterFly:write_mem(result:rsc(8)(0).@) butterFly:write_mem(result:rsc(9)(0).@) butterFly:write_mem(result:rsc(10)(0).@) butterFly:write_mem(result:rsc(11)(0).@) butterFly:write_mem(result:rsc(12)(0).@) butterFly:write_mem(result:rsc(0)(0).@)#1 butterFly:write_mem(result:rsc(1)(0).@)#1 butterFly:write_mem(result:rsc(2)(0).@)#1 butterFly:write_mem(result:rsc(3)(0).@)#1 butterFly:write_mem(result:rsc(4)(0).@)#1 butterFly:write_mem(result:rsc(5)(0).@)#1 butterFly:write_mem(result:rsc(6)(0).@)#1 butterFly:write_mem(result:rsc(7)(0).@)#1 butterFly:write_mem(result:rsc(8)(0).@)#1 butterFly:write_mem(result:rsc(9)(0).@)#1 butterFly:write_mem(result:rsc(10)(0).@)#1 butterFly:write_mem(result:rsc(11)(0).@)#1 butterFly:write_mem(result:rsc(12)(0).@)#1 butterFly:write_mem(result:rsc(13)(0).@) butterFly:write_mem(result:rsc(14)(0).@) butterFly:write_mem(result:rsc(13)(0).@)#1 butterFly:write_mem(result:rsc(14)(0).@)#1}
directive set /ntt_flat/core/butterFly:f2:read_mem(result:rsc(3)(0).@) -IGNORE_DEPENDENCY_FROM {butterFly:write_mem(result:rsc(0)(0).@) butterFly:write_mem(result:rsc(1)(0).@) butterFly:write_mem(result:rsc(2)(0).@) butterFly:write_mem(result:rsc(3)(0).@) butterFly:write_mem(result:rsc(4)(0).@) butterFly:write_mem(result:rsc(5)(0).@) butterFly:write_mem(result:rsc(6)(0).@) butterFly:write_mem(result:rsc(7)(0).@) butterFly:write_mem(result:rsc(8)(0).@) butterFly:write_mem(result:rsc(9)(0).@) butterFly:write_mem(result:rsc(10)(0).@) butterFly:write_mem(result:rsc(11)(0).@) butterFly:write_mem(result:rsc(12)(0).@) butterFly:write_mem(result:rsc(0)(0).@)#1 butterFly:write_mem(result:rsc(1)(0).@)#1 butterFly:write_mem(result:rsc(2)(0).@)#1 butterFly:write_mem(result:rsc(3)(0).@)#1 butterFly:write_mem(result:rsc(4)(0).@)#1 butterFly:write_mem(result:rsc(5)(0).@)#1 butterFly:write_mem(result:rsc(6)(0).@)#1 butterFly:write_mem(result:rsc(7)(0).@)#1 butterFly:write_mem(result:rsc(8)(0).@)#1 butterFly:write_mem(result:rsc(9)(0).@)#1 butterFly:write_mem(result:rsc(10)(0).@)#1 butterFly:write_mem(result:rsc(11)(0).@)#1 butterFly:write_mem(result:rsc(12)(0).@)#1 butterFly:write_mem(result:rsc(13)(0).@) butterFly:write_mem(result:rsc(14)(0).@) butterFly:write_mem(result:rsc(13)(0).@)#1 butterFly:write_mem(result:rsc(14)(0).@)#1}
directive set /ntt_flat/core/butterFly:f2:read_mem(result:rsc(4)(0).@) -IGNORE_DEPENDENCY_FROM {butterFly:write_mem(result:rsc(0)(0).@) butterFly:write_mem(result:rsc(1)(0).@) butterFly:write_mem(result:rsc(2)(0).@) butterFly:write_mem(result:rsc(3)(0).@) butterFly:write_mem(result:rsc(4)(0).@) butterFly:write_mem(result:rsc(5)(0).@) butterFly:write_mem(result:rsc(6)(0).@) butterFly:write_mem(result:rsc(7)(0).@) butterFly:write_mem(result:rsc(8)(0).@) butterFly:write_mem(result:rsc(9)(0).@) butterFly:write_mem(result:rsc(10)(0).@) butterFly:write_mem(result:rsc(11)(0).@) butterFly:write_mem(result:rsc(12)(0).@) butterFly:write_mem(result:rsc(0)(0).@)#1 butterFly:write_mem(result:rsc(1)(0).@)#1 butterFly:write_mem(result:rsc(2)(0).@)#1 butterFly:write_mem(result:rsc(3)(0).@)#1 butterFly:write_mem(result:rsc(4)(0).@)#1 butterFly:write_mem(result:rsc(5)(0).@)#1 butterFly:write_mem(result:rsc(6)(0).@)#1 butterFly:write_mem(result:rsc(7)(0).@)#1 butterFly:write_mem(result:rsc(8)(0).@)#1 butterFly:write_mem(result:rsc(9)(0).@)#1 butterFly:write_mem(result:rsc(10)(0).@)#1 butterFly:write_mem(result:rsc(11)(0).@)#1 butterFly:write_mem(result:rsc(12)(0).@)#1 butterFly:write_mem(result:rsc(13)(0).@) butterFly:write_mem(result:rsc(14)(0).@) butterFly:write_mem(result:rsc(13)(0).@)#1 butterFly:write_mem(result:rsc(14)(0).@)#1}
directive set /ntt_flat/core/butterFly:f2:read_mem(result:rsc(5)(0).@) -IGNORE_DEPENDENCY_FROM {butterFly:write_mem(result:rsc(0)(0).@) butterFly:write_mem(result:rsc(1)(0).@) butterFly:write_mem(result:rsc(2)(0).@) butterFly:write_mem(result:rsc(3)(0).@) butterFly:write_mem(result:rsc(4)(0).@) butterFly:write_mem(result:rsc(5)(0).@) butterFly:write_mem(result:rsc(6)(0).@) butterFly:write_mem(result:rsc(7)(0).@) butterFly:write_mem(result:rsc(8)(0).@) butterFly:write_mem(result:rsc(9)(0).@) butterFly:write_mem(result:rsc(10)(0).@) butterFly:write_mem(result:rsc(11)(0).@) butterFly:write_mem(result:rsc(12)(0).@) butterFly:write_mem(result:rsc(0)(0).@)#1 butterFly:write_mem(result:rsc(1)(0).@)#1 butterFly:write_mem(result:rsc(2)(0).@)#1 butterFly:write_mem(result:rsc(3)(0).@)#1 butterFly:write_mem(result:rsc(4)(0).@)#1 butterFly:write_mem(result:rsc(5)(0).@)#1 butterFly:write_mem(result:rsc(6)(0).@)#1 butterFly:write_mem(result:rsc(7)(0).@)#1 butterFly:write_mem(result:rsc(8)(0).@)#1 butterFly:write_mem(result:rsc(9)(0).@)#1 butterFly:write_mem(result:rsc(10)(0).@)#1 butterFly:write_mem(result:rsc(11)(0).@)#1 butterFly:write_mem(result:rsc(12)(0).@)#1 butterFly:write_mem(result:rsc(13)(0).@) butterFly:write_mem(result:rsc(14)(0).@) butterFly:write_mem(result:rsc(13)(0).@)#1 butterFly:write_mem(result:rsc(14)(0).@)#1}
directive set /ntt_flat/core/butterFly:f2:read_mem(result:rsc(6)(0).@) -IGNORE_DEPENDENCY_FROM {butterFly:write_mem(result:rsc(0)(0).@) butterFly:write_mem(result:rsc(1)(0).@) butterFly:write_mem(result:rsc(2)(0).@) butterFly:write_mem(result:rsc(3)(0).@) butterFly:write_mem(result:rsc(4)(0).@) butterFly:write_mem(result:rsc(5)(0).@) butterFly:write_mem(result:rsc(6)(0).@) butterFly:write_mem(result:rsc(7)(0).@) butterFly:write_mem(result:rsc(8)(0).@) butterFly:write_mem(result:rsc(9)(0).@) butterFly:write_mem(result:rsc(10)(0).@) butterFly:write_mem(result:rsc(11)(0).@) butterFly:write_mem(result:rsc(12)(0).@) butterFly:write_mem(result:rsc(0)(0).@)#1 butterFly:write_mem(result:rsc(1)(0).@)#1 butterFly:write_mem(result:rsc(2)(0).@)#1 butterFly:write_mem(result:rsc(3)(0).@)#1 butterFly:write_mem(result:rsc(4)(0).@)#1 butterFly:write_mem(result:rsc(5)(0).@)#1 butterFly:write_mem(result:rsc(6)(0).@)#1 butterFly:write_mem(result:rsc(7)(0).@)#1 butterFly:write_mem(result:rsc(8)(0).@)#1 butterFly:write_mem(result:rsc(9)(0).@)#1 butterFly:write_mem(result:rsc(10)(0).@)#1 butterFly:write_mem(result:rsc(11)(0).@)#1 butterFly:write_mem(result:rsc(12)(0).@)#1 butterFly:write_mem(result:rsc(13)(0).@) butterFly:write_mem(result:rsc(14)(0).@) butterFly:write_mem(result:rsc(13)(0).@)#1 butterFly:write_mem(result:rsc(14)(0).@)#1}
directive set /ntt_flat/core/butterFly:f2:read_mem(result:rsc(7)(0).@) -IGNORE_DEPENDENCY_FROM {butterFly:write_mem(result:rsc(0)(0).@) butterFly:write_mem(result:rsc(1)(0).@) butterFly:write_mem(result:rsc(2)(0).@) butterFly:write_mem(result:rsc(3)(0).@) butterFly:write_mem(result:rsc(4)(0).@) butterFly:write_mem(result:rsc(5)(0).@) butterFly:write_mem(result:rsc(6)(0).@) butterFly:write_mem(result:rsc(7)(0).@) butterFly:write_mem(result:rsc(8)(0).@) butterFly:write_mem(result:rsc(9)(0).@) butterFly:write_mem(result:rsc(10)(0).@) butterFly:write_mem(result:rsc(11)(0).@) butterFly:write_mem(result:rsc(12)(0).@) butterFly:write_mem(result:rsc(0)(0).@)#1 butterFly:write_mem(result:rsc(1)(0).@)#1 butterFly:write_mem(result:rsc(2)(0).@)#1 butterFly:write_mem(result:rsc(3)(0).@)#1 butterFly:write_mem(result:rsc(4)(0).@)#1 butterFly:write_mem(result:rsc(5)(0).@)#1 butterFly:write_mem(result:rsc(6)(0).@)#1 butterFly:write_mem(result:rsc(7)(0).@)#1 butterFly:write_mem(result:rsc(8)(0).@)#1 butterFly:write_mem(result:rsc(9)(0).@)#1 butterFly:write_mem(result:rsc(10)(0).@)#1 butterFly:write_mem(result:rsc(11)(0).@)#1 butterFly:write_mem(result:rsc(12)(0).@)#1 butterFly:write_mem(result:rsc(13)(0).@) butterFly:write_mem(result:rsc(14)(0).@) butterFly:write_mem(result:rsc(13)(0).@)#1 butterFly:write_mem(result:rsc(14)(0).@)#1}
directive set /ntt_flat/core/butterFly:f2:read_mem(result:rsc(8)(0).@) -IGNORE_DEPENDENCY_FROM {butterFly:write_mem(result:rsc(0)(0).@) butterFly:write_mem(result:rsc(1)(0).@) butterFly:write_mem(result:rsc(2)(0).@) butterFly:write_mem(result:rsc(3)(0).@) butterFly:write_mem(result:rsc(4)(0).@) butterFly:write_mem(result:rsc(5)(0).@) butterFly:write_mem(result:rsc(6)(0).@) butterFly:write_mem(result:rsc(7)(0).@) butterFly:write_mem(result:rsc(8)(0).@) butterFly:write_mem(result:rsc(9)(0).@) butterFly:write_mem(result:rsc(10)(0).@) butterFly:write_mem(result:rsc(11)(0).@) butterFly:write_mem(result:rsc(12)(0).@) butterFly:write_mem(result:rsc(0)(0).@)#1 butterFly:write_mem(result:rsc(1)(0).@)#1 butterFly:write_mem(result:rsc(2)(0).@)#1 butterFly:write_mem(result:rsc(3)(0).@)#1 butterFly:write_mem(result:rsc(4)(0).@)#1 butterFly:write_mem(result:rsc(5)(0).@)#1 butterFly:write_mem(result:rsc(6)(0).@)#1 butterFly:write_mem(result:rsc(7)(0).@)#1 butterFly:write_mem(result:rsc(8)(0).@)#1 butterFly:write_mem(result:rsc(9)(0).@)#1 butterFly:write_mem(result:rsc(10)(0).@)#1 butterFly:write_mem(result:rsc(11)(0).@)#1 butterFly:write_mem(result:rsc(12)(0).@)#1 butterFly:write_mem(result:rsc(13)(0).@) butterFly:write_mem(result:rsc(14)(0).@) butterFly:write_mem(result:rsc(13)(0).@)#1 butterFly:write_mem(result:rsc(14)(0).@)#1}
directive set /ntt_flat/core/butterFly:f2:read_mem(result:rsc(9)(0).@) -IGNORE_DEPENDENCY_FROM {butterFly:write_mem(result:rsc(0)(0).@) butterFly:write_mem(result:rsc(1)(0).@) butterFly:write_mem(result:rsc(2)(0).@) butterFly:write_mem(result:rsc(3)(0).@) butterFly:write_mem(result:rsc(4)(0).@) butterFly:write_mem(result:rsc(5)(0).@) butterFly:write_mem(result:rsc(6)(0).@) butterFly:write_mem(result:rsc(7)(0).@) butterFly:write_mem(result:rsc(8)(0).@) butterFly:write_mem(result:rsc(9)(0).@) butterFly:write_mem(result:rsc(10)(0).@) butterFly:write_mem(result:rsc(11)(0).@) butterFly:write_mem(result:rsc(12)(0).@) butterFly:write_mem(result:rsc(0)(0).@)#1 butterFly:write_mem(result:rsc(1)(0).@)#1 butterFly:write_mem(result:rsc(2)(0).@)#1 butterFly:write_mem(result:rsc(3)(0).@)#1 butterFly:write_mem(result:rsc(4)(0).@)#1 butterFly:write_mem(result:rsc(5)(0).@)#1 butterFly:write_mem(result:rsc(6)(0).@)#1 butterFly:write_mem(result:rsc(7)(0).@)#1 butterFly:write_mem(result:rsc(8)(0).@)#1 butterFly:write_mem(result:rsc(9)(0).@)#1 butterFly:write_mem(result:rsc(10)(0).@)#1 butterFly:write_mem(result:rsc(11)(0).@)#1 butterFly:write_mem(result:rsc(12)(0).@)#1 butterFly:write_mem(result:rsc(13)(0).@) butterFly:write_mem(result:rsc(14)(0).@) butterFly:write_mem(result:rsc(13)(0).@)#1 butterFly:write_mem(result:rsc(14)(0).@)#1}
directive set /ntt_flat/core/butterFly:f2:read_mem(result:rsc(10)(0).@) -IGNORE_DEPENDENCY_FROM {butterFly:write_mem(result:rsc(0)(0).@) butterFly:write_mem(result:rsc(1)(0).@) butterFly:write_mem(result:rsc(2)(0).@) butterFly:write_mem(result:rsc(3)(0).@) butterFly:write_mem(result:rsc(4)(0).@) butterFly:write_mem(result:rsc(5)(0).@) butterFly:write_mem(result:rsc(6)(0).@) butterFly:write_mem(result:rsc(7)(0).@) butterFly:write_mem(result:rsc(8)(0).@) butterFly:write_mem(result:rsc(9)(0).@) butterFly:write_mem(result:rsc(10)(0).@) butterFly:write_mem(result:rsc(11)(0).@) butterFly:write_mem(result:rsc(12)(0).@) butterFly:write_mem(result:rsc(0)(0).@)#1 butterFly:write_mem(result:rsc(1)(0).@)#1 butterFly:write_mem(result:rsc(2)(0).@)#1 butterFly:write_mem(result:rsc(3)(0).@)#1 butterFly:write_mem(result:rsc(4)(0).@)#1 butterFly:write_mem(result:rsc(5)(0).@)#1 butterFly:write_mem(result:rsc(6)(0).@)#1 butterFly:write_mem(result:rsc(7)(0).@)#1 butterFly:write_mem(result:rsc(8)(0).@)#1 butterFly:write_mem(result:rsc(9)(0).@)#1 butterFly:write_mem(result:rsc(10)(0).@)#1 butterFly:write_mem(result:rsc(11)(0).@)#1 butterFly:write_mem(result:rsc(12)(0).@)#1 butterFly:write_mem(result:rsc(13)(0).@) butterFly:write_mem(result:rsc(14)(0).@) butterFly:write_mem(result:rsc(13)(0).@)#1 butterFly:write_mem(result:rsc(14)(0).@)#1}
directive set /ntt_flat/core/butterFly:f2:read_mem(result:rsc(11)(0).@) -IGNORE_DEPENDENCY_FROM {butterFly:write_mem(result:rsc(0)(0).@) butterFly:write_mem(result:rsc(1)(0).@) butterFly:write_mem(result:rsc(2)(0).@) butterFly:write_mem(result:rsc(3)(0).@) butterFly:write_mem(result:rsc(4)(0).@) butterFly:write_mem(result:rsc(5)(0).@) butterFly:write_mem(result:rsc(6)(0).@) butterFly:write_mem(result:rsc(7)(0).@) butterFly:write_mem(result:rsc(8)(0).@) butterFly:write_mem(result:rsc(9)(0).@) butterFly:write_mem(result:rsc(10)(0).@) butterFly:write_mem(result:rsc(11)(0).@) butterFly:write_mem(result:rsc(12)(0).@) butterFly:write_mem(result:rsc(0)(0).@)#1 butterFly:write_mem(result:rsc(1)(0).@)#1 butterFly:write_mem(result:rsc(2)(0).@)#1 butterFly:write_mem(result:rsc(3)(0).@)#1 butterFly:write_mem(result:rsc(4)(0).@)#1 butterFly:write_mem(result:rsc(5)(0).@)#1 butterFly:write_mem(result:rsc(6)(0).@)#1 butterFly:write_mem(result:rsc(7)(0).@)#1 butterFly:write_mem(result:rsc(8)(0).@)#1 butterFly:write_mem(result:rsc(9)(0).@)#1 butterFly:write_mem(result:rsc(10)(0).@)#1 butterFly:write_mem(result:rsc(11)(0).@)#1 butterFly:write_mem(result:rsc(12)(0).@)#1 butterFly:write_mem(result:rsc(13)(0).@) butterFly:write_mem(result:rsc(14)(0).@) butterFly:write_mem(result:rsc(13)(0).@)#1 butterFly:write_mem(result:rsc(14)(0).@)#1}
directive set /ntt_flat/core/butterFly:f2:read_mem(result:rsc(12)(0).@) -IGNORE_DEPENDENCY_FROM {butterFly:write_mem(result:rsc(0)(0).@) butterFly:write_mem(result:rsc(1)(0).@) butterFly:write_mem(result:rsc(2)(0).@) butterFly:write_mem(result:rsc(3)(0).@) butterFly:write_mem(result:rsc(4)(0).@) butterFly:write_mem(result:rsc(5)(0).@) butterFly:write_mem(result:rsc(6)(0).@) butterFly:write_mem(result:rsc(7)(0).@) butterFly:write_mem(result:rsc(8)(0).@) butterFly:write_mem(result:rsc(9)(0).@) butterFly:write_mem(result:rsc(10)(0).@) butterFly:write_mem(result:rsc(11)(0).@) butterFly:write_mem(result:rsc(12)(0).@) butterFly:write_mem(result:rsc(0)(0).@)#1 butterFly:write_mem(result:rsc(1)(0).@)#1 butterFly:write_mem(result:rsc(2)(0).@)#1 butterFly:write_mem(result:rsc(3)(0).@)#1 butterFly:write_mem(result:rsc(4)(0).@)#1 butterFly:write_mem(result:rsc(5)(0).@)#1 butterFly:write_mem(result:rsc(6)(0).@)#1 butterFly:write_mem(result:rsc(7)(0).@)#1 butterFly:write_mem(result:rsc(8)(0).@)#1 butterFly:write_mem(result:rsc(9)(0).@)#1 butterFly:write_mem(result:rsc(10)(0).@)#1 butterFly:write_mem(result:rsc(11)(0).@)#1 butterFly:write_mem(result:rsc(12)(0).@)#1 butterFly:write_mem(result:rsc(13)(0).@) butterFly:write_mem(result:rsc(14)(0).@) butterFly:write_mem(result:rsc(13)(0).@)#1 butterFly:write_mem(result:rsc(14)(0).@)#1}
directive set /ntt_flat/core/butterFly:f2:read_mem(result:rsc(13)(0).@) -IGNORE_DEPENDENCY_FROM {butterFly:write_mem(result:rsc(0)(0).@) butterFly:write_mem(result:rsc(1)(0).@) butterFly:write_mem(result:rsc(2)(0).@) butterFly:write_mem(result:rsc(3)(0).@) butterFly:write_mem(result:rsc(4)(0).@) butterFly:write_mem(result:rsc(5)(0).@) butterFly:write_mem(result:rsc(6)(0).@) butterFly:write_mem(result:rsc(7)(0).@) butterFly:write_mem(result:rsc(8)(0).@) butterFly:write_mem(result:rsc(9)(0).@) butterFly:write_mem(result:rsc(10)(0).@) butterFly:write_mem(result:rsc(11)(0).@) butterFly:write_mem(result:rsc(12)(0).@) butterFly:write_mem(result:rsc(13)(0).@) butterFly:write_mem(result:rsc(14)(0).@) butterFly:write_mem(result:rsc(0)(0).@)#1 butterFly:write_mem(result:rsc(1)(0).@)#1 butterFly:write_mem(result:rsc(2)(0).@)#1 butterFly:write_mem(result:rsc(3)(0).@)#1 butterFly:write_mem(result:rsc(4)(0).@)#1 butterFly:write_mem(result:rsc(5)(0).@)#1 butterFly:write_mem(result:rsc(6)(0).@)#1 butterFly:write_mem(result:rsc(7)(0).@)#1 butterFly:write_mem(result:rsc(8)(0).@)#1 butterFly:write_mem(result:rsc(9)(0).@)#1 butterFly:write_mem(result:rsc(10)(0).@)#1 butterFly:write_mem(result:rsc(11)(0).@)#1 butterFly:write_mem(result:rsc(12)(0).@)#1 butterFly:write_mem(result:rsc(13)(0).@)#1 butterFly:write_mem(result:rsc(14)(0).@)#1}
directive set /ntt_flat/core/butterFly:f2:read_mem(result:rsc(14)(0).@) -IGNORE_DEPENDENCY_FROM {butterFly:write_mem(result:rsc(0)(0).@) butterFly:write_mem(result:rsc(1)(0).@) butterFly:write_mem(result:rsc(2)(0).@) butterFly:write_mem(result:rsc(3)(0).@) butterFly:write_mem(result:rsc(4)(0).@) butterFly:write_mem(result:rsc(5)(0).@) butterFly:write_mem(result:rsc(6)(0).@) butterFly:write_mem(result:rsc(7)(0).@) butterFly:write_mem(result:rsc(8)(0).@) butterFly:write_mem(result:rsc(9)(0).@) butterFly:write_mem(result:rsc(10)(0).@) butterFly:write_mem(result:rsc(11)(0).@) butterFly:write_mem(result:rsc(12)(0).@) butterFly:write_mem(result:rsc(13)(0).@) butterFly:write_mem(result:rsc(14)(0).@) butterFly:write_mem(result:rsc(0)(0).@)#1 butterFly:write_mem(result:rsc(1)(0).@)#1 butterFly:write_mem(result:rsc(2)(0).@)#1 butterFly:write_mem(result:rsc(3)(0).@)#1 butterFly:write_mem(result:rsc(4)(0).@)#1 butterFly:write_mem(result:rsc(5)(0).@)#1 butterFly:write_mem(result:rsc(6)(0).@)#1 butterFly:write_mem(result:rsc(7)(0).@)#1 butterFly:write_mem(result:rsc(8)(0).@)#1 butterFly:write_mem(result:rsc(9)(0).@)#1 butterFly:write_mem(result:rsc(10)(0).@)#1 butterFly:write_mem(result:rsc(11)(0).@)#1 butterFly:write_mem(result:rsc(12)(0).@)#1 butterFly:write_mem(result:rsc(13)(0).@)#1 butterFly:write_mem(result:rsc(14)(0).@)#1}
go allocate
go extract
