directive set /inPlaceNTT_DIF/inPlaceNTT_DIF:core/inPlaceNTT_DIF:core:conc/STAGE_LOOP:lshift RESOURCE_NAME COMP_LOOP-5:tmp:lshift:rg
directive set /inPlaceNTT_DIF/inPlaceNTT_DIF:core/inPlaceNTT_DIF:core:conc/COMP_LOOP-5:tmp:lshift RESOURCE_NAME COMP_LOOP-5:tmp:lshift:rg
directive set /inPlaceNTT_DIF/inPlaceNTT_DIF:core/inPlaceNTT_DIF:core:conc/COMP_LOOP-1:tmp:lshift RESOURCE_NAME COMP_LOOP-1:tmp:lshift:rg
directive set /inPlaceNTT_DIF/inPlaceNTT_DIF:core/inPlaceNTT_DIF:core:conc/COMP_LOOP-2:tmp:lshift RESOURCE_NAME COMP_LOOP-1:tmp:lshift:rg
directive set /inPlaceNTT_DIF/inPlaceNTT_DIF:core/inPlaceNTT_DIF:core:conc/COMP_LOOP-3:tmp:lshift RESOURCE_NAME COMP_LOOP-1:tmp:lshift:rg
directive set /inPlaceNTT_DIF/inPlaceNTT_DIF:core/inPlaceNTT_DIF:core:conc/COMP_LOOP-5:tmp:mul RESOURCE_NAME COMP_LOOP-2:tmp:mul:rg
directive set /inPlaceNTT_DIF/inPlaceNTT_DIF:core/inPlaceNTT_DIF:core:conc/COMP_LOOP-2:tmp:mul RESOURCE_NAME COMP_LOOP-2:tmp:mul:rg
directive set /inPlaceNTT_DIF/inPlaceNTT_DIF:core/inPlaceNTT_DIF:core:conc/COMP_LOOP-4:tmp:mul RESOURCE_NAME COMP_LOOP-2:tmp:mul:rg
directive set /inPlaceNTT_DIF/inPlaceNTT_DIF:core/inPlaceNTT_DIF:core:conc/COMP_LOOP-6:tmp:mul RESOURCE_NAME COMP_LOOP-2:tmp:mul:rg
directive set /inPlaceNTT_DIF/inPlaceNTT_DIF:core/inPlaceNTT_DIF:core:conc/COMP_LOOP-8:tmp:mul RESOURCE_NAME COMP_LOOP-2:tmp:mul:rg
directive set /inPlaceNTT_DIF/inPlaceNTT_DIF:core/inPlaceNTT_DIF:core:conc/COMP_LOOP-3:tmp:mul RESOURCE_NAME COMP_LOOP-2:tmp:mul:rg
directive set /inPlaceNTT_DIF/inPlaceNTT_DIF:core/inPlaceNTT_DIF:core:conc/COMP_LOOP-7:tmp:mul RESOURCE_NAME COMP_LOOP-2:tmp:mul:rg
directive set /inPlaceNTT_DIF/inPlaceNTT_DIF:core/inPlaceNTT_DIF:core:conc/COMP_LOOP-1:tmp:mul RESOURCE_NAME COMP_LOOP-1:mul:rg
directive set /inPlaceNTT_DIF/inPlaceNTT_DIF:core/inPlaceNTT_DIF:core:conc/COMP_LOOP-1:mul RESOURCE_NAME COMP_LOOP-1:mul:rg
directive set /inPlaceNTT_DIF/inPlaceNTT_DIF:core/inPlaceNTT_DIF:core:conc/COMP_LOOP-2:mul RESOURCE_NAME COMP_LOOP-1:mul:rg
directive set /inPlaceNTT_DIF/inPlaceNTT_DIF:core/inPlaceNTT_DIF:core:conc/COMP_LOOP-3:mul RESOURCE_NAME COMP_LOOP-1:mul:rg
directive set /inPlaceNTT_DIF/inPlaceNTT_DIF:core/inPlaceNTT_DIF:core:conc/COMP_LOOP-4:mul RESOURCE_NAME COMP_LOOP-1:mul:rg
directive set /inPlaceNTT_DIF/inPlaceNTT_DIF:core/inPlaceNTT_DIF:core:conc/COMP_LOOP-5:mul RESOURCE_NAME COMP_LOOP-1:mul:rg
directive set /inPlaceNTT_DIF/inPlaceNTT_DIF:core/inPlaceNTT_DIF:core:conc/COMP_LOOP-6:mul RESOURCE_NAME COMP_LOOP-1:mul:rg
directive set /inPlaceNTT_DIF/inPlaceNTT_DIF:core/inPlaceNTT_DIF:core:conc/COMP_LOOP-7:mul RESOURCE_NAME COMP_LOOP-1:mul:rg
directive set /inPlaceNTT_DIF/inPlaceNTT_DIF:core/inPlaceNTT_DIF:core:conc/COMP_LOOP-8:mul RESOURCE_NAME COMP_LOOP-1:mul:rg
directive set /inPlaceNTT_DIF/inPlaceNTT_DIF:core/inPlaceNTT_DIF:core:conc/COMP_LOOP:acc#16 RESOURCE_NAME COMP_LOOP:acc#16:rg
directive set /inPlaceNTT_DIF/inPlaceNTT_DIF:core/inPlaceNTT_DIF:core:conc/STAGE_LOOP:acc RESOURCE_NAME COMP_LOOP:acc#16:rg
directive set /inPlaceNTT_DIF/inPlaceNTT_DIF:core/inPlaceNTT_DIF:core:conc/COMP_LOOP-2:acc RESOURCE_NAME COMP_LOOP-2:acc:rg
directive set /inPlaceNTT_DIF/inPlaceNTT_DIF:core/inPlaceNTT_DIF:core:conc/VEC_LOOP:acc#1 RESOURCE_NAME COMP_LOOP-2:acc:rg
directive set /inPlaceNTT_DIF/inPlaceNTT_DIF:core/inPlaceNTT_DIF:core:conc/STAGE_LOOP:acc#1 RESOURCE_NAME COMP_LOOP-1:tmp:acc:rg
directive set /inPlaceNTT_DIF/inPlaceNTT_DIF:core/inPlaceNTT_DIF:core:conc/COMP_LOOP-1:tmp:acc RESOURCE_NAME COMP_LOOP-1:tmp:acc:rg
directive set /inPlaceNTT_DIF/inPlaceNTT_DIF:core/inPlaceNTT_DIF:core:conc/COMP_LOOP-1:acc#8 RESOURCE_NAME COMP_LOOP-1:acc#8:rg
directive set /inPlaceNTT_DIF/inPlaceNTT_DIF:core/inPlaceNTT_DIF:core:conc/COMP_LOOP-2:acc#8 RESOURCE_NAME COMP_LOOP-1:acc#8:rg
directive set /inPlaceNTT_DIF/inPlaceNTT_DIF:core/inPlaceNTT_DIF:core:conc/COMP_LOOP-3:acc#8 RESOURCE_NAME COMP_LOOP-1:acc#8:rg
directive set /inPlaceNTT_DIF/inPlaceNTT_DIF:core/inPlaceNTT_DIF:core:conc/COMP_LOOP-4:acc#8 RESOURCE_NAME COMP_LOOP-1:acc#8:rg
directive set /inPlaceNTT_DIF/inPlaceNTT_DIF:core/inPlaceNTT_DIF:core:conc/COMP_LOOP-5:acc#8 RESOURCE_NAME COMP_LOOP-1:acc#8:rg
directive set /inPlaceNTT_DIF/inPlaceNTT_DIF:core/inPlaceNTT_DIF:core:conc/COMP_LOOP-6:acc#8 RESOURCE_NAME COMP_LOOP-1:acc#8:rg
directive set /inPlaceNTT_DIF/inPlaceNTT_DIF:core/inPlaceNTT_DIF:core:conc/COMP_LOOP-7:acc#8 RESOURCE_NAME COMP_LOOP-1:acc#8:rg
directive set /inPlaceNTT_DIF/inPlaceNTT_DIF:core/inPlaceNTT_DIF:core:conc/COMP_LOOP-8:acc#8 RESOURCE_NAME COMP_LOOP-1:acc#8:rg
directive set /inPlaceNTT_DIF/inPlaceNTT_DIF:core/inPlaceNTT_DIF:core:conc/COMP_LOOP-1:acc#6 RESOURCE_NAME COMP_LOOP-1:acc#6:rg
directive set /inPlaceNTT_DIF/inPlaceNTT_DIF:core/inPlaceNTT_DIF:core:conc/COMP_LOOP-2:acc#6 RESOURCE_NAME COMP_LOOP-1:acc#6:rg
directive set /inPlaceNTT_DIF/inPlaceNTT_DIF:core/inPlaceNTT_DIF:core:conc/COMP_LOOP-3:acc#6 RESOURCE_NAME COMP_LOOP-1:acc#6:rg
directive set /inPlaceNTT_DIF/inPlaceNTT_DIF:core/inPlaceNTT_DIF:core:conc/COMP_LOOP-4:acc#6 RESOURCE_NAME COMP_LOOP-1:acc#6:rg
directive set /inPlaceNTT_DIF/inPlaceNTT_DIF:core/inPlaceNTT_DIF:core:conc/COMP_LOOP-5:acc#6 RESOURCE_NAME COMP_LOOP-1:acc#6:rg
directive set /inPlaceNTT_DIF/inPlaceNTT_DIF:core/inPlaceNTT_DIF:core:conc/COMP_LOOP-6:acc#6 RESOURCE_NAME COMP_LOOP-1:acc#6:rg
directive set /inPlaceNTT_DIF/inPlaceNTT_DIF:core/inPlaceNTT_DIF:core:conc/COMP_LOOP-7:acc#6 RESOURCE_NAME COMP_LOOP-1:acc#6:rg
directive set /inPlaceNTT_DIF/inPlaceNTT_DIF:core/inPlaceNTT_DIF:core:conc/COMP_LOOP-8:acc#6 RESOURCE_NAME COMP_LOOP-1:acc#6:rg
directive set /inPlaceNTT_DIF/inPlaceNTT_DIF:core/inPlaceNTT_DIF:core:conc/COMP_LOOP:mux1h#185 RESOURCE_NAME COMP_LOOP:mux1h#185:rg
directive set /inPlaceNTT_DIF/inPlaceNTT_DIF:core/inPlaceNTT_DIF:core:conc/COMP_LOOP:mux1h#186 RESOURCE_NAME COMP_LOOP:mux1h#185:rg
directive set /inPlaceNTT_DIF/inPlaceNTT_DIF:core/inPlaceNTT_DIF:core:conc/COMP_LOOP:mux1h#187 RESOURCE_NAME COMP_LOOP:mux1h#185:rg
directive set /inPlaceNTT_DIF/inPlaceNTT_DIF:core/inPlaceNTT_DIF:core:conc/COMP_LOOP:mux1h#188 RESOURCE_NAME COMP_LOOP:mux1h#185:rg
directive set /inPlaceNTT_DIF/inPlaceNTT_DIF:core/inPlaceNTT_DIF:core:conc/COMP_LOOP:mux1h#189 RESOURCE_NAME COMP_LOOP:mux1h#185:rg
directive set /inPlaceNTT_DIF/inPlaceNTT_DIF:core/inPlaceNTT_DIF:core:conc/COMP_LOOP:mux1h#190 RESOURCE_NAME COMP_LOOP:mux1h#185:rg
directive set /inPlaceNTT_DIF/inPlaceNTT_DIF:core/inPlaceNTT_DIF:core:conc/COMP_LOOP:mux1h#191 RESOURCE_NAME COMP_LOOP:mux1h#185:rg
directive set /inPlaceNTT_DIF/inPlaceNTT_DIF:core/inPlaceNTT_DIF:core:conc/COMP_LOOP:mux1h#192 RESOURCE_NAME COMP_LOOP:mux1h#185:rg
