directive set /DIT_RELOOP/DIT_RELOOP:core/core/IDX_LOOP-1:lshift.idiv.sva REGISTER_NAME IDX_LOOP-1:lshift.idiv.sva
directive set /DIT_RELOOP/DIT_RELOOP:core/core/IDX_LOOP-2:lshift.idiv.sva REGISTER_NAME IDX_LOOP-1:lshift.idiv.sva
directive set /DIT_RELOOP/DIT_RELOOP:core/core/tmp#1.lpi#4.dfm REGISTER_NAME tmp#1.lpi#4.dfm
directive set /DIT_RELOOP/DIT_RELOOP:core/core/tmp#3.lpi#4.dfm REGISTER_NAME tmp#1.lpi#4.dfm
directive set /DIT_RELOOP/DIT_RELOOP:core/core/IDX_LOOP:f1#1.sva REGISTER_NAME IDX_LOOP:f1#1.sva
directive set /DIT_RELOOP/DIT_RELOOP:core/core/IDX_LOOP:f1.sva REGISTER_NAME IDX_LOOP:f1#1.sva
directive set /DIT_RELOOP/DIT_RELOOP:core/core/IDX_LOOP:modulo_dev(return)#1.sva REGISTER_NAME IDX_LOOP:f1#1.sva
directive set /DIT_RELOOP/DIT_RELOOP:core/core/IDX_LOOP:modulo_dev(return)#3.sva REGISTER_NAME IDX_LOOP:f1#1.sva
directive set /DIT_RELOOP/DIT_RELOOP:core/core/IDX_LOOP-1:mul.mut REGISTER_NAME IDX_LOOP-1:mul.mut
directive set /DIT_RELOOP/DIT_RELOOP:core/core/IDX_LOOP-2:mul.mut REGISTER_NAME IDX_LOOP-1:mul.mut
