directive set /inPlaceNTT_DIT_precomp/inPlaceNTT_DIT_precomp:core/core/COMP_LOOP:twiddle_help#1.sva REGISTER_NAME COMP_LOOP:twiddle_help#1.sva
directive set /inPlaceNTT_DIT_precomp/inPlaceNTT_DIT_precomp:core/core/COMP_LOOP:twiddle_help#2.sva REGISTER_NAME COMP_LOOP:twiddle_help#1.sva
directive set /inPlaceNTT_DIT_precomp/inPlaceNTT_DIT_precomp:core/core/COMP_LOOP:twiddle_help#3.sva REGISTER_NAME COMP_LOOP:twiddle_help#1.sva
directive set /inPlaceNTT_DIT_precomp/inPlaceNTT_DIT_precomp:core/core/COMP_LOOP:twiddle_help.sva REGISTER_NAME COMP_LOOP:twiddle_help#1.sva
directive set /inPlaceNTT_DIT_precomp/inPlaceNTT_DIT_precomp:core/core/COMP_LOOP:twiddle_f#1.sva REGISTER_NAME COMP_LOOP:twiddle_f#1.sva
directive set /inPlaceNTT_DIT_precomp/inPlaceNTT_DIT_precomp:core/core/COMP_LOOP:twiddle_f#2.sva REGISTER_NAME COMP_LOOP:twiddle_f#1.sva
directive set /inPlaceNTT_DIT_precomp/inPlaceNTT_DIT_precomp:core/core/COMP_LOOP:twiddle_f#3.sva REGISTER_NAME COMP_LOOP:twiddle_f#1.sva
directive set /inPlaceNTT_DIT_precomp/inPlaceNTT_DIT_precomp:core/core/COMP_LOOP:twiddle_f.sva REGISTER_NAME COMP_LOOP:twiddle_f#1.sva
directive set /inPlaceNTT_DIT_precomp/inPlaceNTT_DIT_precomp:core/core/COMP_LOOP-1:VEC_LOOP:slc(VEC_LOOP:acc)(22).itm REGISTER_NAME COMP_LOOP-1:VEC_LOOP:slc(VEC_LOOP:acc)(22).itm
directive set /inPlaceNTT_DIT_precomp/inPlaceNTT_DIT_precomp:core/core/run_ac_sync_tmp_dobj.sva REGISTER_NAME COMP_LOOP-1:VEC_LOOP:slc(VEC_LOOP:acc)(22).itm
directive set /inPlaceNTT_DIT_precomp/inPlaceNTT_DIT_precomp:core/core/VEC_LOOP:acc#10.cse#1.sva REGISTER_NAME VEC_LOOP:acc#10.cse#1.sva
directive set /inPlaceNTT_DIT_precomp/inPlaceNTT_DIT_precomp:core/core/VEC_LOOP:acc#10.cse#2.sva REGISTER_NAME VEC_LOOP:acc#10.cse#1.sva
directive set /inPlaceNTT_DIT_precomp/inPlaceNTT_DIT_precomp:core/core/VEC_LOOP:acc#10.cse#3.sva REGISTER_NAME VEC_LOOP:acc#10.cse#1.sva
directive set /inPlaceNTT_DIT_precomp/inPlaceNTT_DIT_precomp:core/core/VEC_LOOP:acc#10.cse.sva REGISTER_NAME VEC_LOOP:acc#10.cse#1.sva
directive set /inPlaceNTT_DIT_precomp/inPlaceNTT_DIT_precomp:core/core/factor1#1.sva REGISTER_NAME factor1#1.sva
directive set /inPlaceNTT_DIT_precomp/inPlaceNTT_DIT_precomp:core/core/factor1#2.sva REGISTER_NAME factor1#1.sva
directive set /inPlaceNTT_DIT_precomp/inPlaceNTT_DIT_precomp:core/core/factor1#3.sva REGISTER_NAME factor1#1.sva
directive set /inPlaceNTT_DIT_precomp/inPlaceNTT_DIT_precomp:core/core/factor1.sva REGISTER_NAME factor1#1.sva
directive set /inPlaceNTT_DIT_precomp/inPlaceNTT_DIT_precomp:core/core/COMP_LOOP-1:operator>><96,false>:operator>><96,false>:slc(mult:t:mul)(63-32).itm REGISTER_NAME COMP_LOOP-1:operator>><96,false>:operator>><96,false>:slc(mult:t:mul)(63-32).itm
directive set /inPlaceNTT_DIT_precomp/inPlaceNTT_DIT_precomp:core/core/COMP_LOOP-2:operator>><96,false>:operator>><96,false>:slc(mult:t:mul)(63-32).itm REGISTER_NAME COMP_LOOP-1:operator>><96,false>:operator>><96,false>:slc(mult:t:mul)(63-32).itm
directive set /inPlaceNTT_DIT_precomp/inPlaceNTT_DIT_precomp:core/core/COMP_LOOP-3:operator>><96,false>:operator>><96,false>:slc(mult:t:mul)(63-32).itm REGISTER_NAME COMP_LOOP-1:operator>><96,false>:operator>><96,false>:slc(mult:t:mul)(63-32).itm
directive set /inPlaceNTT_DIT_precomp/inPlaceNTT_DIT_precomp:core/core/COMP_LOOP-4:operator>><96,false>:operator>><96,false>:slc(mult:t:mul)(63-32).itm REGISTER_NAME COMP_LOOP-1:operator>><96,false>:operator>><96,false>:slc(mult:t:mul)(63-32).itm
directive set /inPlaceNTT_DIT_precomp/inPlaceNTT_DIT_precomp:core/core/mult:x#1.sva REGISTER_NAME COMP_LOOP-1:operator>><96,false>:operator>><96,false>:slc(mult:t:mul)(63-32).itm
directive set /inPlaceNTT_DIT_precomp/inPlaceNTT_DIT_precomp:core/core/mult:x#2.sva REGISTER_NAME COMP_LOOP-1:operator>><96,false>:operator>><96,false>:slc(mult:t:mul)(63-32).itm
directive set /inPlaceNTT_DIT_precomp/inPlaceNTT_DIT_precomp:core/core/mult:x#3.sva REGISTER_NAME COMP_LOOP-1:operator>><96,false>:operator>><96,false>:slc(mult:t:mul)(63-32).itm
directive set /inPlaceNTT_DIT_precomp/inPlaceNTT_DIT_precomp:core/core/mult:x.sva REGISTER_NAME COMP_LOOP-1:operator>><96,false>:operator>><96,false>:slc(mult:t:mul)(63-32).itm
directive set /inPlaceNTT_DIT_precomp/inPlaceNTT_DIT_precomp:core/core/VEC_LOOP:modulo_sub(return)#1.sva REGISTER_NAME COMP_LOOP-1:operator>><96,false>:operator>><96,false>:slc(mult:t:mul)(63-32).itm
directive set /inPlaceNTT_DIT_precomp/inPlaceNTT_DIT_precomp:core/core/VEC_LOOP:modulo_sub(return)#2.sva REGISTER_NAME COMP_LOOP-1:operator>><96,false>:operator>><96,false>:slc(mult:t:mul)(63-32).itm
directive set /inPlaceNTT_DIT_precomp/inPlaceNTT_DIT_precomp:core/core/VEC_LOOP:modulo_sub(return)#3.sva REGISTER_NAME COMP_LOOP-1:operator>><96,false>:operator>><96,false>:slc(mult:t:mul)(63-32).itm
directive set /inPlaceNTT_DIT_precomp/inPlaceNTT_DIT_precomp:core/core/VEC_LOOP:modulo_sub(return).sva REGISTER_NAME COMP_LOOP-1:operator>><96,false>:operator>><96,false>:slc(mult:t:mul)(63-32).itm
directive set /inPlaceNTT_DIT_precomp/inPlaceNTT_DIT_precomp:core/core/VEC_LOOP:j#2(10:0).sva#1 REGISTER_NAME VEC_LOOP:j#2(10:0).sva#1
directive set /inPlaceNTT_DIT_precomp/inPlaceNTT_DIT_precomp:core/core/VEC_LOOP:j#3(10:0).sva#1 REGISTER_NAME VEC_LOOP:j#2(10:0).sva#1
directive set /inPlaceNTT_DIT_precomp/inPlaceNTT_DIT_precomp:core/core/VEC_LOOP:j(10:0).sva#1 REGISTER_NAME VEC_LOOP:j#2(10:0).sva#1
directive set /inPlaceNTT_DIT_precomp/inPlaceNTT_DIT_precomp:core/core/VEC_LOOP:acc#1.cse#2.sva REGISTER_NAME VEC_LOOP:acc#1.cse#2.sva
directive set /inPlaceNTT_DIT_precomp/inPlaceNTT_DIT_precomp:core/core/VEC_LOOP:acc#1.cse.sva REGISTER_NAME VEC_LOOP:acc#1.cse#2.sva
directive set /inPlaceNTT_DIT_precomp/inPlaceNTT_DIT_precomp:core/core/VEC_LOOP:j#2(10:0).sva(9:0) REGISTER_NAME VEC_LOOP:acc#1.cse#2.sva
directive set /inPlaceNTT_DIT_precomp/inPlaceNTT_DIT_precomp:core/core/VEC_LOOP:j(10:0).sva(9:0) REGISTER_NAME VEC_LOOP:acc#1.cse#2.sva
directive set /inPlaceNTT_DIT_precomp/inPlaceNTT_DIT_precomp:core/core/VEC_LOOP:j#3(10:0).sva(9:0) REGISTER_NAME VEC_LOOP:acc#1.cse#2.sva
