directive set /inPlaceNTT_DIT_precomp/inPlaceNTT_DIT_precomp:core/core/VEC_LOOP:j#1.sva REGISTER_NAME VEC_LOOP:j#1.sva
directive set /inPlaceNTT_DIT_precomp/inPlaceNTT_DIT_precomp:core/core/VEC_LOOP:modulo_sub(return)#1.sva REGISTER_NAME VEC_LOOP:j#1.sva
directive set /inPlaceNTT_DIT_precomp/inPlaceNTT_DIT_precomp:core/core/VEC_LOOP:modulo_sub(return)#2.sva REGISTER_NAME VEC_LOOP:j#1.sva
directive set /inPlaceNTT_DIT_precomp/inPlaceNTT_DIT_precomp:core/core/VEC_LOOP:modulo_sub(return)#3.sva REGISTER_NAME VEC_LOOP:j#1.sva
directive set /inPlaceNTT_DIT_precomp/inPlaceNTT_DIT_precomp:core/core/VEC_LOOP:modulo_sub(return)#4.sva REGISTER_NAME VEC_LOOP:j#1.sva
directive set /inPlaceNTT_DIT_precomp/inPlaceNTT_DIT_precomp:core/core/VEC_LOOP:modulo_sub(return)#5.sva REGISTER_NAME VEC_LOOP:j#1.sva
directive set /inPlaceNTT_DIT_precomp/inPlaceNTT_DIT_precomp:core/core/VEC_LOOP:modulo_sub(return)#6.sva REGISTER_NAME VEC_LOOP:j#1.sva
directive set /inPlaceNTT_DIT_precomp/inPlaceNTT_DIT_precomp:core/core/VEC_LOOP:modulo_sub(return)#7.sva REGISTER_NAME VEC_LOOP:j#1.sva
directive set /inPlaceNTT_DIT_precomp/inPlaceNTT_DIT_precomp:core/core/VEC_LOOP:modulo_sub(return).sva REGISTER_NAME VEC_LOOP:j#1.sva
directive set /inPlaceNTT_DIT_precomp/inPlaceNTT_DIT_precomp:core/core/COMP_LOOP:twiddle_help#1.sva REGISTER_NAME COMP_LOOP:twiddle_help#1.sva
directive set /inPlaceNTT_DIT_precomp/inPlaceNTT_DIT_precomp:core/core/COMP_LOOP:twiddle_help#2.sva REGISTER_NAME COMP_LOOP:twiddle_help#1.sva
directive set /inPlaceNTT_DIT_precomp/inPlaceNTT_DIT_precomp:core/core/COMP_LOOP:twiddle_help#3.sva REGISTER_NAME COMP_LOOP:twiddle_help#1.sva
directive set /inPlaceNTT_DIT_precomp/inPlaceNTT_DIT_precomp:core/core/COMP_LOOP:twiddle_help#4.sva REGISTER_NAME COMP_LOOP:twiddle_help#1.sva
directive set /inPlaceNTT_DIT_precomp/inPlaceNTT_DIT_precomp:core/core/COMP_LOOP:twiddle_help#5.sva REGISTER_NAME COMP_LOOP:twiddle_help#1.sva
directive set /inPlaceNTT_DIT_precomp/inPlaceNTT_DIT_precomp:core/core/COMP_LOOP:twiddle_help#6.sva REGISTER_NAME COMP_LOOP:twiddle_help#1.sva
directive set /inPlaceNTT_DIT_precomp/inPlaceNTT_DIT_precomp:core/core/COMP_LOOP:twiddle_help#7.sva REGISTER_NAME COMP_LOOP:twiddle_help#1.sva
directive set /inPlaceNTT_DIT_precomp/inPlaceNTT_DIT_precomp:core/core/COMP_LOOP:twiddle_help.sva REGISTER_NAME COMP_LOOP:twiddle_help#1.sva
directive set /inPlaceNTT_DIT_precomp/inPlaceNTT_DIT_precomp:core/core/COMP_LOOP:twiddle_f#1.sva REGISTER_NAME COMP_LOOP:twiddle_f#1.sva
directive set /inPlaceNTT_DIT_precomp/inPlaceNTT_DIT_precomp:core/core/COMP_LOOP:twiddle_f#2.sva REGISTER_NAME COMP_LOOP:twiddle_f#1.sva
directive set /inPlaceNTT_DIT_precomp/inPlaceNTT_DIT_precomp:core/core/COMP_LOOP:twiddle_f#3.sva REGISTER_NAME COMP_LOOP:twiddle_f#1.sva
directive set /inPlaceNTT_DIT_precomp/inPlaceNTT_DIT_precomp:core/core/COMP_LOOP:twiddle_f#4.sva REGISTER_NAME COMP_LOOP:twiddle_f#1.sva
directive set /inPlaceNTT_DIT_precomp/inPlaceNTT_DIT_precomp:core/core/COMP_LOOP:twiddle_f#5.sva REGISTER_NAME COMP_LOOP:twiddle_f#1.sva
directive set /inPlaceNTT_DIT_precomp/inPlaceNTT_DIT_precomp:core/core/COMP_LOOP:twiddle_f#6.sva REGISTER_NAME COMP_LOOP:twiddle_f#1.sva
directive set /inPlaceNTT_DIT_precomp/inPlaceNTT_DIT_precomp:core/core/COMP_LOOP:twiddle_f#7.sva REGISTER_NAME COMP_LOOP:twiddle_f#1.sva
directive set /inPlaceNTT_DIT_precomp/inPlaceNTT_DIT_precomp:core/core/COMP_LOOP:twiddle_f.sva REGISTER_NAME COMP_LOOP:twiddle_f#1.sva
directive set /inPlaceNTT_DIT_precomp/inPlaceNTT_DIT_precomp:core/core/COMP_LOOP-1:VEC_LOOP:slc(VEC_LOOP:acc)(20).itm REGISTER_NAME COMP_LOOP-1:VEC_LOOP:slc(VEC_LOOP:acc)(20).itm
directive set /inPlaceNTT_DIT_precomp/inPlaceNTT_DIT_precomp:core/core/run_ac_sync_tmp_dobj.sva REGISTER_NAME COMP_LOOP-1:VEC_LOOP:slc(VEC_LOOP:acc)(20).itm
directive set /inPlaceNTT_DIT_precomp/inPlaceNTT_DIT_precomp:core/core/VEC_LOOP:acc#10.cse#1.sva REGISTER_NAME VEC_LOOP:acc#10.cse#1.sva
directive set /inPlaceNTT_DIT_precomp/inPlaceNTT_DIT_precomp:core/core/VEC_LOOP:acc#10.cse#2.sva REGISTER_NAME VEC_LOOP:acc#10.cse#1.sva
directive set /inPlaceNTT_DIT_precomp/inPlaceNTT_DIT_precomp:core/core/VEC_LOOP:acc#10.cse#3.sva REGISTER_NAME VEC_LOOP:acc#10.cse#1.sva
directive set /inPlaceNTT_DIT_precomp/inPlaceNTT_DIT_precomp:core/core/VEC_LOOP:acc#10.cse#4.sva REGISTER_NAME VEC_LOOP:acc#10.cse#1.sva
directive set /inPlaceNTT_DIT_precomp/inPlaceNTT_DIT_precomp:core/core/VEC_LOOP:acc#10.cse#5.sva REGISTER_NAME VEC_LOOP:acc#10.cse#1.sva
directive set /inPlaceNTT_DIT_precomp/inPlaceNTT_DIT_precomp:core/core/VEC_LOOP:acc#10.cse#6.sva REGISTER_NAME VEC_LOOP:acc#10.cse#1.sva
directive set /inPlaceNTT_DIT_precomp/inPlaceNTT_DIT_precomp:core/core/VEC_LOOP:acc#10.cse#7.sva REGISTER_NAME VEC_LOOP:acc#10.cse#1.sva
directive set /inPlaceNTT_DIT_precomp/inPlaceNTT_DIT_precomp:core/core/VEC_LOOP:acc#10.cse.sva REGISTER_NAME VEC_LOOP:acc#10.cse#1.sva
directive set /inPlaceNTT_DIT_precomp/inPlaceNTT_DIT_precomp:core/core/factor1#1.sva REGISTER_NAME factor1#1.sva
directive set /inPlaceNTT_DIT_precomp/inPlaceNTT_DIT_precomp:core/core/factor1#2.sva REGISTER_NAME factor1#1.sva
directive set /inPlaceNTT_DIT_precomp/inPlaceNTT_DIT_precomp:core/core/factor1#3.sva REGISTER_NAME factor1#1.sva
directive set /inPlaceNTT_DIT_precomp/inPlaceNTT_DIT_precomp:core/core/factor1#4.sva REGISTER_NAME factor1#1.sva
directive set /inPlaceNTT_DIT_precomp/inPlaceNTT_DIT_precomp:core/core/factor1#5.sva REGISTER_NAME factor1#1.sva
directive set /inPlaceNTT_DIT_precomp/inPlaceNTT_DIT_precomp:core/core/factor1#6.sva REGISTER_NAME factor1#1.sva
directive set /inPlaceNTT_DIT_precomp/inPlaceNTT_DIT_precomp:core/core/factor1#7.sva REGISTER_NAME factor1#1.sva
directive set /inPlaceNTT_DIT_precomp/inPlaceNTT_DIT_precomp:core/core/factor1.sva REGISTER_NAME factor1#1.sva
directive set /inPlaceNTT_DIT_precomp/inPlaceNTT_DIT_precomp:core/core/VEC_LOOP:mult(vec)#1.sva REGISTER_NAME VEC_LOOP:mult(vec)#1.sva
directive set /inPlaceNTT_DIT_precomp/inPlaceNTT_DIT_precomp:core/core/VEC_LOOP:mult(vec)#2.sva REGISTER_NAME VEC_LOOP:mult(vec)#1.sva
directive set /inPlaceNTT_DIT_precomp/inPlaceNTT_DIT_precomp:core/core/VEC_LOOP:mult(vec)#3.sva REGISTER_NAME VEC_LOOP:mult(vec)#1.sva
directive set /inPlaceNTT_DIT_precomp/inPlaceNTT_DIT_precomp:core/core/VEC_LOOP:mult(vec)#4.sva REGISTER_NAME VEC_LOOP:mult(vec)#1.sva
directive set /inPlaceNTT_DIT_precomp/inPlaceNTT_DIT_precomp:core/core/VEC_LOOP:mult(vec)#5.sva REGISTER_NAME VEC_LOOP:mult(vec)#1.sva
directive set /inPlaceNTT_DIT_precomp/inPlaceNTT_DIT_precomp:core/core/VEC_LOOP:mult(vec)#6.sva REGISTER_NAME VEC_LOOP:mult(vec)#1.sva
directive set /inPlaceNTT_DIT_precomp/inPlaceNTT_DIT_precomp:core/core/VEC_LOOP:mult(vec)#7.sva REGISTER_NAME VEC_LOOP:mult(vec)#1.sva
directive set /inPlaceNTT_DIT_precomp/inPlaceNTT_DIT_precomp:core/core/VEC_LOOP:mult(vec).sva REGISTER_NAME VEC_LOOP:mult(vec)#1.sva
directive set /inPlaceNTT_DIT_precomp/inPlaceNTT_DIT_precomp:core/core/VEC_LOOP:j#2(12:0).sva#1 REGISTER_NAME VEC_LOOP:j#2(12:0).sva#1
directive set /inPlaceNTT_DIT_precomp/inPlaceNTT_DIT_precomp:core/core/VEC_LOOP:j#3(12:0).sva#1 REGISTER_NAME VEC_LOOP:j#2(12:0).sva#1
directive set /inPlaceNTT_DIT_precomp/inPlaceNTT_DIT_precomp:core/core/VEC_LOOP:j#4(12:0).sva#1 REGISTER_NAME VEC_LOOP:j#2(12:0).sva#1
directive set /inPlaceNTT_DIT_precomp/inPlaceNTT_DIT_precomp:core/core/VEC_LOOP:j#5(12:0).sva#1 REGISTER_NAME VEC_LOOP:j#2(12:0).sva#1
directive set /inPlaceNTT_DIT_precomp/inPlaceNTT_DIT_precomp:core/core/VEC_LOOP:j#6(12:0).sva#1 REGISTER_NAME VEC_LOOP:j#2(12:0).sva#1
directive set /inPlaceNTT_DIT_precomp/inPlaceNTT_DIT_precomp:core/core/VEC_LOOP:j#7(12:0).sva#1 REGISTER_NAME VEC_LOOP:j#2(12:0).sva#1
directive set /inPlaceNTT_DIT_precomp/inPlaceNTT_DIT_precomp:core/core/VEC_LOOP:j(12:0).sva#1 REGISTER_NAME VEC_LOOP:j#2(12:0).sva#1
directive set /inPlaceNTT_DIT_precomp/inPlaceNTT_DIT_precomp:core/core/VEC_LOOP:acc#1.cse#2.sva REGISTER_NAME VEC_LOOP:acc#1.cse#2.sva
directive set /inPlaceNTT_DIT_precomp/inPlaceNTT_DIT_precomp:core/core/VEC_LOOP:acc#1.cse#4.sva REGISTER_NAME VEC_LOOP:acc#1.cse#2.sva
directive set /inPlaceNTT_DIT_precomp/inPlaceNTT_DIT_precomp:core/core/VEC_LOOP:acc#1.cse#6.sva REGISTER_NAME VEC_LOOP:acc#1.cse#2.sva
directive set /inPlaceNTT_DIT_precomp/inPlaceNTT_DIT_precomp:core/core/VEC_LOOP:acc#1.cse.sva REGISTER_NAME VEC_LOOP:acc#1.cse#2.sva
directive set /inPlaceNTT_DIT_precomp/inPlaceNTT_DIT_precomp:core/core/VEC_LOOP:j#2(12:0).sva(11:0) REGISTER_NAME VEC_LOOP:acc#1.cse#2.sva
directive set /inPlaceNTT_DIT_precomp/inPlaceNTT_DIT_precomp:core/core/VEC_LOOP:j#4(12:0).sva(11:0) REGISTER_NAME VEC_LOOP:acc#1.cse#2.sva
directive set /inPlaceNTT_DIT_precomp/inPlaceNTT_DIT_precomp:core/core/VEC_LOOP:j#6(12:0).sva(11:0) REGISTER_NAME VEC_LOOP:acc#1.cse#2.sva
directive set /inPlaceNTT_DIT_precomp/inPlaceNTT_DIT_precomp:core/core/VEC_LOOP:j(12:0).sva(11:0) REGISTER_NAME VEC_LOOP:acc#1.cse#2.sva
directive set /inPlaceNTT_DIT_precomp/inPlaceNTT_DIT_precomp:core/core/VEC_LOOP:j#7(12:0).sva(11:0) REGISTER_NAME VEC_LOOP:acc#1.cse#2.sva
directive set /inPlaceNTT_DIT_precomp/inPlaceNTT_DIT_precomp:core/core/VEC_LOOP:j#3(12:0).sva(11:0) REGISTER_NAME VEC_LOOP:acc#1.cse#2.sva
directive set /inPlaceNTT_DIT_precomp/inPlaceNTT_DIT_precomp:core/core/VEC_LOOP:j#5(12:0).sva(11:0) REGISTER_NAME VEC_LOOP:acc#1.cse#2.sva
directive set /inPlaceNTT_DIT_precomp/inPlaceNTT_DIT_precomp:core/core/VEC_LOOP:acc.psp.sva REGISTER_NAME VEC_LOOP:acc#1.cse#2.sva
directive set /inPlaceNTT_DIT_precomp/inPlaceNTT_DIT_precomp:core/core/VEC_LOOP:acc#11.psp.sva REGISTER_NAME VEC_LOOP:acc#11.psp.sva
directive set /inPlaceNTT_DIT_precomp/inPlaceNTT_DIT_precomp:core/core/VEC_LOOP:acc#13.psp.sva REGISTER_NAME VEC_LOOP:acc#11.psp.sva
directive set /inPlaceNTT_DIT_precomp/inPlaceNTT_DIT_precomp:core/core/COMP_LOOP-5:twiddle_f:lshift.itm REGISTER_NAME VEC_LOOP:acc#11.psp.sva
directive set /inPlaceNTT_DIT_precomp/inPlaceNTT_DIT_precomp:core/core/VEC_LOOP:acc#12.psp.sva REGISTER_NAME VEC_LOOP:acc#11.psp.sva
