directive set /peaceNTT/peaceNTT:core/core/COPY_LOOP:i(12:3).sva(8:0) REGISTER_NAME COPY_LOOP:i(12:3).sva(8:0)
directive set /peaceNTT/peaceNTT:core/core/STAGE_LOOP:base(8:0).sva REGISTER_NAME COPY_LOOP:i(12:3).sva(8:0)
directive set /peaceNTT/peaceNTT:core/core/STAGE_LOOP:base:acc.cse.sva REGISTER_NAME STAGE_LOOP:base:acc.cse.sva
directive set /peaceNTT/peaceNTT:core/core/STAGE_LOOP:c(3:0).sva REGISTER_NAME STAGE_LOOP:base:acc.cse.sva
directive set /peaceNTT/peaceNTT:core/core/COMP_LOOP:f2:slc(COMP_LOOP:f2:read_mem(xt:rsc(0)(7).@)#15)(63-0).itm REGISTER_NAME COMP_LOOP:f2:slc(COMP_LOOP:f2:read_mem(xt:rsc(0)(7).@)#15)(63-0).itm
directive set /peaceNTT/peaceNTT:core/core/tmp#12(63:0).lpi#3.dfm REGISTER_NAME COMP_LOOP:f2:slc(COMP_LOOP:f2:read_mem(xt:rsc(0)(7).@)#15)(63-0).itm
directive set /peaceNTT/peaceNTT:core/core/COMP_LOOP-8:f2:acc.itm REGISTER_NAME COMP_LOOP-8:f2:acc.itm
directive set /peaceNTT/peaceNTT:core/core/COMP_LOOP:f2:mux1h.itm REGISTER_NAME COMP_LOOP-8:f2:acc.itm
directive set /peaceNTT/peaceNTT:core/core/COMP_LOOP-1:f2:acc.itm REGISTER_NAME COMP_LOOP-1:f2:acc.itm
directive set /peaceNTT/peaceNTT:core/core/COMP_LOOP:f2:mux#15.itm REGISTER_NAME COMP_LOOP-1:f2:acc.itm
directive set /peaceNTT/peaceNTT:core/core/COMP_LOOP-2:f2:acc.itm REGISTER_NAME COMP_LOOP-2:f2:acc.itm
directive set /peaceNTT/peaceNTT:core/core/COMP_LOOP:f2:mux#4.itm REGISTER_NAME COMP_LOOP-2:f2:acc.itm
directive set /peaceNTT/peaceNTT:core/core/COMP_LOOP-3:f2:acc.itm REGISTER_NAME COMP_LOOP-3:f2:acc.itm
directive set /peaceNTT/peaceNTT:core/core/COMP_LOOP:f2:mux#9.itm REGISTER_NAME COMP_LOOP-3:f2:acc.itm
directive set /peaceNTT/peaceNTT:core/core/COPY_LOOP#1:i:acc#10.itm REGISTER_NAME COPY_LOOP#1:i:acc#10.itm
directive set /peaceNTT/peaceNTT:core/core/COPY_LOOP#1:i:acc#11.itm REGISTER_NAME COPY_LOOP#1:i:acc#10.itm
directive set /peaceNTT/peaceNTT:core/core/COPY_LOOP#1:i:acc#13.itm REGISTER_NAME COPY_LOOP#1:i:acc#10.itm
directive set /peaceNTT/peaceNTT:core/core/COPY_LOOP#1:i:acc#14.mut REGISTER_NAME COPY_LOOP#1:i:acc#10.itm
directive set /peaceNTT/peaceNTT:core/core/COPY_LOOP#1:i:acc#15.mut REGISTER_NAME COPY_LOOP#1:i:acc#10.itm
directive set /peaceNTT/peaceNTT:core/core/COMP_LOOP:f2:read_mem(twiddle:rsc(0)(0).@).ncse.sva REGISTER_NAME COPY_LOOP#1:i:acc#10.itm
directive set /peaceNTT/peaceNTT:core/core/COMP_LOOP-4:f2:acc.itm REGISTER_NAME COMP_LOOP-4:f2:acc.itm
directive set /peaceNTT/peaceNTT:core/core/COMP_LOOP:f2:mux1h#2.itm REGISTER_NAME COMP_LOOP-4:f2:acc.itm
directive set /peaceNTT/peaceNTT:core/core/COMP_LOOP-5:f2:acc.itm REGISTER_NAME COMP_LOOP-5:f2:acc.itm
directive set /peaceNTT/peaceNTT:core/core/COPY_LOOP#1:i:acc#9.itm REGISTER_NAME COMP_LOOP-5:f2:acc.itm
directive set /peaceNTT/peaceNTT:core/core/COMP_LOOP:f2:mux1h#4.itm REGISTER_NAME COMP_LOOP-5:f2:acc.itm
directive set /peaceNTT/peaceNTT:core/core/COPY_LOOP#1:i:acc#12.itm REGISTER_NAME COPY_LOOP#1:i:acc#12.itm
directive set /peaceNTT/peaceNTT:core/core/COPY_LOOP#1:i:acc#8.itm REGISTER_NAME COPY_LOOP#1:i:acc#12.itm
directive set /peaceNTT/peaceNTT:core/core/COMP_LOOP-7:f2:acc.itm REGISTER_NAME COPY_LOOP#1:i:acc#12.itm
directive set /peaceNTT/peaceNTT:core/core/COMP_LOOP:f2:slc(COMP_LOOP:f2:read_mem(xt:rsc(0)(0).@)#1)(63-0).itm REGISTER_NAME COPY_LOOP#1:i:acc#12.itm
directive set /peaceNTT/peaceNTT:core/core/COMP_LOOP-6:f2:acc.itm REGISTER_NAME COMP_LOOP-6:f2:acc.itm
directive set /peaceNTT/peaceNTT:core/core/COMP_LOOP:f2:mux1h#6.itm REGISTER_NAME COMP_LOOP-6:f2:acc.itm
directive set /peaceNTT/peaceNTT:core/core/tmp#10(127:64).lpi#3.dfm REGISTER_NAME COMP_LOOP-6:f2:acc.itm
directive set /peaceNTT/peaceNTT:core/core/COPY_LOOP#1:i(12:3).sva(8:0) REGISTER_NAME COPY_LOOP#1:i(12:3).sva(8:0)
directive set /peaceNTT/peaceNTT:core/core/COPY_LOOP#1:i:slc(COMP_LOOP-8:f2:acc#3)(11-3).psp.sva REGISTER_NAME COPY_LOOP#1:i(12:3).sva(8:0)
directive set /peaceNTT/peaceNTT:core/core/COPY_LOOP#1:i(12:3).sva#1 REGISTER_NAME COPY_LOOP#1:i(12:3).sva#1
directive set /peaceNTT/peaceNTT:core/core/COPY_LOOP:i(12:3).sva#1 REGISTER_NAME COPY_LOOP#1:i(12:3).sva#1
