directive set /inPlaceNTT_DIF/inPlaceNTT_DIF:core/inPlaceNTT_DIF:core:conc/mult:if:acc RESOURCE_NAME modulo_sub:if:acc:rg
directive set /inPlaceNTT_DIF/inPlaceNTT_DIF:core/inPlaceNTT_DIF:core:conc/modulo_sub:if:acc RESOURCE_NAME modulo_sub:if:acc:rg
directive set /inPlaceNTT_DIF/inPlaceNTT_DIF:core/inPlaceNTT_DIF:core:conc/VEC_LOOP:acc#8 RESOURCE_NAME VEC_LOOP:acc#8:rg
directive set /inPlaceNTT_DIF/inPlaceNTT_DIF:core/inPlaceNTT_DIF:core:conc/mult:res:acc RESOURCE_NAME VEC_LOOP:acc#8:rg
directive set /inPlaceNTT_DIF/inPlaceNTT_DIF:core/inPlaceNTT_DIF:core:conc/COMP_LOOP:twiddle_f:lshift RESOURCE_NAME COMP_LOOP:twiddle_f:lshift:rg
directive set /inPlaceNTT_DIF/inPlaceNTT_DIF:core/inPlaceNTT_DIF:core:conc/STAGE_LOOP:lshift RESOURCE_NAME COMP_LOOP:twiddle_f:lshift:rg
directive set /inPlaceNTT_DIF/inPlaceNTT_DIF:core/inPlaceNTT_DIF:core:conc/mult:z:mul RESOURCE_NAME mult:t:mul:rg
directive set /inPlaceNTT_DIF/inPlaceNTT_DIF:core/inPlaceNTT_DIF:core:conc/mult:t:mul RESOURCE_NAME mult:t:mul:rg
directive set /inPlaceNTT_DIF/inPlaceNTT_DIF:core/inPlaceNTT_DIF:core:conc/mult:z_:mul RESOURCE_NAME mult:t:mul:rg
directive set /inPlaceNTT_DIF/inPlaceNTT_DIF:core/inPlaceNTT_DIF:core:conc/STAGE_LOOP:acc#1 RESOURCE_NAME COMP_LOOP:acc#1:rg
directive set /inPlaceNTT_DIF/inPlaceNTT_DIF:core/inPlaceNTT_DIF:core:conc/COMP_LOOP:acc#1 RESOURCE_NAME COMP_LOOP:acc#1:rg
