directive set /stockham_DIT/stockham_DIT:core/core/drf(y).smx.lpi#2 REGISTER_NAME drf(y).smx.lpi#2
directive set /stockham_DIT/stockham_DIT:core/core/drf(y).smx.lpi#3 REGISTER_NAME drf(y).smx.lpi#2
directive set /stockham_DIT/stockham_DIT:core/core/drf(y).smx.lpi#3.dfm#1 REGISTER_NAME drf(y).smx.lpi#2
directive set /stockham_DIT/stockham_DIT:core/core/INNER_LOOP:b#1.sva REGISTER_NAME drf(y).smx.lpi#2
directive set /stockham_DIT/stockham_DIT:core/core/tmp#6.sva#1 REGISTER_NAME drf(y).smx.lpi#2
directive set /stockham_DIT/stockham_DIT:core/core/INNER_LOOP:a:slc(INNER_LOOP-1:q:and.psp)(0)#1.itm REGISTER_NAME INNER_LOOP:a:slc(INNER_LOOP-1:q:and.psp)(0)#1.itm
directive set /stockham_DIT/stockham_DIT:core/core/INNER_LOOP:a:slc(INNER_LOOP-1:q:and.psp)(0).itm REGISTER_NAME INNER_LOOP:a:slc(INNER_LOOP-1:q:and.psp)(0)#1.itm
directive set /stockham_DIT/stockham_DIT:core/core/INNER_LOOP-1:upper:and.psp.sva REGISTER_NAME INNER_LOOP-1:upper:and.psp.sva
directive set /stockham_DIT/stockham_DIT:core/core/INNER_LOOP:t(8:1).sva REGISTER_NAME INNER_LOOP-1:upper:and.psp.sva
directive set /stockham_DIT/stockham_DIT:core/core/INNER_LOOP-1:w:lshift.idiv.sva REGISTER_NAME INNER_LOOP-1:w:lshift.idiv.sva
directive set /stockham_DIT/stockham_DIT:core/core/INNER_LOOP-2:w:lshift.idiv.sva REGISTER_NAME INNER_LOOP-1:w:lshift.idiv.sva
directive set /stockham_DIT/stockham_DIT:core/core/INNER_LOOP-1:b:mul.mut REGISTER_NAME INNER_LOOP-1:b:mul.mut
directive set /stockham_DIT/stockham_DIT:core/core/INNER_LOOP-2:b:mul.mut REGISTER_NAME INNER_LOOP-1:b:mul.mut
directive set /stockham_DIT/stockham_DIT:core/core/INNER_LOOP-1:acc#5.itm REGISTER_NAME INNER_LOOP-1:acc#5.itm
directive set /stockham_DIT/stockham_DIT:core/core/INNER_LOOP-2:acc#5.itm REGISTER_NAME INNER_LOOP-1:acc#5.itm
directive set /stockham_DIT/stockham_DIT:core/core/INNER_LOOP:a#1.lpi#3.dfm REGISTER_NAME INNER_LOOP-1:acc#5.itm
directive set /stockham_DIT/stockham_DIT:core/core/INNER_LOOP:a.lpi#3.dfm REGISTER_NAME INNER_LOOP-1:acc#5.itm
directive set /stockham_DIT/stockham_DIT:core/core/tmp#2.sva#1 REGISTER_NAME INNER_LOOP-1:acc#5.itm
directive set /stockham_DIT/stockham_DIT:core/core/INNER_LOOP:b.sva REGISTER_NAME INNER_LOOP:b.sva
directive set /stockham_DIT/stockham_DIT:core/core/drf(y).smx.lpi#3.dfm REGISTER_NAME INNER_LOOP:b.sva
directive set /stockham_DIT/stockham_DIT:core/core/OUTER_LOOP:acc#2.itm REGISTER_NAME OUTER_LOOP:acc#2.itm
directive set /stockham_DIT/stockham_DIT:core/core/shift(3:0).sva REGISTER_NAME OUTER_LOOP:acc#2.itm
